### ISSUE TITLE
RL framework roadmap

### ISSUE THREAD

**Issue by ChiahungTai** [microsoft/qlib#1006]
## ❓ Questions and Help
Hi, there and @you-n-g,
According to the #107, what is your RL framework roadmap?
Or another questions is what is the next step of qlib? Do you have a roadmap or right now is in the bug fixing and refatoring stage?
I thinks that is good to refactor the code and make it robost after some major delivers.
Anyway, look forward to knowing the plan of qlib. And see what I can help.

**Comment by you-n-g** [comment]
We are merging some RL support features for Qlib recently. 
Please make discussions in that thread :)

**Comment by ChiahungTai** [comment]
> We are merging some RL support features for Qlib recently. Please make discussions in that thread :)

Got it! Thanks for your reply.

**Comment by ChiahungTai** [comment]
> We are merging some RL support features for Qlib recently. Please make discussions in that thread :)

By the way, can you point out which thread. I can't find the thread in the issues. Thanks.

**Comment by you-n-g** [comment]
Sorry for forgetting to paste the link https://github.com/microsoft/qlib/issues/1011

**Comment by ChiahungTai** [comment]
> Sorry for forgetting to paste the link #1011

No problem!
