### ISSUE TITLE
how can i use strategy module only and edit self-design strategy

### ISSUE THREAD

**Issue by franceslius** [microsoft/qlib#1009]
## ❓ Questions and Help

I saw that qlib workflow usually utilized with training model and decisions made by fitted model signal, but I want use the decision generation module only. Like, I had a factor data already, can I backtest my strategy only by the factors(signals) without training part?

I looked up the whole instruction documents in your officicial website, and I didn't read any single chapter about this, would you please give some examples or instrutions about it?

Thanks a lot!

**Comment by you-n-g** [comment]
You can train a model first and then save the predictions.
And then you can use the strategy module  without retraining models  https://qlib.readthedocs.io/en/latest/component/strategy.html#running-backtest
