### ISSUE TITLE
Is changing `Power` from an NpElemOperator to an NpPairOperator a good idea?

### ISSUE THREAD

**Issue by wuzhe1234** [microsoft/qlib#1010]
In order to achieve the expression like **"Power($close, Rank($close, 14))"** which is fairly common in fomulla alpha.

I guess we could use following code:

`class Power(NpPairOperator):
    def __init__(self, feature_left, feature_right):
        super(PairPower, self).__init__(feature_left, feature_right, "power")`

Finally, we could add a __rpow__ magic method to **Expression** class

**Comment by you-n-g** [comment]
@wuzhe1234
I think it is a good idea.
Looking forward to your contribution :)
