### ISSUE TITLE
Yahoo collecor not responding while update data

### ISSUE THREAD

**Issue by hensejiang** [microsoft/qlib#1016]
## ❓ Questions and Help
This issue seems not same as days ago while the yahoo script returns connection failed, now it just hangs there with no response. Please see the screenshot.
![image](https://user-images.githubusercontent.com/43102199/160120254-ac367cc2-80fd-420d-b8f2-733ac7c55e70.png)

**Comment by hensejiang** [comment]
Any update on this? 
Or, do you recommend an alternative way to fetch daily update data? I was thinking of manual update from Baostock but still prefer Qlib internal functions doing the job to keep consistency of the whole system.

**Comment by you-n-g** [comment]
@hensejiang 

Yahoo! Finance has blocked the access from China. Please change your network if you want to use the Yahoo data crawler.

https://github.com/microsoft/qlib/pull/1077

**Comment by hensejiang** [comment]
Not a surprise. Will seek for other data source.
Thanks for the info.
