### ISSUE TITLE
Does qlib support inremental dataset handler?

### ISSUE THREAD

**Issue by ChiahungTai** [microsoft/qlib#1017]
Hi, there and @you-n-g,
For daily runing trader with qlib, we might need a inremental dataset handler to leverage the proceed dataset. For example, we already have a processed Alpha 158 dataset on 3/19(Tue), and after the marker close time on 3/19(Tue), we might run a program to process the all market dataset. Is there any efficient way like incremential dataset handler to process the qlib data? We might only need to collect the 3/19 market data and transform to qlib data format(qlib already have an example by update_data_to_bin), load the processed data(end on 3/18), load the 3/19 data and combine both qlib data and trabsform to update to date Alpha158 data.
Thanks.

**Comment by you-n-g** [comment]
Sorry,  currently, Qlib doesn't support incrementally updating handler.
It is indeed an important requirement.

**Comment by ChiahungTai** [comment]
Thanks for your reply. :)
