### ISSUE TITLE
Download csi300 info failed

### ISSUE THREAD

**Issue by liujianliuku** [microsoft/qlib#1019]
## 🐛 Bug Description
It seems orginal website changed their path
<img width="840" alt="image" src="https://user-images.githubusercontent.com/4394975/160270928-ffc6828d-fe40-43ef-868e-7bf6b4fa15ba.png">

## To Reproduce

1.
1.
1.

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version:
 - Python version:
 - OS (`Windows`, `Linux`, `MacOS`):
 - Commit number (optional, please provide it if you are using the dev version):

**Comment by SunsetWolf** [comment]
Hi! @liujianliuku 
Although the site has changed their path, this does not cause the download of CSI300 data to fail.

**Comment by SunsetWolf** [comment]
This issue was fixed in [PR 1046](https://github.com/microsoft/qlib/pull/1046).
