### ISSUE TITLE
Wrong stock code in qlib_data/cn_data/instruments/csi300.txt

### ISSUE THREAD

**Issue by LUS8806** [microsoft/qlib#1026]
Hi there,

I find the following wrong codes in "qlib_data/cn_data/instruments/csi300.txt"
SZ688008
SZ688009
SZ688012
SZ688036
SZ688111
SZ688126
SZ688169
SZ688363
SZ688396

These stocks are listed on shanghai exchange and should be SH688***

Thanks,

Song

**Comment by FluidDoctor** [comment]
That's likely because something like this in somewhere : return f"SH{symbol}" if symbol.startswith("60") else f"SZ{symbol}"

**Comment by SunsetWolf** [comment]
This issue was fixed in [PR 1046](https://github.com/microsoft/qlib/pull/1046).
