### ISSUE TITLE
How can I get which stocks have been sold/bought in TopkDropoutStrategy?

### ISSUE THREAD

**Issue by igor17400** [microsoft/qlib#1027]
## ❓ Questions and Help

As the documentation says

> Topk-Drop algorithm：
> Topk: The number of stocks held
> Drop: The number of stocks sold on each trading day
> Currently, the number of held stocks is Topk. On each trading day, the Drop number of held stocks with the worst prediction > score will be sold, and the same number of unheld stocks with the best prediction score will be bought.

After I execute the backtest code below, **_how can I get to know which stocks have been sold/bought in TopkDropoutStrategy?_**

```
# backtest and analysis
with R.start(experiment_name="backtest_analysis"):
    # backtest & analysis
    par = PortAnaRecord(recorder, port_analysis_config, "day")
    par.generate()
```

**Comment by al33m501** [comment]
You can get detailed information about portfolio positions from `portfolio_analysis/positions_normal_1day.pkl`
Example:
```
with R.start(experiment_name="backtest_analysis"):
    recorder = R.get_recorder(recorder_id=rid, experiment_name="train_model")
    model = recorder.load_object("trained_model")

    # prediction
    recorder = R.get_recorder()
    ba_rid = recorder.id
    sr = SignalRecord(model, dataset, recorder)
    sr.generate()

    # backtest & analysis
    par = PortAnaRecord(recorder, port_analysis_config, "day")
    par.generate()

recorder = R.get_recorder(recorder_id=ba_rid, experiment_name="backtest_analysis")
positions = recorder.load_object("portfolio_analysis/positions_normal_1day.pkl")
```

**Comment by igor17400** [comment]
@al33m501 thank very much!
It worked successfully
