### ISSUE TITLE
Why did my trading stop on a certain day?

### ISSUE THREAD

**Issue by zzz6060092** [microsoft/qlib#1028]
## ❓ Questions and Help
My backtest's start time is 2021-12-10,and the end time is 2022-03-11.But my trading stopped on 2022-01-04.Why are there no trades on later dates?
![image](https://user-images.githubusercontent.com/52370630/161020818-a2084caa-7198-4a50-b769-7de8eb77aacf.png)
![image](https://user-images.githubusercontent.com/52370630/161020900-0a28038c-9ec9-4772-a576-3c30f4e000a7.png)

**Comment by you-n-g** [comment]
Maybe you can add a conditional  breakpoint [here](https://github.com/microsoft/qlib/blob/main/qlib/contrib/strategy/signal_strategy.py#L124)
```
if   pred_start_time > XXX: import ipdb; ipdb.set_trace()
```

**Comment by you-n-g** [comment]
I guess the score may be empty after 2022-01-04.
