### ISSUE TITLE
What is the correspondence between the date of prediction and the dates during backtest? 

### ISSUE THREAD

**Issue by Chlorie** [microsoft/qlib#1029]
Suppose that I use `Alpha360` for the input features, which contains data from day (T-59) to day T and by default the label is given as `Ref($close, -2) / Ref($close, -1) - 1`, thus what the model predicts on day T should be traded on T+2. Where is this time difference addressed in the backtest? I don't see any date adjustments in the example code.

And also, if for example I use `Ref($close, -1) / $close - 1` as the prediction target, (how) should I adjust the dates in the prediction dataframe?

Thanks!

**Comment by you-n-g** [comment]
https://qlib.readthedocs.io/en/latest/component/data.html#example


Can your question be answered by this doc?
![image](https://user-images.githubusercontent.com/465606/165503292-f6a0d2cd-29e6-42cb-98df-f5f8b9dc52e0.png)
