### ISSUE TITLE
Is there any buy or sell function for simulation trading? 

### ISSUE THREAD

**Issue by a6225301** [microsoft/qlib#103]
## 📖 Documentation

Perferct work and thanks all the contributors. 
In the documentation, i can not find the buy or sell function for simulation trading , is there any possbile solution ?
Anymore, is there any solution to provide the functions such as before the stock market operation, after the stock market opertion ?

**Comment by you-n-g** [comment]
In our current design.
We use a module named `strategy` to generate orders from forecast signals
Here are the [docs](https://qlib.readthedocs.io/en/latest/component/strategy.html) and [code](https://github.com/microsoft/qlib/blob/main/qlib/contrib/strategy/strategy.py#L253)
