### ISSUE TITLE
load a subset of factors of handler

### ISSUE THREAD

**Issue by specialuse** [microsoft/qlib#1030]
## ❓ Questions and Help

hi,
Suppose I want to construct a dataset from  dataset1_conf below, where  **handler1 is a instance of DataHandler**  include factors data. My question is if I can load a subset of factors of handler? because some models do note need to much inputs.
thanks

dataset1_conf = {
            "class": "DatasetH",
            "module_path": "qlib.data.dataset",
            "kwargs": {
                "handler": handler1,
                "segments":dataset.segments,
            },
        }
dataset1 = init_instance_by_config(dataset1_conf)

**Comment by you-n-g** [comment]
You can filter columns by handler processors.
Here is [an example](https://github.com/microsoft/qlib/blob/main/examples/benchmarks/GRU/workflow_config_gru_Alpha158.yaml#L13)
