### ISSUE TITLE
DoubleEnsemble causes KeyError

### ISSUE THREAD

**Issue by heury** [microsoft/qlib#1033]
## To Reproduce

1. qrun .\examples\benchmarks\DoubleEnsemble\workflow_config_doubleensemble_Alpha158.yaml

## Screenshot
I think variable "i_b" should be "b" on line 163 of qlib/contrib/model/double_ensemble.py

![image](https://user-images.githubusercontent.com/17853131/161637543-85fc9d71-719e-4bbe-903b-1763d79e7778.png)

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version:   0.8.4.99
 - Python version: 3.8
 - OS (`Windows`, `Linux`, `MacOS`): Windows
 - Commit number (optional, please provide it if you are using the dev version):

**Comment by you-n-g** [comment]
Hi, 
I fail to reproduce your issue in the latest version.  Could you please give more details about how to reproduce this error ? 
![image](https://user-images.githubusercontent.com/465606/165505960-4298d7d2-ffaf-4d6e-8b60-de32483fcc09.png)
