### ISSUE TITLE
question about highfreq example

### ISSUE THREAD

**Issue by heury** [microsoft/qlib#1034]
I want to use qlib in live trading.

I read README.md under examples/hifreq because I think it is example about intraday trading. 
It explain about workflow.py
But, there are no training or inference code in the workflow.py.
It just contains get_data and dump_and_load_dataset which generate dataset.pkl and dataset_backtest.pkl.

I can trainin and evalute model with following command, but it does not use dataset.pkl and dataset_backtest.pkl.
qrun examples/highfreq/workflow_config_High_Freq_Tree_Alpha158.yaml

So, I am confused with these pkl files.
What are the purpose of these pkl files and how can I use them for highfreq trading?

**Comment by SunsetWolf** [comment]
Can [this document](https://qlib.readthedocs.io/en/latest/advanced/serial.html) solve your problem?

**Comment by heury** [comment]
I know that workflow.py saves data in serialization format. But, I don't know how to use it in highfreq trading.
I wonder why serialization example is under the highfreq directory.

**Comment by bxdd** [comment]
I think the '.pkl' file includes some states (such as variance or mean), if u wanna save ur dataset (or its states) for the further use, you can load the aforementioned '.pkl' file and process new data series with the older states (such as normalization).

**Comment by heury** [comment]
I don't understand that.
dataset.pkl and dataset_backtest.pkl do not contain any real data.
They just contain config data which can be loaded from config file.
After running prepare method, it will load data from files.
So, it takes 26 sec to load data and it is not good for real time trading.

**Comment by bxdd** [comment]
It contains some statistics of data (such as standard deviation). If you receive real-time data in real-time trading, you can directly use this statistic to preprocess the data.

**Comment by heury** [comment]
I understand what you mean. Thanks for your kind explaination
