### ISSUE TITLE
No module named 'qlib.tests

### ISSUE THREAD

**Issue by quinnnnnnnnn** [microsoft/qlib#104]
## ❓ Questions and Help

(TF2..1) D:\winAI\qlib-main>python scripts/get_data.py qlib_data --target_dir ~/.qlib/qlib_data/cn_data --region cn
Traceback (most recent call last):
  File "scripts/get_data.py", line 4, in <module>
    from qlib.tests.data import GetData
ModuleNotFoundError: No module named 'qlib.tests'
I have already pip install pyqlib, why this happened？

**Comment by AnonymousJY** [comment]
Yes I get the same error.

**Comment by aleeusgr** [comment]
I use conda and had the same error. I created new environment, installed qlib via provided script (python setup.py install), did initialization (from the documentation page) and after was able to run the test script successfully.

**Comment by you-n-g** [comment]
Hi,
pip install pyqlib will install qlib==0.6.0
But the qlib will

**Comment by you-n-g** [comment]
pip will install latest stable qlib. However the main branch of qlib is in active development. If you want to test the latest scripts or functions in main branch. Please install qlib with `python setup.py install` or `python setup.py develop` 

Thanks

**Comment by zhupr** [comment]
You can try it like this:
- uninstall pyqlib: `python -m pip uninstall pyqlib`
- delete "pyqlib*" and "qlib*" under `site-packages`
- reinstall qlib: `pip install pyqlib` or `python setup.py install`

**Comment by XuChongBo** [comment]
cd source_dir_root
touch ./scripts/__init__.py
python -m scripts.get_data qlib_data --target_dir ~/.qlib/qlib_data/cn_data --region cn

it works for me. hope it helps.

attention: qlib.tests package is not included in site-packages after qlib installed.

**Comment by you-n-g** [comment]
Hi, 
We've release a new version(0.6.1) of qlib just now.
Some recent features in dev version are included. 
 
So you can solve this problem by ` pip install --upgrade pyqlib`  or follow the instructions  in [homepage](https://github.com/microsoft/qlib#installation) to install dev version of qlib.

**Comment by AnonymousJY** [comment]
I was able to resolve this by creating new "Conda" virtual environment and installing by `pip install pyqlib`. One additional library I had to install was `pip install nbformat`. Thanks.

**Comment by uredkar** [comment]
This worked for me.
git clone https://github.com/microsoft/qlib.git && cd qlib
pip install .
