### ISSUE TITLE
An error in detailed_workflow.ipynb

### ISSUE THREAD

**Issue by heury** [microsoft/qlib#1045]
## To Reproduce

The keyword-"time_per_step" is missing in port_analysis_config

"executor": {
            "time_per_step"
        "class": "SimulatorExecutor",
        "module_path": "qlib.backtest.executor",
        _**"kwargs": {: "day",**_
            "generate_portfolio_metrics": True,
        },
    },

## Expected Behavior

It should be as follows

"executor": {
        "class": "SimulatorExecutor",
        "module_path": "qlib.backtest.executor",
        _"kwargs": {**"time_per_step": "day",**_
            "generate_portfolio_metrics": True,
        },
    }

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version:
 - Python version:
 - OS (`Windows`, `Linux`, `MacOS`):
 - Commit number (optional, please provide it if you are using the dev version):

**Comment by FluidDoctor** [comment]
"executor": {
"class": "SimulatorExecutor",
"module_path": "qlib.backtest.executor",
"kwargs": {"time_per_step": "day",
"generate_portfolio_metrics": True,
},
},

**Comment by you-n-g** [comment]
This is been fixed by https://github.com/microsoft/qlib/pull/1084

**Comment by heury** [comment]
I confirmed it has been fixed.
