### ISSUE TITLE
How to get label when the dataset is TSDatasetH?

### ISSUE THREAD

**Issue by LUS8806** [microsoft/qlib#1051]
Hi,
I'm trying to get the label data from the dataset when the dataset is TSDatasetH. 

When I do using these codes:

```
label_df = dataset.prepare("test", col_set="label")
```

It returns a qlib.data.dataset.TSDataSampler.

I need a dataframe. How can I get label dataframe when the dataset is TSDatasetH?

Thx,

Song

**Comment by zoaamour** [comment]
label_df = dataset.handler.fetch(dataset.segments["test"], col_set="label")

@LUS8806
