### ISSUE TITLE
How can I do incremental training?

### ISSUE THREAD

**Issue by heury** [microsoft/qlib#1058]
## ❓ Questions and Help

I found a solution how to save and load models. 
But I can't find a solution how to do incremental training with it.
Is there any example or documents to refer?
I think online_srv example is close to the solution. 
But, there is only first_train in the example

**Comment by you-n-g** [comment]
Currently, we don't have any runnable examples for incremental training.
But we have created an interface for this purpose in our design.
https://github.com/microsoft/qlib/blob/main/qlib/model/base.py#L85

You can find an example in the docs

**Comment by heury** [comment]
Thanks. It provides right example.
