### ISSUE TITLE
Label calculation

### ISSUE THREAD

**Issue by igor17400** [microsoft/qlib#1060]
## ❓ Questions and Help

In the following [documentation](https://qlib.readthedocs.io/en/latest/component/data.html#feature) it says the following

> In the **Alpha158**, Qlib uses the label `Ref($close, -2)/Ref($close, -1) - 1` that means the change from T+1 to T+2, rather than Ref($close, -1)/$close - 1, of which the reason is that when getting the T day close price of a china stock, the stock can be bought on T+1 day and sold on T+2 day.

However, in **Aplha360** should we use the same equation - `Ref($close, -2)/Ref($close, -1) - 1` - for label? Or should we use `Ref($close, -1)/$close - 1 `?

In this other [page](https://qlib.readthedocs.io/en/latest/component/report.html) from the documentation it says,

- For _ic_
> The Pearson correlation coefficient series between label and prediction score. In the above example, the label is formulated as `Ref($close, -1)/$close - 1`. Please refer to [Data Feature](https://qlib.readthedocs.io/en/latest/component/data.html#feature) for more details.

**_Are those two formulas related? Shouldn't them be the same?_**

**Comment by you-n-g** [comment]
Thanks for your reporting. 
@SunsetWolf  will fix this BUG.

**Comment by igor17400** [comment]
@you-n-g if it is of any help I can fix this documentation. 
I just need to undersand what exactly is wrong.

 Is  it the IC definition? Or the equation that should be used in Aplha360 which should be `Ref($close, -1)/$close - 1 `?

**Comment by SunsetWolf** [comment]
Sorry for taking so long to reply to you, I have made changes to this issue in [this PR](https://github.com/microsoft/qlib/pull/1092).
