### ISSUE TITLE
Is the annualized return calculation wrong?

### ISSUE THREAD

**Issue by igor17400** [microsoft/qlib#1067]
## ❓ Questions and Help

The `annualized_return` calculation  under `evaluate.py` file is defined under the [link](https://github.com/microsoft/qlib/blob/main/qlib/contrib/evaluate.py).

In this file, the default normalization frequency variable for days is being configured as `Freq.NORM_FREQ_DAY: 238`. However, shouldn't it be 252? Since the average number of trading days is 252.

**Comment by igor17400** [comment]
Actually, it seems that the equation used to calculate annualized return is wrong.
Shouldn't it be one of the equations in the images below?

![Screen Shot 2022-04-21 at 22 10 50](https://user-images.githubusercontent.com/42355184/164577060-dda2e7d1-62f0-4d88-bc61-04f8628eb9a6.png)

![Screen Shot 2022-04-21 at 22 11 24](https://user-images.githubusercontent.com/42355184/164577098-f866079f-3571-4483-b06e-61456ee14fb8.png)

Images removed from the [link](https://www.investopedia.com/terms/a/annualized-total-return.asp)

**Comment by igor17400** [comment]
I have found this [link](https://www.assetmacro.com/financial-terms/annualized-return/) that uses the same equatio as theone provided under `evaluate.py`, however I've not found any other reference to confirma that such calculation is indeed correct

**Comment by you-n-g** [comment]
Yes.  It is different from the definition of annualized return.
It is implemented by design.
Qlib tries to cumulated returns by summation instead of production to avoid the cumulated curve being skewed exponentially.
All the calculation of annualized returns follows this principle in Qlib.
