### ISSUE TITLE
How to run HIST model by using alpha158

### ISSUE THREAD

**Issue by stockcoder** [microsoft/qlib#1075]
## ❓ Questions and Help

anyone can give me an introduction？I want to use HIST model on alpha158

**Comment by FluidDoctor** [comment]
https://github.com/Wentao-Xu/HIST

**Comment by you-n-g** [comment]
Hi,  @Wentao-Xu ,  could you add some explanation about this question?

**Comment by Wentao-Xu** [comment]
> ## ❓ Questions and Help
> anyone can give me an introduction？I want to use HIST model on alpha158

Hi, to use the HIST model on alpha158, you need to change the encoder from GRU/LSTM to MLP.
