### ISSUE TITLE
Are there any index data of US, for example, SP500?

### ISSUE THREAD

**Issue by lauht** [microsoft/qlib#1079]
## ❓ Questions and Help
I just wonder how to set benchmark when I backtest my model in the stock data of US. Are there index data (for example, SP500) provided in the provider_uri?
I would be appreciate for any reply.

**Comment by SunsetWolf** [comment]
I am glad to reply to your issue. I read your question carefully and it can be roughly divided into two sub-questions.
Q1: How to set the benchmark?
I think [this document](https://qlib.readthedocs.io/en/latest/component/strategy.html) is very helpful for this question, the keyword is "benchmark".
Q2：Is index data provided in provider_uri?
The index data (e.g. SP500 stock pool) is included in the provider_uri, provided that you download it manually, I suggest you read [this document](https://github.com/microsoft/qlib/blob/main/scripts/data_collector/us_index/README.md) to understand how to download the index data (e.g. SP500 stock pool).
I hope my answer is helpful to you. Thanks.

**Comment by lauht** [comment]
> 

Thanks for your patience to answer my questions and your help was greatly appreciated!
