### ISSUE TITLE
Why the dataset is normalized by the closed price of the first day?

### ISSUE THREAD

**Issue by haoboiler** [microsoft/qlib#109]
## ❓ Questions and Help
By using the data download by the get_data.py and using the code from data retrieval tutorial, the price in the dataframe is normalized by the closed price of the first day. How can I get the real price of the stock?

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

**Comment by you-n-g** [comment]
@haoboiler 
Qlib normalize data for making model training easier.
If you want to retrieve the original data, please refer to  the [doc](https://qlib.readthedocs.io/en/latest/start/getdata.html)
