### ISSUE TITLE
How to use multi GPUs to train the model

### ISSUE THREAD

**Issue by Xxiaoting** [microsoft/qlib#1098]
When I was training the GATs model using all the Chinese stock market data (by setting instrument = 'all'), it turns out an error 'RuntimeError: CUDA out of memory'. Actually I have two GPUs but only one was using when I did the training. How can I use multi GPUs to do the training? 

Thanks for the help in advance.

**Comment by gagaein** [comment]
Hello, I am facing the same problem. Have you solved it:)

**Comment by you-n-g** [comment]
Qlib provides a framework for quant research. But it does not manage the computation resource.
You integrate https://pytorch.org/docs/stable/generated/torch.nn.DataParallel.html or something else into  https://github.com/microsoft/qlib/blob/main/qlib/contrib/model/pytorch_gats.py to fully leverage your resource.
