### ISSUE TITLE
Segmentation Fault when qrun with lightgbm workflow config

### ISSUE THREAD

**Issue by ethanygao** [microsoft/qlib#1099]
## 🐛 Bug Description

(quant) ➜  examples git:(main) ✗ qrun benchmarks/LightGBM/workflow_config_lightgbm_Alpha158.yaml

[98703:MainThread](2022-05-15 11:46:07,937) INFO - qlib.Initialization - [config.py:402] - default_conf: client.
[98703:MainThread](2022-05-15 11:46:07,938) INFO - qlib.Initialization - [__init__.py:74] - qlib successfully initialized based on client settings.
[98703:MainThread](2022-05-15 11:46:07,939) INFO - qlib.Initialization - [__init__.py:76] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/ethangao/.qlib/qlib_data/cn_data')}
[98703:MainThread](2022-05-15 11:46:07,939) INFO - qlib.workflow - [expm.py:315] - <mlflow.tracking.client.MlflowClient object at 0x14edf7760>
[98703:MainThread](2022-05-15 11:46:07,946) INFO - qlib.workflow - [exp.py:257] - Experiment 1 starts running ...
[98703:MainThread](2022-05-15 11:46:07,990) INFO - qlib.workflow - [recorder.py:293] - Recorder 8c4e3c2a5a964599a557c41d714f06e6 starts running under Experiment 1 ...
[98703:MainThread](2022-05-15 11:46:29,059) INFO - qlib.timer - [log.py:113] - Time cost: 19.860s | Loading data Done
[98703:MainThread](2022-05-15 11:46:29,410) INFO - qlib.timer - [log.py:113] - Time cost: 0.148s | DropnaLabel Done
/Users/ethangao/anaconda3/envs/quant/lib/python3.8/site-packages/pyqlib-0.8.5.99-py3.8-macosx-11.0-arm64.egg/qlib/data/dataset/processor.py:316: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols] = df[cols].groupby("datetime").apply(self.zscore_func)
[98703:MainThread](2022-05-15 11:46:31,216) INFO - qlib.timer - [log.py:113] - Time cost: 1.806s | CSZScoreNorm Done
[98703:MainThread](2022-05-15 11:46:31,216) INFO - qlib.timer - [log.py:113] - Time cost: 2.157s | fit & process data Done
[98703:MainThread](2022-05-15 11:46:31,217) INFO - qlib.timer - [log.py:113] - Time cost: 22.019s | Init data Done
[1]    98703 segmentation fault  qrun benchmarks/LightGBM/workflow_config_lightgbm_Alpha158.yaml
/Users/ethangao/anaconda3/envs/quant/lib/python3.8/site-packages/joblib/externals/loky/backend/resource_tracker.py:318: UserWarning: resource_tracker: There appear to be 2 leaked folder objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/Users/ethangao/anaconda3/envs/quant/lib/python3.8/site-packages/joblib/externals/loky/backend/resource_tracker.py:333: UserWarning: resource_tracker: /var/folders/p9/cx1phmtx281gtdxynjxdq10h0000gn/T/joblib_memmapping_folder_98703_3731598bf534428094bea80f2d0b9e92_2e5f444f65694d989d1865682326f2e3: FileNotFoundError(2, 'No such file or directory')
  warnings.warn('resource_tracker: %s: %r' % (name, e))
/Users/ethangao/anaconda3/envs/quant/lib/python3.8/site-packages/joblib/externals/loky/backend/resource_tracker.py:333: UserWarning: resource_tracker: /var/folders/p9/cx1phmtx281gtdxynjxdq10h0000gn/T/joblib_memmapping_folder_98703_f22da3ae43364f70af912e976efb002d_4c8de556f1fb44388c7feeb8e5da73f4: FileNotFoundError(2, 'No such file or directory')
  warnings.warn('resource_tracker: %s: %r' % (name, e))

## To Reproduce

1.cd examples # Avoid running program under the directory contains qlib
2.qrun benchmarks/LightGBM/workflow_config_lightgbm_Alpha158.yaml

## Expected Behavior

'The following are analysis results of the excess return without cost.'
                       risk
mean               0.000708
std                0.005626
annualized_return  0.178316
information_ratio  1.996555
max_drawdown      -0.081806
'The following are analysis results of the excess return with cost.'
                       risk
mean               0.000512
std                0.005626
annualized_return  0.128982
information_ratio  1.444287
max_drawdown      -0.091078

## Screenshot

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/4847774/168456721-7094c9ff-086c-440a-9c21-db4bf46d2170.png">

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

Darwin
arm64
macOS-12.3.1-arm64-arm-64bit
Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:05:16)  [Clang 12.0.1 ]

Qlib version: 0.8.5.99
numpy==1.22.3
pandas==1.4.2
scipy==1.8.0
requests==2.25.1
sacred==0.8.2
python-socketio==5.5.2
redis==4.2.2
python-redis-lock==3.7.0
schedule==1.1.0
cvxpy==1.2.0
hyperopt==0.1.2
fire==0.4.0
statsmodels==0.13.2
xlrd==2.0.1
plotly==5.6.0
matplotlib==3.5.1
tables==3.7.0
pyyaml==6.0
mlflow==1.24.0
tqdm==4.61.2
loguru==0.6.0
lightgbm==3.3.0
tornado==6.1
joblib==1.1.0
fire==0.4.0
ruamel.yaml==0.17.21

## Additional Notes

1. I manually installed qlib by:
git clone https://github.com/microsoft/qlib.git && cd qlib
pip install .
(For the dependencies those returning errors when installing by pip, I installed them manually using conda)

2. I also manually installed torch==1.11.0, xgboost==1.6.1, catboost==1.0.5

3. This error seems like: https://github.com/microsoft/qlib/issues/798, but there did not exist a solution either.

4. Similarly, I cannot pass the pytest by running `python -m pytest ./tests`, which returns:

> 101 warnings, 16 errors in 2.37s:

<img width="1443" alt="image" src="https://user-images.githubusercontent.com/4847774/168456906-958530d5-4071-4d51-b6a4-55669c11da52.png">

**Comment by solmix** [comment]
I had the same problem

**Environment**
Darwin
arm64
macOS-12.2.1-arm64-arm-64bit
Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:05:16)  [Clang 12.0.1 ]

Qlib version: 0.8.5.99
numpy==1.22.4
pandas==1.4.2
scipy==1.8.1
requests==2.27.1
sacred==0.8.2
python-socketio==5.6.0
redis==4.3.1
python-redis-lock==3.7.0
schedule==1.1.0
cvxpy==1.2.1
hyperopt==0.1.2
fire==0.4.0
statsmodels==0.13.2
xlrd==2.0.1
plotly==5.8.0
matplotlib==3.5.2
tables==3.7.0
pyyaml==6.0
mlflow==1.26.0
tqdm==4.64.0
loguru==0.6.0
lightgbm==3.3.2
tornado==6.1
joblib==1.1.0
fire==0.4.0
ruamel.yaml==0.17.21

**Comment by solmix** [comment]
build https://github.com/cvxpy/cvxpy  manually，not use conda，run workflow is ok.

**Comment by ethanygao** [comment]
> build https://github.com/cvxpy/cvxpy manually，not use conda，run workflow is ok.

Hi @solmix, thanks for your reply. But I do not think it is the issue about cvxpy, my cvxpy works well on my M1 mac.

I also tried uninstall cvxpy, and rebuild it from source, the Segmentation Fault of qlib remains.

**Comment by YZY0419** [comment]
THANK YOU so much
