### ISSUE TITLE
DDG -DA案例里面的训练环境

### ISSUE THREAD

**Issue by lukekingca** [microsoft/qlib#1106]
## ❓ Questions and Help
DDG -DA案例里面的训练环境是什么，有没什么建议呢？用ryzen 3800x+64g内存跑24小时了，还是在Recorder 4a9884ee9f044ebe9d8e414aa89b7b20 starts running under Experiment 1 ... 状态，cpu占用一直是50%左右
We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

**Comment by you-n-g** [comment]
Please press `ctrl+c` to interrupt the program and attach the detailed error traceback

**Comment by lukekingca** [comment]
> Please press `ctrl+c` to interrupt the program and attach the detailed error traceback

thanks priviously it was running under pycharm's terminal, press ctrl+c types a ^c,but still goes on. now I've switched to ubuntu's bash terminal,run the programme,it's in experiment2 now.

**Comment by lukekingca** [comment]
> Please press `ctrl+c` to interrupt the program and attach the detailed error traceback

Still, it wasn't working..I thought it was enviorment problem. So I did a pip install pyqlib agian.guess what, it upgraded lightbm to version 3.3.2,then it all works.
