### ISSUE TITLE
尝试执行示例代码出错了ValueError: operands could not be broadcast together with shapes (0,) (3011,)

### ISSUE THREAD

**Issue by liuhuanshuo** [microsoft/qlib#112]
## ❓ Questions and Help

前面安装配置一切OK

官方说明是使用`qrun benchmarks/LightGBM/workflow_config_lightgbm.yaml`

但是我目录下没有这个文件，只有类似的以yaml结尾的两个文件，于是不管执行

`qrun benchmarks/LightGBM/workflow_config_lightgbm_Alpha360.yaml `还是

`qrun benchmarks/LightGBM/workflow_config_lightgbm_Alpha158.yaml  ` 都提示

`ValueError: operands could not be broadcast together with shapes (0,) (3011,) `

似乎是数据上格式不匹配，没有对数据及文件进行任何修改，执行XGBOOST目录下其他yaml都是同样的问题！

**Comment by you-n-g** [comment]
Thanks for find the link error on the README. It is fixed now.

Did you follow [these steps](https://github.com/microsoft/qlib/blob/main/README.md#data-preparation) download the data? 
You can try [these steps](https://qlib.readthedocs.io/en/latest/start/getdata.html) to check if the data works

**Comment by liuhuanshuo** [comment]
> Thanks for find the link error on the README. It is fixed now.
> 
> Did you follow [these steps](https://github.com/microsoft/qlib/blob/main/README.md#data-preparation) download the data?
> You can try [these steps](https://qlib.readthedocs.io/en/latest/start/getdata.html) to check if the data work

Thanks for your reply. I have solved it. The reason is that my pandas and numpy version are too early

**Comment by you-n-g** [comment]
Very glad to see that it works for you. 
I'll close this issue now.
