### ISSUE TITLE
question about HIST pretrain model LSTM?

### ISSUE THREAD

**Issue by LiuHao-THU** [microsoft/qlib#1124]
hello, I have a question about the pre-train checkpoints in HIST.

when I train HIST Model with or without pre-train checkpoints model_lstm_csi300.pkl, 
the performance with pre-train checkpoints is much better than the model without it.

so how can I generate LSTM pre-train checkpoints? just train with the same settings using LSTM?

step1. Train LSTM and save checkpoints
step2. Train HIST using previous LSTM init HIST's self.rnn

?

**Comment by Wentao-Xu** [comment]
Yes, you can generate LSTM pre-train checkpoints and train with the same settings using LSTM. The training process is same as the steps you mentioned.

**Comment by 280777510** [comment]
@Wentao-Xu [model_lstm_csi300.pkl](https://github.com/microsoft/qlib/blob/main/examples/benchmarks/LSTM/model_lstm_csi300.pkl) 

Dear author,How do I generate this file(microsoft/qlib/blob/main/examples/benchmarks/LSTM/model_lstm_csi300.pkl) by myself?
