### ISSUE TITLE
how to enable cache with redis?

### ISSUE THREAD

**Issue by rambo-yuanbo** [microsoft/qlib#1137]
Hi,

If I initialize qlib noly with a provider_uri like this:
    qlib.init(provider_uri='~/.qlib/qlib_data/cn_data')

it seems that no cache is being done: 
1. I found the keys empty on redis
2. when I repeat calling sth like  D.features(instruments, fields, start_time='2010-01-01', end_time='2017-12-31', freq='day'), it always takes very long to get the data. No speeding up with cache.

If I initialize qlib with this params:  qlib.init(provider_uri='~/.qlib/qlib_data/cn_data', dataset_cache="SimpleDatasetCache"), obviously SimpleDatasetCache is doing its job. 

But still, 
1. what's the diffrenence between a DatasetCache and an expression_cache?
2. how do I enable expression_cache?
3. how do I enable the cache on redis?

Many thanks!

**Comment by newlyedward** [comment]
代码里面只看到实现了DiskExpresssionCache和DatasetCache，并且只能自己更新，如果需要数据超过Cash上的数据范围也不会更新，需要自己另外写Script去调用update。

1、本机启动redis， 不是本机启动redis还需要在congfigure中修改redis配置，redis其实没用，只是写cache是使用了redis的lock
2、congfigure中修改"expression_cache":  "DiskExpressionCache",，expresion就是类似$close/$high这样的表达式
3、MODE_CONF中修改"dataset_cache":  "DiskDatasetCache",, dataset是整个训练需要的特征值得集合

**Comment by rambo-yuanbo** [comment]
> 代码里面只看到实现了DiskExpresssionCache和DatasetCache，并且只能自己更新，如果需要数据超过Cash上的数据范围也不会更新，需要自己另外写Script去调用update。
> 
> 1、本机启动redis， 不是本机启动redis还需要在congfigure中修改redis配置，redis其实没用，只是写cache是使用了redis的lock 2、congfigure中修改"expression_cache": "DiskExpressionCache",，expresion就是类似$close/$high这样的表达式 3、MODE_CONF中修改"dataset_cache": "DiskDatasetCache",, dataset是整个训练需要的特征值得集合

Hi @newlyedward,

想继续请教几个问题
1. 您的意思是不是，在qlib实现中，没有用redis做实际cache，仅仅用了redis的lock机制？那如果没有打开redis服务（提供lock机制），qlib的cache是否能正常工作？
实际上，我在redis server的命令行中见到有这种：
[44856] 18 Jun 11:01:03.925 * 100 changes in 300 seconds. Saving...
[44856] 18 Jun 11:01:03.935 * Background saving started by pid 59820
但在redis-cli中查询 keys，没有查到任何新的keys

3. 我还是没有搞清楚ExpressionCache和DatasetCache的差异。之前我尝试仅使用SimpleDatasetCache
qlib.init(provider_uri='~/.qlib/qlib_data/cn_data', dataset_cache="SimpleDatasetCache"),
并取数据
 D.features(instruments, fields, start_time='2010-01-01', end_time='2017-12-31', freq='day'),
其中fieds中也包含expression
fields = ['$close', '$volume', 'Ref($close, 1)', 'Mean($close, 3)', '$high-$low']
实际运行时，第一次取logging显示形成了cahce，第二次取很快

4. 我用DiskDatasetCache代替SimpleDatasetCache，似乎更强一些，修改取数据的参数（如start_time更晚）后仍然从cache读数而非重来，代码结束再次运行也是从cache度数而非重来。
但DiskDatasetCache的代码中提到 """Prepared cache mechanism for server."""
不是很明白此处的server /client的模式差异。看了qlib相关文档，还没搞懂。

**Comment by newlyedward** [comment]
没有打开redis，根据现在代码cache是不起作用的，需要修改qlib代码

espression是针对fields的节约了计算的时间，dataset是针对训练集，测试集的数据，如果同样的数据特征值，只是优化模型，可以直接从dataset cache中直接取数据，如果修改dataset参数就需要重新缓存数据

**Comment by you-n-g** [comment]
@rambo-yuanbo
Qlib   的 DiskDatasetCache  机制是会预先缓存全时段数据的， 之后时间字段的变化就不需要重新缓存了。

Qlib Server本质上还是用的 DiskDatasetCache，  它的区别仅仅是在 有多个client时， server可以集中管理缓存， 不用每个clien
t自己管理
