### ISSUE TITLE
ValueError: instruments not exists for market <ticker> using my converted csv data into Qlib format

### ISSUE THREAD

**Issue by AnonymousJY** [microsoft/qlib#114]
## ❓ Questions and Help

Hi, 

I've converted my data for a particular US stock into Qlib format using command from [doc](https://qlib.readthedocs.io/en/latest/component/data.html#converting-csv-format-into-qlib-format) `python scripts/dump_bin.py dump_all --csv_path  ~/.qlib/csv_data/my_data --qlib_dir ~/.qlib/qlib_data/my_data --include_fields open,close,high,low,volume,factor`. Should a <ticker name>.txt file be created in ~/.qlib/qlib_data/my_data/instruments? I only see all.txt but the context inside the all.txt changes each time I add another ticker.

I think this is causing an issue for me to run the "train mode" example you provided with my data because I get a `ValueError: instruments not exists for market AAPL` for example. 

Thanks.

**Comment by zhupr** [comment]
@AnonymousJY Hi，
What is the format of the csv file and the "train model" config?

**Comment by AnonymousJY** [comment]
> @AnonymousJY Hi，
> What is the format of the csv file and the "train model" config?

Thanks for asking.
The format of the csv file is the following.
![Screen Shot 2020-12-13 at 22 52 35](https://user-images.githubusercontent.com/36392746/102038730-000a5d00-3d96-11eb-81f5-3f1c9a283c00.png)
The frequency is daily.

The file name is AAPL.csv. After converting the csv file with columns [open, close, high, low, volume], the bin files are saved in `~/.qlib/qlib_data/my_data/features/aapl` (e.g., close.day.bin).

The "train model" is the same as one in [here](https://github.com/microsoft/qlib/blob/main/examples/workflow_by_code.ipynb). Basically, I tried to change the dataset but run the same workflow example you guys provided.

**Comment by zhupr** [comment]
@AnonymousJY  Hi，

The `market` in config should be the stock list, which is the file in the `instruments` directory.
For example, `D.features(["AAPL"], ["$close"])` is correct, `D.features(D.instruments("AAPL"), ["$close"])` is wrong.
You can set the `market` in [here](https://github.com/microsoft/qlib/blob/main/examples/workflow_by_code.ipynb) to `all` to:`market = "all"` `benchmarket = "AAPL"`, `all` is the data set used by train, `benchmark` is the benchmark for comparison of backtest results (single stock)

**Comment by AnonymousJY** [comment]
> @AnonymousJY Hi，
> 
> The `market` in config should be the stock list, which is the file in the `instruments` directory.
> For example, `D.features(["AAPL"], ["$close"])` is correct, `D.features(D.instruments("AAPL"), ["$close"])` is wrong.
> You can set the `market` in [here](https://github.com/microsoft/qlib/blob/main/examples/workflow_by_code.ipynb) to `all` to:`market = "all"` `benchmarket = "AAPL"`, `all` is the data set used by train, `benchmark` is the benchmark for comparison of backtest results (single stock)

@zhupr Thanks.
After training my data, the output is the following, which I think is not working correctly.
![Screen Shot 2020-12-14 at 22 44 31](https://user-images.githubusercontent.com/36392746/102168265-f64c2c80-3e5d-11eb-9e86-2c78fbad2040.png)

The training code is the exact from this [notebook](https://github.com/microsoft/qlib/blob/main/examples/workflow_by_code.ipynb). `market=all` and `benchmarket=AAPL`.

The all.txt file only has AAPL.

However, when I run with your given data in `cn_data` I can get similar results as yours.

Is this something you can point me to the right direction? Thanks.

**Comment by you-n-g** [comment]
@AnonymousJY  I think you can set some break points  (like `import pdb; pdb.set_trace()`) before  [fitting models](https://github.com/microsoft/qlib/blob/main/qlib/contrib/model/gbdt.py#L50) and check the data.

**Comment by AnonymousJY** [comment]
> @AnonymousJY I think you can set some break points (like `import pdb; pdb.set_trace()`) before [fitting models](https://github.com/microsoft/qlib/blob/main/qlib/contrib/model/gbdt.py#L50) and check the data.

@you-n-g Thanks for the guidance. I think the problem is in the column `label`. After preparing data using `.prepare`, it returns `label` with same float numbers (see below screenshot).
![Screen Shot 2021-01-04 at 00 00 43](https://user-images.githubusercontent.com/36392746/103502661-ea7dd580-4e1f-11eb-9d38-ae0b6b7562be.png)

However, I'm not sure why this is the case, because I don't see any issue with the features (see below).
![Screen Shot 2021-01-04 at 00 03 07](https://user-images.githubusercontent.com/36392746/103502770-4e080300-4e20-11eb-876b-fc390b271867.png)

Do you or anyone else might know why the same float numbers are generated?
Thanks.

**Comment by you-n-g** [comment]
@AnonymousJY 
The dataset will use ZScoreNorm processor for label. 

https://github.com/microsoft/qlib/blob/main/qlib/data/dataset/processor.py#L196
https://github.com/microsoft/qlib/blob/main/qlib/contrib/data/handler.py#L37

If you only contains 2 stocks.   You will get values like you image after cross-sectional zscore normalization.

**Comment by AnonymousJY** [comment]
> @AnonymousJY
> The dataset will use ZScoreNorm processor for label.
> 
> https://github.com/microsoft/qlib/blob/main/qlib/data/dataset/processor.py#L196
> https://github.com/microsoft/qlib/blob/main/qlib/contrib/data/handler.py#L37
> 
> If you only contains 2 stocks. You will get values like you image after cross-sectional zscore normalization.

@you-n-g 
Thanks for the reply.

So for your working sample in "workflow_by_code.ipynb", the user would need to feed in multiple stock data like the example for the Chinese stocks in `cn_data` in order for that example model to train. Am I correct?

**Comment by you-n-g** [comment]
@AnonymousJY  
Currently, the released strategy examples are for multi-instrument selection (it is the hotest problem in practical Quant research).
The trading for single asset get relative low priority.
The setting of single asset  is similar to high-frequency trading https://github.com/microsoft/qlib/projects/2
We will consider releasing examples for single stock strategy in the future after we release high-frequency trading module.

**Comment by AnonymousJY** [comment]
> @AnonymousJY
> Currently, the released strategy examples are for multi-instrument selection (it is the hotest problem in practical Quant research).
> The trading for single asset get relative low priority.
> The setting of single asset is similar to high-frequency trading https://github.com/microsoft/qlib/projects/2
> We will consider releasing examples for single stock strategy in the future after we release high-frequency trading module.

@you-n-g 
Thanks for the reply. I look forward to that release.
Closing this ticket.
