### ISSUE TITLE
DoubleEnsemble doesn't Honor sub_weights When Computing Loss Values

### ISSUE THREAD

**Issue by bridgream** [microsoft/qlib#1143]
Hello, I notice in `fit()`, `loss_values` is computed based on the average prediction of trained sub-models (i.e. `pred_ensemble`): 
https://github.com/microsoft/qlib/blob/a87b02619aee4aff9c5aba23a66e614106050d75/qlib/contrib/model/double_ensemble.py#L90-L91

However, in `predict()`, the final output is the weighted sum of predictions of sub-models: 
https://github.com/microsoft/qlib/blob/a87b02619aee4aff9c5aba23a66e614106050d75/qlib/contrib/model/double_ensemble.py#L245-L248

In the paper https://arxiv.org/abs/2010.01265, the authors don't use weights for sub-models when making predictions. In fact, it is mentioned that
> We note it is possible to set a weight for each sub-model or develop a stacked generalization ensemble (aka stacking). In general, a proper way to combine the sub-models can further improve the performance and we leave it as a future research direction.

My questions are:
1. should we honor the weights when computing `loss_values`? 
2. without removing the flexibility of using custom `sub_weights`, is it better to use equal weights (i.e. `[1/6]*6`) as default values? https://github.com/microsoft/qlib/blob/a87b02619aee4aff9c5aba23a66e614106050d75/qlib/contrib/model/double_ensemble.py#L47

**Comment by you-n-g** [comment]
@bridgream  Thanks for reporting.

@lwwang1995  will help on this issue.

**Comment by lwwang1995** [comment]
Hi, @bridgream 
This bug has been fixed in [PR 1205](https://github.com/microsoft/qlib/pull/1205).
