### ISSUE TITLE
Cannot install pyqlib

### ISSUE THREAD

**Issue by 22susuLu** [microsoft/qlib#115]
install latest version of python 3.9, but it cannot install pyqlib, report not find version.

**Comment by AnonymousJY** [comment]
> install latest version of python 3.9, but it cannot install pyqlib, report not find version.

@22susuLu Hi.
I think python 3.9 is not supported according to [README.md](https://github.com/microsoft/qlib/blob/main/README.md). Maybe try with python 3.8?

**Comment by you-n-g** [comment]
@AnonymousJY  Thanks for your reply.

@22susuLu  Some of the dependencies of Qlib doesn't support Python 3.9.

**Comment by 22susuLu** [comment]
thanks, one note found is by default installing it installed the numpy 1.19.4 version, but that one has bug compatible with python 3.7 64bit, so downgrade to 1.19.3 works.
