### ISSUE TITLE
No trading operations on custom dataset

### ISSUE THREAD

**Issue by JeremyPKU** [microsoft/qlib#116]
## ❓ Questions and Help
Hi,
    I was trying the qlib backtest experiment on my custom dataset, which was formerly built from SPY.  And the data generation part seemed ok. 
<img width="1440" alt="截屏2020-12-14 上午11 35 58" src="https://user-images.githubusercontent.com/75962823/102037762-8b203d00-3e00-11eb-83b2-6c98d867f506.png">
When it came to backtesting,  I fed the input dataset and the benchmark data as:  
<img width="605" alt="截屏2020-12-14 上午11 37 23" src="https://user-images.githubusercontent.com/75962823/102037859-d1759c00-3e00-11eb-98df-bcb0aeff4157.png">
<img width="1026" alt="截屏2020-12-14 上午11 51 40" src="https://user-images.githubusercontent.com/75962823/102038645-c3287f80-3e02-11eb-96ad-c7373fe3aa60.png">
Then the model training process was perfectly finished, and the parameters are following:
<img width="549" alt="截屏2020-12-14 上午11 40 27" src="https://user-images.githubusercontent.com/75962823/102038106-5c569680-3e01-11eb-9ab8-7aa1720e840e.png">
But for the prediction step, there was no trading operations reported, compared to the default example scripts.
<img width="512" alt="截屏2020-12-14 上午11 42 42" src="https://user-images.githubusercontent.com/75962823/102038160-7d1eec00-3e01-11eb-9a01-968a5a23c576.png">
Is it a problem from my dataset? For the factor column in the .csv inputs, Im somewhat confused about its meaning. In your paper, 'factor' is regarded as features. Should I comprehend the 'factor' as the alphas in your scripts such as Alpha158?

**Comment by you-n-g** [comment]
Sorry for making the example a little confued.

The trading is used as a method to evaluate the signal (which is hiding in `PortAnaRecord` (Portfolio Analysis Record)).

I think make the trading modules more explicit will be better.

**Comment by JeremyPKU** [comment]
Grateful for your advices.

My trouble indeed is that there is no buy/sell operations at all, rather than being hided in `PortAnaRecord`. I found this  fault after I tried the same config for the example dataset, and the default results showed like this (with buy or sell after the daily trade begins, while I have  got none for my data):
<img width="1021" alt="截屏2020-12-14 下午2 17 06" src="https://user-images.githubusercontent.com/75962823/102046808-0ee52400-3e17-11eb-9816-cbde9fa3da2a.png">

Cause there is no buy/sell operations, the statistic results of predictions are `NaN` .
<img width="620" alt="截屏2020-12-14 下午2 14 28" src="https://user-images.githubusercontent.com/75962823/102046715-d2192d00-3e16-11eb-9184-3f89c325fd1d.png">

**Comment by zhupr** [comment]
@JeremyPKU  Hi，
What is the value of the `benchmark`? 
You can use the following code to get the benchmark data correctly: `D.features([benchmark], ["$close/Ref($close,1)-1"])`

**Comment by JeremyPKU** [comment]
@zhupr Hi,

The benchmark choices listed in the qlib doc are `SH000905 CSI 500`, but I need to benchmark with SPY&500. So I just input the custom benchmark data, with a type of `pandas.core.series.Series`. 

Just now, I added more logs and discovered that the reason for no trading was that all the symbols were specified as non-tradable. And the logs of `Exchange.codes` and `Exchange.quote` told that the market was set "all", but the quote was empty. Back to my data.bin, the `instruments/all.txt` and `calendars/day.txt` have correct date and symbols. Im working to figure out the data disappearance in `Exchange.quote`, and looking forward to your suggestions.

**Comment by zhupr** [comment]
@JeremyPKU 


> @zhupr Hi,
> 
> The benchmark choices listed in the qlib doc are `SH000905 CSI 500`, but I need to benchmark with SPY&500. So I just input the custom benchmark data, with a type of `pandas.core.series.Series`.
> 
> Just now, I added more logs and discovered that the reason for no trading was that all the symbols were specified as non-tradable. Back to my data.bin, the `instruments/all.txt` and `calendars/day.txt` have correct date and symbols. Im working to figure out the tradable check failure, and looking forward to your suggestions.

- If `exchange.quote` is empty, you can look at `exchange.py` *def set_quote*: D.features(codes, self.all_fields, start_date, end_date, disk_cache=True).dropna(subset=["$close"])
- `non-tradable`,  look at `exchange.py` *`def check_stock_suspended`*/*`def check_stock_limit`*

**Comment by JeremyPKU** [comment]
@zhupr 
Grateful for your suggestions!

- the non-tradable problem is attributed to the default parameter `limit_threshold`, which is not suitable to the US stock price changes. And that's resolved.
- another bug in benchmark data is that the length and index of the custom benchmark data should the same as test data. However, as I prepared my custom data, I kept the benchmark data a same scale of the total train-validation-test dataset. Im not sure whether other users will meet such a poor bug. Maybe it will be greater if you give out more directions on custom dataset and benchmark preparation, or even finish the data scaling before entering the analysis part.
- A last bug Id like to report is the index of `report_df` gained from `backtest.backtest`. As the example showed by the following figure, where I set the test time-scale from 2020-06-01 to 2020-09-25, but the time-index of `report_df` ranges from 2020-06-02 to 2020-09-25 , plus 1999-11-10.  A same length but one day different. 
<img width="982" alt="截屏2020-12-14 下午8 22 53" src="https://user-images.githubusercontent.com/75962823/102080856-28539380-3e4a-11eb-90b5-bf78b9ab31fb.png">

**Comment by you-n-g** [comment]
Hi,
@JeremyPKU 
Thanks for reporting.

- We'll try passing a benchmark series with longer length and check the result.
- It is hard to believe there appears the date 1999-11-10...  Can you print the value of [`predict_dates`](https://github.com/microsoft/qlib/blob/main/qlib/contrib/backtest/backtest.py#L56) when the bug appears. 


Thanks!

**Comment by JeremyPKU** [comment]
Hi,
Here is a screen shot for the `predict_dates` and the `report_df`. It seems that the bug day in `report_df` just meets exactly with the first day of the input dataset. The guess is also consistent with the scene where I input the custom dataset. 
<img width="506" alt="截屏2020-12-15 上午10 11 45" src="https://user-images.githubusercontent.com/75962823/102159474-989bfc80-3ebe-11eb-829a-eb49961a0a4a.png">
Thanks!

**Comment by JeremyPKU** [comment]
@zhupr Hi,

I just got some clues that might contribute to the problems.

- Its not the length of custom benchmark but the dytpe of benchmark series index that raise an error, the dytpe has to be decoded as timestamp when `read_csv`. Thats my carelessness to pass a benchmark series with object-type index.
- For the time scale differences in the test data, following may be a good instance to tell the bug. In the provided example pipeline, the test data timescale is set `"test": ("2017-01-01", "2020-08-01")`. But the `report_df` starts from 2017-01-04 and ends at 2020-08-03, with one trade-day delay. If the last day for the delayed `report_df` is not included in the total dataset, then the first day seems to be appended. 
<img width="759" alt="102314518-8e0c6080-3fad-11eb-93f1-8dcbdcedbaa9" src="https://user-images.githubusercontent.com/75962823/102440949-2e20c300-405c-11eb-81f3-f73f3890e1b4.png">
Please help to check and fix. 

Best wishes~

**Comment by you-n-g** [comment]
@zhupr  It seems we should check the data type of benchmark series

@JeremyPKU  
The delay of starting date is the expected behaviour
The first working day in 2017 is  Jan. 3rd. 
If we make prediction on Jan. 3rd, the earliest date we can trade is Jan 4th
![image](https://user-images.githubusercontent.com/465606/102442122-97093a80-405e-11eb-96ed-5bf328a38018.png)


We are solving other bugs (the issue of the non-existing last day) related to your other issue here https://github.com/microsoft/qlib/pull/125
We'll notifiy you when we are ready.

**Comment by you-n-g** [comment]
@JeremyPKU 
The  "non-existing last day" bug is fixed here  https://github.com/microsoft/qlib/pull/148

Please check it. Thanks!

**Comment by JeremyPKU** [comment]
Nice~
