### ISSUE TITLE
pit too slow

### ISSUE THREAD

**Issue by specialJeff** [microsoft/qlib#1168]
## ❓ Questions and Help

hi.
I use pit type data to calculate some financial factors like growth rate,asset ratio... but it took hours to do the calculations for less than 30 fundmental factors. Then I changed the freq to "month" ,but the tech factors can not be calculated. 
Blow is part of the code, where I changed a little in Alpha158 to add the calculation of about 30 financial factors.

data_handler_config = {"start_time":"2018-01-01",
                      "end_time":"2022-06-30",
                      "fit_start_time":"2018-01-01",
                      "fit_end_time":"2022-06-30",
                      "instruments":instruments,
                       "freq":"month",
                      }
h = Alpha158(**data_handler_config)

**Comment by you-n-g** [comment]
The current PIT calculation process is not optimized.   We may try to optimize it in the future if we have more bandwidth.
Your contribution is welcome (maybe you can start by contributing a test to demonstrate the performance issue). 

The frequency parameter for the handler can't be changed freely.  The underlying `bin` data frequency must be supported. (You can check what is supported in `~/.qlib/qlib_data/cn_data/calendars`)
