### ISSUE TITLE
Possibility to utilize categorical data

### ISSUE THREAD

**Issue by fyc0707** [microsoft/qlib#1172]
My feature dataset contains a lot of categorical data... I found qlib only supports float dump. Is there a practical way to dump and train with categorical data? Thanks in advance.

**Comment by you-n-g** [comment]
The underlying `.bin` data does not support categorical data directly. 
You may convert it to float before storing them 
Thanks.

**Comment by fyc0707** [comment]
> The underlying `.bin` data does not support categorical data directly. 
> You may convert it to float before storing them 
> Thanks.

Thanks so much for your reply. I'm giving it a try.
