### ISSUE TITLE
 "instruments " can't used when construct DataHandlerLP 

### ISSUE THREAD

**Issue by specialuse** [microsoft/qlib#1174]
hi,
 I use staticDataLoader to load dataframe in memory, then construct DataHandlerLP. But " instruments " can't used. codes are like this:
codes:
sdl = StaticDataLoader(config=df)  # df is a dataframe
ds = DataHandlerLP(instruments='csi300',start_time='20100101',end_time='20120601',data_loader=sdl)
ds construct filed.
but if i remove "instuments='csi300'" ,ds is ok.
I wonder why?  and how can I use "instuments" to choose stock sample?

thanks

**Comment by you-n-g** [comment]
Can you give your full error traceback? 
Thanks
