### ISSUE TITLE
expression using qlib.data.ops.features get different results

### ISSUE THREAD

**Issue by SpacedDot** [microsoft/qlib#1181]
## ❓ Questions and Help

```
>> from qlib.data import D
>> data = D.features(["sh600519"], ["(($high / $close) + ($open / $close)) * (($high / $close) + ($open / $close)) / ($high / $close) + ($open / $close)"], start_time="20200101")
```
![image](https://user-images.githubusercontent.com/90094434/177457832-17cce27c-fcef-49b1-8dd1-e05ecd3bf15b.png)
```
from qlib.data.ops import *
f1 = Feature("high") / Feature("close")
f2 = Feature("open") / Feature("close")
f3 = f1 + f2
f4 = f3 * f3 / f3
data = D.features(["sh600519"], [f4], start_time="20200101")
data.head()
```
![image](https://user-images.githubusercontent.com/90094434/177457871-ac2f1770-5e72-4c23-b6e8-5ba76270e85d.png)

I follow the instruction here: https://qlib.readthedocs.io/en/latest/start/getdata.html
Very strange two expressions get different results. I don't know if this is a bug or not.

**Comment by you-n-g** [comment]
Is this what you want? 
I think one pair of parentheses is missing.

"(($high / $close) + ($open / $close)) * (($high / $close) + ($open / $close)) / **(** ($high / $close) + ($open / $close) **)**"

**Comment by SpacedDot** [comment]
> Is this what you want? I think one pair of parentheses is missing.
> 
> "(($high / $close) + ($open / $close)) * (($high / $close) + ($open / $close)) / **(** ($high / $close) + ($open / $close) **)**"

Oh！ I didn't notice that. Thanks. I thought these two expression is the same. Apparently it's not.
Thank you very much.

And I think the tutorial author better fix it. It's kind of confusing....HH

**Comment by you-n-g** [comment]
Thanks.  It is fixed now.
Your contribution is also welcome :)
