### ISSUE TITLE
Misleading Error "Please install necessary libs for CatBoostModel."

### ISSUE THREAD

**Issue by you-n-g** [microsoft/qlib#1187]
## 🐛 Bug Description

Qlib does not require the installation of packages like `CatBoostModel`

But the output looks a little misleading.

## To Reproduce
Run `examples/workflow_by_code.ipynb` in jupyter notebook.

## Expected Behavior

Successfully run the script without installing CatBoostModel and warning.

## Screenshot
![image](https://user-images.githubusercontent.com/465606/177905185-57a43596-b180-4c52-8df9-0e88b95640b4.png)

**Comment by Derek-Wds** [comment]
Maybe we could do some like:
```python
class CatBoostModel:
    def __init__(self):
        try:
            from catboost import ***
        except ModuleNotFoundError:
            print("Warning.")
```
But I feel like this is not elegant enough and may be regarded as invalid in some format style like PEP8.
Here may be an alternative:
<img width="907" alt="image" src="https://user-images.githubusercontent.com/26081991/178068920-53b72697-beb5-41d1-be7f-a97c9583b8c7.png">

**Comment by OussCHE** [comment]
I've debugged the code , it is triggered if catboost is not installed. We can modify the warning to be similar to all other warnings (like when LGBModel or double_ensemble are not available)

I am still new to the library , so any advice would be appreciated.

 
![error_location](https://user-images.githubusercontent.com/72355098/180658434-6df96f03-5753-45cc-ab4e-93ee61f19915.PNG)

**Comment by you-n-g** [comment]
I think this language support may be useful to make this module cleaner.
We can have a unified implementation of  `__getattr__` to handle all kinds of imports.

https://stackoverflow.com/a/48916205
