### ISSUE TITLE
Are normalization reversible?

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#1194]
## ❓ Questions and Help
Suppose I use CSRankNorm on my labels, and I got scores as prediction results. Are these scores reversible, that I can calculate a label from a given score?

**Comment by you-n-g** [comment]
Qlib does not explicitly leave a hook to reverse the prediction to its original meaning before processing (a lot of trading strategies do not need such a step).
You can implement it in your own trading strategy (here is [an example](https://github.com/microsoft/qlib/blob/main/qlib/contrib/strategy/optimizer/enhanced_indexing.py#L114)).
