### ISSUE TITLE
how to create a feature expression which include a condition?

### ISSUE THREAD

**Issue by luzming** [microsoft/qlib#1195]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

I want to create a feature based on a condition ,e.g. 1 if $a>0 & $b>0 else 0. Sorry I searched but did not find a clue...

I intent to create a custom handler.

thank you!

**Comment by newlyedward** [comment]
可以直接调用
from qlib.data.ops import *
Operators.if(condition, feature_left, feature_right)

**Comment by you-n-g** [comment]
Hope this example will be helpful
 https://qlib.readthedocs.io/en/latest/start/getdata.html#api 
![image](https://user-images.githubusercontent.com/465606/179528371-47ef3c54-c5fe-41d3-a42a-587767893084.png)
