### ISSUE TITLE
report_graph plots no curves but only axis and legends

### ISSUE THREAD

**Issue by JeremyPKU** [microsoft/qlib#120]
## ❓ Questions and Help
Hi, me again.
This time I met a problem in the analysis process. All the other plots were perfect except `analysis_position.report_graph`, in which only axis and legends were presented without curves. The plot failure appeared both on the default dataset and custom dataset. I need your help to figure out whether its a constriction of my jupyter notebook that hide these curves, like package or environment differences or other reasons.

**Comment by you-n-g** [comment]
@JeremyPKU 
Hello, could you give us more info by running this script?
https://github.com/microsoft/qlib/blob/main/scripts/collect_info.py
`python collect_info.py all`

Thanks

**Comment by JeremyPKU** [comment]
Hi, 
    Here is my env info:
`Darwin
x86_64
Darwin-19.6.0-x86_64-i386-64bit
Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64

Python version: 3.7.4 (default, Aug 13 2019, 15:17:50)  [Clang 4.0.1 (tags/RELEASE_401/final)]

Qlib version: 0.6.0.dev
numpy==1.17.2
pandas==0.25.1
scipy==1.3.1
requests==2.22.0
sacred==0.8.1
pymongo==3.7.2
python-socketio==3.1.2
redis==3.5.3
python-redis-lock==3.7.0
schedule==0.6.0
cvxpy==1.0.21
hyperopt==0.1.1
fire==0.3.1
statsmodels==0.10.1
xlrd==1.2.0
plotly==4.12.0
matplotlib==3.1.1
tables==3.5.2
pyyaml==5.1.2
mlflow==1.12.1
tqdm==4.36.1
loguru==0.5.3
lightgbm==2.3.0
tornado==6.0.3
joblib==0.13.2
fire==0.3.1
ruamel.yaml==0.16.12`

Thanks!

**Comment by zhupr** [comment]
@JeremyPKU Hi,
Can you send the screenshots and output, it would be better if you can provide a sample of *`report_df`*

**Comment by JeremyPKU** [comment]
@zhupr Hi,
this is the `report_normal_df` gained from example pipeline, and the `analysis_position.report_graph` is still failed.
<img width="764" alt="截屏2020-12-16 下午2 46 54" src="https://user-images.githubusercontent.com/75962823/102314518-8e0c6080-3fad-11eb-93f1-8dcbdcedbaa9.png">

**Comment by you-n-g** [comment]
The data looks quite right....
Could you please provide the output of `report_normal_df.dtypes` ?
@JeremyPKU

**Comment by JeremyPKU** [comment]
Its a little frustrating hhhhh. Other figures are correctly plotted and the data is also right. So the env info of my jupyter is fine too?
`report_normal_df.dtypes`
<img width="215" alt="截屏2020-12-16 下午3 02 54" src="https://user-images.githubusercontent.com/75962823/102316114-505d0700-3fb0-11eb-81b0-da66edf6237a.png">

**Comment by zhupr** [comment]
@JeremyPKU Hi,
You can first update pandas to solve this problem: `pip install -U pandas`

It will be fixed in the `main` branch later, and PR has been mentioned

**Comment by JeremyPKU** [comment]
Nice~~

**Comment by you-n-g** [comment]
@JeremyPKU 
This bug will be fixed in this PR https://github.com/microsoft/qlib/pull/125/files#diff-19c3e93d3945f55afb0c4218634c7cdc0b0519ddad67b124c7ad6a077b8cbe5a

It is expected that lower version of pandas will also be right  after it is merged
