### ISSUE TITLE
请问数据下载下来之后数据如何在已下载的基础上增量更新？

### ISSUE THREAD

**Issue by caijynb** [microsoft/qlib#1218]
python scripts/get_data.py qlib_data --target_dir \~/.qlib/qlib_data/cn_data --region cn
直接运行该命令获取到的数据到2020-09-25为止，存放的目录是\~/.qlib/qlib_data/cn_data

如何在之前的数据基础上更新至2022-07-20
https://qlib.readthedocs.io/en/latest/component/data.html#data-preparation 该章节给出的命令是：
python scripts/data_collector/yahoo/collector.py update_data_to_bin --qlib_data_1d_dir <user data dir> --trading_date <start date> --end_date <end date>
替换掉参数后命令为：
python scripts/data_collector/yahoo/collector.py update_data_to_bin --qlib_data_1d_dir ~/.qlib/qlib_data/cn_data --trading_date 2020-09-25 --end_date 2022-07-20

运行报错：
_get_simple: 1 :name 'start_' is not defined

**Comment by caijynb** [comment]
如果更换命令的保存路径：python scripts/data_collector/yahoo/collector.py update_data_to_bin --qlib_data_1d_dir ~/test/cn_data --trading_date 2020-09-25 --end_date 2022-07-20

会下载数据再报错`get_simple: 1 :name 'start' is not defined`

且下载下来的数据依然是到2020-09-25为止

**Comment by Lay-du** [comment]
Hello，I'm having the same problem you had before，have you solved it？

**Comment by SunsetWolf** [comment]
Can [this PR](https://github.com/microsoft/qlib/pull/1257) help you?

**Comment by Alsac** [comment]
Maybe your qlib_data_1d_dir should be ~/.qlib/qlib_data/cn_data/, you lost the symbol "/" in the last。

**Comment by jeremy-feng** [comment]
Thanks to Alsac. This works for me:

```
python scripts/data_collector/yahoo/collector.py update_data_to_bin --qlib_data_1d_dir ~/.qlib/qlib_data/cn_data/ --trading_date 2020-09-26 --end_date 2023-04-08
```

**Comment by Jessie-Zhang123** [comment]
> 感谢阿尔萨克。这对我来说有效：
> 
> ```
> python scripts/data_collector/yahoo/collector.py update_data_to_bin --qlib_data_1d_dir ~/.qlib/qlib_data/cn_data/ --trading_date 2020-09-26 --end_date 2023-04-08
> ```

How long did it take you to download using this statement? It took me a long time to download using the same statement.
