### ISSUE TITLE
Simplify the command to download the data

### ISSUE THREAD

**Issue by you-n-g** [microsoft/qlib#1232]
## 🌟 Feature Description

Currently, user should use the following command to download the data.
![image](https://user-images.githubusercontent.com/465606/180944946-20cb4b7e-f46e-4ac6-8c03-621dcc261813.png)

This requires the following steps.
1. Install Qlib
2. clone the source code of Qlib
3.  Run the script to download the data

This can be simplified by integrating the downloading script into a Qlib module. So users can download data with only two steps
1. Install Qlib
2. Run qlib module to download data like this `python -m qlib.XXX.get_data qlib_data --target_dir ~/.qlib/qlib_data/cn_data --region cn`

**Comment by HyeongminMoon** [comment]
I tried this. Is this correct implementation what you intended?

**Comment by you-n-g** [comment]
Yes!
It is merged now!
