### ISSUE TITLE
在执行数据过滤器的时候响应时间非常慢

### ISSUE THREAD

**Issue by sh4j** [microsoft/qlib#1237]
请问，在使用ExpressionDFilter过滤器时，需要7分钟左右才可以得到响应。不知道是不是我的系统原因，还是我哪里少设置了参数， 在仔细查阅了官网文档，并没有发现有类似的解释。
qlib版本：0.8.6.99
python版本:3.9.10
系统：MacOS(M1 MAX arm)
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/31843172/181350263-b7f4772c-1e7d-43c7-8d77-ae1efc472f44.png">

**Comment by you-n-g** [comment]
Qlib 现在版本的  filter 确实  还有很多优化空间，

个人觉得主要可以优化的点如下
1. Fitler的选择 和 后面表达式的选择是串行的关系，  filter每个字段的选取和 数据字段的选取同样耗时。
2. 而且这里默认没有开启缓存。https://github.com/microsoft/qlib/blob/main/qlib/data/filter.py#L349


众人拾柴火焰高
