### ISSUE TITLE
I was wondering after training the model.  How do I export the model to onnyx so I can run inference on it in production?

### ISSUE THREAD

**Issue by will-berger** [microsoft/qlib#1240]
## ❓ Questions and Help

I was wondering after training the model.  How do I export the model to something like onnyx so I can install the model in production and run inference on it.

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

**Comment by you-n-g** [comment]
Qlib is just a framework and does not limit the underlying ML framework and computation resource. 

You can use [qlib model ](https://github.com/microsoft/qlib/blob/main/qlib/model/base.py) directly or use the [internal model ](https://github.com/microsoft/qlib/blob/main/qlib/contrib/model/pytorch_nn.py#L146) directly.
