### ISSUE TITLE
如果需要融合在模型里的feature本身就是由别的模型生产的，应该怎么把整个流程串起来？

### ISSUE THREAD

**Issue by TerrenceVarada** [microsoft/qlib#1243]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

看了一下qlib.data.ops，和get_feature_config的写法。是不是不太支持模型融合或者复杂feature的导入。是否在原有框架下有更灵活的自定义方案？

**Comment by you-n-g** [comment]
如果 feature 的格式 遵守  在特定时间戳， 特定股票上， 有一个数值， 可以把它像高开底收这种字段  导入系统 变成 `.bin` 文件。
