### ISSUE TITLE
HIST model is missing supportive file "qlib_csi300_stock2concept.npy"

### ISSUE THREAD

**Issue by hensejiang** [microsoft/qlib#1259]
## ❓ Questions and Help
This "stock2concept.npy" file is listed by HIST benchmark test yaml conf as well in the model sourcecode, while it appears not existing:
<img width="401" alt="image" src="https://user-images.githubusercontent.com/43102199/185749801-fedaf840-c2ee-4429-9ed4-8520703b09ab.png">

It's easy to find that in the specified folder that file does NOT exist:
<img width="401" alt="image" src="https://user-images.githubusercontent.com/43102199/185750078-4cbb2046-31c1-4871-8957-2dc5dee2542a.jpg">

Any idea? Thank you.

**Comment by hensejiang** [comment]
Oh, found the download link http://fintech.msra.cn/stock_data/downloads/qlib_csi300_stock2concept.npy
This is solved. Will close this issue.

**Comment by berisfu** [comment]
> Oh, found the download link http://fintech.msra.cn/stock_data/downloads/qlib_csi300_stock2concept.npy This is solved. Will close this issue.

it's no longer accessible.

**Comment by Boneflame** [comment]
> > Oh, found the download link http://fintech.msra.cn/stock_data/downloads/qlib_csi300_stock2concept.npy This is solved. Will close this issue.
> 
> it's no longer accessible.

I found it in the HIST's author's repo:
https://github.com/Wentao-Xu/HIST/blob/main/data/csi300_stock2concept.npy
