### ISSUE TITLE
HIST: weight calculation for the concept representation

### ISSUE THREAD

**Issue by EternalConfession** [microsoft/qlib#1261]
As described in the article, the concept representation is calculated due to the capitalization of stocks.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/16853865/186107490-c2c70956-f85b-4c58-9b10-7a44230fa7dc.png">

But I didn't see capitalization of stocks in the code as in: 

https://github.com/microsoft/qlib/blob/e78fe48a262b0f65ceabba4e0ce8a169b716dbc7/qlib/contrib/model/pytorch_hist.py#L447

Will this have an influence on the result?

**Comment by pop0121** [comment]
According to my understanding, after reading the code, it uses some way to approximate the market capitalization based weights.
