### ISSUE TITLE
关于指数数据获取的疑问

### ISSUE THREAD

**Issue by louis-xuy** [microsoft/qlib#1274]
在获取指数成分股获取脚本 index.py的164行的这部分代码，我认为是有问题的， 不应该用reverse，判断股票是否被删除或者新增加， 应该是和上一次的数据比较，reverse 之后，那每次比较的对象就错了

![捕获](https://user-images.githubusercontent.com/8952852/187685251-a53e0181-9cac-43a0-a11a-174c0f6f7ee2.PNG)

**Comment by SunsetWolf** [comment]
Sorry for taking so long to reply to your issue. I don't think it is a problem to use `reverse=True`.
The reason for this is that there are two fields in `history_companies`: date and symbol.
`reverse=True` keeps the `last_code` list of symbols with newer dates and the `_currenet_code` list of symbols with older dates. This will ensure that `add_code` and `remote_code` are calculated correctly.
I hope my reply helps, thank you!
