### ISSUE TITLE
Are there any classification benchmark results in qlib evaluated in ACC, MCC, F1?

### ISSUE THREAD

**Issue by Waterkin** [microsoft/qlib#1277]
Hi, I am wondering whether there are any classification results for researchers to refer to. And can I use benchmark models to predict the rise and fall of a stock? How can I do that?
Thanks~

**Comment by pop0121** [comment]
I'm interested in this research direction too. I think, possibly, classifiers, or mulitple classifiers, may give better training signals than MSE regression learning objective. 

Moreover, if the classic TopKDropout strategy is used, then it is natural to come to a simple classification objective.
