### ISSUE TITLE
Process 'Killed' running your example

### ISSUE THREAD

**Issue by AnonymousJY** [microsoft/qlib#128]
## ❓ Questions and Help

Hi,

I allocated 4GB RAM in a VM to run your example `qrun benchmarks/LightGBM/workflow_config_lightgbm_Alpha158.yaml` and the process was 'killed'. 
![Screen Shot 2020-12-16 at 10 58 31](https://user-images.githubusercontent.com/36392746/102373018-c69c4200-3f8d-11eb-8942-c8bd826f2263.png)

I'm not certain if it is RAM issue but I suspect it is. Is there a requirement of RAM size?

Thanks.

**Comment by you-n-g** [comment]
@AnonymousJY 
Qlib list the requirements here `https://github.com/microsoft/qlib/blob/main/examples/README.md`

**Comment by AnonymousJY** [comment]
> @AnonymousJY
> Qlib list the requirements here `https://github.com/microsoft/qlib/blob/main/examples/README.md`

@you-n-g Thanks.
