### ISSUE TITLE
Demo link from the Quick Start section doesn't work

### ISSUE THREAD

**Issue by kimwei** [microsoft/qlib#1280]
## 📖 Documentation

The 'demo' link (https://terminalizer.com/view/3f24561a4470) from the Quick Start section of the documentation doesn't work.

Raw docs:
```
Here is a quick demo shows how to install Qlib......
```

**Comment by SunsetWolf** [comment]
I didn't find the problem you mentioned, the 'demo' link you mentioned is working fine.
![image](https://user-images.githubusercontent.com/30293408/199238225-9f1ccb5f-be6a-4817-aa04-648d416b2b67.png)
