### ISSUE TITLE
Can Qlib automatically generator the trading strategy base on the real history data and the predict data from the predict models?

### ISSUE THREAD

**Issue by joshua-xia** [microsoft/qlib#1281]
## 🌟 Feature Description
In the most situation, I have the real history data and the predict data from the predict models, those datas can be used as features, and my objective is to max the Sharpe Ratio or Sortino Ratio and the Retures, I knew there are some trading strategy template, and we can optimize the trading strategy parameters. but I think the best way is to use algorithm to generate the optimal trading strategy automatically.

**Comment by you-n-g** [comment]
Hi,  IIUC,
A strategy is a function that input trading signal and outputs trading decision.
Generating a strategy meaning selecting the parameters in a specific strategy hypothesis space.
Qlib has some off-the-shelf strategies with configurable parameters.
Though it currently does not provide methods to automatically select its parameters, it provides [some examples](https://github.com/microsoft/qlib/tree/main/examples/hyperparameter/LightGBM) to search parameters based on third-party libraries.   

You can easily meet your requirements by adding the strategies' hyperparameters into the search space.

**Comment by SunsetWolf** [comment]
You can read the [Record Template](https://qlib.readthedocs.io/en/latest/component/recorder.html#record-template) section of the documentation to learn how to set the parameters of the backtest.
