### ISSUE TITLE
Can i use a dataset other than the one provided by Qlib to learn the model? 

### ISSUE THREAD

**Issue by Haaae** [microsoft/qlib#1284]
## ❓ Questions and Help
Can I use a dataset other than the one provided by Qlib to learn the model?
If possible, is it correct to follow the contents of [Converting CSV Format into Qlib Format](https://qlib.readthedocs.io/en/latest/component/data.html#converting-csv-format-into-qlib-format)?

**Comment by SunsetWolf** [comment]
Yes, in addition to the data provided by Qlib, you can also prepare your own data, [convert it to Qlib format](https://qlib.readthedocs.io/en/latest/component/data.html#converting-csv-format-into-qlib-format), and use it to learn the model.

**Comment by kkwLiu** [comment]
> Sure, but u also have another choice, just try [StaticDataLoader](https://github.com/microsoft/qlib/blob/fb5888be9ee976c3e3879e7298e3a0a1030db37e/qlib/data/dataset/loader.py#L220-L271). It's more convenient because u needn‘t convert ur own data into Qlib format.

hello, i am wondering how i can train the models after loading my pickle file by staticdataloader, i am quite a green hand... could you please give me more instructions?
