### ISSUE TITLE
How to control the time range (T) of the input?

### ISSUE THREAD

**Issue by Gwan-Siu** [microsoft/qlib#1286]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

For financial time series data, the input size is (N, F, T). How to control the value of T?

**Comment by ELKYang** [comment]
Have u solved this question? I have the same question as u.

**Comment by Gwan-Siu** [comment]
> 

No, I am still investing. Do you solve this problem?

**Comment by ELKYang** [comment]
u can use TSDataset to control the temporal length.



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 10/14/2022 15:11 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [microsoft/qlib] How to control the time range (T) of the input? (Issue #1286) |

No, I am still investing. Do you solve this problem?

**Comment by you-n-g** [comment]
For the underlying data,  it is tabular data  <stock, absolute timestamp, feature>,
when you say ` (N, F, T)`,  I guess you are referring `<sample, feature, relative timestamp>`.
The relative timestamp is different from the absolute timestamp, but we can create `<sample, feature, relative timestamp>`  from the tabular data  `<stock, absolute timestamp, feature>`, which [TSDataset](https://github.com/microsoft/qlib/blob/c4ee9ff88266665046d78e3f338f35a4c0afb8d4/qlib/data/dataset/__init__.py#L643)  is responsible for it. 
I think [step_len](https://github.com/microsoft/qlib/blob/c4ee9ff88266665046d78e3f338f35a4c0afb8d4/qlib/data/dataset/__init__.py#L665) is what you are looking for.
