### ISSUE TITLE
关于强化学习单元测试数据集的疑问

### ISSUE THREAD

**Issue by myl17** [microsoft/qlib#1290]
请问可以提供一下强化学习单元测试部分（test_saoe_simple.py）的数据处理脚本吗？尝试使用高频数据脚本处理后的数据进行ppo训练，但单元测试失败了，推测可能是因为数据格式不对导致训练失败

**Comment by 280777510** [comment]
> 请问可以提供一下强化学习单元测试部分（test_saoe_simple.py）的数据处理脚本吗？尝试使用高频数据脚本处理后的数据进行ppo训练，但单元测试失败了，推测可能是因为数据格式不对导致训练失败

您好，你Qlib是安装在win10上的？可以加个好友请问下安装问题？

**Comment by you-n-g** [comment]
您好， 可以参考 CI  里面的数据下载内容 https://github.com/microsoft/qlib/blob/main/.github/workflows/test_qlib_from_source.yml#L127 

我们的RL 模块还在积极开发中，欢迎关注我们最新的开发进展& 积极反馈
