### ISSUE TITLE
Difference between signal and indicator?

### ISSUE THREAD

**Issue by pop0121** [microsoft/qlib#1292]
It seems to me that the concept "indicator" is only related to Reinforcenmen Learning approaches?

## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

**Comment by you-n-g** [comment]
Can you tell us the source of the word concept `indicator`?

**Comment by pop0121** [comment]
I think this concept is mostly used in `backtest` and `executor`. 

For instance, in `BaseExecturor`, there is this code snippet:
![屏幕快照 2022-11-27 上午9 52 42](https://user-images.githubusercontent.com/2706109/204117205-0ab7bed7-9ad7-4dfc-a8bf-30f905bc3ba7.png)

And in `backtest_loop`, there is this code snippet:
![屏幕快照 2022-11-27 上午9 52 53](https://user-images.githubusercontent.com/2706109/204117212-0e11c18a-bf26-43ac-9a96-32133d6d04c2.png)
