### ISSUE TITLE
能通过更改yaml文件的qlib.contrib.data.handler路径，使用本地开发的因子数据集嘛?

### ISSUE THREAD

**Issue by sorotiger** [microsoft/qlib#1295]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

**Comment by pop0121** [comment]
可以修改provider_uri来切换数据集，修改handler主要是从数据到因子和学习目标的加工过程
