### ISSUE TITLE
用标准化后的标签还是原始收益率标签来生成累计收益率图表？

### ISSUE THREAD

**Issue by quantcn** [microsoft/qlib#1296]
在例子文件workflow_by_code.ipynb生成累计收益率图表的代码是：
label_df = dataset.prepare("test", col_set="label")
label_df.columns = ['label']

pred_label = pd.concat([label_df, pred_df], axis=1, sort=True).reindex(label_df.index)
analysis_model.model_performance_graph(pred_label) # 生成累计收益率图表
我的问题是，这里label_df 取得的标签label是预处理后（比如经过标准化处理）的推理数据集标签，并不是原始的收益率，那么据此生成累计收益率图表是不是不合适，我觉得应该采用原始label（代表未经标准化处理的原始收益率）来生成累计收益率图表。
不知我的理解对否？

**Comment by fyc0707** [comment]
model_performance_graph不生成累计收益率相关的图吧

**Comment by lerit** [comment]
为何是经过预处理的呢,prepare的data_key用于指定预处理方式,你这里并没有指定,我认为并未预处理,不想下面这种:
```
dataset.prepare("test", col_set=["feature", "label"], data_key=DataHandlerLP.DK_I)
```

**Comment by fyc0707** [comment]
> 

data_key默认就是DK_I吧
