### ISSUE TITLE
model.get_feature_importance() return column_xx not features name

### ISSUE THREAD

**Issue by quantcn** [microsoft/qlib#1297]
get_feature_importance() will return importance value of column_xx not features' name. How to make it return importance value of features' name.

**Comment by SunsetWolf** [comment]
Sorry for the late reply to your issue. You can use `dataset.handler.get_feature_config()` to get the features' name, and then replace column_xx with features' name, here is the script:
```
feature_importance = model.get_feature_importance()
fea_expr, fea_name = dataset.handler.get_feature_config()
feature_importance = {fea_name[int(i.split("_")[1])]: v for i,v in feature_importance.items()}
```
