### ISSUE TITLE
Alpha360 data preprocess does not work. Problem may come from ZScoreNorm

### ISSUE THREAD

**Issue by quantcn** [microsoft/qlib#1306]
Hi, I have run the example workflow_by_code.ipynb. pls note that I added infer_processors in the data_handler_config as following: 
data_handler_config = {
    "start_time": "2008-01-01",
    "end_time": "2010-12-31",
    "fit_start_time": "2008-01-01",
    "fit_end_time": "2008-12-31",
    "instruments": stockpool,
    
    "infer_processors": [
    {"class": "ProcessInf", "kwargs": {}},
    {"class": "ZScoreNorm", "kwargs": {}},
    {"class": "Fillna", "kwargs": {}},
    ],
    "learn_processors": [
    {"class": "DropnaLabel"},
    {"class": "CSZScoreNorm", "kwargs": {"fields_group": "label"}},
    ] ,
    "label": ["Ref($close, -2) / Ref($close, -1) - 1"]
}

# 任务参数配置
task = {

    "dataset": {  #　因子库数据集参数配置
        # 数据集类，是Dataset with Data(H)andler的缩写，即带数据处理器的数据集
        "class": "DatasetH",
        # 数据集类所在模块
        "module_path": "qlib.data.dataset",
        # 数据集参数配置，这些参数传给数据集类
        "kwargs": { 
            "handler": { # 数据集使用的数据处理器配置
                "class": "Alpha158", # 数据处理器类，继承自DataHandlerLP
                "module_path": "qlib.contrib.data.handler", # 数据处理器类所在模块
                "kwargs": data_handler_config, # 数据处理器参数配置
            },
            "segments": { # 数据集划分标准
                "train": ("2008-01-01", "2008-12-31"), # 此时段的数据为训练集
                "valid": ("2009-01-01", "2009-12-31"), # 此时段的数据为验证集
                "test": ("2010-01-01", "2010-12-31"),  # 此时段的数据为测试集
            },
        },
    },
}

When I changed the handler to Alpha360 in the handler config section. I checked the results of the following statements.
dataset.prepare('test', data_key='raw')
dataset.prepare('test', data_key='infer')

I found that the results are the same which should be different. It seems the test data isn't preprocessed.

If I changed the hander to Alpha158, then the results are different. So, it seems that Alpha360's data preprocess doesn't work while Alpha158 does.

After some debug, I think the problem comes from class ZScoreNorm. I modified a line, please see the comment in the code.

`class ZScoreNorm(Processor):

    def __call__(self, df):
        def normalize(x, mean_train=self.mean_train, std_train=self.std_train, ignore=self.ignore):
            print('ignore',ignore)
            if (~ignore).all():             
                return (x - mean_train) / std_train
            for i in range(ignore.size):  
                if not ignore[i]:
                    # x[i] = (x[i] - mean_train) / std_train # Error, should be modified
                    x[:, i] = (x[:,i] - mean_train[i]) / std_train[i] # This is correct
   
            return x
        df.loc(axis=1)[self.cols] = normalize(df[self.cols].values)
        return df`

**Comment by pop0121** [comment]
I'm suspecting that the issue you mentioned may due to the fit date range you set, though not 100% sure. Maybe we can discuss a bit. 

If you are using `append` mode in `Processor`, the learning processors will automiatically include the inference procerssors. 

When you have this setting:
`
"fit_start_time": "2008-01-01",
"fit_end_time": "2008-12-31",
`
and
`
"valid": ("2009-01-01", "2009-12-31"),
`
then the valid data would not go through the learning processors with "learnable prarameters" anymore. 

But I'm also interested in your suggeted modifications, which seems quite reasonable. 

Hope someone would confirm this issue.

**Comment by quantcn** [comment]
It seems class MinMaxNorm has the same problem

**Comment by SunsetWolf** [comment]
Will [this PR](https://github.com/microsoft/qlib/pull/1398) solve your problem?
