### ISSUE TITLE
Don't use `.values` to try to modify the values.

### ISSUE THREAD

**Issue by pop0121** [microsoft/qlib#1307]
After about 10 hours of debugging, I finally located an severe issue regarding to the use of `.values` when make value assignment in the built-in `Processor` (precisely, `Fillna`). 

It is very dangerous to use `.values` to modify the data in the `DataFrame`. So I suggest maybe it's better to convert back to the conventional `df[col] = xxx` way of value assignments, and do not sacrifice safety for speed. 

Code:
```
df.values[nan_select] = self.fill_value
```

Ref:
https://stackoverflow.com/questions/55709890/why-does-value-assignment-silently-fail-or-do-the-wrong-thing-and-how-can-i-stop

## To Reproduce

1.
1.
1.

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version:
 - Python version:
 - OS (`Windows`, `Linux`, `MacOS`):
 - Commit number (optional, please provide it if you are using the dev version):

**Comment by SunsetWolf** [comment]
OK, thanks for the heads up, I think the `.values` in the reference is not working because of the data type issue. I don't understand where the danger of using `.values` as you describe comes from?

**Comment by wangxk15** [comment]
Same issue here! The df.values is not working in the Fillna processor!! It took me hours to find this reason. After revising the __call__function, the nan values disappear.
