### ISSUE TITLE
can provide another much smaller sample dataset?

### ISSUE THREAD

**Issue by davidxiao** [microsoft/qlib#131]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

As a starter with quantitative trading, I'd like to play with Qlib sample in my laptop with limited resources, while it requires 16GB memory to walk through the current sample, which blocks me playing and learning it with limited resource, at least at early stage.
So, is it possible to provide another much smaller data set sample?
Personally, the sample mainly demo how it works instead of bad/good performance.

Thanks

**Comment by zhupr** [comment]
@davidxiao Hi,
The recommendation is 16G memory, a smaller memory should also be possible.

There is a small data set, which is only used in the `test`, you can use it to run through the entire process: 
```bash
python get_data.py qlib_data --name qlib_data_simple --version latest --interval 1d --region cn
```

**Comment by davidxiao** [comment]
Hi, @zhupr ,
   Thanks, nice,
   It's be great if could add related info in document, so it's easy for other people

  Pls feel free to close it.
