### ISSUE TITLE
怎样排除指数参与训练？回测时，如何排除指数？

### ISSUE THREAD

**Issue by quantcn** [microsoft/qlib#1311]
请问模型训练时，怎样排除指数，比如沪深300指数SH000300？
另外，回测时，如何排除指数，也就是不要交易指数？

**Comment by SunsetWolf** [comment]
This question depends on your actual code. and the data you are using.
You can use `qlib.data.filter.NameDFilter`, write regular expressions, and exclude indices,
Put it in the `filter_pipe` list in `data_handler_config`.
The `benchmark` is used to [calculate the excess return](https://github.com/microsoft/qlib/blob/main/qlib/workflow/record_temp.py#L492-L497) during backtesting.
If you use the historical data provided by qlib, and the `market` is set to `csi300`, then the training process does not include the index data, which you can see in `instruments/csi300.txt`.

**Comment by hugo2046** [comment]
自己把instruments中的all.txt复制一下重命名为pool.txt,并把里面的指数删掉就行
