### ISSUE TITLE
一个很好的第三方编写的Qlib中文技术教程

### ISSUE THREAD

**Issue by quantcn** [microsoft/qlib#1315]
Qlib是非常强大的AI量化投研平台，可惜以往缺乏中文技术教程。
现在有第三方发布了第一个系统化的中文视频教程：“[扫地僧AI量化平台Qlib给力教程系列一：核心篇](https://zhuanlan.zhihu.com/p/572943571)”，感兴趣的用户可以参考。
[也可参考这里](https://ke.qq.com/course/5838458#term_id=106051065)。

**Comment by wangze586** [comment]
一般般, 想学的新手看官方教程

**Comment by quantcn** [comment]
看官方教程绝没有看这个容易入门。有些东西官方教程没讲，比如怎样通过web页查看实验结果。

**Comment by quant2008** [comment]
> Qlib是非常强大的AI量化投研平台，可惜以往缺乏中文技术教程。 现在有第三方发布了第一个系统化的中文视频教程：“[扫地僧AI量化平台Qlib给力教程系列一：核心篇](https://zhuanlan.zhihu.com/p/572943571)”，感兴趣的用户可以参考。 [也可参考这里](https://ke.qq.com/course/5838458#term_id=106051065)。

看了课程，对我来说非常有用。很多英文文档看不明白的东西，看了视频立马就理解了。之前看英文文档一直没太搞明白预测回测过程中产生的中间结果文件存在哪里，怎么重复利用，看了这个视频终于明白了。

**Comment by you-n-g** [comment]
非常欢迎这种帮助科普 Qlib 的文档，
如果大家愿意一起把相关的内容补充到Qlib的官方文档就更好啦！ 
众人拾柴火焰高！ 😃

**Comment by ling1042133624** [comment]
卖课。刚刚看了一下，全部课加起来，2000块左右

**Comment by bones1234567** [comment]
一看就是广告

**Comment by berisfu** [comment]
不要脸。卖课的，还死贵

**Comment by mmschzs** [comment]
不要脸。卖课的，还死贵

**Comment by mmschzs** [comment]
不要脸。卖课的，还死贵。

**Comment by CyAlcher** [comment]
不要脸。卖课的，还死贵。

**Comment by aoowoo** [comment]
你真是活全家了

**Comment by ZhanRao** [comment]
上面就是一个卖课，价格贼贵，不要脸
