### ISSUE TITLE
Only for AI driven? or open to traditional strategies as well?

### ISSUE THREAD

**Issue by davidxiao** [microsoft/qlib#132]
Seems a stupid question,
But out of curiosity, if I'd like to combine both traditional and AI-driven strategies, what consistent practice will be?

**Comment by you-n-g** [comment]
The interface is compatible with traditionl methods.
For exmaple, user could also use linear models for forecasting
https://github.com/microsoft/qlib/blob/main/examples/benchmarks/README.md

We are also try to include traidition [risk control methods](https://github.com/microsoft/qlib/tree/main/qlib/portfolio). 

Thanks for your attention to Qlib.
