### ISSUE TITLE
CSI500 SH000905 missing when downloading data from Yahoo

### ISSUE THREAD

**Issue by davide97l** [microsoft/qlib#1323]
I downloaded the Chinese data from Yahoo up to 2022 using the command `python collector.py download_data --source_dir ~/.qlib/stock_data/source/cn_data --start 2020-01-01 --end 2022-10-10 --delay 1 --interval 1d --region CN` as suggested [here](https://github.com/microsoft/qlib/tree/main/scripts/data_collector/yahoo#collector-yahoofinance-data-to-qlib).

After repeating the process twice  I noticed that the benchmark for the CSI500 index, which is SH000905 is missing from the downloaded data. However the. SH000300 of the CSI300 index is normally present. Is there something wrong with my procedure?

Similarly, when I try to download the updated instruments following the instructions [here](https://github.com/microsoft/qlib/tree/main/scripts/data_collector/cn_index#collector-data), the benchmark index is always missing.

Thank you in advance for your help!

**Comment by davide97l** [comment]
Hello? Is someone active here?

**Comment by SunsetWolf** [comment]
Hi, I also encountered the same problem, you can add the csi500 index code [here](https://github.com/microsoft/qlib/blob/main/scripts/data_collector/yahoo/collector.py#L226), which can solve the problem.
You can also submit a pr, fix the problem, and become a contributor to qlib.
