### ISSUE TITLE
redis connection failed(host=127.0.0.1 port=6379), cache will not be used!

### ISSUE THREAD

**Issue by specialuse** [microsoft/qlib#133]
hi,
when I initialize qlib, qlib.init(provider_uri=provider_uri, region=REG_CN), there is a warning that I am not sure if it is matters :  
[23416:MainThread](2020-12-18 08:56:05,312) WARNING - qlib.Initialization - [__init__.py:58] - redis connection failed(host=127.0.0.1 port=6379), cache will not be used!

**Comment by you-n-g** [comment]
@specialuse 
Qlib use some lock mechanism based on redis to manage cache.
If you don't have a redis-server , you can also use Qlib successfully without cache.

**Comment by specialuse** [comment]
thanks

> @specialuse
> Qlib use some lock mechanism based on redis to manage cache.
> If you don't have a redis-server , you can also use Qlib successfully without cache.

thanks

**Comment by BigW** [comment]
Hi - I get a similar error that results in my process getting killed despite the comments above that you can use Qlib successfully without cache. Any help welcome as I have tried to run this a couple of times ending in the process getting killed in terminal or the kernel dropping in Jupyter. Thank you!
`(QLIB3TEST) warren@warren-VivoBook-ASUSLaptop-X512DA-X512DA:~$ cd qlib
(QLIB3TEST) warren@warren-VivoBook-ASUSLaptop-X512DA-X512DA:~/qlib$ ls
CHANGES.rst	    docs      LICENSE  qlib_data  scripts      setup.py
CODE_OF_CONDUCT.md  examples  qlib     README.md  SECURITY.md  tests
(QLIB3TEST) warren@warren-VivoBook-ASUSLaptop-X512DA-X512DA:~/qlib$ cd examples
(QLIB3TEST) warren@warren-VivoBook-ASUSLaptop-X512DA-X512DA:~/qlib/examples$ ls
benchmarks  mlruns     run_all_model.py        workflow_by_code.py
highfreq    README.md  workflow_by_code.ipynb
(QLIB3TEST) warren@warren-VivoBook-ASUSLaptop-X512DA-X512DA:~/qlib/examples$ cd benchmarks
(QLIB3TEST) warren@warren-VivoBook-ASUSLaptop-X512DA-X512DA:~/qlib/examples/benchmarks$ ls
ALSTM	  DoubleEnsemble  GRU	    Linear  MLP        SFM     TFT
CatBoost  GATs		  LightGBM  LSTM    README.md  TabNet  XGBoost
(QLIB3TEST) warren@warren-VivoBook-ASUSLaptop-X512DA-X512DA:~/qlib/examples/benchmarks$ cd LightGBM
(QLIB3TEST) warren@warren-VivoBook-ASUSLaptop-X512DA-X512DA:~/qlib/examples/benchmarks/LightGBM$ ls
mlruns		  workflow_config_lightgbm_Alpha158.yaml
README.md	  workflow_config_lightgbm_Alpha360.yaml
requirements.txt
(QLIB3TEST) warren@warren-VivoBook-ASUSLaptop-X512DA-X512DA:~/qlib/examples/benchmarks/LightGBM$ qrun workflow_config_lightgbm_Alpha360.yaml
[4046:MainThread](2021-03-19 22:21:52,853) INFO - qlib.Initialization - [config.py:276] - default_conf: client.
[4046:MainThread](2021-03-19 22:21:52,854) WARNING - qlib.Initialization - [config.py:291] - redis connection failed(host=127.0.0.1 port=6379), cache will not be used!
[4046:MainThread](2021-03-19 22:21:52,855) INFO - qlib.Initialization - [__init__.py:46] - qlib successfully initialized based on client settings.
[4046:MainThread](2021-03-19 22:21:52,855) INFO - qlib.Initialization - [__init__.py:47] - data_path=/home/warren/.qlib/qlib_data/cn_data
[4046:MainThread](2021-03-19 22:23:10,497) INFO - qlib.timer - [log.py:81] - Time cost: 77.410s | Loading data Done
Killed
(QLIB3TEST) warren@warren-VivoBook-ASUSLaptop-X512DA-X512DA:~/qlib/examples/benchmarks/LightGBM$ 
`

**Comment by BigW** [comment]
> Hi - I get a similar error that results in my process getting killed despite the comments above that you can use Qlib successfully without cache. Any help welcome as I have tried to run this a couple of times ending in the process getting killed in terminal or the kernel dropping in Jupyter. Thank you!
> `(QLIB3TEST) warren@warren-VivoBook-ASUSLaptop-X512DA-X512DA:~$ cd qlib (QLIB3TEST) warren@warren-VivoBook-ASUSLaptop-X512DA-X512DA:~/qlib$ ls CHANGES.rst docs LICENSE qlib_data scripts setup.py CODE_OF_CONDUCT.md examples qlib README.md SECURITY.md tests (QLIB3TEST) warren@warren-VivoBook-ASUSLaptop-X512DA-X512DA:~/qlib$ cd examples (QLIB3TEST) warren@warren-VivoBook-ASUSLaptop-X512DA-X512DA:~/qlib/examples$ ls benchmarks mlruns run_all_model.py workflow_by_code.py highfreq README.md workflow_by_code.ipynb (QLIB3TEST) warren@warren-VivoBook-ASUSLaptop-X512DA-X512DA:~/qlib/examples$ cd benchmarks (QLIB3TEST) warren@warren-VivoBook-ASUSLaptop-X512DA-X512DA:~/qlib/examples/benchmarks$ ls ALSTM DoubleEnsemble GRU Linear MLP SFM TFT CatBoost GATs LightGBM LSTM README.md TabNet XGBoost (QLIB3TEST) warren@warren-VivoBook-ASUSLaptop-X512DA-X512DA:~/qlib/examples/benchmarks$ cd LightGBM (QLIB3TEST) warren@warren-VivoBook-ASUSLaptop-X512DA-X512DA:~/qlib/examples/benchmarks/LightGBM$ ls mlruns workflow_config_lightgbm_Alpha158.yaml README.md workflow_config_lightgbm_Alpha360.yaml requirements.txt (QLIB3TEST) warren@warren-VivoBook-ASUSLaptop-X512DA-X512DA:~/qlib/examples/benchmarks/LightGBM$ qrun workflow_config_lightgbm_Alpha360.yaml [4046:MainThread](2021-03-19 22:21:52,853) INFO - qlib.Initialization - [config.py:276] - default_conf: client. [4046:MainThread](2021-03-19 22:21:52,854) WARNING - qlib.Initialization - [config.py:291] - redis connection failed(host=127.0.0.1 port=6379), cache will not be used! [4046:MainThread](2021-03-19 22:21:52,855) INFO - qlib.Initialization - [__init__.py:46] - qlib successfully initialized based on client settings. [4046:MainThread](2021-03-19 22:21:52,855) INFO - qlib.Initialization - [__init__.py:47] - data_path=/home/warren/.qlib/qlib_data/cn_data [4046:MainThread](2021-03-19 22:23:10,497) INFO - qlib.timer - [log.py:81] - Time cost: 77.410s | Loading data Done Killed (QLIB3TEST) warren@warren-VivoBook-ASUSLaptop-X512DA-X512DA:~/qlib/examples/benchmarks/LightGBM$ `

Ubuntu users may have firewall issues and try ```sudo ufw disable``` to resolve this
