### ISSUE TITLE
D.features is 100x slower than pandas.

### ISSUE THREAD

**Issue by sailxjx** [microsoft/qlib#1343]
I compared qlib's D.features with the original pandas function and was surprised to find that `D.features` is 100 times slower than pandas.

How does this happen and how can I speed up qlib's query function?

<img width="1193" alt="Screen Shot 2022-11-09 at 10 06 25" src="https://user-images.githubusercontent.com/909853/200719981-d9a6e084-74c0-4ff9-b402-0f3999a2446d.png">

**Comment by sailxjx** [comment]
As a complement, the shape of the entire dataset is (8664, 5)

**Comment by ChiahungTai** [comment]
Did the df is already loaded from file?
The D.feature is including the time of loading from files.
In this case, (2*5 + 1) files, I guess.

**Comment by sailxjx** [comment]
Yes, df is from memory.

How can we use some features of D.features (like pass csi500 as a stock pool) at the same time without losing performance?

Or can we only use D.features and data handler for preprocessing, use dataset.prepare to get the pandas dataframe, then query the dataframe by the original apis of pandas? That will loss a lot of benefits of qlib's data processing.

**Comment by bxdd** [comment]
In ur example, qlib and pandas do completely different things. I think it's not rational to compare constructing features by qlib and slicing df by pandas.

**Comment by pop0121** [comment]
In qlib's design, there is `LocalFeatureProvider` that wraps `D.features` to load the entire dataset from disk to memory, while the rest of the data pipeline (including `DataHandler` and `Dataset` etc.) relies on in-memory DataFrame. 

However, you can implement your own `DataHandler` or `Dataset` to load data as demand from disk (but that would be quite a lot work I guess).
