### ISSUE TITLE
the lastest date is 2020-09-25, are there some data rolling errors?

### ISSUE THREAD

**Issue by liufeirong** [microsoft/qlib#136]

**Comment by you-n-g** [comment]
Hello, 
What do you mean by `data rolling errors`.
Thanks.

**Comment by liufeirong** [comment]
The alpha158's lastest  date is 2020-09-25,but raw data is 2020-12-18,i guess that the return result's date index exists  bug  in rolling.pyx

**Comment by you-n-g** [comment]
Thanks for reporting.

The latest date depends not only the end date of the data, but also the test end date https://github.com/microsoft/qlib/blob/main/examples/benchmarks/LightGBM/workflow_config_lightgbm_Alpha158.yaml#L53

**Comment by liufeirong** [comment]
I had setted  the data config end_time to 2020-12-18. 

import qlib
from qlib.contrib.data.handler import Alpha158
data_handler_config = {
    "start_time": "2014-01-01",
    "end_time": "2020-12-18",
    "fit_start_time": "2008-01-01",
    "fit_end_time": "2014-12-31",
    "instruments": "csi300",
}
if __name__ == "__main__":
    qlib.init()
    h = Alpha158(**data_handler_config)

    # get all the columns of the data
    print(h.get_cols())

    # fetch all the labels
    print(h.fetch(col_set="label"))

    # fetch all the features
    print(h.fetch(col_set="feature”))

h.fetch(col_set="feature").tail()

The result displays that:
		KMID	KLEN	KMID2	KUP	KUP2	KLOW	KLOW2	KSFT	KSFT2	OPEN0	...	VSUMN5	VSUMN10	VSUMN20	VSUMN30	VSUMN60	VSUMD5	VSUMD10	VSUMD20	VSUMD30	VSUMD60
datetime	instrument																					
2020-09-25	SZ300413	0.014902	0.028392	0.524862	0.010510	0.370167	0.002980	0.104971	0.007372	0.259665	0.985317	...	0.428346	0.676687	0.642549	0.515998	0.517741	0.143307	-0.353373	-0.285098	-0.031997	-0.035482
SZ300433	-0.015789	0.031579	-0.499997	0.000929	0.029414	0.014861	0.470589	-0.001858	-0.058823	1.016043	...	0.750042	0.778911	0.578567	0.512691	0.532542	-0.500084	-0.557822	-0.157134	-0.025382	-0.065085
SZ300498	-0.012243	0.019589	-0.625002	0.004897	0.249999	0.002449	0.124999	-0.014691	-0.750001	1.012395	...	0.651959	0.550290	0.741564	0.507788	0.520992	-0.303918	-0.100581	-0.483128	-0.015577	-0.041983
SZ300601	-0.021212	0.063011	-0.336641	0.028770	0.456576	0.013030	0.206783	-0.036952	-0.586434	1.021672	...	0.465855	0.508975	0.514560	0.523693	0.500761	0.068290	-0.017950	-0.029119	-0.047386	-0.001522
SZ300628	-0.005217	0.024066	-0.216781	0.003534

**Comment by hadrianl** [comment]
@liufeirong @you-n-g 
- This is probably a BUG about `dump_bin.py`.
-  After `dump_all`, I got the same error and found out that `day.txt` in `calendars` dir was overwrited instead of appened.
- add previous `date` into `day.txt` will solve this.
