### ISSUE TITLE
What dose angle bracket with capital letters mean in the yaml configuration file?

### ISSUE THREAD

**Issue by Vincent4zzzz** [microsoft/qlib#1370]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

In the workflow, the model can be saved by `R.save_objects`, but how can we save model by qrun?

Another question is that what does this mean in the configruation file?
`model: <MODEL>
dataset: <DATASET>`

**Comment by quant2008** [comment]
<MODEL>，<DATASET>表示要引用外部变量。可参考[qlib视频课程](https://ke.qq.com/course/5838458#term_id=106051065)里有讲解。
