### ISSUE TITLE
Hey any guys now the china stock api website? 炒中国股可以接入哪些网站？

### ISSUE THREAD

**Issue by aquosw** [microsoft/qlib#1377]
## ❓ Questions and Help

Hey any guys now the china stock api website?

you know like this, i quote some docs below:

> Users can also provide their own data in CSV format. However, the CSV data must satisfies following criterions:
> CSV file is named after a specific stock or the CSV file includes a column of the stock name.
> CSV file must includes a column for the date, and when dumping the data, user must specify the date column name.

Question is: Which website to get the data, and in each way (on each website it seems to be different as the scheme is), How can we format the csv data correctly so as to follow the quote above? Shorter said, which website, and what is the correct scheme?

I'm afraid that the csv convert is ok, but cannot run training!

I think it's quite important especially for Chinese users, which can easily get confused by the flood of alphabets! 
I just cannot stand such many words and english searches, and I cannot give more thanks if someone'd like to help me!

And it's also very kind if you can take me further to some python skills related to your solution(and modules)!

Auto-generated by QLib, and I've really read:
We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

**Comment by aquosw** [comment]
(frustrated as a newbie who don't know he is)

**Comment by aquosw** [comment]
(i just enjoy free demo and easy thats what i think opensource is)

**Comment by ChiahungTai** [comment]
你可以打中文，許多主要開發者都會中文。

**Comment by Indie-Studio** [comment]
https://github.com/chenditc/investment_data/releases
update every trading day

**Comment by quant2008** [comment]
这个[qlib视频课程](https://ke.qq.com/course/5838458#term_id=106051065)里演示了如何从akshare下载中国A股数据，并转换成qlib可用的格式。它第一课有知识点pdf文档，可免费下载。

**Comment by seifer08ms** [comment]
> 这个[qlib视频课程](https://ke.qq.com/course/5838458#term_id=106051065)里演示了如何从akshare下载中国A股数据，并转换成qlib可用的格式。它第一课有知识点pdf文档，可免费下载。

能达到实时行情监控的效果吗

**Comment by flizzywine** [comment]
you can use package tushare  to dump_update to qlib format [link](https://blog.csdn.net/weixin_44177216/article/details/123661858)
