### ISSUE TITLE
test_contrib_model.py running error

### ISSUE THREAD

**Issue by libeiheng** [microsoft/qlib#1380]
## Environment

$python collect_info.py all

Darwin
x86_64
macOS-10.16-x86_64-i386-64bit
Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
Python version: 3.10.8 (main, Nov  4 2022, 08:45:18) [Clang 12.0.0 ]
Qlib version: 0.8.6.99
numpy==1.21.5
pandas==1.5.1
scipy==1.7.3
requests==2.28.1
sacred==0.8.2
python-socketio==5.7.2
redis==4.3.5
python-redis-lock==4.0.0
schedule==1.1.0
cvxpy==1.2.0
hyperopt==0.1.2
fire==0.4.0
statsmodels==0.13.2
xlrd==2.0.1
plotly==5.9.0
matplotlib==3.5.3
tables==3.7.0
pyyaml==6.0
mlflow==1.30.0
tqdm==4.64.1
loguru==0.6.0
lightgbm==3.3.3
tornado==6.2
joblib==1.1.1
fire==0.4.0
ruamel.yaml==0.17.21

##Error
 Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)

thanks for your help, team.

**Comment by ChiahungTai** [comment]
Do you install lightgbm properly?
You might need to install lightgbm and run it successfully first.
