### ISSUE TITLE
Question about evaluation

### ISSUE THREAD

**Issue by maciejdomagala** [microsoft/qlib#140]
Hi there! I've been playing around with the TFT model and predictions on Alpha158 dataset. I had a couple questions about the flow overall.
From what I understood, model is generating predictions for all instruments within the forecasting horizon.
Q1: Final prediction seems to be defined as average of 0.5 and 0.9 quantile of the 'prediction interval'. Is there any particular reason for using such formula?
After obtaining these results there is a part of the code with the correlation calculation for results. 
Q2: How are the IC and Rank IC indices exactly interpreted here? Is there any other analysis performed in order to check the quality of the forecast? (MSE, MAPE or any other classic metrics).

I am enjoying the implementation and would greatly appreciate some help with these aspects. Thanks!

**Comment by you-n-g** [comment]
Hi, @maciejdomagala  
First I'll answer your Q2
The IC and Rank IC  is caluclated here https://github.com/microsoft/qlib/blob/main/qlib/workflow/record_temp.py#L178
It indicates the pearson correlation and spearman correlation betweeen the prediction and future return.
It is a very typical metric in Quant.
Some classical metrics like MSE and MAPE is very common in ML. But there will be a huge gap between them and the final return for trading.

@wendili-cs Will help to answer the Q1

**Comment by wendili-cs** [comment]
For Q1, the TFT paper compared P90 and P50 results and found they are similar across all datasets. In our experiment, we found that the model is sensitive to hyperparameters. Using the average of them is a kind of ensemble to make the prediction more stable in different periods.

**Comment by maciejdomagala** [comment]
Thanks for answering! So just to clear up - IC and Rank IC are the only statistical measure we apply to 'check' the quality of prediction from the model? 
One more question about applying the TopKDropout strategy. Is the decision about trading stocks based solely on the prediction result from the model? 
From what I noticed, we are working with the 'Score' column from the final dataframe. And the way it is calculated for each index and each date it is taking a 't+4' time index shifted in time by one date. Could you explain why are these values obtained that way and not by using the 't+5' column for a prediction on given date respectively?

**Comment by you-n-g** [comment]
@maciejdomagala  Yes.   IC and Rank IC are metrics for evaluation the forecasting signal.
The TopKDropout's decision will depend on the prediction from the model. Besides, the hyperparameters of TopKDropout strategies wil l affect its actions too.

**Comment by wendili-cs** [comment]
Because in the previous version, the meaning of the label is the change of the price after 5 days, and TFT will use all the previous features and labels. In order to avoid including future information, we choose the TFT output on the fifth day (t+4). The total predicted length is related to the training process, the current predict length is 6 (t+0 --> t+5, you can also set it to other values x, then it will be t+0 --> t+x-1), so the fifth-day prediction is (t+4), if choose (t+5), we will lose one day's feature, which means losing the information. If we choose (t+3) or less, future information will be included.

**Comment by maciejdomagala** [comment]
That's helpful, cheers!
