### ISSUE TITLE
Issue about speed up dataloading when rolling trainning models.

### ISSUE THREAD

**Issue by chenkigba** [microsoft/qlib#1408]
## ❓ Questions and Help

When using RollingTask.task_training(tasks), it will try to load data everytime it train a new model.

I wonder if I can load all data at once and then chop it when I need some segment of the whole dataset.

It always takes long time in every episode.
![image](https://user-images.githubusercontent.com/72114686/210480027-b9a2f4c1-6b90-40ab-acd1-39b42ff29962.png)
![image](https://user-images.githubusercontent.com/72114686/210480059-294866ee-89cb-447c-b5eb-84377bf6e362.png)

**Comment by NotF404** [comment]
You can cache the DataFrame to disk, so that you experiments with same data just need to load data once.
