### ISSUE TITLE
How to define deal_price as next day open price during backtest?

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#1412]
## ❓ Questions and Help
If I want to use the open price of the following trading day as my deal price during the backtest, how should I define the `deal_price` in `exchange_kwargs`?

**Comment by LUS8806** [comment]
<img width="348" alt="image" src="https://user-images.githubusercontent.com/14008897/223758079-92c99e4e-b0e2-4efa-a7ce-f52d7a6805cc.png">
set the param "deal_price" in basktest as 'open'
