### ISSUE TITLE
Document update on QLibDataHandler

### ISSUE THREAD

**Issue by Jerryzhuht** [microsoft/qlib#142]
It seems that we have removed the class `QLibDataHandler`  in the latest released version. Can we update the doc part at: https://github.com/microsoft/qlib/blob/main/docs/advanced/alpha.rst

**Comment by bxdd** [comment]
Thanks for your feedback, we will update the documentation later

**Comment by you-n-g** [comment]
@Jerryzhuht   It is merged now.  Please check it  :)

**Comment by Jerryzhuht** [comment]
@you-n-g Thanks for the prompt respond. Now it looks good to me :)
