### ISSUE TITLE
what is the best practice to save the pipeline of data preprocessor?

### ISSUE THREAD

**Issue by tarjintor** [microsoft/qlib#1429]
Hello,I am use qlib to train some model now,
and i need use some learnable data preprocessor before the data feed to the model such as MinMaxNorm

But the Processor class not have a save method, if i want to predict or eval some new data beyond the original dataset during the training,what should I do so I can use the preprocessor extractly the same as I use in training?

**Comment by tarjintor** [comment]
I found that I can only use pickle to save the preprocess and then load it again to reconstruct the handler,set init_data=False，and then call setup_data with init_type="load_state"
after that _infer attribute now is what I need

the most important part is that I can only store the preprocessors by pickle。I read the source code and I found qlib design the class Serializable for that

So I guess this is the best practice now.

**Comment by chuhuan88** [comment]
Hello, can you share the downloaded dataset with me, I can't get on Yahoo, thank you very much.

**Comment by kachadx** [comment]
But the Processor class not have a save method, if i want to predict or eval some new data beyond the original dataset during the training,what should I do so I can use the preprocessor extractly the same as I use in training这个有解决方案吗
