### ISSUE TITLE
Questions about workflow_config_hist_Alpha360.yaml: Are model_path, stock2concept and stock_index necessary?

### ISSUE THREAD

**Issue by Wendroff** [microsoft/qlib#1431]
## ❓ Questions and Help

There are some args of model HIST in workflow_config_hist_Alpha360.yaml like this：

model_path: "benchmarks/LSTM/model_lstm_csi300.pkl"
stock2concept: "benchmarks/HIST/qlib_csi300_stock2concept.npy"
stock_index: "benchmarks/HIST/qlib_csi300_stock_index.npy"

Some qusetions:

1 It seems model_path is a pretrained model. Is it necessary? If it was setted as None, what gonna happen?
2 I downloaded the stock2concept matrix and found there were nearly 4000 concepts and 735 stocks. If I want train the model based on a larger instrument, how can I expand the stock2concept matrix?
3. If I want to pretrain an LSTM model, can I just use the config file [workflow_config_lstm_Alpha360.yaml] with little modifications? (https://github.com/microsoft/qlib/blob/main/examples/benchmarks/LSTM/workflow_config_lstm_Alpha360.yaml)

Thank you!

**Comment by chuhuan88** [comment]
Hello, can you share the downloaded dataset with me, I can't get on Yahoo, thank you very much.

**Comment by xiangqingcs** [comment]
> Hello, can you share the downloaded dataset with me, I can't get on Yahoo, thank you very much.

Use the qlib default data, the file name is "20230602160236_qlib_data_cn_1d_latest.zip"
