### ISSUE TITLE
can qlib handle data on gpu

### ISSUE THREAD

**Issue by aurora5161** [microsoft/qlib#1440]
Hi author, I have more than 1000 features to handle, How can I use gpu to handle datas before training? I tried cudf but it didn't work, can you give me some advices?

**Comment by Fivele-Li** [comment]
Yes, you can train models in qlib on a GPU. Here's how you can do it:

1.Install the appropriate version of PyTorch based on your CUDA version. You can refer to this [link.](https://pytorch.org/get-started/locally/) If you have already installed PyTorch in qlib, you will need to uninstall it first.
2.Find a PyTorch-based model in the examples folder and configure it with your own data and parameters. Alternatively, you can build your own PyTorch-based model. You can refer to this [example.](https://github.com/microsoft/qlib/tree/main/examples/benchmarks/MLP)
