### ISSUE TITLE
Usage of Static DataLoader

### ISSUE THREAD

**Issue by kkwLiu** [microsoft/qlib#1453]
## ❓ Questions and Help

 I am wondering how I can train the models after loading my pickle file by staticdataloader, I am quite a green hand and there seems very few examples about static dataloader to follow... I am grateful for any instructions. And I'll appreciate it if you could offer me some example codes.

**Comment by Fivele-Li** [comment]
`dh = DataHandlerLP.from_df(df)
ds = DatasetH(dh, segments={"train": ("20180101", "20181231"), "valid": ("20190101", "20191231")})`
