### ISSUE TITLE
Future Warning in qlib.utils.paral

### ISSUE THREAD

**Issue by Wendroff** [microsoft/qlib#1455]
## To Reproduce

When I use the RobustZScoreNorm process, future warning as below shown up:

/home/******/anaconda3/envs/qlib3.8/lib/python3.8/site-packages/qlib/utils/paral.py:54: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether turns a like-indexed object.
To preserve the previous behavior, use

        >>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

        >>> .groupby(..., group_keys=True)
  return df.groupby(axis=axis, level=level).apply(apply_func)

Can you guys fix this? Thanks!

**Comment by Fivele-Li** [comment]
I use the latest main branch and run the unit test test_dataset.py::TestDataset::testTSDataset on the latest main branch, and I couldn't reproduce your issue. Could you provide more information to reproduce this problem?
![image](https://github.com/microsoft/qlib/assets/128388363/975a31b8-73a9-4548-b467-fe9bbbc9b071)
