### ISSUE TITLE
横截面特征生成

### ISSUE THREAD

**Issue by louis-xuy** [microsoft/qlib#1456]
现在qlib计算衍生特征都是基于时间序列的方式，如何生成横截面特征？

**Comment by hugo2046** [comment]
我看因子生成的流程是先生成每只股票的pd.Series,然后在用pd.concat拼接到一起；而横截面类似于在df中做df.apply(axis=1)这种操作。直接在qlib.data.ops里面构建因子可能无法构造横截面的特征;如果要做横截面的操作前面的一些代码都需要改。

**Comment by qianyun210603** [comment]
单机部署的话可以参考我的Fork，https://github.com/qianyun210603/qlib/tree/csload_parallel，里面实现了CSRank，CSScale的ops。

**Comment by hugo2046** [comment]
好家伙 厉害的 我先学习一下 谢谢

YQ Tsui ***@***.***> 于2023年3月23日周四 15:42写道：
