### ISSUE TITLE
Where is Hyperparameters Tuning Engine(HTE) ?

### ISSUE THREAD

**Issue by royshan** [microsoft/qlib#1458]
## ❓ Questions and Help

Hi, there. Thank you very much for building qlib. The qlib paper mentions Hyperparameters Tuning Engine(HTE). However, I can't find how to use HTE in the docs, source code or examples. Could you provide some pointers?

**Comment by chuhuan88** [comment]
Hello, can you share the downloaded dataset with me, I can't get on Yahoo, thank you very much.
