### ISSUE TITLE
【DDG_DA】workflow.py run_all  can‘t success

### ISSUE THREAD

**Issue by cxDlogver** [microsoft/qlib#1459]
## ❓ workflow.py run_all  can‘t success
I run the orginal codes by python workflow.py run_all but can't success
An error occurred when executing dataset = init_instance_by_config(task["dataset"])
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Administrator\\qlib\\examples\\benchmarks_dynamic\\baseline\\lightgbm_alpha158_handler_horizon20.pkl\\'
But the file is already generated in the path

**Comment by chuhuan88** [comment]
Hello, can you share the downloaded dataset with me, I can't get on Yahoo, thank you very much.

**Comment by cxDlogver** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/qlib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月14日(星期二) 晚上11:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/qlib] 【DDG_DA】workflow.py run_all  can‘t success (Issue #1459)





 
Hello, can you share the downloaded dataset with me, I can't get on Yahoo, thank you very much.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

20230307023127_qlib_data_cn_1d_latest.zip (9.34M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=6a64366538940fc7af90c8c31e3457174c1053065e04030019540f005919560a05511b0300015215565104550151040f00550156381d650a045605550b045208065707570f6b14545d06690159400467570a69545c6b095940014511164e0c483459&t=exs_ftn_download&code=4d6e84e8




20230307023307_qlib_data_cn_1d_latest.zip (187.44M, 2023年04月14日 11:29 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=6d6163668fd678c7a8959dc01233021c4b155451565506061e575a57551e000306534e5f0356551e065307000702545005050753341a3001035350560703070301525056036c415f5a033c025547516c500f3c57506c5c52470410121a495943335c&t=exs_ftn_download&code=3acf4303

**Comment by qianyun210603** [comment]
there shouldn't be `\` after `.pkl` here:
'C:\Users\Administrator\qlib\examples\benchmarks_dynamic\baseline\lightgbm_alpha158_handler_horizon20.pkl\'

Maybe related to PR #1475
