### ISSUE TITLE
packaging package causes import error for LegacyVersion class

### ISSUE THREAD

**Issue by iamnagesh** [microsoft/qlib#1465]
## 🐛 Bug Description

When initialising qlib an import error occurs for LegacyVersion class in packaging/version.py due to deprecation within the latest versions of the packaging library.

## To Reproduce

Steps to reproduce the error:

1. Create a virtual environment
2. ```pip install pyqlib```
3. Initialise qlib by running ```qlib.init()``` after importing the package

## Fix

When installing pyqlib using pip with dependencies, ```packaging 21.9``` is installed which produces the above error.

```
pip uninstall packaging
pip install packaging==21.3
# packaging==21.3 because statsmodels 0.13.5 requires packaging>=21.3
```

 - Qlib version: 0.9.1
 - Python version: 3.8.8 (Anaconda Version 2021.04)
 - OS : MacOS

**Comment by LoveingStatistics** [comment]
I have the same issue, and I follow the fix step, but I still can't solve it.

Could you give me some help?

Qlib version:  '0.9.3.99'
python:3.10.8(Anaconda 2021.04)
OS: Windows
