### ISSUE TITLE
Mismatching of rebalancing frequency and the return in training dataset in benchmark_dynamic examples

### ISSUE THREAD

**Issue by qianyun210603** [microsoft/qlib#1483]
## ❓ Questions and Help

In the benchmark_dynamic examples (Rolling and DDG-DA), the model are trained against 20-day returns (i.e. `$Ref(close, -20)/$Ref(close, -1)`). However, in backtesting the rebalancing frequency is still 1 day. Looks like a mismatch here. To my understanding, if model are trained against 20-day return, the rebalencing frequency should also be 20 days to ensure that each stock held realizes its 20-day return.

Any consideration here?

Thanks!

**Comment by qianyun210603** [comment]
Thanks @Fivele-Li. Looks more tests needed to figure out how to get best performance.

**Comment by quant2008** [comment]
how to adjust the rebalancing frequency is still not resolved?
