### ISSUE TITLE
how to drop some factors(columns) after DatasetH or DataHandler?

### ISSUE THREAD

**Issue by CharlieChi** [microsoft/qlib#1489]
## ❓ Questions and Help

how to drop some factors(columns) after DatasetH or DataHandler? 
or we must change the configs of DataHandler and rerun it?

**Comment by Fivele-Li** [comment]
As far as I know, there is currently no way to drop factors after DatasetH/DataHandler.Perhaps you could provide your use case and we can see if there are other methods that can meet your current needs.

**Comment by CharlieChi** [comment]
> As far as I know, there is currently no way to drop factors after DatasetH/DataHandler.Perhaps you could provide your use case and we can see if there are other methods that can meet your current needs.

well，thanks for response，if we cant drop factors after DatasetH or DataHandler, then we have to rerun DataHandler, but datahandler with fliter is quit slow， for my instance，it takes about 300s, which primarily costs in  filter_pipe.

and the output of DatasetH and DataHandler are basticly combination of dataframes，drop columns from a dataframe should be convenient
