### ISSUE TITLE
Dose the CSV data i prepared need to be adjust?

### ISSUE THREAD

**Issue by quinnnnnnnnn** [microsoft/qlib#149]
## ❓ Questions and Help
I don't know if the word （adjust）is correct  ,i'm not a english native speaker  0v0
Should i adjust the impact of the  stock price discontinuity caused by the  Ex-right and ex-dividends?

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

**Comment by you-n-g** [comment]
@quinnnnnnnnn  
The price and volumn  data with qlib format should be adjusted.
We will add more docs about it later. 
Thanks
