### ISSUE TITLE
Confused terms for beginner 

### ISSUE THREAD

**Issue by kyhoolee** [microsoft/qlib#1493]
I saw that you use some kind of dataset like Alpha360, Alpha158, and some Chinese stock instrument - but without clearly explaination, or referencing. It's really difficult for any beginner who want to explore this Qlib framework 
https://github.com/kyhoolee/qlib/blob/main/examples/benchmarks/README.md

Anyone can give me some easy and intuitive starting point of using Qlib framework

**Comment by Fivele-Li** [comment]
Here is a document for users who are new to the qlib project: [Qlib Documentation.](https://qlib.readthedocs.io/en/latest/index.html) If you want to learn about the construction method of Alpha features, you can refer to this code: [handle.py.](https://github.com/microsoft/qlib/blob/main/qlib/contrib/data/handler.py) I hope it will be helpful to you.

**Comment by quant2008** [comment]
> I saw that you use some kind of dataset like Alpha360, Alpha158, and some Chinese stock instrument - but without clearly explaination, or referencing. It's really difficult for any beginner who want to explore this Qlib framework https://github.com/kyhoolee/qlib/blob/main/examples/benchmarks/README.md
> 
> Anyone can give me some easy and intuitive starting point of using Qlib framework

可以参考这个qlib视频教程
[https://www.cctalk.com/m/group/90710187](https://www.cctalk.com/m/group/90710187)
