### ISSUE TITLE
Timeout downloading 1min interval data

### ISSUE THREAD

**Issue by kyhoolee** [microsoft/qlib#1494]
I follow the data prepration step from README
```
python -m qlib.run.get_data qlib_data --target_dir ~/.qlib/qlib_data/cn_data_1min --region cn --interval 1min
```
But I can not download the data. How to add config parameters, such as timeout, or increasing buffer, ... to fix this issue 
```requests.exceptions.ConnectionError: HTTPSConnectionPool(host='qlibpublic.blob.core.windows.net', port=443): Read timed out.```

**Comment by Fivele-Li** [comment]
Try closing your VPN may solve the issue :-)
