### ISSUE TITLE
Bug: current_iter check in Checkpoint callback in RL trainer

### ISSUE THREAD

**Issue by ChenglongChen** [microsoft/qlib#1497]
I have found that there might be a bug in the ``current_iter`` in [Checkpoint](https://github.com/microsoft/qlib/blob/main/qlib/rl/trainer/callbacks.py#L203).

According to the [definition](https://github.com/microsoft/qlib/blob/main/qlib/rl/trainer/callbacks.py#L67): since ``on_iter_end`` is called **after** the bump of ``current_iter``, when the previous iteration is considered complete.

This [check](https://github.com/microsoft/qlib/blob/main/qlib/rl/trainer/callbacks.py#L261) should be

`
trainer.current_iter % self.every_n_iters
`

instead of

`
(trainer.current_iter + 1) % self.every_n_iters
`

Otherwise, it will cause mismatch of the evaluation metrics and the corresponding checkpoint being saved if ``every_n_iters > 1``.

Assuming ``every_n_iters = 10``, you will get checkpoints saved at 9-th, 19-th, 29-th iteration.

**Comment by Fivele-Li** [comment]
Hi,could you mind sending a PR to fix this issue and become one of the contributors of Qlib? : )
