### ISSUE TITLE
Is tensorflow model available ?

### ISSUE THREAD

**Issue by Yablon** [microsoft/qlib#15]
Examples show that pytorch models can be used in qlib.

I wonder is tensorflow models available in this framework?

**Comment by you-n-g** [comment]
Qlib is not coupled with any machine learning tools (e.g. tensorflow pytorch)
It only provides interfaces.  Any model implements the interfaces can be integrated into qlib.
Currently, we provide two exmaple written by lightgbm and pytroch.  We will have more examples in future.

Your PR is welcomed!

**Comment by bxdd** [comment]
Hi, the `TensorFlow` models are not provided. We provide `lightGBM` and `PyTorch`  DNN models as the baseline. If you want to use models with `TensorFlow`, you can integrate custom models into `Qlib`, please refer to the `Integration` document(https://qlib.readthedocs.io/en/latest/start/integration.html) for more details.

**Comment by Yablon** [comment]
OK, Thank you.

**Comment by you-n-g** [comment]
@Yablon 
We will keep issue open until we implement a tensorflow based model.
Thanks
