### ISSUE TITLE
close(1) is previous bar's close price, close(-1) is next bar's price, and close is current bar's close price?

### ISSUE THREAD

**Issue by qtbgo** [microsoft/qlib#150]
close(1) is previous bar's close price, close(-1) is next bar's price, and close is current bar's close price?
Am I correct on the index of close?

**Comment by you-n-g** [comment]
Hi, @qtbgo

What do you mean by `close(1)` ?   
Can you explain it with code exmaple?

Thanks.

**Comment by qtbgo** [comment]
close(1) means ($close, 1).

**Comment by you-n-g** [comment]
https://github.com/microsoft/qlib/blob/main/qlib/data/ops.py#L743

Here is the docs about the Ref operation.

**Comment by qtbgo** [comment]
So, what is the exact time we issue an order? at the begin of the current bar or at the end of current?
If at begin, then the order can be executed at the current bar. If at the end, then the order can only be executed at the next bar.

**Comment by you-n-g** [comment]
In our daily dfrequency data,  the data with `close` timestamp `2020-12-25` represents the close price of`2020-12-25`
