### ISSUE TITLE
I have features and label from different dataset, what handler or dataloader should I use?

### ISSUE THREAD

**Issue by smangj** [microsoft/qlib#1501]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

**Comment by Fivele-Li** [comment]
Hi,I think there are roughly two types of features/labels: 
1) pre-calculated data, which can be loaded into Qlib by loading a .csv file, see [converting-csv-format-into-qlib-format](https://qlib.readthedocs.io/en/latest/component/data.html#converting-csv-format-into-qlib-format) for details; 
2) data that needs to be calculated using built-in expressions in Qlib. You can refer to the Alpha158 class in [Alpha158](https://github.com/microsoft/qlib/blob/46264dfec9419bd22c413f674f78fb755860f420/qlib/contrib/data/handler.py#L142) for editing your own features. If you need to perform more detailed operations on the features, you can use existing/custom processors (refer to [DropnaProcessor)](https://github.com/microsoft/qlib/blob/46264dfec9419bd22c413f674f78fb755860f420/qlib/data/dataset/processor.py#L94) by referencing them in the YAML file.

**Comment by Fivele-Li** [comment]
3. You can also refer to the examples of D.features() in [detailed_workflow.ipynb](https://github.com/microsoft/qlib/blob/main/examples/tutorial/detailed_workflow.ipynb) which enable you to quickly use built-in expressions in Qlib.

**Comment by smangj** [comment]
thank you for answering. I have inherited DataLoaderDH and overload self.load() to merge dfs from different dataset into one.

> 3. You can also refer to the examples of D.features() in [detailed_workflow.ipynb](https://github.com/microsoft/qlib/blob/main/examples/tutorial/detailed_workflow.ipynb) which enable you to quickly use built-in expressions in Qlib.

**Comment by j123425** [comment]
Hi, I have the same problem of using my own features and labels. I have dumped all the data of my features and labels into the folder ".qlib/qlib_data/my_data/features". But I am not sure how to tell qlib which is feature and which is label for model training in dataset initialization.
