### ISSUE TITLE
how returns in report_normal_1day.pkl are normlized?

### ISSUE THREAD

**Issue by quant2008** [microsoft/qlib#1511]
Hi, in the following:
report_normal_1day_df = predict_recorder.load_object("portfolio_analysis/report_normal_1day.pkl")
returns = report_normal_1day_df['return']

It seems returns are not original returns, they seems to be normlized.  I wonder how returns in report_normal_1day.pkl are normlized?

**Comment by Fivele-Li** [comment]
Hi，In portfolio_metrics, the "return" is obtained by calculating the change in account_value and adding the cost, so it is different from the return that is obtained by only calculating the account_value. I am not sure if this answers your question.

https://github.com/microsoft/qlib/blob/7234308651c725ef1e4b40ad1f55c06df782c4f3/qlib/backtest/account.py#L283

**Comment by quant2008** [comment]
Then why I send this returns to quantstatus, it gives different annualized return than qlib's annualized return?
pls check https://github.com/microsoft/qlib/issues/1512
