### ISSUE TITLE
What code can i use to see the score of the most recent trading day?

### ISSUE THREAD

**Issue by quinnnnnnnnn** [microsoft/qlib#155]
## ❓ Questions and Help
I used my own data(till 2020-12-25) to run example work flow, How to see the top5 or buttom 5 or all of them's score to trade on the stock market tomorrow? THX  XD
We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

**Comment by you-n-g** [comment]
Hi, @quinnnnnnnnn 
You can use [Recorder](https://qlib.readthedocs.io/en/latest/component/recorder.html) to retreive the model predictions.
