### ISSUE TITLE
workflow_config_gats_Alpha360.yaml: How is file model_lstm_csi300.pkl generated?

### ISSUE THREAD

**Issue by xiangqingcs** [microsoft/qlib#1554]
## ❓ Questions and Help

**When i training the GATs model, using qlib's default data and the project's default yml file, run the script as follows:**

> Running CMD: D:\ProgramData\Anaconda3\envs\py38_torch112\python.exe D:\ProgramData\Anaconda3\envs\py38_torch112\Scripts\qrun.exe E:\qlib_study\qlib_0.8.6_examples\benchmarks\GATs\workflow_config_gats_Alpha360.yaml GATs run_all_model_records

**The LSTM model cannot be found, and the following error message is displayed:**

> ERROR - qlib.workflow - [utils.py:41] - An exception has been raised[FileNotFoundError: [Errno 2] No such file or directory: 'benchmarks/LSTM/model_lstm_csi300.pkl'].

**Then i training the LSTM model, using the default configuration file of example, train the LSTM model and run the script as follows:**

> Running CMD: D:\ProgramData\Anaconda3\envs\py38_torch112\python.exe D:\ProgramData\Anaconda3\envs\py38_torch112\Scripts\qrun.exe E:\qlib_study\qlib_0.8.6_examples\benchmarks\LSTM\workflow_config_lstm_Alpha360.yaml LSTM run_all_model_records

**The model will then be trained, the file <E:\qlib_study\qlib_0.8.6_examples\run_all_model_records\12\8e71a303be1d46ef8d27a0ff7baa18ea\artifacts\params.pkl> is changed to model_lstm_csi300.pkl, placed in the path benchmarks/LSTM, and then training the GATS model, after which the following error occurs: "[RuntimeError: Invalid magic number; corrupt file?]"**

### **So how is this LSTM trained, How is file model_lstm_csi300.pkl generated?**

**The detailed error information is as follows:**

> [38504:MainThread](2023-06-16 09:26:55,296) ERROR - qlib.workflow - [utils.py:41] - An exception has been raised[RuntimeError: Invalid magic number; corrupt file?].
>   File "D:\ProgramData\Anaconda3\envs\py38_torch112\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "D:\ProgramData\Anaconda3\envs\py38_torch112\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "D:\ProgramData\Anaconda3\envs\py38_torch112\Scripts\qrun.exe\__main__.py", line 7, in <module>
>     sys.exit(run())
>   File "D:\ProgramData\Anaconda3\envs\py38_torch112\lib\site-packages\qlib\workflow\cli.py", line 72, in run
>     fire.Fire(workflow)
>   File "D:\ProgramData\Anaconda3\envs\py38_torch112\lib\site-packages\fire\core.py", line 141, in Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>   File "D:\ProgramData\Anaconda3\envs\py38_torch112\lib\site-packages\fire\core.py", line 475, in _Fire
>     component, remaining_args = _CallAndUpdateTrace(
>   File "D:\ProgramData\Anaconda3\envs\py38_torch112\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
>     component = fn(*varargs, **kwargs)
>   File "D:\ProgramData\Anaconda3\envs\py38_torch112\lib\site-packages\qlib\workflow\cli.py", line 66, in workflow
>     recorder = task_train(config.get("task"), experiment_name=experiment_name)
>   File "D:\ProgramData\Anaconda3\envs\py38_torch112\lib\site-packages\qlib\model\trainer.py", line 127, in task_train
>     _exe_task(task_config)
>   File "D:\ProgramData\Anaconda3\envs\py38_torch112\lib\site-packages\qlib\model\trainer.py", line 49, in _exe_task
>     auto_filter_kwargs(model.fit)(dataset, reweighter=reweighter)
>   File "D:\ProgramData\Anaconda3\envs\py38_torch112\lib\site-packages\qlib\utils\__init__.py", line 963, in _func
>     return func(*args, **new_kwargs)
>   File "D:\ProgramData\Anaconda3\envs\py38_torch112\lib\site-packages\qlib\contrib\model\pytorch_gats.py", line 262, in fit
>     pretrained_model.load_state_dict(torch.load(self.model_path, map_location=self.device))
>   File "D:\ProgramData\Anaconda3\envs\py38_torch112\lib\site-packages\torch\serialization.py", line 713, in load
>     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>   File "D:\ProgramData\Anaconda3\envs\py38_torch112\lib\site-packages\torch\serialization.py", line 922, in _legacy_load
>     raise RuntimeError("Invalid magic number; corrupt file?")
> RuntimeError: Invalid magic number; corrupt file?
> [16048:MainThread](2023-06-16 09:26:58,025) ERROR - qlib.workflow - [utils.py:41] - An exception has been raised[RuntimeError: Error when executing command: D:\ProgramData\Anaconda3\envs\py38_torch112\python.exe D:\ProgramData\Anaconda3\envs\py38_torch112\Scripts\qrun.exe E:\qlib_study\qlib_0.8.6_examples\benchmarks\GATs\workflow_config_gats_Alpha360.yaml GATs run_all_model_records].
>   File "E:/qlib_study/qlib_0.8.6_examples/run_all_model.py", line 410, in <module>
>     fire.Fire(ModelRunner)  # run all the model
>   File "d:\ProgramData\Anaconda3\envs\py38_torch112\lib\site-packages\fire\core.py", line 141, in Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>   File "d:\ProgramData\Anaconda3\envs\py38_torch112\lib\site-packages\fire\core.py", line 475, in _Fire
>     component, remaining_args = _CallAndUpdateTrace(
>   File "d:\ProgramData\Anaconda3\envs\py38_torch112\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
>     component = fn(*varargs, **kwargs)
>   File "E:/qlib_study/qlib_0.8.6_examples/run_all_model.py", line 39, in _return_wrapped
>     return function_to_decorate(*args, **kwargs)
>   File "E:/qlib_study/qlib_0.8.6_examples/run_all_model.py", line 366, in run
>     errs = execute(
>   File "E:/qlib_study/qlib_0.8.6_examples/run_all_model.py", line 93, in execute
>     raise RuntimeError(f"Error when executing command: {cmd}")
> RuntimeError: Error when executing command: D:\ProgramData\Anaconda3\envs\py38_torch112\python.exe D:\ProgramData\Anaconda3\envs\py38_torch112\Scripts\qrun.exe E:\qlib_study\qlib_0.8.6_examples\benchmarks\GATs\workflow_config_gats_Alpha360.yaml GATs run_all_model_records
>

**Comment by tycallen** [comment]
same problem here
