### ISSUE TITLE
回测如何使用自定义的资产价格数据？

### ISSUE THREAD

**Issue by zzxfriend** [microsoft/qlib#1559]
## ❓ Questions and Help

回测如何使用自定义的资产价格数据？
我想通过直接传入score_df和具有open，high，low，close资产价格的dataframe进行topkdropn策略的回测，但是我不想先将其转换为qlib的内置数据格式bin，这会显得很麻烦。

**Comment by quant2008** [comment]
你可以将这些数据传给比如backtrader进行回测，在backtrader中编写策略。可以参考 [扫地僧AI量化平台Qlib给力教程系列一：核心篇](https://ke.qq.com/course/5838458#term_id=106051065) 中的13节13.与backtrader结合
