### ISSUE TITLE
requests.exceptions.HTTPError: 409 Client Error: Public access is not permitted on this storage account. for url: https://qlibpublic.blob.core.windows.net/data/default/stock_data/v2/qlib_data_cn_1d_0.9.1.zip

### ISSUE THREAD

**Issue by danbo6** [microsoft/qlib#1565]
Hi， I recently met this error while trying to load data. Previouly ther was no such issue, i was able to use this script before, but now it failed. Anyone can help?

**Comment by SunsetWolf** [comment]
This issue has been fixed in [PR 1558](https://github.com/microsoft/qlib/pull/1558), using the source installation, which solves this problem.
