### ISSUE TITLE
请问在yaml文件中，<MODEL> <DATASET> 的作用是什么？为什么要这样写?

### ISSUE THREAD

**Issue by moesakura** [microsoft/qlib#1567]
## ❓ Questions and Help

请问在yaml文件中，<MODEL> <DATASET> 的作用是什么？为什么要这样写?

**Comment by quant2008** [comment]
这个代表要引用程序中的变量，可以参考“[扫地僧AI量化平台Qlib给力教程系列一：核心篇](https://ke.qq.com/course/5838458#term_id=106051065)“中的第5节 05.从yaml文件生成配置字典，有介绍

**Comment by SunsetWolf** [comment]
Model is the configuration related to the machine learning model. dataset is related to the configuration of the factor dataset.. It is written in json format, so that it can be processed into a yaml file, which is easy for users to use.

**Comment by SunsetWolf** [comment]
> 这个代表要引用程序中的变量，可以参考“[扫地僧AI量化平台Qlib给力教程系列一：核心篇](https://ke.qq.com/course/5838458#term_id=106051065)“中的第5节 05.从yaml文件生成配置字典，有介绍

我们非常欢迎帮助别人解决问题的人, 而不是做广告的人.
