### ISSUE TITLE
When can Qlib support MacOS Ventura(MacOS 13)?

### ISSUE THREAD

**Issue by ikaroinory** [microsoft/qlib#1571]
## ❓ Questions and Help

I noticed the v0.9.2 already support MacOS Big Sur(MacOS 11), but my Mac's operating system is MacOS Ventura(MacOS 13), I try some methods to install Qlib on M1 architecture but there are always warning or error at runtime, so I sincerely hope developers can release the Qlib that is compatible with M1 architecture as soon as possible.

**Comment by Silhouettes-of-U** [comment]
it runs well on my MacOS13...

**Comment by SunsetWolf** [comment]
Will this problem be solved by installing the latest version of qlib now?

**Comment by gwz94** [comment]
Managed to install qlib with my MacOS Venturra under python 3.8.17 env.
Installed the library from the source stated at the homepage then have to manually solve some of the error like missing HDF5. 

For the HDF5 problem, you can solve it by using the code below. The rest, just google about it and you will get an answer
`HDF5_DIR=/opt/homebrew/opt/hdf5 BLOSC_DIR=/opt/homebrew/opt/c-blosc LZO_DIR=/opt/homebrew/opt/lzo BZIP2_DIR=/opt/homebrew/opt/bzip2 pip install tables==3.6.1      
`

Hope this is helpful. :)
