### ISSUE TITLE
Code block not showing on website

### ISSUE THREAD

**Issue by benheckmann** [microsoft/qlib#1572]
## 📖 Documentation

On [this](https://qlib.readthedocs.io/en/latest/component/data.html#converting-csv-format-into-qlib-format) page of the docs, some code blocks are not visible, for example after the text "where the data are in the following format" (section Converting CSV Format into Qlib Format). In my case, I can't see the block in Chrome or Safari, even though it is in the source code.

Sidenote: there are some grammatical errors on this page as well. Running it through ChatGPT once would fix most of them.

**Comment by SunsetWolf** [comment]
Will [this pull requests](https://github.com/microsoft/qlib/pull/1618) solve your problem?

**Comment by benheckmann** [comment]
Yes, thanks!
