### ISSUE TITLE
Notebook不显示图片问题

### ISSUE THREAD

**Issue by xinzheli628** [microsoft/qlib#158]
## To Reproduce

1.在notebook上Demo代码运行成功后，图片不能成功显示，加入%matplotlib inline无效果
1.
1.

## Environment

**Note**: One could run `python scripts/collect_info.py` under the `qlib` directory to get the following information.

 - Qlib version:lastest
 - Python version:3.7
 - OS (`Windows`, `Linux`, `MacOS`):Win10 &Mac 
 - Commit number (optional, please provide it if you are using the dev version):

**Comment by xinzheli628** [comment]
Jupyter-lab无法显示图片，换成notebook打开可以显示图片。。。

**Comment by tengerye** [comment]
@xinzheli628  I had similar issue, but it problem came from the Plotly. Please add the full traceback if there is any.
