### ISSUE TITLE
Quick Start don't work with windows

### ISSUE THREAD

**Issue by Petzy68** [microsoft/qlib#1586]
## To Reproduce

1. Follow the Quick Start on a Windows 11 machine. Doesn't matter if it is Python 3.7, 3.8 or 3.9
2. Doesn't matter if you install from source or with pip install pyqlib
3. All examples starting with Data Preparation will get the error:
File "C:\Users\Peter\AppData\Roaming\Python\Python38\site-packages\scipy\sparse\linalg\_isolve\iterative.py", line 9, in <module> from . import _iterative. ImportError: DLL load failed while importing _iterative: The specified module could not be found.
4. 

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version: 0.9.2.99
 - Python version: 3.7, 3.8 and 3.9
 - OS (`Windows`, `Linux`, `MacOS`): Windows
 - Commit number (optional, please provide it if you are using the dev version):

**Comment by quant2008** [comment]
通常此类问题都是安装环境混乱导致的。qlib对安装环境和依赖的要求非常高，安装不好很容易出问题，你可以按照“[扫地僧微软AI量化平台Qlib教程系列一](https://www.cctalk.com/m/group/90710187)”中的课程 “[1.2 安装Qlib](https://www.cctalk.com/v/16764198104427)” 严格按照视频里的环境和步骤安装qlib，就不会出错。这个安装视频是免费可看的。

**Comment by SunsetWolf** [comment]
Try creating a new virtual environment with conda to install qlib.
