### ISSUE TITLE
请问qlib推荐的电脑硬件配置是？

### ISSUE THREAD

**Issue by quant2008** [microsoft/qlib#1597]
您好。我们知道，推荐配置一般有最小配置，一般配置，豪华配置。
我这里咨询的是一般配置，比如：
内存多大？
gpu是否需要，若需要配啥型号？
cpu型号

**Comment by Starr8845** [comment]
实测最少16G内存，32G内存较为宽松
GPU如果要跑深度学习模型显存最少6G，8G或12G以上会宽松一些
如果是Windows系统劝你用WSL，在Windows下会有奇奇怪怪的bug
CPU没有显著要求，较新的PC均可
