### ISSUE TITLE
there is the question when I run python .\run_all_model.py run --models=lightgbm

### ISSUE THREAD

**Issue by zhangzhongwd** [microsoft/qlib#1607]
## ❓ Questions and Help
RuntimeError: Error when executing command: C:\Users\admin\AppData\Local\Temp\tmpcf6xl_kn\bin\python -m pip install -r D:\quant\qlib_learn\qlib\examples\benchmarks\LightGBM\requirements.txt

How can I fix it. 
My environment is:
pandas=1.5.3
numpy=1.23.5

how can I degrade numpy and pandas' versions as shown in LightGBM\requirements.txt

**Comment by SunsetWolf** [comment]
I don't know if you have `pip` in your `C:\Users\admin\AppData\Local\Temp\tmpcf6xl_kn\bin\` path, but if you do, you can try installing it using the `C:\Users\admin\AppData\Local\Temp\tmpcf6xl_kn\bin\pip install` method, and if that doesn't work, you can use conda to create a new virtual environment to install it, which is the most recommended method.
