### ISSUE TITLE
AttributeError: 'float' object has no attribute 'lower'

### ISSUE THREAD

**Issue by quant2008** [microsoft/qlib#1613]
我执行 python scripts/data_collector/yahoo/collector.py 从yahoo finance下载美股数据。
之后运行qlib自带例子，出现如下错误
AttributeError: 'float' object has no attribute 'lower'
![image](https://github.com/microsoft/qlib/assets/116711018/11c22610-ba1a-412c-8549-f8fa1f5319f5)

类似错误 https://github.com/microsoft/qlib/issues/1428

**Comment by quant2008** [comment]
发现原因了，删除两个股票的数据 NA, NAN. 这两个股票代码需要特殊处理。

**Comment by SunsetWolf** [comment]
I installed the latest version of qlib using the `python -m pip install -e .[dev]` command and then used the `python collector.py download_data --source_dir ~/.qlib/stock_data/source/us_data --start 2020-01-01 --end 2020-12-31 --delay 1 --interval 1d --region US` command to try to get the US stock data for 2020 and did not find this issue .
