### ISSUE TITLE
A bug in calculating mdd

### ISSUE THREAD

**Issue by HaoningChen** [microsoft/qlib#1615]
## 🐛 Bug Description
in qlib.contrib.repport.analysis_position.report line 25:  

The original code is "return series - series.cummax()"  
Maybe the correct code is "return (series - series.cummax()) / series.cummax()"

**Comment by Fivele-Li** [comment]
For the purpose of optimizing the visualization experience, Qlib uses the method of cumulative return to display the historical return curve of a strategy. Therefore, when calculating the maximum drawdown (MDD), there is no need to divide it by the historical peak value. This is different from the conventional understanding of MDD calculation. However, in general, the difference between the two methods is not significant. If you want to obtain the MDD in terms of cumulative meaning, you need to modify the calculation method of return to cumulative return.

https://github.com/microsoft/qlib/blob/05d67b38287a22d43d55aee76e8fb3bba87c5f48/qlib/contrib/evaluate.py#L27-L33
