### ISSUE TITLE
how to explain the prediction result

### ISSUE THREAD

**Issue by yxengine** [microsoft/qlib#1616]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

Sorry, I'm a newbie who just started using qlib
After finishing the training, I printed a prediction result, but I don't quite understand its meaning, can anyone explain what it means
![image](https://github.com/microsoft/qlib/assets/129268404/eaf105b7-ffbb-4705-9944-d2b1df6c97eb)

**Comment by quant2008** [comment]
score默认情况下就是对未来收益率，即label的预测，当然，这个label表示的收益率是经过预处理的，见下图。
[https://www.cctalk.com/v/16765433061336?sid=](![image](https://github.com/microsoft/qlib/assets/116711018/f7382477-4a52-4a78-9c68-c84333373680))
