### ISSUE TITLE
滚动预测中训练集变化问题

### ISSUE THREAD

**Issue by quant2008** [microsoft/qlib#1620]
滚动预测时，每一滚训练集都在变化，导致某些处理器处理器的learnable state (such as standard deviation, mean, etc.) 需要变化。但目前qlib提供的例子如examples\benchmarks_dynamic\baseline，examples\model_rolling\task_manager_rolling.py，有些处理器如RobustZScoreNorm的fit操作，基于的数据是固定在第一滚的结果，不会变化。

有个讨论https://github.com/microsoft/qlib/issues/383 提到RollingDataHandler，似乎可以解决这个问题。但似乎还没有完整的使用它进行训练预测的例子。不知现在滚动训练预测有没有解决这个问题的例子？

**Comment by Fivele-Li** [comment]
RollingDataHandler中的方法没有被采用到现有的例子中，你可以参考现在DDG-DA中生成rollingData的gen_following_tasks方法：
https://github.com/microsoft/qlib/blob/4c30e5827b74bcc45f14cf3ae0c1715459ed09ae/qlib/workflow/task/gen.py#L301

尝试通过修改传入task的dataset配置实现想要的操作。

**Comment by quant2008** [comment]
不太明白您的意思。您是说现有的[DDG-DA](https://github.com/microsoft/qlib/blob/4c30e5827b74bcc45f14cf3ae0c1715459ed09ae/examples/benchmarks_dynamic/DDG-DA/workflow.py)这个例子已经解决了这个问题吗？参考该例子即可吗？
