### ISSUE TITLE
How to load dataset from pandas dataframe?

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#1621]
How to load dataset without the need of qlib_data directory, using dataframe to feed the dataset directly? This would be necessary in HF trading as disk I/O is very slow.

**Comment by Fivele-Li** [comment]
You can use the from_df method to load dataset from dataframe.
https://github.com/microsoft/qlib/blob/05d67b38287a22d43d55aee76e8fb3bba87c5f48/tests/data_mid_layer_tests/test_handler.py#L16

**Comment by 2young-2simple-sometimes-naive** [comment]
> You can use the from_df method to load dataset from dataframe.
> 
> https://github.com/microsoft/qlib/blob/05d67b38287a22d43d55aee76e8fb3bba87c5f48/tests/data_mid_layer_tests/test_handler.py#L16

Thanks for the replay. I do need the processed data, which is defined by fields and names under QlibDataLoader. I only found initialization methods with D.features, which seems only load from qlib_data dir? Is there any way to use D.features directly loading from pandas dataframe?
