### ISSUE TITLE
how to short stocks in backtest?

### ISSUE THREAD

**Issue by ericyue** [microsoft/qlib#1624]
I read some issues and find currently qlib didn't support short stocks. 

Is there any instructions about how to do this by myself? any ideas will be appreciate:)

**Comment by Fivele-Li** [comment]
Here is a backtesting script available for evaluating short-selling effectiveness：
https://github.com/microsoft/qlib/blob/05d67b38287a22d43d55aee76e8fb3bba87c5f48/qlib/contrib/evaluate.py#L261
But it hasn't been maintained for a long time. Some of the methods in it are outdated. You can try referring to this method and make some modifications.
