### ISSUE TITLE
plotting got stuck  while use 1min data backtest

### ISSUE THREAD

**Issue by ericyue** [microsoft/qlib#1625]
When backtest by 1min data (such as valid data contains half a year 1min bar) , the analysis_position.report_grap and analysis_model.model_performance_graph got stuck due to poor efficiency of plotly. 
is there any solution ? or a good idea is to replace plotly with matplotlib.

**Comment by ericyue** [comment]
I think the solution is resample the plot to daily too.  I can not find related function or docs about this in Qlib. If not supported   currently , is there any tips which function does this ?  Maybe I can try to fix.

**Comment by Fivele-Li** [comment]
As you mentioned, currently Qlib does not have a method for resampling graph data. You can write a new method and selectively call it in the appropriate places, such as analysis_position.report_graph and analysis_model.model_performance_graph, based on the amount of data available.
You are welcome to send a PR to fix this issue and become one of the contributors of Qlib.
