### ISSUE TITLE
descriptor 'lower' for 'str' objects doesn't apply to a 'float' object

### ISSUE THREAD

**Issue by guoz14** [microsoft/qlib#1628]
I tried updating data on existing datasets retrieved from Yahoo Finance using collector.py but received the following error.

The code used is: 
python scripts/data_collector/yahoo/collector.py update_data_to_bin --qlib_data_1d_dir ~/desktop/quant_engine/qlib_data/us_data --trading_date 2023-08-16 --end_date 2023-08-17 --region US

"us_data" folder saved those three folders (calendar, features, and instruments) which contain data collected, normalized, and dumped following the instruction.

![image](https://github.com/microsoft/qlib/assets/47837118/b28142e6-53cb-4d5b-b4ed-9697acb08394)

**Comment by quant2008** [comment]
你把pandas降级到1.5.3，numpy降级到1.23.5试试。安装视频可[参考这里](https://www.cctalk.com/v/16764198104427?sid=)，如果严格按这个视频安装，则各个包的版本就是对的。

**Comment by SunsetWolf** [comment]
Is the data you are using self-generated? You can check the following `instruments/all.txt` for abnormal data.
The data I downloaded using `scripts/get_data`  and didn’t find the problem you describe.

**Comment by guoz14** [comment]
> Is the data you are using self-generated? You can check the following `instruments/all.txt` for abnormal data. The data I downloaded using `scripts/get_data` and didn’t find the problem you describe.

The data is downloaded from Yahoo Finance by using the code provided in this link https://github.com/microsoft/qlib/tree/main/scripts/data_collector/yahoo#Automatic-update-of-daily-frequency-data

which is
python collector.py download_data --source_dir ~/.qlib/stock_data/source/us_data --start 2020-01-01 --end 2020-12-31 --delay 1 --interval 1d --region US

**Comment by SunsetWolf** [comment]
> > Is the data you are using self-generated? You can check the following `instruments/all.txt` for abnormal data. The data I downloaded using `scripts/get_data` and didn’t find the problem you describe.
> 
> The data is downloaded from Yahoo Finance by using the code provided in this link https://github.com/microsoft/qlib/tree/main/scripts/data_collector/yahoo#Automatic-update-of-daily-frequency-data
> 
> which is python collector.py download_data --source_dir ~/.qlib/stock_data/source/us_data --start 2020-01-01 --end 2020-12-31 --delay 1 --interval 1d --region US

Is the data in `~/desktop/quant_engine/qlib_data/us_data` your own generated data? You can check if the data in `~/desktop/quant_engine/qlib_data/us_data/instruments/all.txt` is in an exception. Because from the error message you provided, it may be due to the existence of abnormal values in ~/desktop/quant_engine/qlib_data/us_data/instruments/all.txt.

**Comment by guoz14** [comment]
> > > Is the data you are using self-generated? You can check the following `instruments/all.txt` for abnormal data. The data I downloaded using `scripts/get_data` and didn’t find the problem you describe.
> > 
> > 
> > The data is downloaded from Yahoo Finance by using the code provided in this link https://github.com/microsoft/qlib/tree/main/scripts/data_collector/yahoo#Automatic-update-of-daily-frequency-data
> > which is python collector.py download_data --source_dir ~/.qlib/stock_data/source/us_data --start 2020-01-01 --end 2020-12-31 --delay 1 --interval 1d --region US
> 
> Is the data in `~/desktop/quant_engine/qlib_data/us_data` your own generated data? You can check if the data in `~/desktop/quant_engine/qlib_data/us_data/instruments/all.txt` is in an exception. Because from the error message you provided, it may be due to the existence of abnormal values in ~/desktop/quant_engine/qlib_data/us_data/instruments/all.txt.

Yes the data is newly generated by using the qlib yahoo collector for US data not from get_data. I found that the line that is bugging is line 572 in qlib/utils/__init__.py, which is 

miss_code = set(pd.read_csv(_instrument, sep="\t", header=None).loc[:, 0].apply(str.lower)) - set(code_names)

The thing is somehow this part pd.read_csv(_instrument, sep="\t", header=None).loc[:, 0] is not identified as str but float. Therefore it fails to apply str.lower to this Series. I change it to pd.read_csv(_instrument, sep="\t", header=None).loc[:, 0].astype(str) then it works.

**Comment by SunsetWolf** [comment]
> > > > Is the data you are using self-generated? You can check the following `instruments/all.txt` for abnormal data. The data I downloaded using `scripts/get_data` and didn’t find the problem you describe.
> > > 
> > > 
> > > The data is downloaded from Yahoo Finance by using the code provided in this link https://github.com/microsoft/qlib/tree/main/scripts/data_collector/yahoo#Automatic-update-of-daily-frequency-data
> > > which is python collector.py download_data --source_dir ~/.qlib/stock_data/source/us_data --start 2020-01-01 --end 2020-12-31 --delay 1 --interval 1d --region US
> > 
> > 
> > Is the data in `~/desktop/quant_engine/qlib_data/us_data` your own generated data? You can check if the data in `~/desktop/quant_engine/qlib_data/us_data/instruments/all.txt` is in an exception. Because from the error message you provided, it may be due to the existence of abnormal values in ~/desktop/quant_engine/qlib_data/us_data/instruments/all.txt.
> 
> Yes the data is newly generated by using the qlib yahoo collector for US data not from get_data. I found that the line that is bugging is line 572 in qlib/utils/**init**.py, which is
> 
> miss_code = set(pd.read_csv(_instrument, sep="\t", header=None).loc[:, 0].apply(str.lower)) - set(code_names)
> 
> The thing is somehow this part pd.read_csv(_instrument, sep="\t", header=None).loc[:, 0] is not identified as str but float. Therefore it fails to apply str.lower to this Series. I change it to pd.read_csv(_instrument, sep="\t", header=None).loc[:, 0].astype(str) then it works.

Ok, very glad you solved the issue.
