### ISSUE TITLE
生成csi100股池文件，出错

### ISSUE THREAD

**Issue by quant2008** [microsoft/qlib#1629]
我运行 python collector.py --index_name CSI100 --qlib_dir ~/.qlib/qlib_data/cn_data --method parse_instruments，想生成csi100股池文件，得到如下出错信息，是什么原因呢？
![image](https://github.com/microsoft/qlib/assets/116711018/183ec338-02d1-49a2-9be3-5a9ce9dee02e)

**Comment by Fivele-Li** [comment]
我使用你的参数跑了几次没有复现你说的问题：
![image](https://github.com/microsoft/qlib/assets/128388363/8a4b82c8-6c85-4e29-bc44-ce8abfd81e3d)
![image](https://github.com/microsoft/qlib/assets/128388363/d64d88b6-4a45-40fa-ab7a-081901f20e02)

可以查看下是否因为网络不稳定导致下载文件异常，同时你也可以打印一下retry_request的参数和返回以定位问题。

**Comment by quant2008** [comment]
我是windows下，python3.8 最新的qlib。还是有问题

**Comment by quant2008** [comment]
我在cn_index\collector.py中修订 CSIIndex.get_changes()方法，在其中加入time.sleep(2)，就正常了。估计是远程对过快的频繁访问施加了限制

**Comment by moesakura** [comment]
我这边也触发了这个问题 现在是首次访问都会报错
是否可以考虑增加增量模式

**Comment by Peakara** [comment]
更新的csi100.txt为什么有时候有128只？
