### ISSUE TITLE
ModuleNotFoundError: No module named 'qlib.contrib.estimator'

### ISSUE THREAD

**Issue by a6225301** [microsoft/qlib#163]
## ❓ Questions and Help

Hi, i have installed the pyqlib successfully, and when i test the code :
import sys
from pathlib import Path
import qlib
import pandas as pd
from qlib.config import REG_CN
from qlib.contrib.model.gbdt import LGBModel
from qlib.contrib.estimator.handler import QLibDataHandlerClose
from qlib.contrib.strategy.strategy import TopkDropoutStrategy
from qlib.contrib.evaluate import (
    backtest as normal_backtest,
    risk_analysis,
)

It occurs the error with : 
![image](https://user-images.githubusercontent.com/22911232/103325750-27e10c80-4a88-11eb-9d60-16cfae844892.png)

**Comment by you-n-g** [comment]
Please upgrade you qlib versionto latest version.
`estimator` is no longer be used now.

**Comment by a6225301** [comment]
How about that error ? It seems to come from the Cython ?

ModuleNotFoundError: No module named 'qlib.data._libs.rolling'

**Comment by bxdd** [comment]
I think you can read the error message carefully. Are there any tips similar to "Do not import qlib package in the repository directory" in the error message?
