### ISSUE TITLE
A few questions for help in official examples

### ISSUE THREAD

**Issue by ghyzx** [microsoft/qlib#1648]
Hello gentleman, I have a few questions need help,thanks.
In official examples (https://github.com/microsoft/qlib/blob/main/examples/workflow_by_code.ipynb) , 'benchmark=SH000300' is the benchmark for comparison and is easy to understand.

1.However, it seems that the 'market' can only assign limited indices such as CSI300, CSI500, and CSI800, and cannot specify specific stock codes. How can we analyze only a few specified stocks (not in CSI300)?

2.How can the process/log of selecting stocks (which stocks were bought/sold on which day) be seen when using the "TopkDropoutStrategy" in backtesting?

-------------------------------------------------------
您好，有几个疑问请教一下：
在官方示例（https://github.com/microsoft/qlib/blob/main/examples/workflow_by_code.ipynb）中，benchmark = "SH000300" 是对照的基准，容易理解，
1.但是 market 似乎只能赋值csi300, csi500, csi800等有限指数，而不能指定具体股票代码，如何只分析指定的几支股票了（尤其是不在csi300里的股票）？
2.当使用"TopkDropoutStrategy"回测时，其筛选股票的过程/log（哪一天买进/卖出什么股票）如何才能看到了？

**Comment by quant2008** [comment]
你这个涉及
1 如何自定义股池文件
2 如何查看策略买卖记录。

关于1，很简单，你可以模仿csi300.txt，自己创建股池文件，比如mypool.txt。
关于2，可以在配置文件设置verbose，如下
![1694933558805](https://github.com/microsoft/qlib/assets/116711018/cfc17ec1-7b63-48b2-bd17-565d98fb5ab2)
另外，可以参考[这里](https://www.cctalk.com/m/group/90710187)。

**Comment by ghyzx** [comment]
@quant2008 , Thank you for your timely answer, appreciate!
