### ISSUE TITLE
The benchmark ['SH000300'] does not exist!

### ISSUE THREAD

**Issue by Thomas-Frew** [microsoft/qlib#1649]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

Hello everyone!

**I am getting the issue: The benchmark ['SH000300'] does not exist. Please provide the right benchmark.
Do I need to download this benchmark somehow? If so, how do I do so?**

Thanks!

**Comment by SunsetWolf** [comment]
I'd like to know, how did this issue come about? It would be very helpful for me to check the issue.
