### ISSUE TITLE
Could not normalize data downloaded from Yahoo Finance using the collector function provided

### ISSUE THREAD

**Issue by guoz14** [microsoft/qlib#1663]
## 🐛 Bug Description

I could not normalize data downloaded from Yahoo Finance using the collector function provided.

## To Reproduce

1. RUN: python scripts/data_collector/yahoo/collector.py download_data --source_dir ~/desktop/quant_engine/qlib_data/us_data --start 2000-01-02 --end 2023-09-29 --delay 1 --interval 1d --region US
2. RUN: python scripts/data_collector/yahoo/collector.py normalize_data --source_dir ~/desktop/quant_engine/qlib_data/us_data --normalize_dir ~/desktop/quant_engine/qlib_data/us_1d_nor --region US --interval 1d
3. The bug will pop up in step 2 

## Screenshot

![image](https://github.com/microsoft/qlib/assets/47837118/ed0ad23b-5963-449d-85d2-012c55efb86a)

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version: 0.9.3
 - Python version: 3.8.17
 - OS (`Windows`, `Linux`, `MacOS`): 'Windows'
 - Commit number (optional, please provide it if you are using the dev version):

## Additional Notes

my pandas version is 1.5.3

**Comment by SunsetWolf** [comment]
I was using the same two commands as you:. 
```
python scripts/data_collector/yahoo/collector.py download_data --source_dir /data/qlib_data/us_data --start 2000-01-02 --end 2023-09-29 --delay 1 --interval 1d --region US
python scripts/data_collector/yahoo/collector.py normalize_data --source_dir /data/qlib_data/us_data --normalize_dir /data/qlib_data/us_data_normalize --region US --interval 1d
```
In the second step, which is normalize_data, the problem you describe was not found.
I think that the problem you describe may be caused by incomplete data being downloaded. Try checking your data, or re-downloading the data, it might solve the problem.

**Comment by guoz14** [comment]
> I was using the same two commands as you:. 
> 
> ```
> 
> python scripts/data_collector/yahoo/collector.py download_data --source_dir /data/qlib_data/us_data --start 2000-01-02 --end 2023-09-29 --delay 1 --interval 1d --region US
> 
> python scripts/data_collector/yahoo/collector.py normalize_data --source_dir /data/qlib_data/us_data --normalize_dir /data/qlib_data/us_data_normalize --region US --interval 1d
> 
> ```
> 
> In the second step, which is normalize_data, the problem you describe was not found.
> 
> I think that the problem you describe may be caused by incomplete data being downloaded. Try checking your data, or re-downloading the data, it might solve the problem.


Thanks! I think it is related to how pandas identifies the format of datetime. I tried downloading several ETF data from Bloomberg, checking every one of them to make sure they were in the correct format, normalizing them, and dumping them. While it did not work out on my desktop, it worked out on Colab, which means even if my data are clean data, the code still won't work on my desktop. Super weird.

**Comment by SunsetWolf** [comment]
> > I was using the same two commands as you:.
> > ```
> > 
> > python scripts/data_collector/yahoo/collector.py download_data --source_dir /data/qlib_data/us_data --start 2000-01-02 --end 2023-09-29 --delay 1 --interval 1d --region US
> > 
> > python scripts/data_collector/yahoo/collector.py normalize_data --source_dir /data/qlib_data/us_data --normalize_dir /data/qlib_data/us_data_normalize --region US --interval 1d
> > ```
> > 
> > 
> > In the second step, which is normalize_data, the problem you describe was not found.
> > I think that the problem you describe may be caused by incomplete data being downloaded. Try checking your data, or re-downloading the data, it might solve the problem.
> 
> Thanks! I think it is related to how pandas identifies the format of datetime. I tried downloading several ETF data from Bloomberg, checking every one of them to make sure they were in the correct format, normalizing them, and dumping them. While it did not work out on my desktop, it worked out on Colab, which means even if my data are clean data, the code still won't work on my desktop. Super weird.

After seeing your reply, I switched to windows, created a new virtual environment in windows, then pulled the latest code and installed it, running the command: `python collector.py normalize_data --source_dir E:/yahoo_data/us_source --normalize_dir E:/yahoo_data/us_normalize --interval 1d --region cn`
Still didn't find the problem you described, finally I noticed that my pandas version is 1.5.3.

**Comment by guoz14** [comment]
> > > I was using the same two commands as you:.
> > > ```
> > > 
> > > python scripts/data_collector/yahoo/collector.py download_data --source_dir /data/qlib_data/us_data --start 2000-01-02 --end 2023-09-29 --delay 1 --interval 1d --region US
> > > 
> > > python scripts/data_collector/yahoo/collector.py normalize_data --source_dir /data/qlib_data/us_data --normalize_dir /data/qlib_data/us_data_normalize --region US --interval 1d
> > > ```
> > > 
> > > 
> > > In the second step, which is normalize_data, the problem you describe was not found.
> > > I think that the problem you describe may be caused by incomplete data being downloaded. Try checking your data, or re-downloading the data, it might solve the problem.
> > 
> > 
> > Thanks! I think it is related to how pandas identifies the format of datetime. I tried downloading several ETF data from Bloomberg, checking every one of them to make sure they were in the correct format, normalizing them, and dumping them. While it did not work out on my desktop, it worked out on Colab, which means even if my data are clean data, the code still won't work on my desktop. Super weird.
> 
> After seeing your reply, I switched to windows, created a new virtual environment in windows, then pulled the latest code and installed it, running the command: `python collector.py normalize_data --source_dir E:/yahoo_data/us_source --normalize_dir E:/yahoo_data/us_normalize --interval 1d --region cn` Still didn't find the problem you described, finally I noticed that my pandas version is 1.5.3.

No worries. I think if it works out on Colab then it is good. The reason why I say maybe it is pandas on my desktop is that I failed trying the code with ETF data either with a different bug "Casting to unit-less dtype 'datetime64' is not supported. Pass e.g. 'datetime64[ns]' instead." while it works on Colab perfectly. Again a pandas datetime issue. I am working in Hong Kong using my work desktop of which the region setting is Hong Kong while the time format is the same as US using MM/DD/YYYY; I guess that could be the source of the problem?

**Comment by ElonJustin7** [comment]
> I was using the same two commands as you:.
> 
> ```
> python scripts/data_collector/yahoo/collector.py download_data --source_dir /data/qlib_data/us_data --start 2000-01-02 --end 2023-09-29 --delay 1 --interval 1d --region US
> python scripts/data_collector/yahoo/collector.py normalize_data --source_dir /data/qlib_data/us_data --normalize_dir /data/qlib_data/us_data_normalize --region US --interval 1d
> ```
> 
> In the second step, which is normalize_data, the problem you describe was not found. I think that the problem you describe may be caused by incomplete data being downloaded. Try checking your data, or re-downloading the data, it might solve the problem.

Hello, I encountered an error while normalizing data downloaded from Yahoo Finance using the collector function. The error message is: "TypeError: can't compare offset-naive and offset-aware datetimes." This occurred during the normalization process. Do you know how to resolve this issue?
![1](https://github.com/microsoft/qlib/assets/129352610/ac7feae2-d52e-454c-8cf7-c3f31bfca3d8)
