### ISSUE TITLE
Do you have some size compare between csv, databases or hdf5

### ISSUE THREAD

**Issue by Qxxxx** [microsoft/qlib#167]
## ❓ Questions and Help

Hi qlib teams,

You have compare the speed of qlib data between some other database. Do you have some compare regarding the storage size?

**Comment by you-n-g** [comment]
Please refer to our paper. The first line of the table described the storage size of the different solutions.
![image](https://user-images.githubusercontent.com/465606/103451200-f5d7e080-4cfb-11eb-9b2a-a83e3525ed5b.png)

**Comment by Qxxxx** [comment]
Thanks a lot!
