### ISSUE TITLE
关于将后下载的指数数据补充到dump好的文件夹内的问题

### ISSUE THREAD

**Issue by ElonJustin7** [microsoft/qlib#1678]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

If using my own prepared data, how can I supplement the additional index stock pool and index price data into the folder where I've dumped the data using my own data? The index files include SH000300.csv and SH000905.csv, and the stock pools are csi300.txt and csi500.txt.

**Comment by SunsetWolf** [comment]
If you want to do an incremental update to an existing bin file, you can use the following command.
`python scripts/dump_bin.py dump_update --csv_path <csv path> --qlib_dir <qlib dir> --freq day --date_field_name <date field name> --symbol_field_name <symbol field name> --exclude_fields <date field name, symbol field name>`
If you want to update csi300.txt and csi500.txt, it is mentioned in [this documentation](https://qlib.readthedocs.io/en/latest/component/data.html#stock-pool-market).
