### ISSUE TITLE
adjust_dates in config

### ISSUE THREAD

**Issue by qtbgo** [microsoft/qlib#168]
## ❓ Questions and Help
Hi, could you give a config example on "adjust_dates" setting for strategy TopkDropoutStrategy. for example, every week one, we adjust position.
    "strategy": { # 策略相关参数
        "class": "TopkDropoutStrategy", # 策略类
        "module_path": "qlib.contrib.strategy.strategy", # 策略类所属模块
        "kwargs": { # 策略类参数
            "topk": 50,
            "n_drop": 5,
            "adjust_dates": **????**
        },
    },

**Comment by you-n-g** [comment]
The `adjust_dates` is a list of dates.
It will be passed into [this initialization function](https://github.com/microsoft/qlib/blob/main/qlib/contrib/strategy/strategy.py#L231)

And here is some docstring about the usage 
https://github.com/microsoft/qlib/blob/main/qlib/contrib/strategy/strategy.py#L120
https://github.com/microsoft/qlib/blob/main/qlib/contrib/strategy/strategy.py#L128

**Comment by qtbgo** [comment]
Yes, I see the code and I know it's dates list. What I don't know is how to config it in the "kwargs" section.
I tried: "adjust_dates": [2020-1-1] or  ['2010-1-1'], didn't work.

**Comment by you-n-g** [comment]
Here is my config. It works well in my case. Based on https://github.com/microsoft/qlib/blob/main/examples/benchmarks/LightGBM/workflow_config_lightgbm_Alpha158.yaml , I  only changed two places marked in the image.

![image](https://user-images.githubusercontent.com/465606/103476730-4847f880-4df3-11eb-9d93-eeed1ab0dfe8.png)

**Comment by qtbgo** [comment]
Thank you for your reply. But I'm not using a yaml file, I am working on your workflow_by_code.ipynb, it uses a dict to keep config information. And I tried your method in the dict, still didn't work. Any idea?

**Comment by you-n-g** [comment]
@qtbgo  
You can set a  break point (import pdb; pdb.set_trace()) here to check what happens when checking trading date
https://github.com/microsoft/qlib/blob/46c8d791ac0d9a3adccfcbf2a0d94e917467e056/qlib/contrib/strategy/strategy.py#L128
