### ISSUE TITLE
get_data数据更新问题

### ISSUE THREAD

**Issue by ElonJustin7** [microsoft/qlib#1682]
## 🐛 Bug Description

之前看到issue里有回答可以通过python scripts/get_data.py qlib_data --target_dir ~/.qlib/qlib_data/cn_data_v2  --version  #v2将下载日期更新到2021-06-11，但使用该命令下载后仍然只下载到和原来一样的到2020-09-25的数据，请问有人知道哪里出问题了吗？

**Comment by SunsetWolf** [comment]
Use `python scripts/get_data.py qlib_data --target_dir ~/.qlib/qlib_data/cn_data_v2 --version v2` command to download the data, is after the download, normalize, dump processed data, this data is stored in the cloud, for you to download the use of this data is relatively old, if you want to use the latest data, you can download the data, and then after the normalize, dump, qlib also provides the [relevant scripts](https://github.com/microsoft/qlib/blob/main/scripts/data_collector/yahoo/README.md), for your reference to use.

**Comment by ElonJustin7** [comment]
谢谢你！我还想问一个问题，当我使用我自己准备的数据（不是从yahoo finance上得到的）的时候，发现回测得到的结果明显比使用Qlib官方数据得到的结果要好。查看发现Qlib的数据中把一些涨停的股票当天数据置为了NAN，猜测不知道是不是因为这个原因。请问关于将自己准备的raw data需要处理涨停和跌停的数据为NAN吗？或者自己准备的数据还需要进行哪些更全面的预处理呢？

**Comment by ElonJustin7** [comment]
> As you mentioned, it is normal that the backtesting results of your data are better than the backtesting results of the official data. As for going from raw data to qlib data, there are three steps to go through: download, normalize, dump. The normalize step can be customized, which will also directly affect the final test results. qlib also welcomes you to do similar explorations. In addition, the official qlib data is based on the steps in [this document](https://github.com/microsoft/qlib/blob/main/scripts/data_collector/yahoo/README.md).

谢谢！而当我使用最新的代码python scripts/data_collector/yahoo/collector.py normalize_data时，出现了新的错误：AttributeError: 'Index' object has no attribute 'tz_localize'。看起来是与collector.py中新添加的一行代码有关，如下图所示。然而，这似乎本应该解决之前的TypeError: can't compare offset-naive and offset-aware datetimes的问题。这是什么原因呢？
<img width="967" alt="2" src="https://github.com/microsoft/qlib/assets/129352610/e488bd7b-e3c9-43e3-a2df-14c75e9db5c8">
![1](https://github.com/microsoft/qlib/assets/129352610/2194c7cd-7db2-4cde-bcc4-9d9dbab16466)

**Comment by graceYan777** [comment]
> > As you mentioned, it is normal that the backtesting results of your data are better than the backtesting results of the official data. As for going from raw data to qlib data, there are three steps to go through: download, normalize, dump. The normalize step can be customized, which will also directly affect the final test results. qlib also welcomes you to do similar explorations. In addition, the official qlib data is based on the steps in [this document](https://github.com/microsoft/qlib/blob/main/scripts/data_collector/yahoo/README.md).
> 
> 谢谢！而当我使用最新的代码python scripts/data_collector/yahoo/collector.py normalize_data时，出现了新的错误：AttributeError: 'Index' object has no attribute 'tz_localize'。看起来是与collector.py中新添加的一行代码有关，如下图所示。然而，这似乎本应该解决之前的TypeError: can't compare offset-naive and offset-aware datetimes的问题。这是什么原因呢？ <img alt="2" width="967" src="https://private-user-images.githubusercontent.com/129352610/285413253-e488bd7b-e3c9-43e3-a2df-14c75e9db5c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NjI4MzIsIm5iZiI6MTczMjc2MjUzMiwicGF0aCI6Ii8xMjkzNTI2MTAvMjg1NDEzMjUzLWU0ODhiZDdiLWUzYzktNDNlMy1hMmRmLTE0Yzc1ZTlkYjVjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwMjU1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2ZkZjA2OWRlMjVhYmI2ZDU1YzFmMTY2MmEzZmEwMDE4N2M0ODFmNmU3MWI2Y2NhNGEyNjhjYTNjZWZlMGMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tBRdLfDlPZS-G5czW9mUo1Ff3PokXw8o5kcjvDtlv_Y"> ![1](https://github.com/microsoft/qlib/assets/129352610/2194c7cd-7db2-4cde-bcc4-9d9dbab16466)

请问怎么解决的呢  我这边也有这个问题AttributeError: 'Index' object has no attribute 'tz_localize'
