### ISSUE TITLE
An error while **normalizing data** downloaded from Yahoo Finance

### ISSUE THREAD

**Issue by ElonJustin7** [microsoft/qlib#1699]
## ❓ Questions and Help

Hello, I encountered an error while **normalizing data** downloaded from Yahoo Finance using the collector function. The error message is: **"TypeError: can't compare offset-naive and offset-aware datetimes."** This occurred during the normalization process. Does anyone know how to resolve this issue? Thanks!
![1](https://github.com/microsoft/qlib/assets/129352610/625a9f9f-ae04-4e6d-8301-893e2e7f3a0b)

**Comment by guoz14** [comment]
I have encountered the same error before. I re-downloaded the raw data and it worked. I do not know what is the reason though

**Comment by ElonJustin7** [comment]
> I have encountered the same error before. I re-downloaded the raw data and it worked. I do not know what is the reason though

Thanks! And did you use a larger max_worker when re-downloading the data? It seems like the normal re-download is too slow and might take more than eight hours.

**Comment by guoz14** [comment]
yes I used 6 out of 8 in total. I do not suggest using the maximum workers lol, it may fail in the middle. I think I re-downloaded several times; yahoo finance is kinda unstable. You may want to get another data source in the end.
