### ISSUE TITLE
Seeking Update for Latest CSI300 Constituents Data Post-2020-09-25

### ISSUE THREAD

**Issue by VictorLore** [microsoft/qlib#1700]
Hi,

The csi300.txt file from the instrument folder contains data only up to 2020-09-25. Even if I tried fetching data using 
`D.list_instruments(instruments=D.instruments(market='csi300'), as_list=False)`, I still got the latest date as of 2020-09-25.

I'm looking to access the rolling constituents of the CSI300 index up to the most recent date. Is there a way to obtain this data through Qlib? Any guidance or suggestions on how to update or access the latest CSI300 constituents would be greatly appreciated.

**Comment by guoz14** [comment]
You may want to check this 

https://github.com/microsoft/qlib/tree/main/scripts/data_collector/cn_index
