### ISSUE TITLE
Label Impact is big

### ISSUE THREAD

**Issue by bbfrog** [microsoft/qlib#171]
Just using the default cn_data and example: qrun benchmarks/LightGBM/workflow_config_lightgbm_Alpha158.yaml
The label is generated by using close price in Alpha158 class: return (["Ref($close, -2)/Ref($close, -1) - 1"], ["LABEL0"])
The results look like very good:
'The following are analysis results of the excess return with cost.'
                       risk
mean               0.000495
std                0.005662
annualized_return  0.124615
information_ratio  1.386366
max_drawdown      -0.086166

Actually using vwap price in trading is more realistic than close price especially for big money. I tried to using Alpha158vwap, but it has this error: ERROR - qlib.workflow - [utils.py:35] - An exception has been raised[AttributeError: 'Index' object has no attribute 'swaplevel']. Maybe it is because the default data doesn't have the vwap feature?

Then I tried to use open price in label which is also not realistic but just a try: return (["Ref($open, -2)/Ref($open, -1) - 1"], ["LABEL0"]) //This is the only change I made.
The results doesn't look good: Please help to check whether there is a bug in training or some other reasons.
'The following are analysis results of the excess return with cost.'
                       risk
mean              -0.000078
std                0.005230
annualized_return -0.019764
information_ratio -0.238053
max_drawdown      -0.264827

**Comment by bbfrog** [comment]
port_analysis_config.backtest.deal_price need change to 'open', otherwise the backtest still uses the close price as deal price which is not align with training. After this change, the results look fine.

**Comment by you-n-g** [comment]
@bbfrog   We want to use vwap as out deal_prices, too.
But the public data source Yahoo doesn't privde vwap data.

**Comment by bbfrog** [comment]
Thanks, that's fine. Have u tried to change market from "csi300" to "all" in training? With this only change, the results became very bad. Any reason?

**Comment by you-n-g** [comment]
We've tried this on our high-quality data.
Normally,  trading on all stocks will produce much better results (IC, annual retrun) on csi300 if the size risk factor doesn't affect too much.

**Comment by bbfrog** [comment]
What's your meaning of high-quality data? 
And is it expected that using market "all" in the default cn_data provides bad results? Thanks!

**Comment by you-n-g** [comment]
High-quality data means the bought data instead the data crawled from Yahoo finance.
I'll try the model on market "all" and let you know when I get results

**Comment by you-n-g** [comment]
I've just run a model on all instruments.
I've got quite high IC  and low annual return.
![image](https://user-images.githubusercontent.com/465606/103474273-39564b80-4ddd-11eb-9462-898933be005d.png)

I think there are two reasons accounting for such results
1)  The CSI300 stock pool has much advantage to the market  (So it is more reasonable to choose CSI500 as benchmark when you select instruments from all stocks)
- https://xueqiu.com/S/SH000300
- https://xueqiu.com/S/SH000905
2) The current free data quality is low.

**Comment by bbfrog** [comment]
> I've just run a model on all instruments.
> I've got quite high IC and low annual return.
> ![image](https://user-images.githubusercontent.com/465606/103474273-39564b80-4ddd-11eb-9462-898933be005d.png)
> 
> I think there are two reasons accounting for such results
> 
> 1. The CSI300 stock pool has much advantage to the market  (So it is more reasonable to choose CSI500 as benchmark when you select instruments from all stocks)
> 
> * https://xueqiu.com/S/SH000300
> * https://xueqiu.com/S/SH000905
> 
> 1. The current free data quality is low. 

Thanks, your results are similar with mine. The cum return without cost (without subtract CSI300 bench return) is about -0.25, which should also be much lower than CSI500 bench. So it shouldn't be the first reason.

For the data quality issue, would you please run exactly the same experiment in your high quality data and check the results? Understand the reason is very important:) Thanks very much in advance!
