### ISSUE TITLE
numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by financialAIer** [microsoft/qlib#1756]
this project "https://github.com/SJTU-Quant/MASTER" uses qlib to load data. However, when I loaded the data, there is a bug.
the bug content is as follows:

File qlib\\data\\_libs\\rolling.pyx:1 in init qlib.data._libs.rolling

ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).

Could you check this? 
Thank you.

kind regards,

**Comment by l0ngc** [comment]
Hi, I have the same problem. Would you please share how did you solved it?

**Comment by Hanson13** [comment]
pip install -U numpy
