### ISSUE TITLE
I have Indian market data in csv format that contains all columns required for qlib format except the 'factor' column, the meaning of which is not clear from the documentation. I would like to know the nature of the data this column contains and whether the same can be generated by calculation from data in the other columns such as open, close, high, low, volume etc.

### ISSUE THREAD

**Issue by amar012** [microsoft/qlib#176]

**Comment by zhupr** [comment]
@amar012 Hi，
`factor` = `adjusted-close` / `close`
*adjusted price* reference: https://www.investopedia.com/terms/s/splitadjusted.asp

**Comment by amar012** [comment]
> @amar012 Hi，
> `factor` = `adjusted-close` / `close`
> _adjusted price_ reference: https://www.investopedia.com/terms/s/splitadjusted.asp

Thank you very much @zhupr for immediate response.
