### ISSUE TITLE
DDG-DA NaN loss

### ISSUE THREAD

**Issue by l0ngc** [microsoft/qlib#1771]
## To Reproduce

1. download the repo with git clone https://github.com/microsoft/qlib.git
2. install qlib with cd qlib and pip install .
3. cd examples/benchmark_dynamic/DDG-DA/
4.  run DDG-DA with python workflow.py run

## Expected Behavior

Expect DDG-DA could work and new rolling training backtest report could be printed.

## Screenshot

<img width="1189" alt="image" src="https://github.com/microsoft/qlib/assets/50039055/ddb09f73-00dc-4144-9c76-9a98038895f9">

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version: 0.9.3.99
 - Python version: 3.8.19
 - OS (`Windows`, `Linux`, `MacOS`): Linux
 - Commit number (optional, please provide it if you are using the dev version): 98f569eed2252cc7fad0c120cad44f6181c3acf6

## Additional Notes
I also reproduced this BUG on Google Colab, I used T4 GPU and high RAM as my virtual machine.   

https://colab.research.google.com/drive/1T5zIiE-LZi9TdzHIlwVmfV5ag1PdQUw1?usp=sharing  

In my local server, I used two 4090 GPUs, one AMD EPYC 7763 CPU, and 1T ram. Both produce the same error.

**Comment by ZhongHaoAustin** [comment]
You encountered the same issue as I did. To address it, I implemented the following code in `qlib/qlib/contrib/meta/data_selection/dataset.py` at line 183:

```python
d_train = d_train.replace([np.inf, -np.inf], np.nan)
d_test = d_test.replace([np.inf, -np.inf], np.nan)
```

After that, I navigated to the `qlib` directory and executed the following command to install qlib from the source code:

```bash
pip install .
```

Please note that installing from the source code may have specific requirements based on the Python version. In my case, the Python version is 3.8.

**Comment by ssyzymssyzym** [comment]
可能是代码改变了，183行加不了，不合理，我加代码的地方，供参考
            #新加代码
            d_train = d_train.replace([np.inf, -np.inf], np.nan) 
            d_test = d_test.replace([np.inf, -np.inf], np.nan)  
            #下面是原代码
            d_train = d_train.dropna(axis=0)
            d_test = d_test.dropna(axis=0)
