### ISSUE TITLE
 Client Error when downloading data

### ISSUE THREAD

**Issue by Yottaxx** [microsoft/qlib#1791]
Dear authors:

I've just faced  the client error when executing the codes illustrated in your official documentation:

> # download 1d
> python scripts/get_data.py qlib_data --target_dir ~/.qlib/qlib_data/cn_data --region cn
> 
> # download 1min
> python scripts/get_data.py qlib_data --target_dir ~/.qlib/qlib_data/qlib_cn_1min --region cn --interval 1min
> 
> 
or
> from qlib.tests.data import GetData
> 
> GetData().qlib_data(exists_skip=True)

> requests.exceptions.HTTPError: 403 Client Error: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. for url: https://qlibpublic.blob.core.windows.net/data/default/stock_data/v2/qlib_data_cn_1d_0.9.zip?sv=2020-10-02&st=2023-06-21T00%3A58%3A06Z&se=2043-06-22T00%3A58%3A00Z&sr=c&sp=rl&sig=ykiWECM7%2BsPLXE32ZM6p2Tc1mMDeUaCmo8LD%2BOKiAo4%3D

May I wonder is there any solution?

Envs:
Mac ( Intel )
python3.8
the latest version of qlib

**Comment by TompaBay** [comment]
I have similar issue when trying to download us data, wonder how did you solve it?
