### ISSUE TITLE
Variable selection for TFT

### ISSUE THREAD

**Issue by maciejdomagala** [microsoft/qlib#180]
Hi!

In the data preparation script for the Temporal Fusion Transformer Network ```qlib_Alpha158.py``` there is a selection of 20 features available from Alpha158 dataset, e.g. WVMA5, CORR5 etc. Is there any information about the selection method included in the framework? Were these selected after using variable selection network, testing or with other methods? If there is a place to find this information I would be thankful for pointing me there.

**Comment by you-n-g** [comment]
We trained a  model  based on lightGBM and select the 20 features with the higheset feature importance.
