### ISSUE TITLE
failed to create recorder

### ISSUE THREAD

**Issue by obiviously** [microsoft/qlib#181]
## 🐛 Bug Description

qlib.workflow.exp.Experiment base class
the method create_recorder(self, name=None)

In the subclass create_recorder(self, recorder_name=None)

if you use name as its para, it will fail to create a recorder

**Comment by Derek-Wds** [comment]
Thanks for pointing it out! This is indeed a bug for the API of `Experiment` class. I will fix it soon.

**Comment by you-n-g** [comment]
@obiviously  Thanks for your open this issue!
It is fixed now :)
https://github.com/microsoft/qlib/pull/182
