### ISSUE TITLE
Would you introduce about library of mlflow?

### ISSUE THREAD

**Issue by vinsvison** [microsoft/qlib#185]
## ❓ Questions and Help

What is the function of this library？**#MLFLOW**
this is just a  machinelearning frame，when i
run one of  benchmrks ,but it cound't it.

**Comment by you-n-g** [comment]
We implemented an experiments management interface `Qlib Recorder`. 
`mlflow` is one of the storage backend.  So users will interact with  [R](https://qlib.readthedocs.io/en/latest/component/recorder.html) instead of mlflow directly.

**Comment by vinsvison** [comment]
Thanks for your response ,so i feel mlflow which is too heavy?
import it ,Is it necessary？

**Comment by you-n-g** [comment]
Yes, `mlflow` is a little heavy.
So we decouple it from qlib. 

If mlflow becomes a problem for user, user could implement interfaces like [this]( https://github.com/microsoft/qlib/blob/main/qlib/workflow/expm.py#L17)

**Comment by vinsvison** [comment]
ok,i will waiting for your  decouple .

**Comment by you-n-g** [comment]
We've alreadly decoupled mlflow alreadly.
Currently, mlflow is the only backend storage.

**Comment by walter211** [comment]
Could you guys provide a mlflow tutorial, how to run qlib on mlflow, I dig this into few days, hard to get hands on.

**Comment by Derek-Wds** [comment]
Hi @walter211 , is there anything specific bothering you using Qlib right now? I wonder if you could give us more details about what are the problems so that we could help with you.

In fact, mlflow works as one of the storage backends for `Qlib recorder`, which is the experiment management system of Qlib ([link](https://qlib.readthedocs.io/en/latest/component/recorder.html)). We provide some basic interfaces for users to use, and users don't need to worry about how Mlflow works specifically in the system.

**Comment by walter211** [comment]
I want to submit Qlib training on to Mlflow……

**Comment by walter211** [comment]
> ote

yeah, that's it, thx bro!

**Comment by you-n-g** [comment]
@walter211  
Can you give us any hints about why current docs make you confusing?
We will appreciate it very much If you can give us some advices or create a PR about the docs, 

Thanks

**Comment by D-X-Y** [comment]
> We've alreadly decoupled mlflow alreadly.
> Currently, mlflow is the only backend storage.

It seems that Qlib still use "import mlflow" under "workflow", and the installation and running rely on mlflow, thus it does mean decoupling?

**Comment by you-n-g** [comment]
We decoupling mlflow from qlib on the interface level.
We can implement different backends.
mlflow is the default backend.  So we import it in the code now.

**Comment by D-X-Y** [comment]
Gotcha, thanks
