### ISSUE TITLE
about qlib data

### ISSUE THREAD

**Issue by ZFgan** [microsoft/qlib#186]
If you use the pre-reinstatement price，it will  imply future information.Howerer,If you use the real price,there will be problems in the calculation of return.Which kind of raw data is used in qilb?

**Comment by you-n-g** [comment]
@ZFgan Thanks for your reminder.
We use the adjusted-price in our dataset.
The price and volume are adjusted by the first trading day of each stock. So no future info is included in the data.

**Comment by ZFgan** [comment]
if qlib use pre-adjusted price，it will include  future info,because different day has different price

**Comment by ZFgan** [comment]
but if price are adjusted by the first trading day of each stock,some stock's price will too high

**Comment by you-n-g** [comment]
Qlib doesn't use pre-adjusted price.
 Adjusted by the first trading will not leak the future information.
Thought some stock price is high, Qlib will convert it to real price with factor. So it make no difference.

**Comment by ZFgan** [comment]
thanks you.and how to deal with ST?

**Comment by ZFgan** [comment]
and all factors calculate by adj price?like MEAN($CLOSE,5)?

**Comment by you-n-g** [comment]
We didn't do anything special to ST. 
All the factors in our dataset are based on adj pirce and volume

**Comment by ZFgan** [comment]
if i want to csv->qlib.data,i should use adj price and factor?not real price

**Comment by you-n-g** [comment]
You should use adjusted price  and adj-factor https://qlib.readthedocs.io/en/latest/component/data.html#converting-csv-format-into-qlib-format. 
Thanks

**Comment by ZFgan** [comment]
thank you very much

**Comment by ZFgan** [comment]
cs300 is dynamically adjusted,use new will forward-looking deviation

**Comment by you-n-g** [comment]
You are welcome. 
What do you mean by `dynamically adjusted` ?

**Comment by ZFgan** [comment]
cs300 stock pools are different in different periods of time.

**Comment by miaekim** [comment]
I think `dynamically adjusted` means `survivor-bias free data`.

**Comment by you-n-g** [comment]
@ZFgan   
Sorry for fogetting to reply.
We will use historical stock pool  like Point-In-Time data.  The information in the future will not be used in history.
