### ISSUE TITLE
D.features, redis_lock.AlreadyAcquired: Already acquired from this Lock instance.

### ISSUE THREAD

**Issue by pan-cai** [microsoft/qlib#19]
`
instruments = ['SH600000']
fields = ['close', ]
df = D.features(instruments, fields, start_time='2010-01-01', end_time='2012-12-31', freq='day')
print(df)
`

`
Traceback (most recent call last):
  File "test.py", line 127, in <module>
    df = D.features(instruments, fields, start_time='2010-01-01', end_time='2012-12-31', freq='day')
  File "F:\anaconda3\lib\site-packages\qlib-0.5.0-py3.6-win-amd64.egg\qlib\data\data.py", line 968, in features
    return DatasetD.dataset(instruments, fields, start_time, end_time, freq, disk_cache)
  File "F:\anaconda3\lib\site-packages\qlib-0.5.0-py3.6-win-amd64.egg\qlib\data\cache.py", line 301, in dataset
    return self._dataset(instruments, fields, start_time, end_time, freq, disk_cache)
  File "F:\anaconda3\lib\site-packages\qlib-0.5.0-py3.6-win-amd64.egg\qlib\data\cache.py", line 677, in _dataset
    with CacheUtils.writer_lock(self.r, "dataset-%s" % _cache_uri):
  File "F:\anaconda3\lib\contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "F:\anaconda3\lib\site-packages\qlib-0.5.0-py3.6-win-amd64.egg\qlib\data\cache.py", line 200, in writer_lock
    current_cache_wlock.acquire()
  File "F:\anaconda3\lib\site-packages\redis_lock\__init__.py", line 223, in acquire
    raise AlreadyAcquired("Already acquired from this Lock instance.")
redis_lock.AlreadyAcquired: Already acquired from this Lock instance.
`

**Comment by you-n-g** [comment]
Hello,
1) Please try `fields = ['$close', ]` instead of  `fields = ['close', ]`

2) It sees the key of the redis lock has existed in your redis db now.  You can use the following command to clear your redis keys and rerun your commands
![image](https://user-images.githubusercontent.com/465606/94340600-baab7e80-0035-11eb-9f62-8426f3b2f894.png)

Make sure there is not keys in your redis db by running `keys *` in redis.


Can you reproduce this error every time? 
Thanks in advance for your feedbacks

**Comment by pan-cai** [comment]
instruments = ['SH600000', ]
fields = ['$close', ]
df = D.features(instruments, fields, start_time='2010-01-01', end_time='2012-12-31', freq='day')
# df = D.features(instruments, fields, )
print(df)

Traceback (most recent call last):
  File "F:\anaconda3\lib\site-packages\qlib-0.5.0.dev0-py3.6-win-amd64.egg\qlib\data\data.py", line 968, in features
    return DatasetD.dataset(instruments, fields, start_time, end_time, freq, disk_cache)
TypeError: dataset() takes from 3 to 6 positional arguments but 7 were given

  File "F:\anaconda3\lib\site-packages\redis_lock\__init__.py", line 223, in acquire
    raise AlreadyAcquired("Already acquired from this Lock instance.")
redis_lock.AlreadyAcquired: Already acquired from this Lock instance.

**Comment by zhupr** [comment]
@pan-cai 
Hello,
- Have you cleaned up the redis keys?
- You can use the following command to clear your redis keys and rerun your commands, replace ``del *`` with ``flushall``
![image](https://user-images.githubusercontent.com/18660661/94342194-fa786300-0041-11eb-9a89-b5253bd8d2ab.png)

**Comment by you-n-g** [comment]
@pan-cai  @zhupr 
I've created a chat room. 
We can discuss the details if the issue is not solved https://gitter.im/Microsoft/qlib

**Comment by pan-cai** [comment]
- The same error after I cleaned up the redis keys
- The same error after I closed the server of redis
- According to the tutorial, it should work even I closed the server of redis

**Comment by zhupr** [comment]
@pan-cai 
If you are using windows, you can use the following code:
```python
import qlib
from qlib.data import D


if __name__ == "__main__":
    redis_host = "127.0.0.1"
    redis_port = 6379
    qlib.init(redis_host=redis_host, redis_port=redis_port)
    instruments = ["SH600000"]
    fields = ["$close", "$change"]
    df = D.features(instruments, fields, start_time='2010-01-01', end_time='2012-12-31')
    print(df.head())
```

**Comment by you-n-g** [comment]
@pan-cai  This is caused by the limitation of multiprocessing under window.
Please refer to [here](https://stackoverflow.com/a/24374798) for more info.

**Comment by pan-cai** [comment]
Thank you all

@you-n-g @zhupr

It works under windows OS.

=============================
import qlib
from qlib.data import D

if __name__ == "__main__":
    redis_host = "127.0.0.1"
    redis_port = 6379
    provider_uri = "F:/msqlib/qlib_data/cn_data"  # target_dir
    # qlib.init(redis_host=redis_host, redis_port=redis_port)
    qlib.init(provider_uri=provider_uri, region=REG_CN,)
    instruments = ["SH600000"]
    fields = ["$close", "$change"]
    # df = D.features(instruments, fields, start_time='2010-01-01', end_time='2012-12-31')
    df = D.features(instruments, fields, start_time='2010-01-01', end_time='2017-12-31', freq='day', )
    print(df.head())

========================================

**Comment by you-n-g** [comment]
Feel free to contact  us if you have any problems.
