### ISSUE TITLE
how to receive the long/short signals under TopkDropoutStrategy?

### ISSUE THREAD

**Issue by PayneJoe** [microsoft/qlib#195]
How to receive the long/short signals under TopkDropoutStrategy? Do we have to implement it on our own?

**Comment by you-n-g** [comment]
Hi, @PayneJoe 
The signals will be passed as a pandas.Sereis named [score_series](https://github.com/microsoft/qlib/blob/0524a47cf485fad7af118cde25d9981e51d029d2/qlib/contrib/strategy/strategy.py#L253)

If this can't meet your scenario, please give more details about your requriements.
Thanks

**Comment by PayneJoe** [comment]
> pandas

Great! Thanks @you-n-g
