### ISSUE TITLE
Problem with personal data

### ISSUE THREAD

**Issue by Cjaimesg** [microsoft/qlib#199]
## ❓ Questions and Help

Hi, I am followin the example workflow_by_code.ipynb and I am using my own data in csv format, I load data following this documentation https://qlib.readthedocs.io/en/latest/component/data.html#converting-csv-format-into-qlib-format

The problem is when I run 

`with R.start(experiment_name="train_model"):
    R.log_params(**flatten_dict(task))
    model.fit(dataset)
    R.save_objects(trained_model=model)
    rid = R.get_recorder().id`

The model doesn't converge, this is the ouput: 

`[60:MainThread](2021-01-19 19:28:39,745) INFO - qlib.workflow - [expm.py:245] - No tracking URI is provided. Use the default tracking URI.
[60:MainThread](2021-01-19 19:28:39,753) INFO - qlib.workflow - [exp.py:181] - Experiment 1 starts running ...
[60:MainThread](2021-01-19 19:28:39,775) INFO - qlib.workflow - [recorder.py:236] - Recorder 5a7c51cceee6404bbcf31347d6119a83 starts running under Experiment 1 ...
Training until validation scores don't improve for 50 rounds.
[20]	train's l2: nan	valid's l2: 0.833333
[40]	train's l2: nan	valid's l2: 0.833333
Early stopping, best iteration is:
[1]	train's l2: nan	valid's l2: 0.833333`

Testing the problem is in the segment when I define de dataset 

`"segments": {
                "train": ("2010-06-09", "2011-06-08"),
                "valid": ("2017-06-10", "2017-12-31"),
                "test": ("2018-01-01", "2020-08-01"),`

When one of the segments include the `2010-06-09` the model doesn't converge. But the data for this day is normal. 

![image](https://user-images.githubusercontent.com/37803157/105083600-23928880-5a63-11eb-9344-cc3ffd707939.png)

* This data is printed using the QlibDataLoader

Testing I download the predefined data (using QlibDataLoader) in workflow_by_code.ipynb in csv and applying the same transformation and the code works. 

Thanks, sorry for my english, it is not my native language.

**Comment by you-n-g** [comment]
Such raw data without preprocessing can hardly work in most of models.
You can follow the examples in `Qlib` to learn how to build your features and preprocess them.

**Comment by Cjaimesg** [comment]
Excuseme, what do you mean with preprocess? I am converting dataset from csv to bin data using scripts/dump_bin.py and I am applying the same data_handler as is show in `workflow_by_code.ipynb`. 

Further I can print all features with 
```
example_df = dataset.prepare("train")
print(example_df)
```
And this show, 

![image](https://user-images.githubusercontent.com/37803157/105188796-44f68180-5b02-11eb-9d41-532f0ceaf71d.png)

Apparently the only strange thing is the nan value, but is not the only one date with nan values.

**Comment by you-n-g** [comment]
It seems there are some nan in your training data

You can set a break point [here](https://github.com/microsoft/qlib/blob/main/qlib/contrib/model/gbdt.py#L50 )  to check the data

**Comment by Cjaimesg** [comment]
Thanks, i run the same preparation like `def _prepare_data(self, dataset: DatasetH)`
```
from qlib.data.dataset.handler import DataHandlerLP

df_train, df_valid = dataset.prepare(
            ["train", "valid"], col_set=["feature", "label"], data_key=DataHandlerLP.DK_L
        )
x_train, y_train = df_train["feature"], df_train["label"]
x_valid, y_valid = df_valid["feature"], df_valid["label"]
```
It give me the folow error 

![image](https://user-images.githubusercontent.com/37803157/105208307-8c870880-5b16-11eb-8e5d-6e291624ca6f.png)


I see that Label0 is definited by de next function 

```
def get_label_config(self):
        return (["Ref($close, -2)/Ref($close, -1) - 1"], ["LABEL0"])
```

But I dont understand what exactly means the 'Ref', I see that you use in alpha definition https://qlib.readthedocs.io/en/latest/advanced/alpha.html

but is not clear for me `Ref($close, -1)` means the close value for the past day.

**Comment by you-n-g** [comment]
Here is the docs for  [Ref](https://qlib.readthedocs.io/en/latest/reference/api.html#qlib.data.ops.Ref)
