### ISSUE TITLE
 Why is the number of stocks bought and sold sometimes asymmetric

### ISSUE THREAD

**Issue by quinnnnnnnnn** [microsoft/qlib#204]
## ❓ Questions and Help
just like this：
to simplyfy my Questions,  I adjust topk50 n_drop5 to👇
 "kwargs": {
            "topk": 10,
            "n_drop": 1,
        },

[I 2020-02-03]: sell SH600048, price 287.52, amount 2861.8361901134404, value 822820.96.
[I 2020-02-04]: sell SH601688, price 20.18, amount 59980.775791671644, value 1210112.22.
[I 2020-02-04]: buy SH603259, price 132.27, amount 7381.274784139132, value 976287.23.
[I 2020-02-04]: buy SH601012, price 280.91, amount 3505.487841197723, value 984714.73.

someday it just sell. And will cover the position the next day

**Comment by quinnnnnnnnn** [comment]
[I 2020-07-06]: buy SH601088, price 29.39, amount 1858.6890894967614, value 54627.57.
[I 2020-07-07]: sell SH601888, price 433.36, amount 3916.0454728791024, value 1697044.86.
sometimes it just buy 1 stock , and sell one the next day

**Comment by you-n-g** [comment]
There will be some limitations when trading (such as stock suspension).
https://github.com/microsoft/qlib/blob/main/qlib/contrib/backtest/exchange.py#L166
