### ISSUE TITLE
Is there any other strategies being on the way? 

### ISSUE THREAD

**Issue by PayneJoe** [microsoft/qlib#209]
Is there any other strategies being on the way, except for TopkDropout?

**Comment by you-n-g** [comment]
Strategies with risks will be released in the future.
But we have other features with higher priority.  It will take some time before we add new strategies.
Thanks

**Comment by PayneJoe** [comment]
> Strategies with risks will be released in the future.
> But we have other features with higher priority. It will take some time before we add new strategies.
> Thanks

After detailed offline backtesting, I have being conducting a trial for about two weeks with my actual account, customized market, alpha158 along with few additional factors, using the TopkDropout strategy. The result seems much better than I expected by now at least, though small difference exists between actual conduction and offline backtesting! In addition, the fluctuation, appeared in many ways, do not look beautiful. On user's side, continuing optimizing market and factors are easy and effective solutions. On platform's side, maybe strategy with more risky consideration is the GOOD way?

 Looking forward to it! Thanks
