### ISSUE TITLE
请问能得到每个因子的IC吗？

### ISSUE THREAD

**Issue by qtbgo** [microsoft/qlib#212]
## ❓ Questions and Help

执行案例alpha158的实验后，能够得到一个IC图，这个图是所有因子合成为一个因子的IC图吗。能不能得到每个单个因子的IC图？

**Comment by you-n-g** [comment]
Yes. 
You can use these functions to analysis each factor directly. https://qlib.readthedocs.io/en/latest/component/report.html
Thanks.
