### ISSUE TITLE
对于中国用户，能不能弄个QQ群

### ISSUE THREAD

**Issue by monkeycc** [microsoft/qlib#214]
有个技术交流群，会更好一点

**Comment by you-n-g** [comment]
We hope the QA could be shared. 
This will more friendly for all users.

If you want to use Instant Messaging like QQ or Wechat, you can use [gitter](https://gitter.im/Microsoft/qlib?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge), which is public.
 
There are not language restrictions :)
