### ISSUE TITLE
CUDA support ？

### ISSUE THREAD

**Issue by monkeycc** [microsoft/qlib#216]
`python -m pdb qlib/workflow/cli.py examples/benchmarks/LightGBM/workflow_config_lightgbm_Alpha158.yaml
`

I installed it
pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_ stable.html

But I found that I didn't support CUDA

Low CPU efficiency

**Comment by you-n-g** [comment]
Hi,  @monkeycc
Qlib didn't prevent users from using CUDA on the framework level.
Users could use CUDA when implementing specific modules. 

Thanks
