### ISSUE TITLE
How to set the filters for the instruments in workflow configuration file

### ISSUE THREAD

**Issue by shijie2016** [microsoft/qlib#218]
## ❓ Questions and Help

The docs provide an introduction to using filters in data retrieval. However, I am still confused about applying this in YAML workflow configuration file. I add the 'filter_pipe' in the configuration file and it doesn't work. Could I have an example?

qlib_init:
    provider_uri: ./qlibdata"
    region: cn
market: &market csi300
benchmark: &benchmark SH000300

data_handler_config: &data_handler_config
    start_time: 2008-01-01
    end_time: 2021-01-22
    fit_start_time: 2008-01-01
    fit_end_time: 2014-12-31
    instruments:
        market: *market
        **filter_pipe:
            [{filter_type: ExpressionDFilter, rule_expression: ["$close > 1000"], filter_start_time: 2008-01-01, filter_end_time: 2020-01-22, keep: False}]**

....

**Comment by Derek-Wds** [comment]
Hi @shijie2016 , sorry for the late update. This feature has been updated recently ([link](https://github.com/microsoft/qlib/pull/220)). Please now install the latest qlib from source and try again.

Thanks!

**Comment by shijie2016** [comment]
Hi  @Derek-Wds,  thanks for your effort, that helps a lot.  #230 
[alpha_with_filter.txt](https://github.com/microsoft/qlib/files/5897862/alpha_with_filter.txt)
I attach an example YAML file for your reference.
