### ISSUE TITLE
I can run the LSTM , AttributeError: 'DataFrame' object has no attribute 'config'

### ISSUE THREAD

**Issue by 1131683595** [microsoft/qlib#219]
`task = {
    "model":{#模型参数配置
        #模型类
        "class":"LSTM",
        #模型类所在模块
        "module_path":"qlib.contrib.model.pytorch_lstm_ts",
        "kwargs":{#模型超参数配置
            "d_feat": 20,
            "hidden_size": 64,
            "num_layers": 2,
            "dropout": 0.0,
            "n_epochs": 200,
            "lr": 2e-4,
            "early_stop": 10,
            "batch_size": 800,
            "n_jobs": 20,
            "metric": "loss",
            "loss": "mse",
            "GPU": 0,
           
        `}``

[
<img width="722" alt="捕获" src="https://user-images.githubusercontent.com/25927547/105709795-2a346a80-5f51-11eb-900e-8160d7bee0d1.PNG">
](url)

**Comment by you-n-g** [comment]
pytorch_lstm_ts  must be used with   `qlib.data.dataset.TSDatasetH`
Make sure you are using it with the right dataset class.
Thanks

**Comment by 1131683595** [comment]
Thanks a lot bro
I try to run it again&nbsp;



发自我的iPhone


------------------ Original ------------------

**Comment by 1131683595** [comment]
I have studied python for only 2weeks，The item is too big for me。Could u please send your code to me？ I want study how to config it。 thanks for your patience bro



发自我的iPhone


------------------ Original ------------------

**Comment by you-n-g** [comment]
@1131683595 
This is a example based on `qlib.data.dataset.TSDatasetH` and `LSTM`. 
You can compare it with your code and check the difference.
https://github.com/microsoft/qlib/blob/main/examples/benchmarks/LSTM/workflow_config_lstm_Alpha158.yaml

**Comment by pan-cai** [comment]
是不是和pandas的版本有关，需要哪个版本的pandas？

**Comment by 1131683595** [comment]
Thanks&nbsp;



发自我的iPhone


------------------ Original ------------------
From: you-n-g ***@***.***&gt;
Date: Mon,Jan 25,2021 10:09 PM
To: microsoft/qlib ***@***.***&gt;
Cc: 1131683595 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [microsoft/qlib] I can run the LSTM , AttributeError: 'DataFrame' object has no attribute 'config' (#219)





 
pytorch_lstm_ts  must be used with   qlib.data.dataset.TSDatasetH
 Make sure you are using it with the right dataset class.
 Thanks
