### ISSUE TITLE
How to understand analyze graphs?

### ISSUE THREAD

**Issue by lbq779660843** [microsoft/qlib#223]
Hi,

Thanks for sharing qlib. I'm a freshman about quant, and I've run a whole workflow in my SSE index dataset successlly. 

![4](https://user-images.githubusercontent.com/27773249/105970135-fe85c180-60c3-11eb-944a-3859eef7b1f9.PNG)

But I‘m still puzzled about these graphs represent the analysis result of the **market** or a single stock, and how to invest in the market as an individual。

**Comment by you-n-g** [comment]
Please check the explanation of metrics here.

https://qlib.readthedocs.io/en/latest/component/report.html
