### ISSUE TITLE
How to load dnn models?

### ISSUE THREAD

**Issue by PayneJoe** [microsoft/qlib#225]
It seems we can not load model with R.load_object method? Do we have to implement the loading logic with our own?

By the way, I just tried the TFT model.

Thanks~

**Comment by Derek-Wds** [comment]
Hi @PayneJoe , thanks for pointing this out! Yes, indeed, the `R` API we have in Qlib doesn't support saving models, and users have to implement the logic by themselves. 

Qlib has a base model API where users can create their own models. As you can see, the models can either be GBDT or DNN models, which may have different implementations based on various packages (Pytorch, Tensorflow, Lightgbm, etc.). This makes it difficult to find a compact and universal way to save all these models for now. 

We will try to figure something out in the future and if you have any good ideas, feel free to talk with us. Thanks!

**Comment by PayneJoe** [comment]
> Hi @PayneJoe , thanks for pointing this out! Yes, indeed, the `R` API we have in Qlib doesn't support saving models, and users have to implement the logic by themselves.
> 
> Qlib has a base model API where users can create their own models. As you can see, the models can either be GBDT or DNN models, which may have different implementations based on various packages (Pytorch, Tensorflow, Lightgbm, etc.). This makes it difficult to find a compact and universal way to save all these models for now.
> 
> We will try to figure something out in the future and if you have any good ideas, feel free to talk with us. Thanks!

Hi @Derek-Chu , thanks for your immediate reply! 

It troubled me for few hours, since the connecting 'rope' between offline backtesting and actual conduction, either intra-day manual trading or automatic trading, is missing. But it's okay for non-dnn models. 

I am testing the inference part with loaded model TFT, and seeking a more beautiful solution for it is on my roadmap!

Thanks~

**Comment by Derek-Wds** [comment]
We will support model saving and loading in the near future. I will reopen this issue for tracking the process.

Thanks~
