### ISSUE TITLE
What is the EXP_PATH in qlib/trade/main.py?

### ISSUE THREAD

**Issue by AlfredChenZH** [microsoft/qlib#238]
## 🐛 Bug Description

 When I am running the qlib/examples/trade/main.py file to Line 64, which is EXP_PATH = os.environ['EXP_PATH'], it triggers an error saying '*** KeyError: 'EXP_PATH''. And when I call to see os.environ.keys(), it clearly has no key named 'EXP_PATH'. So what is this path? Do I need to do some preparations before running the main code? Thank you very much.

## To Reproduce

1. Run the qlib/examples/trade/main.py code to Line 64.

## Environment

 - Qlib version: 0.6.1.99
 - Python version: 3.7.4 64-bit
 - OS (`Windows`, `Linux`, `MacOS`): Windows

**Comment by you-n-g** [comment]
@AlfredChenZH  
Current version of code is a example. 
The complete runnable version will be released soon.
Please be patient. Thanks :)

**Comment by taingload** [comment]
> @AlfredChenZH
> Current version of code is a example.
> The complete runnable version will be released soon.
> Please be patient. Thanks :)

Hi,I want to ask when we can get new release

**Comment by you-n-g** [comment]
@rk2900 is responsible for this branch. 
Could you please kindly answer this question? 
Thanks.

**Comment by rk2900** [comment]
The runnable code has been updated before March: https://github.com/microsoft/qlib/tree/high-freq-execution/examples/trade
Please have a try about this version and welcome to cite our paper.

We will update the whole framework in July.

**Comment by niurencheng** [comment]
现在解决了吗
