### ISSUE TITLE
Initialization bug in Qlib

### ISSUE THREAD

**Issue by phamanhtu17295** [microsoft/qlib#240]
After downloading data with the code:
python scripts/get_data.py qlib_data --target_dir ~/.qlib/qlib_data/cn_data --region cn

 according to the instruction in https://qlib.readthedocs.io/en/latest/start/initialization.html

I cannot run the following one:
import qlib
# region in [REG_CN, REG_US]
from qlib.config import REG_CN
provider_uri = "~/.qlib/qlib_data/cn_data"  # target_dir
qlib.init(provider_uri=provider_uri, region=REG_CN)

![Screenshot from 2021-02-01 10-33-52](https://user-images.githubusercontent.com/74130487/106412206-ba0a7500-6479-11eb-8066-289ec6029258.png)

**Comment by you-n-g** [comment]
@phamanhtu17295 
Please follow the prompted message.
![image](https://user-images.githubusercontent.com/465606/106449085-90c00800-64be-11eb-9425-8ecfbe7b04b8.png)


Thanks for your report.
