### ISSUE TITLE
Can I use 'pred.pkl' and 'label.pkl' generated by myself with the consistent structure and use Qlib to do backtest and portfolio_analysis?

### ISSUE THREAD

**Issue by JessieJie1998** [microsoft/qlib#249]

**Comment by you-n-g** [comment]
Of course,
Most of Qlib's components can be used standalone.

In the version of `0.5.1`,  our examples are presented in a smaller granularity.
https://github.com/microsoft/qlib/blob/v0.5.1/examples/train_and_backtest.py#L109

You can refer to it and use it in the same way in current version.

We will provide more fine-grained example later.

Thanks for your feedbacks :)
