### ISSUE TITLE
A problem when running the example in server without root permission

### ISSUE THREAD

**Issue by JessieJie1998** [microsoft/qlib#262]
## ❓ Questions and Help

It seems that R.save_objects(model) requires the root permission when making new directory. How can I fix this problem
Thanks.

**Comment by you-n-g** [comment]
@JessieJie1998  
You don't  need root permission to run qlib.
I think you don't have right permission to access current directory.

you can `ls -la` to check the permission setting of your current directory when running Qlib.

Thanks
