### ISSUE TITLE
configuration.yaml file has wrong identation

### ISSUE THREAD

**Issue by lbaiao** [microsoft/qlib#267]
The example configuration file, at https://qlib.readthedocs.io/en/latest/component/workflow.html, has identation issues.

**Comment by you-n-g** [comment]
@lbaiao 

Thanks for your reminder :)
Would you mind send a PR to amend it? 
Its quite simple. Just click this link below 
![image](https://user-images.githubusercontent.com/465606/107465130-a909e400-6b9c-11eb-9a75-ea8e36f04e9d.png)

**Comment by lbaiao** [comment]
Ok, done.

Em qua., 10 de fev. de 2021 às 01:37, you-n-g <notifications@github.com>
escreveu:

**Comment by you-n-g** [comment]
It's great! Thanks so much! It is merged now. :)
