### ISSUE TITLE
Wrong Prices Used During Backtest

### ISSUE THREAD

**Issue by aLeX1443** [microsoft/qlib#270]
## 🐛 Bug Description

Looking at the prices printed during the backtest, they seem to be off from the real prices.

```
[3674:MainThread](2021-02-14 22:10:40,855) INFO - qlib.backtest - [backtest.py:96] - [I 2021-02-12]: trade begin.
[I 2021-02-12]: sell LRCX, price 20.59, amount 173811.35, value 3579092.91.
[I 2021-02-12]: sell MXIM, price 3.30, amount 1035740.10, value 3418408.01.
[I 2021-02-12]: sell PPL, price 2.97, amount 1063778.08, value 3156110.89.
[I 2021-02-12]: sell ADSK, price 24.99, amount 130754.71, value 3267439.13.
```

For example, LRCX closed at `586.16` on `2021-02-12`, not `20.59`. Soure: https://finance.yahoo.com/quote/LRCX/
It seems like all the prices are off by a lot. I checked the raw data csv that gets downloaded by the yahoo data downloader in Qlib, and they have the correct data there.

## To Reproduce

1. Prepare the Yahoo data set for the US market with these instructions: https://github.com/microsoft/qlib/tree/main/scripts/data_collector/yahoo#1d-from-yahoo-1
2. Copy `sp500.txt` from `~/.qlib/qlib_data/us_data/instruments/` to `~/.qlib/stock_data/source/qlib_us_1d/`
3. Run the workflow in this gist with `qrun`: https://gist.github.com/aLeX1443/a56a0eb432c86a757ce1bf5b0cfd82f2

## Environment

 - Qlib version: 0.6.2
 - Python version: 3.7
 - OS: Ubuntu 20.04
 - Commit number (optional, please provide it if you are using the dev version): 0b11dc5

**Comment by you-n-g** [comment]
@aLeX1443 
The printed price is the adjusted price. 
The original  price is  `trade_price / order.factor`. Thanks so much.
https://github.com/microsoft/qlib/blob/main/qlib/contrib/online/executor.py#L151
Thanks for your report

**Comment by aLeX1443** [comment]
I see, thanks! The reason I'd like to see actual prices is I'm putting together a script that takes the price data up until yesterday and makes a prediction for tomorrow. Therefore, to automate a trade on a real exchange through an API, we will need to know the actual price to compute how many shares to buy.

I'll make a PR with this functionality once it is complete, as well as adding `Docker` as an option to run `Qlib`.
