### ISSUE TITLE
How to train rl model?

### ISSUE THREAD

**Issue by asdfqwer2015** [microsoft/qlib#271]
Is it possible to trian a RL model by qlib? Or how to implement a gym wrapper based on qlib?

Thanks.

**Comment by you-n-g** [comment]
We are developing an RL framework for High-frequency trading.
You can check if your requirements could be met after it is released.

Thanks for your feedbacks.

**Comment by asdfqwer2015** [comment]
Thank you for your reply :)

Hope to see the new framework. And will the new framework supports low or medium frequency trading (momentum trading)? If not, is there a way to simply wrap a gym class for momentum trading?

**Comment by you-n-g** [comment]
@asdfqwer2015   Low or medium frequency trading RL framework is not included in the next version recently. But I think the design can be shared to some extent.

**Comment by ChengYen-Tang** [comment]
Hi @you-n-g ,
I have a suggestion. I hope that qlib can be based on the openai gym design environment, so that we can use stable-baselines to quickly switch between different reinforcement learning algorithms.

**Comment by you-n-g** [comment]
@ChengYen-Tang  
In our current plan,  Qlib will not bind to any existing RL Framework.  It will provides some environments and interface which most existing RL framework could leverage easily.  Besides, some examples may be released in the future .

**Comment by 280777510** [comment]
> @ChengYen-Tang In our current plan, Qlib will not bind to any existing RL Framework. It will provides some environments and interface which most existing RL framework could leverage easily. Besides, some examples may be released in the future .

Hello, this year is 2023, the current version supports reinforcement learning and low and medium frequency data combination?
