### ISSUE TITLE
data not found for [SHxxxxxx].vwap

### ISSUE THREAD

**Issue by arisliang** [microsoft/qlib#274]
## 🐛 Bug Description

`qrun` command in `demo.sh` unable to find data, and fail to run

## To Reproduce
`qrun benchmarks/LightGBM/workflow_config_lightgbm_Alpha158.yaml`

## Expected Behavior

qrun demo to run successfully.

## Screenshot

![image](https://user-images.githubusercontent.com/1115503/108241234-95571280-7186-11eb-932c-558c7499d9c8.png)

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

Windows
AMD64
Windows-10-10.0.18362-SP0
10.0.18362

Python version: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]

Qlib version: 0.6.3.99
numpy==1.19.2
pandas==1.2.1
scipy==1.6.0
requests==2.25.1
sacred==0.8.2
python-socketio==3.1.2
redis==3.5.3
python-redis-lock==3.7.0
schedule==1.0.0
cvxpy==1.0.21
hyperopt==0.1.1
fire==0.4.0
statsmodels==0.12.1
xlrd==2.0.1
plotly==4.12.0
matplotlib==3.3.4
tables==3.6.1
pyyaml==5.4.1
mlflow==1.13.1
tqdm==4.56.0
loguru==0.5.3
lightgbm==3.1.1
tornado==6.1
joblib==1.0.0
fire==0.4.0
ruamel.yaml==0.16.12

 - Commit number (optional, please provide it if you are using the dev version): 0b11dc5167d8710368cc2703ec6dc18990c38a38

**Comment by you-n-g** [comment]
Yahoo does not provide `vwap` data. It is not a ERROR.
You can use your own data,

**Comment by you-n-g** [comment]
@zhupr  
Such warning will not appear in linux. Could you please check the warning in windows?  Thanks

**Comment by arisliang** [comment]
>Yahoo does not provide vwap data

Where is the vwap data told to use? Doesn't see it from the yaml config file.

**Comment by you-n-g** [comment]
@arisliang 
Several features use `vwap` in Alpha158  https://github.com/microsoft/qlib/blob/main/qlib/contrib/data/handler.py#L232

**Comment by arisliang** [comment]
Thanks, believe this issue is resolved after getting latest source cbbf6cd82260e533662a7433ba72cf3391347619
