### ISSUE TITLE
如何更换mlflow ui 的地址

### ISSUE THREAD

**Issue by rockkk-c** [microsoft/qlib#276]
## ❓ Questions and Help

模型训练过程追踪默认上传参数到http://activate.navicat.com:5000/，如何更换这个地址呢
![image](https://user-images.githubusercontent.com/58465378/108470878-917dda00-72c5-11eb-857c-d9f5446c841d.png)
试过将exp_manager的参数uri换成新地址http://x.x.x.x:xx，但http://x.x.x.x:xx的artifacts路径下无模型相关信息

**Comment by Derek-Wds** [comment]
Hi, did you start the mlflow server on the machine with `http://x.x.x.x:xx`? Here is the related doc of mlflow server: [link](https://www.mlflow.org/docs/latest/tracking.html#mlflow-tracking-servers).
