### ISSUE TITLE
AttributeError: 'XAxis' object has no attribute '_gridOnMajor'

### ISSUE THREAD

**Issue by arisliang** [microsoft/qlib#278]
## 🐛 Bug Description

In example notebook `workflow_by_code.ipynb`, encountered AttributeError when running line `analysis_model.model_performance_graph(pred_label)`

## To Reproduce

1. Open `workflow_by_code.ipynb`
2. Run all cells

## Expected Behavior

All cells in notebook should run without error.

## Screenshot

![image](https://user-images.githubusercontent.com/1115503/108541443-6d4de780-731d-11eb-84f4-9b6bdf6bb35f.png)

![image](https://user-images.githubusercontent.com/1115503/108541576-92425a80-731d-11eb-9b45-ba5cc6c8187d.png)

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

Linux
x86_64
Linux-5.8.0-43-generic-x86_64-with-glibc2.10
#49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021

Python version: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0]

Qlib version: 0.6.3.99
numpy==1.19.2
pandas==1.2.2
scipy==1.6.0
requests==2.25.1
sacred==0.8.2
python-socketio==3.1.2
redis==3.5.3
python-redis-lock==3.7.0
schedule==1.0.0
cvxpy==1.0.21
hyperopt==0.1.1
fire==0.4.0
statsmodels==0.12.1
xlrd==2.0.1
plotly==4.12.0
matplotlib==3.3.4
tables==3.6.1
pyyaml==5.4.1
mlflow==1.13.1
tqdm==4.56.0
loguru==0.5.3
lightgbm==3.1.1
tornado==6.1
joblib==1.0.1
fire==0.4.0
ruamel.yaml==0.16.12

 - Commit number (optional, please provide it if you are using the dev version):
fa8f1cba06ba511744a0625afdf2cc3ac05302d0

**Comment by kurucan** [comment]
I have the same problem:

![error](https://user-images.githubusercontent.com/7413036/119233371-59d73600-bb31-11eb-985f-222aee63e259.png)

**Comment by kurucan** [comment]
I have the same problem:

![error](https://user-images.githubusercontent.com/7413036/119233371-59d73600-bb31-11eb-985f-222aee63e259.png)

**Comment by arisliang** [comment]
I believe this issue is resolved after getting latest source cbbf6cd82260e533662a7433ba72cf3391347619.

**Comment by arisliang** [comment]
Not sure what happened, after getting commit 40416d8c301efdfadc572a8749be61cc7376d2c3, the issue happens again.

![image](https://user-images.githubusercontent.com/1115503/121556457-7a1a5680-ca46-11eb-81f7-b94ef49498fc.png)

**Comment by zhupr** [comment]
@arisliang Hi,  you can try updating `matplotlib` and `plotly`:`pip install -U matplotlib==3.1.3 plotly==4.12.0`

**Comment by zhupr** [comment]
@kurucan Hi, you can try updating `matplotlib` and `plotly`: `pip install -U matplotlib==3.1.3 plotly==4.12.0`

**Comment by arisliang** [comment]
After running the pip, it works now. Thanks!

**Comment by you-n-g** [comment]
Hi, @arisliang 
Would you mind sending a PR to improve the docs about this Question?
Other users who have similar confusion will be grateful to you :)
Thanks

For example, add some docs here.
https://qlib.readthedocs.io/en/latest/FAQ/FAQ.html

**Comment by arisliang** [comment]
A search in Issues on the error message would lead to this issue directly. Think it should be ok to leave it here.
