### ISSUE TITLE
How to run workflow_by_code.py in pycharm?

### ISSUE THREAD

**Issue by arisliang** [microsoft/qlib#279]
Running workflow_by_code.py in console works, but it gives error when running in pycharm:

>ModuleNotFoundError: No module named 'qlib.data._libs.rolling'.
Do not import qlib package in the repository directory in case of importing qlib from . without compiling

Is it possible to run in pycharm? It'll be easier to debug in the IDE environment.

**Comment by you-n-g** [comment]
Of course.
There are no IDE restrictions on the code.

Please read the error carefully.  You should not run the directory which contains `qlib`
https://github.com/microsoft/qlib/blob/main/qlib/data/ops.py#L23

**Comment by you-n-g** [comment]
@arisliang 
Did the current error info confuse you?  Do you have any suggestions about how to improve the readability of the error message?

Thanks  in advance.

**Comment by arisliang** [comment]
>You should not run it in the directory which contains qlib. 

How to "not run it in the directory which contains qlib" in pycharm? Is it configured in the working directory? Even if I change the working directory to C:\, the same error still happens.

![image](https://user-images.githubusercontent.com/1115503/108632697-39083180-74ab-11eb-8125-adb643879cf3.png)

**Comment by you-n-g** [comment]
@arisliang 
Could you run this  in `cli.py` to check your current path? 
`import os; print('os.getcwd()')`

Thanks.

**Comment by arisliang** [comment]
running `import os; print(os.getcwd())` in `cli.py`

![image](https://user-images.githubusercontent.com/1115503/108702436-39a0d680-7544-11eb-97da-db15ff6f349a.png)

**Comment by bxdd** [comment]
@arisliang Hi, have you configured `Cython support` in pycharm? https://www.jetbrains.com/help/pycharm/cython.html#cython-support

**Comment by arisliang** [comment]
@bxdd  As far as I know yes, I have no issue debugging for other scripts. How do I verify?

**Comment by bxdd** [comment]
Please verify by checking whether there are "*.so" or ".dll" files in the "qlib/data/_libs" folder.
If the verification fails, there are the following two solutions:
* Execute `python setup.py build_ext --inplace` in the source root folder to compile Cython files and generate executable files.
* Go to `Tools --> Run setup.py` Task. Then type in `build_ext` as task name and when prompted for Command-Line input type `--inplace` (https://stackoverflow.com/questions/36880336/setup-of-pycharm-for-cython)

**Comment by arisliang** [comment]
No ".so" or ".dll" file initially.
![image](https://user-images.githubusercontent.com/1115503/108838825-2444ae80-760f-11eb-98c5-0017b83749ab.png)

After executing `python setup.py build_ext --inplace`:

- there're more *.so" files show up.
![image](https://user-images.githubusercontent.com/1115503/108839173-acc34f00-760f-11eb-88cd-67d318440bea.png)

After running the first solution, the workflow_by_code.py runs successfully.
