### ISSUE TITLE
What's the meaning of rolling_slope, rolling_rsquare, and rolling_resi?

### ISSUE THREAD

**Issue by Bowen905** [microsoft/qlib#283]
In the document, slope means regression slope, but in rolling_slope function, there is only one parameter without window size, i just confuse about the regression for what, the parameter autoregression? And, the same question for rolling_rsquare and rolling_resi.

**Comment by bxdd** [comment]
Hi, What you said "there is only one parameter without window size" where can I find it?
And, the regression is an `linear regression` for the (series.index, series.value) in `window`, not autoregression. Please refer to [code](https://github.com/microsoft/qlib/blob/main/qlib/data/_libs/rolling.pyx#L87), obviously, the following code is the slope of linear regression:
```python
return (N*self.xy_sum - self.x_sum*self.y_sum) / (N*self.x2_sum - self.x_sum*self.x_sum)
```

**Comment by Bowen905** [comment]
The slope function code is:
`cdef class Slope(Rolling):
    """1-D array rolling slope"""
    cdef double i_sum # can be used as i2_sum
    cdef double x_sum
    cdef double x2_sum
    cdef double y_sum
    cdef double xy_sum
    def __init__(self, int window):
        super(Slope, self).__init__(window)
        self.i_sum  = 0
        self.x_sum  = 0
        self.x2_sum = 0
        self.y_sum  = 0
        self.xy_sum = 0

    cdef double update(self, double val):
        self.barv.push_back(val)
        self.xy_sum = self.xy_sum - self.y_sum
        self.x2_sum = self.x2_sum + self.i_sum - 2*self.x_sum
        self.x_sum = self.x_sum - self.i_sum
        cdef double _val
        _val = self.barv.front()
        if not isnan(_val):
            self.i_sum -= 1
            self.y_sum -= _val
        else:
            self.na_count -= 1
        self.barv.pop_front()
        if isnan(val):
            self.na_count += 1
            # return NAN
        else:
            self.i_sum  += 1
            self.x_sum  += self.window
            self.x2_sum += self.window * self.window
            self.y_sum  += val
            self.xy_sum += self.window * val
        cdef int N = self.window - self.na_count
        return (N*self.xy_sum - self.x_sum*self.y_sum) / \
            (N*self.x2_sum - self.x_sum*self.x_sum)`
in this slope function, the x means window size, and y means update value, right? My question is, if the inputs are update value and window size, what's the meaning for this regression?

**Comment by bxdd** [comment]
`x` means `series.index` rather than `window size`, y means `series.value`. `window size` is passed in `Slope.__init__`.
By the way, `Slope` is not the `rolling_slope` function, but this https://github.com/microsoft/qlib/blob/main/qlib/data/_libs/rolling.pyx#L197

**Comment by Bowen905** [comment]
Thank you for answering my question, but I'm still confusing about the input x, and y. So, could you give me an example for Slope function? What does the input data set look like?

**Comment by bxdd** [comment]
The return value of `rolling_slope(np.array([1,2,7,10]), 2)` is `np.array([nan, 1, 5, 3])`

**Comment by Bowen905** [comment]
For the example, x, the series.index, is range(4), and y, the series.value, is array([1,2,7,10]), is this right? Is there any economic meaning for this regression?

**Comment by bxdd** [comment]
Hi, what you said is almost right (in fact, there are still some small details that you must read the code to know).

These operators are just basic operations
* rolling_slope: the linear regression slope in the given window
* rolling_rsquare: the R-square `R^2` of  linear regression in the given window
* rolling_resi: the last linear regression residual between `value_{last}` and `slope*index_{last}+interp` in the given window

And they may be used when calculating some alpha factors, such as [Idiosyncratic volatility](https://www.sciencedirect.com/science/article/abs/pii/S0378426616301996)

**Comment by Bowen905** [comment]
Thank you. I get the basic knowledge for those operators, but I'm still not clear about how to use those operators. For example, the alpha factor 'Beta5', which is 'Slope($close, 5)/$close'. In my knowledge, the beta means the correlation between the returns of benchmark index and the returns of a stock. But, for the explanation you give me, i can't find the relationship.

**Comment by bxdd** [comment]
Wow, I’m not sure about the meaning of `Beta5`, but I guess that `Beta5` means the coefficient ![1](https://latex.codecogs.com/gif.latex?\beta) in linear regression ![2](https://latex.codecogs.com/gif.latex?y=\beta_0+X\beta). 
Is it right? @you-n-g

**Comment by you-n-g** [comment]
@bxdd  it is right.   
@Bowen905  It is different from the  Beta you explained.
