### ISSUE TITLE
有社区可以讨论和中文文档吗

### ISSUE THREAD

**Issue by jxtpro** [microsoft/qlib#285]
有社区可以讨论和中文文档吗

**Comment by Derek-Wds** [comment]
Hi, we only have a `gitter` [room](https://gitter.im/Microsoft/qlib?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) and English documents for now. We may try to support Chinese documents in the future. Thanks!

**Comment by jxtpro** [comment]
ok
