### ISSUE TITLE
运行起来有异常提示

### ISSUE THREAD

**Issue by jxtpro** [microsoft/qlib#289]
![image](https://user-images.githubusercontent.com/58840171/109249544-d7392600-7822-11eb-85b3-cd2b594e9782.png)

运行情况

$ cd scripts && python collect_info.py all
Darwin
x86_64
macOS-10.16-x86_64-i386-64bit
Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64

Python version: 3.8.8 (v3.8.8:024d8058b0, Feb 19 2021, 08:48:17)  [Clang 6.0 (clang-600.0.57)]

Qlib version: 0.6.3.99
numpy==1.20.1
pandas==1.2.2
scipy==1.6.1
requests==2.25.1
sacred==0.8.2
python-socketio==3.1.2
redis==3.5.3
python-redis-lock==3.7.0
schedule==1.0.0
cvxpy==1.0.21
hyperopt==0.1.1
fire==0.4.0
statsmodels==0.12.2
xlrd==2.0.1
plotly==4.12.0
matplotlib==3.1.3
tables==3.6.1
pyyaml==5.4.1
mlflow==1.14.0
tqdm==4.57.0
loguru==0.5.3
lightgbm==3.1.1
tornado==6.1
joblib==1.0.1
fire==0.4.0
ruamel.yaml==0.16.12

**Comment by zhupr** [comment]
@jxtpro Hi,
This is a warning from `plotly`. Future versions will be compatible with the new version of `plotly`.
Can the graphics be displayed normally?

**Comment by jxtpro** [comment]
图形可以正常显示的
