### ISSUE TITLE
qrun.exe SyntaxError: Non-UTF-8 code starting with '\x90' 

### ISSUE THREAD

**Issue by pan-cai** [microsoft/qlib#293]
win10

qlib 0.6.3.99 

`SyntaxError: Non-UTF-8 code starting with '\x90' in file xxx/Scripts/qrun.exe on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`

![屏幕截图 2021-03-02 073320](https://user-images.githubusercontent.com/12426310/109573293-c130ab80-7b29-11eb-9f11-128a17214a8d.png)

**Comment by you-n-g** [comment]
@pan-cai 
Could you give more information about your env by
https://github.com/microsoft/qlib/blob/main/scripts/collect_info.py

Thanks

**Comment by pan-cai** [comment]
qlib降到0.6.2, 并将numpy升级到最新，可以正常使用了

谢谢
