### ISSUE TITLE
"Unexpected keyword argument 'freq' " when runnning workflow.py

### ISSUE THREAD

**Issue by Abzd** [microsoft/qlib#294]
## 🐛 Bug Description

TypeError: __init__() got an unexpected keyword argument 'freq'

## To Reproduce

1. Change the directiory to '/qlib/highfreq/'
2. Run the command 'python workflow.py'

## Expected Behavior

Data prepared.

## Screenshot

![261614653336_ pic_hd](https://user-images.githubusercontent.com/26544989/109593450-f4843200-7b4b-11eb-85c1-16ebaca77bcb.jpg)

## Environment

 - Qlib version: 0.6.1.99
 - Python version: 3.8.8
 - OS (`Windows`, `Linux`, `MacOS`): MacOS

**Comment by bxdd** [comment]
@Abzd Hi, you can try to use the latest version of Qlib, the old version does not support the high-frequency part.

**Comment by pierremotard** [comment]
@bxdd Hi, I can clone the latest branch and work on the main branch but when I checkout to high-freq-execution branch, the setup.py seems to be outdated and I get the same error as above. To sum up, I cannot use the branch high-freq-execution on a recent version. 

**Environment**

- Python version: 3.8.12
- OS: MacOS Big Sur - M1 chip

**Comment by you-n-g** [comment]
@rk2900  will help to answer the problems on the  `high-freq-execution` branch

**Comment by rk2900** [comment]
fixed, please have a try.
