### ISSUE TITLE
Is it possible to realize weighted machine learning on Qlib?

### ISSUE THREAD

**Issue by JessieJie1998** [microsoft/qlib#295]
## ❓ Questions and Help

I want to give different weights to each stock based on market value, and  train the lightGBM model with the samples and their weights. But it seems troublesome for me to realize weighted machine learning under the framework of Qlib.
If I can get the weight for each stock outside Qlib, is it possible to realize weighted machine learning on Qlib?
I think I should modify codes in Qlib.contrib.model?

Thanks!

**Comment by you-n-g** [comment]
@JessieJie1998 
Hi, it is possible to train model with weighted samples in Qlib.

Here is an example from my personal code base.
![image](https://user-images.githubusercontent.com/465606/109637093-4a2a0000-7b87-11eb-8467-cf90014830b7.png)

The weights are stored as a column in the dataset. 
You can follow this example.

We may release examples with weighted samples in the future.

**Comment by JessieJie1998** [comment]
@you-n-g Thanks for your prompt reply
