### ISSUE TITLE
Can Not Create Dataset

### ISSUE THREAD

**Issue by D-X-Y** [microsoft/qlib#299]
## Demo Code Failed

When I run the following codes:
```
import os
import sys
import qlib

from qlib import config as qconfig
from qlib.utils import init_instance_by_config

qlib.init(provider_uri='~/.qlib/qlib_data/cn_data', region=qconfig.REG_CN)

dataset_config = {
            "class": "DatasetH",
            "module_path": "qlib.data.dataset",
            "kwargs": {
                "handler": {
                    "class": "Alpha158",
                    "module_path": "qlib.contrib.data.handler",
                    "kwargs": {
                        "start_time": "2008-01-01",
                        "end_time": "2020-08-01",
                        "fit_start_time": "2008-01-01",
                        "fit_end_time": "2014-12-31",
                        "instruments": "csi300",
                    },
                },
                "segments": {
                    "train": ("2008-01-01", "2014-12-31"),
                    "valid": ("2015-01-01", "2016-12-31"),
                    "test": ("2017-01-01", "2020-08-01"),
                },
            },
        }

dataset = init_instance_by_config(dataset_config)
```
It raised the following error:
![image](https://user-images.githubusercontent.com/9547057/109665829-8a01df00-7ba9-11eb-91e5-39e993b00418.png)

## To Reproduce

Just copy and pase the above code, then run it.

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version: The branch updated at 3 days ago: https://github.com/microsoft/qlib/commit/a96f0c2e5fa427ce33660c8791fa2057c6f423fc
 - Python version: Python 3.8.3
 - OS (`Windows`, `Linux`, `MacOS`): MacOS

**Comment by you-n-g** [comment]
@D-X-Y  Thanks for your report.
You can try following code.
```
if __name__ == "__main__":
     dataset = init_instance_by_config(dataset_config)
```
There are some limitations on python multiple processing.

https://stackoverflow.com/questions/34086112/python-multiprocessing-pool-stuck
https://docs.python.org/3/library/multiprocessing.html#multiprocessing-programming
![image](https://user-images.githubusercontent.com/465606/109748142-4e036400-7c13-11eb-8c76-8f9ad123d2a8.png)

**Comment by D-X-Y** [comment]
Thanks for your response. It works on my mac now.
A following question is, in the example nootbook: https://github.com/microsoft/qlib/blob/main/examples/workflow_by_code.ipynb 
There is no __main__ module, and does it mean this notebook cannot be runned in jupyter?
