### ISSUE TITLE
Why amount is not an integer？

### ISSUE THREAD

**Issue by quinnnnnnnnn** [microsoft/qlib#303]
## ❓ Questions and Help

I found that after setting verbose to true, the transaction volume in the transaction record is not an integer
The trading volume in the Chinese stock market needs to be a multiple of 100

[I 2020-01-03]: buy SZ300274, price 75.17, amount 2519.4217586817786, value 189390.79.
[I 2020-01-03]: buy SH600823, price 23.60, amount 8046.938388189488, value 189884.77.
[I 2020-01-03]: buy SH601808, price 21.69, amount 8691.459719098943, value 188533.98.
[I 2020-01-03]: buy SH601688, price 23.65, amount 7986.108958097924, value 188857.14.

**Comment by you-n-g** [comment]
@quinnnnnnnnn 
The amount is an adjusted value.

https://quantdare.com/approach-to-dividend-adjustment-factors-calculation/

**Comment by quinnnnnnnnn** [comment]
thanks

**Comment by quinnnnnnnnn** [comment]
@you-n-g Thanks! 
Could you tell me why price multiplied by amount does not equal value?

**Comment by you-n-g** [comment]
@quinnnnnnnnn 
There are two reasons that result in such a inequality
- Qlib use float32 to store the data which will introduce some accuracy loss.
- The inequality exists in the orignal data, too.

**Comment by quinnnnnnnnn** [comment]
@you-n-g Thanks for your answer
