### ISSUE TITLE
What is the basis for determining the target amount？

### ISSUE THREAD

**Issue by quinnnnnnnnn** [microsoft/qlib#305]
## ❓ Questions and Help
sry,I am not a native English speaker😝
In my opinion, amount is determined according to the adjust price & account cash, Such us,  when the position is opened on the first day, I guess the rule of amount is less than 10000000/50/adjust price & the bigger the better.
If this is the case, then the backtest is a little different from reality. 
Cause the strategies in reality are based on unadjusted price. If someone wants to buy stocks with equal weight, then he may prefer to use the unadjusted price instead of the adjusted price. Then unless we use the adjust price to buy stocks in the future, the amount in the historical backtest will be different from the actual amount.
In this case, the yield and other indicators are okay, but the amount of stocks may be irregular in real history.
I am very confused. I used  adjust data, Could you help me out?

**Comment by quinnnnnnnnn** [comment]
In this case, the cash in the account will also have a low utilization rate, because the adjusted price is higher than the real price

**Comment by you-n-g** [comment]
@quinnnnnnnnn 

Qlib will use original price  instead of adjusted price while trading.

https://github.com/microsoft/qlib/blob/main/qlib/contrib/backtest/exchange.py#L272

**Comment by quinnnnnnnnn** [comment]
@you-n-g Hi!

There seems to be something wrong with the data I used.

Here is the data i used. They all adjusted

date        | code | stock_code | volume | open      |       high |         low    |      close |    factor |  change |     vwap  | money
2020/1/3 | 2019 | SZ002019 | 264617 | 159.4865 | 160.9967 | 155.6604 | 156.5666 | 10.0685 | -0.0152 | 157.4293 | 4.14E+08

and my deal price is: "deal_price": "vwap"

here is deal log
[I 2020-01-03]: buy SZ002019, price 157.43, amount 1201.757241954933, value 189191.79.

it seems like there is no adjustment.
should i use unadjust vwap data? or I use it wrong?

**Comment by you-n-g** [comment]
@quinnnnnnnnn 

All the data in qlib are adjusted data when storing and calculating.
So the data in the log is also adjusted data.

The only exception is order dealing.

**Comment by quinnnnnnnnn** [comment]
@you-n-g 请问，如果workflow_by_code.ipynb里verbose=True输出的log的信息不是真的交易信息，那么我要怎么查看回测里真实的成交股票，成交价格和成交量呢？
我注意到在运行workflow_by_code.ipynb后，有些比如：pred_df，pred_df_dates，report_normal_df，positions，analysis_df可以打印出来查看，但并不包含我所需要的信息，是否还有其他可供查看的信息呢？谢谢!

**Comment by quinnnnnnnnn** [comment]
如果我另存一列vwap_original然后将交易价格设置为 "deal_price": "vwap_original"log信息是否会和真实的成交价格和成交量一致呢

**Comment by bxdd** [comment]
@quinnnnnnnnn hi, I will create a pull request to support this.
