### ISSUE TITLE
If/else support in data processor

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#307]
## 🌟 Feature Description
support if / else in data processor

## Motivation

I would like to filter out the label that's too small (e.g., < 0.1%) by setting them all to 0.0 so the model would not focus on predicting them.

**Comment by you-n-g** [comment]
Hi,
I think you can build such processor with our experssion engine and this filter https://github.com/microsoft/qlib/blob/main/qlib/data/dataset/processor.py#L105
