### ISSUE TITLE
qrun 运行workflow的结果有一些不太明白的地方

### ISSUE THREAD

**Issue by iceworld724** [microsoft/qlib#308]
我刚才在聚宽数据集上运行了LightGBM workflow，结果有一些不太明白的地方

1. 为什么2021-03-04的交易记录打印了两次？
2. 还有2021-03-01到2021-03-03每天买入和卖出的股票数不等，按照[Topk-Drop algorithm](https://qlib.readthedocs.io/en/latest/component/strategy.html#topkdropoutstrategy)  的解释和我的workflow配置，似乎应该每天换5只股票？

控制台打印的信息比较长，截图只截取了一部分。
workflow的配置见附件。

环境python 3.7， win10
版本0.6.2 

![image](https://user-images.githubusercontent.com/36391334/110074955-fef93280-7dbc-11eb-9573-081647e6d812.png)

[workflow_config_lightgbm_Alpha158.yaml.txt](https://github.com/microsoft/qlib/files/6088550/workflow_config_lightgbm_Alpha158.yaml.txt)

**Comment by you-n-g** [comment]
交易不到5支 是因为涨跌停限制导致有的股票无法买入或者卖出

**Comment by atlasju** [comment]
请问，每次交易的明细怎么打印出来的，我直接跑的例子，没有这个明细，或者这个明细在哪里保存了？

**Comment by you-n-g** [comment]
@atlasju 
You can use `order_list=True` to save the orders into recorder
https://github.com/microsoft/qlib/blob/main/qlib/workflow/record_temp.py#L253
