### ISSUE TITLE
Reason for using profits of previous day in example yamls

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#313]
In the example workflows given, they are using profits of previous trading day as label:
`"label": ["Ref($close, -2) / Ref($close, -1) - 1"]`
Why not use the profits of current trading day?
`"label": ["Ref($close, -1) / $close - 1"]`

**Comment by you-n-g** [comment]
`"Ref($close, -2) / Ref($close, -1) - 1"` indicates the profit of **next trading** day instead of previous trading day.
In other words,  it indicates that what profit could be gained if we buy a stock tomorrow and sell it the day after tomorrow.

**Comment by 2young-2simple-sometimes-naive** [comment]
So `Ref($close, -1)` means the close price of tomorrow, not yesterday?

**Comment by you-n-g** [comment]
Yes 
https://qlib.readthedocs.io/en/latest/reference/api.html#qlib.data.ops.Ref
