### ISSUE TITLE
How to extract alpha158 or alpha360 features from a given dataframe?

### ISSUE THREAD

**Issue by zhuangz-ma** [microsoft/qlib#315]
## ❓ Questions and Help

Hi, thank you for this great tool. 
I have two questions. 
1. I want to test alpha158 and alpha360 features with my own workflow(outside this framework), but I didn't find a method in which input is raw dataFrame and output is a dataFrame with features. How to extract alpha158 or alpha360 features from a given dataframe instead of a local file?
2. I want to test the trained model with real-time data. For now, my solution is saving the model as a local file, then loading the model in an outside real-time environment. Is this the supposed way to test real-time data?

**Comment by you-n-g** [comment]
1. Currently the best way to get the dataset is convert your data to Qlib bin format https://qlib.readthedocs.io/en/latest/component/data.html#qlib-format-dataset
In the near future, we make the storage layer replacable, which may support your requirements.

2. In the design of qlib,  real data processing and inferencing is supported.  But we didn't provide a example now.   Related examples may be released in https://github.com/microsoft/qlib/pull/290

**Comment by zhuangz-ma** [comment]
Thank you.
