### ISSUE TITLE
Can the transaction price used in the back test be unadjusted?

### ISSUE THREAD

**Issue by quinnnnnnnnn** [microsoft/qlib#316]
## ❓ Questions and Help

I have noticed that the historical transaction price is the adjusted price, which makes the equal weight strategy meaningless, because if the adjusted price is used, the weight of all stocks is not equal in history.

**Comment by you-n-g** [comment]
The `equal weight` indicates that  Qlib try to allocate same amount of money on each assets.
The price and the volume are adjusted together. Therefore  it will not affect the amount of money.

**Comment by quinnnnnnnnn** [comment]
@you-n-g  thans！ I think I just did not adjust the amount data

**Comment by quinnnnnnnnn** [comment]
@you-n-g thank for ur answer！
But If there are two stocks, one historically adjusted price is 200, while the historical real price is 100, the factor is equal to 2. The other one has a historically adjusted price of 200, and the real price in history is 200, with a factor equal to 1.
According to qlib's algorithm, the adjustment price is used in the back test, so the amount and value are equal because the adjustment price is the same, but in the real history, the price difference between the two is twice the same and will not be bought at the same amount. Won't this lead to the distortion of the rate of return?

**Comment by you-n-g** [comment]
@quinnnnnnnnn 
The price and the amount of the stock is adjusted together.
The amount of money will not be affected by how you adjust them or whether you adjust them.
