### ISSUE TITLE
Is there any method to append data to dataset?

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#320]
For example, if I would like to use under live trading, it would be tedious to dump_all, then build dataset again for each new input data. Is there anyway to directly append new data to existing dataset object, and generate features and labels?

**Comment by zhupr** [comment]
@2young-2simple-sometimes-naive Hi,
You can append data like this: `python dump_bin.py dump_update --csv_path <new data dir> --qlib_dir <qlib_data_dir>.....`

**Comment by 2young-2simple-sometimes-naive** [comment]
> @2young-2simple-sometimes-naive Hi,
> You can append data like this: `python dump_bin.py dump_update --csv_path <new data dir> --qlib_dir <qlib_data_dir>.....`

Sorry, this is not what I meant. In the example workflow, data set is initialized by:
`dataset = init_instance_by_config(task["dataset"])`
Is there any way to append data to this dataset?

**Comment by you-n-g** [comment]
I guess your requirements are building the input dataset for recent data for high performance online inference.

The design of the underlying data infrastructure have considered such requirements. 
Examples will be given in this PR  https://github.com/microsoft/qlib/pull/290 soon

**Comment by jeffzhengye** [comment]
Also need this feature.
