### ISSUE TITLE
Does double ensemble support DNN models?

### ISSUE THREAD

**Issue by PayneJoe** [microsoft/qlib#321]
How to configure for it if the answer is YES?

**Comment by Derek-Wds** [comment]
Unfortunately NO for now. We only support `Lightgbm` submodels for now. If you want to use DNN, you can refer to the code and add one by yourself.

Hope it helps~

**Comment by PayneJoe** [comment]
> Unfortunately NO. We only support `Lightgbm` submodels for now. If you want to use DNN, you can refer to the code and add one by yourself.
> 
> We may update the model in the future. Hope it helps~

Thanks~
