### ISSUE TITLE
normalize in yahoo collector

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#330]
## ❓ Questions and Help

For the yahoo collector.py, the documentation says it need to download, normalize, then dump. Is the normalize step necessary? Does this mean for any update to the existing data (e.g, I have data from 2020-01-01 to 2021-01-01, want to add data from 2021-01-02 to 2021-03-01), I need to re-normalize the entire csv, not just the appending csv?

**Comment by zhupr** [comment]
@2young-2simple-sometimes-naive Hi,
- The function of `normalize` is to fill-nan and adjust, etc; 
- If the data of "*2021-01-02 to 2021-03-01*" has been adjusted, it can be directly appended without re-normalize the entire csv
- If the data used is from [qlib cn_data](https://qlib.readthedocs.io/en/latest/start/initialization.html?highlight=get_data.py#id1), it is recommended to re-normalize the entire csv
