### ISSUE TITLE
是否可提供灵活的因子计算接口

### ISSUE THREAD

**Issue by Jialeen** [microsoft/qlib#335]
qlib提供的因子计算式子是固定的，在使用时候需要用其他的计算因子，比如说用智能算法选择因子等等，就需要修改源码，这对研究和使用来说太不方便以及耗时。因此我想是否可以开放一个接口，让使用者自己设计的因子也能嵌入到框架中。

**Comment by you-n-g** [comment]
@Jialeen  
User could create his own data handler and dataset.
You can follow the example https://github.com/microsoft/qlib/blob/main/qlib/contrib/data/handler.py#L46 and implement your own dataset in your module.
