### ISSUE TITLE
calculate feature without given protocal

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#338]
Hi. I would like to use existing external packages (e.g, [ta](https://github.com/bukosabino/ta)) to calculate features, so I no longer need to define formulas in the example [given here](https://github.com/microsoft/qlib/blob/e8d7a226516430dc13c5d6d92f80e50ed5f51b5d/docs/advanced/alpha.rst). Is there anyway I can feed features using calculated numbers, instead of formulas?

**Comment by you-n-g** [comment]
You can query the raw data and then feed it into other packages.

**Comment by 2young-2simple-sometimes-naive** [comment]
> You can query the raw data and then feed it into other packages.
Yes. The documentation already have example for extracting data from .bin files. The problem is how to feed the calculated numbers to be a feature in the dataset to be trained.

**Comment by you-n-g** [comment]
The dataset , datahandler, and dataloader layer didn't force user to create dataset from qlib's `.bin` files directly.
You can create your own dataloader for your data. 
You can reference to https://github.com/microsoft/qlib/blob/main/qlib/data/dataset/loader.py#L183
It requires some modification to make it suit your requirements.

**Comment by 2young-2simple-sometimes-naive** [comment]
> The dataset , datahandler, and dataloader layer didn't force user to create dataset from qlib's `.bin` files directly.
> You can create your own dataloader for your data.
> You can reference to https://github.com/microsoft/qlib/blob/main/qlib/data/dataset/loader.py#L183
> It requires some modification to make it suit your requirements.

Thank you. Is there any way to append these data to existing data loaded from `.bin` files?

**Comment by you-n-g** [comment]
Sorry,  
In our current workflow, users have to start from loading data from dataloader to get latest data..
Updating the data in the memroy will consider a lot of things,  such as preprocessing,  different version of data (raw data, data for inference , data for learning).  So we think that the most convient solution to get new data is starting from loading original data.
Do you have suggestions about current design?
Thanks.
