### ISSUE TITLE
How to fill unavailable data with last available data

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#349]
For example, suppose volume data for AAPL on 2020-03-03 is missing. It looks like the current handlers will generate volume related features as 0, which worsen the model. Would it be possible to define a handler, to fill missing data with the data from the previous day?

**Comment by you-n-g** [comment]
You can use this operator.
https://github.com/microsoft/qlib/blob/main/examples/highfreq/highfreq_ops.py#L54

PS: please remember to register it before using it.
