### ISSUE TITLE
Missing data and incremental download cn stock price data

### ISSUE THREAD

**Issue by PalanQu** [microsoft/qlib#352]
## ❓ Questions and Help

I use following command to download data
`python scripts/get_data.py qlib_data --target_dir ~/.qlib/qlib_data/cn_data --region cn`
I have two questions

1. There is no data after 2020-10-01, I use following command to check the data, If there something wrong with my code or the data after 2020-09-01 is missing?
`D.features(['SH600519'], ['$close'], start_time='2020-09-01', end_time='2021-01-31', freq='day')`
2. Is there a way to incremental download the cn stock price data?

**Comment by zhupr** [comment]
Hi, @PalanQu 
You can do as follows：
- collector data from yahoo, reference: https://github.com/microsoft/qlib/tree/main/scripts/data_collector/yahoo
- dump data using `dump_update`, reference: https://qlib.readthedocs.io/en/latest/component/data.html#converting-csv-format-into-qlib-format 
    ```python
    python scripts/dump_bin.py dump_update --csv_path <new data dir> --qlib_dir <you qlib data dir> --exclude_fields date,datetime,symbol
    ```
