### ISSUE TITLE
Backtest on randomly generated data

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#354]
## Motivation

There should be a backtest based on pure randomly generated data. The idea is that if the model can make profit over random data, it is overfitting.
See the discussion [here](https://www.reddit.com/r/algotrading/comments/m8mhy1/anyone_is_using_randomized_data_instead_of/?utm_source=share&utm_medium=ios_app&utm_name=iossmf)

**Comment by you-n-g** [comment]
Hi, 
You can randomly generate a dataset and train a model on it. 
I think it will be possible to make profit on training data while backtest after overfitting.
