### ISSUE TITLE
Is `change` necessary for us stock

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#355]
## ❓ Questions and Help
The file `exchange.py` specifies that `change` in the test data is used for calculating stock limit. As there is no `limit_threshold` on US stock, does that mean I can delete all change.bin for us data?

**Comment by you-n-g** [comment]
No,  you can't delete it.
`$change` is necessary. It indicates the price change from previous tradable date.
It will be very important if stock  suspension exists.

**Comment by 2young-2simple-sometimes-naive** [comment]
> No, you can't delete it.
> `$change` is necessary. It indicates the price change from previous tradable date.
> It will be very important if stock suspension exists.

Honestly I don't think it matters to the model as the change does not take into the training process. It may be important to some strategy.

**Comment by you-n-g** [comment]
@Angry
It is important when backtesting.
