### ISSUE TITLE
如何安装qlib

### ISSUE THREAD

**Issue by 15636550858** [microsoft/qlib#361]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

**Comment by zhupr** [comment]
@15636550858 Hi,
qlib installation: https://qlib.readthedocs.io/en/latest/start/installation.html#qlib-installation
