### ISSUE TITLE
如何使用qrun

### ISSUE THREAD

**Issue by onepointfuck** [microsoft/qlib#363]
之前一直用jupyter运行python文件，Qlib由内置qrun方法。不知道如何使用，在安装文件的cmd运行qrun方法，也没有效果

**Comment by you-n-g** [comment]
Did you encounter any problems when following the quick start on index page https://github.com/microsoft/qlib#quick-start ? 
Thanks

**Comment by onepointfuck** [comment]
> Did you encounter any problems when following the quick start on index page https://github.com/microsoft/qlib#quick-start ?
> Thanks

**Comment by onepointfuck** [comment]
The problem has been solved, thank you
