### ISSUE TITLE
Get original data from dataset instance

### ISSUE THREAD

**Issue by fzc621** [microsoft/qlib#364]
Hi,

I am working on creating my own RecordTemplates, which needs some original data from the dataset, say "vwap" or "volume". So I have to save "vwap.pkl" or "volume.pkl" within my own SignalRecorder.  Is it possible to save those objects, similar to the "label.pkl" saved by Qlib's SignalRecoder? I am able to make it in a "dirty" way:
``` python
vwap_df = D.features(D.instruments(market="all"), ["$vwap"], start_time="2019-07-01", end_time="2019-12-31")
vwap = vwap_df.swaplevel().sort_index() 
self.recorder.save_objects(**{"vwap.pkl": vwap})
```
Is there any better way to make it? Using the dataset class? I got stuck in retrieving the original data via dataset class.

Thanks

**Comment by you-n-g** [comment]
@fzc621  
This is really a great Quesetion. 
I think minor midifications are required if you want to record something about the database.

1. Create a base class `DatasetRecord` for storing info from database.

2. We change the workflow of the trainner. 
```
if  issubclass(recorder,  DatasetRecord):
    pass the dataset when initialization recorder 
```
Example and functions below maybe helpful
- https://github.com/microsoft/qlib/blob/main/qlib/model/trainer.py#L33
- https://github.com/microsoft/qlib/blob/main/qlib/utils/__init__.py#L185

3. Create your own subclass of DatabaseRecord and save your info in the recorder.


Your  PR is welcome!  :)

**Comment by fzc621** [comment]
Thanks for your reply! I will try to submit a PR!
