### ISSUE TITLE
Can qlib use the transformer model in pytorch

### ISSUE THREAD

**Issue by onepointfuck** [microsoft/qlib#366]
Can qlib use the transformer model in pytorch?

**Comment by Derek-Wds** [comment]
Hi, qlib does not support running pytorch's transformer directly, but you could make a customized model by inheriting qlib's model which includes the transformer module from pytorch. You can refer to this GRU [model](https://github.com/microsoft/qlib/blob/main/qlib/contrib/model/pytorch_gru.py) for details.

**Comment by onepointfuck** [comment]
> Hi, qlib does not support running pytorch's transformer directly, but you could make a customized model by inheriting qlib's model class and includes the transformer module from pytorch. You can refer to this GRU [model](https://github.com/microsoft/qlib/blob/main/qlib/contrib/model/pytorch_gru.py) for details.

Got it, thank you
