### ISSUE TITLE
Training time is too long

### ISSUE THREAD

**Issue by onepointfuck** [microsoft/qlib#367]
It took 8 hours to train an LSTM model, but there was no result. Is such a long training time normal?

**Comment by Derek-Wds** [comment]
Hi, could you please tell us how you run the model? Usually, you can train the LSTM model to convergence with one GPU in 1 hour.

**Comment by onepointfuck** [comment]
> Hi, could you please tell us how you run the model? Usually, you can train the LSTM model to convergence with one GPU in 1 hour.

Run the model directly on the jupyter notebook without using qrun. Use Chinese market, Shanghai and Shenzhen 300, data within one year

**Comment by Derek-Wds** [comment]
It is most likely that you are running the models on CPU. I would suggest you check your jupyter with `torch.cuda.is_available()`. 

If the result is true, then pytorch should detect your GPU and use gpu to train the model. If not, maybe you could refer to [this](https://stackoverflow.com/questions/51002045/how-to-make-jupyter-notebook-to-run-on-gpu) and enable your GPU on jupyter.

**Comment by onepointfuck** [comment]
> It is most likely that you are running the models on CPU. I would suggest you check your jupyter with `torch.cuda.is_available()`.
> 
> If the result is true, then pytorch should detect your GPU and use gpu to train the model. If not, maybe you could refer to [this](https://stackoverflow.com/questions/51002045/how-to-make-jupyter-notebook-to-run-on-gpu) and enable your GPU on jupyter.

知道了，谢谢。
