### ISSUE TITLE
Double Ensemble MlflowException

### ISSUE THREAD

**Issue by simin75simin** [microsoft/qlib#369]
hi, so i ran a cn data on google colab. alstm worked fine but double ensemble keep giving issues, i manage to solve some by cloning the repo and install via setup.py and uninstalling / reinstalling numpy. but this one i do not know how to solve:
MlflowException: Got invalid value Series([], dtype: float64) for metric 'IC' (timestamp=1616595157552). Please specify value as a valid double (64-bit floating point)

if i have only sh000300 in my instruments, it's gonna produce the following value error:
ValueError: Bin edges must be unique: array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]).
You can drop duplicate edges by setting the 'duplicates' kwarg

i followed instructions on data collector's markdown page to download cn data up until 03/01/2021. my yaml file looks like this:
qlib_init:
    provider_uri: "/content/gdrive/MyDrive/qlib/qlib_data/qlib_cn_1d"
    region: cn
market: &market 
benchmark: &benchmark SH000300
data_handler_config: &data_handler_config
    start_time: 2008-01-01
    end_time: 2021-03-01
    fit_start_time: 2008-01-01
    fit_end_time: 2018-12-31
    instruments: ['SH000300', 'SH000903']
port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy.strategy
        kwargs:
            topk: 50
            n_drop: 5
    backtest:
        verbose: True
        limit_threshold: 0.095
        account: 50000
        benchmark: *benchmark
        deal_price: close
        open_cost: 0.0005
        close_cost: 0.0015
        min_cost: 5
task:
    model:
        class: DEnsembleModel
        module_path: qlib.contrib.model.double_ensemble
        kwargs:
            base_model: "gbm"
            loss: mse
            num_models: 6
            enable_sr: True
            enable_fs: True
            alpha1: 1
            alpha2: 1
            bins_sr: 10
            bins_fs: 5
            decay: 0.5
            sample_ratios:
                - 0.8
                - 0.7
                - 0.6
                - 0.5
                - 0.4
            sub_weights:
                - 1
                - 0.2
                - 0.2
                - 0.2
                - 0.2
                - 0.2
            epochs: 28
            colsample_bytree: 0.8879
            learning_rate: 0.2
            subsample: 0.8789
            lambda_l1: 205.6999
            lambda_l2: 580.9768
            max_depth: 8
            num_leaves: 210
            num_threads: 20
            verbosity: -1
    dataset:
        class: DatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: Alpha158
                module_path: qlib.contrib.data.handler
                kwargs: *data_handler_config
            segments:
                train: [2008-01-01, 2018-12-31]
                valid: [2019-01-01, 2020-07-31]
                test: [2020-08-01, 2020-03-01]
    record:
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs: {}
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs:
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs:
            config: *port_analysis_config

thanks for answering in advance.

**Comment by you-n-g** [comment]
@simin75simin 
The `test: [2020-08-01, 2020-03-01]` looks a little strange. 
Why is your test segment empty?
