### ISSUE TITLE
Forecast target

### ISSUE THREAD

**Issue by onepointfuck** [microsoft/qlib#376]
1. Qlib's forecast goal is to rank stocks and make the prediction score about stocks. I can't understand the meaning of this. Can you explain it?
2. Whether the forecast target can be changed to the forecast of stock price
Thank you

**Comment by you-n-g** [comment]
@onepointfuck  
1. The demo is try to improve the performance of `stock selection` and gain excess return over the benchmark. So the accurracy of ranking is very important.
2. Yes.  You can try it.

**Comment by PalanQu** [comment]
@you-n-g 
If the latest price data is of 2021-03-01, and have trained a model using history data, how can i predict the  stock price of 2021-03-02 or after that? , There are no features so we can not predict, how to do that?

**Comment by you-n-g** [comment]
If you train a model  input feature on time `T` and output the price `T+1`  
Then your model can predict  2021-03-02  on 2021-03-01.

**Comment by PalanQu** [comment]
@you-n-g 
Thanks for your response, could you please tell me are there any methods or examples about these prediction?

**Comment by you-n-g** [comment]
@PalanQu 
Predicting the price directly did not produce any good results in our previous experiments. 
So  we have no slimilar example yet.
