### ISSUE TITLE
ERROR: Cannot uninstall 'ruamel-yaml'. 

### ISSUE THREAD

**Issue by ctwillson** [microsoft/qlib#377]
- ERR Detail:
ERROR: Cannot uninstall 'ruamel-yaml'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
- Platform:Windows 10&Mac Os
- Python version: 3.8.5

**Comment by onepointfuck** [comment]
Try it when installing --ignore-installed ruamel.yaml

**Comment by ctwillson** [comment]
> Try it when installing --ignore-installed ruamel.yaml

It works！
