### ISSUE TITLE
Installing from Source File Failed

### ISSUE THREAD

**Issue by D-X-Y** [microsoft/qlib#382]
Dear Authors,

Thanks for the awesome project. I'm trying to install qlib from source codes by "python setup.py install".
However, it failed with the following errors:
![image](https://user-images.githubusercontent.com/9547057/113087856-10e0c080-9217-11eb-9482-fe70880cb587.png)

It seems that qlib relies on qdldl and failed to install this package.. May I seek some help?

My machine is Linux with Anaconda-Python3.7

Best,

**Comment by Derek-Wds** [comment]
It seems that your `CMake` or `gcc` version is out of date. You could try to update these two packages and see if it works.

**Comment by D-X-Y** [comment]
Thanks @Derek-Wds , I'm using "gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)". Let me try a new gcc.
