### ISSUE TITLE
How to use RollingDataHandler to train model?

### ISSUE THREAD

**Issue by Wendroff** [microsoft/qlib#383]
## ❓ Questions and Help

I see you just add a new example of  rolling_process_data. However, No model training process was included in that example. Can you give a full example using this data handler? I guess model need to be trained in each iteration but I'm not sure. Thank you!

**Comment by Wendroff** [comment]
Is it in the coming feature? https://github.com/microsoft/qlib/pull/290

**Comment by you-n-g** [comment]
@Wendroff  
Yes, you are right.    Examples of rolling training model will be released in https://github.com/microsoft/qlib/pull/290 .
It works now and we are polishing it. You can try it now. Your feedbacks are highly welcomed.

RollingDataHandler is an example to demonstrate how to partly share data preprocessing when rolling data  for performance consideration.
