### ISSUE TITLE
请问回测后，回测的交易明细数据存放在哪里了？

### ISSUE THREAD

**Issue by atlasju** [microsoft/qlib#385]
比如使用代码范例
qrun benchmarks/LightGBM/workflow_config_lightgbm_Alpha158.yaml

运行完之后怎么看交易明细？

谢谢！

**Comment by bxdd** [comment]
Hi, I am sorry for my late reply. You can set `return_order is True` when trading, see https://github.com/microsoft/qlib/blob/3033fdf4b794c5936bceac6fb770abb1243fb245/examples/workflow_by_code.py#L38

After trading, run `recorder.load_objects('portfolio_analysis\order_normal.pkl')` to see trading details. Related code is here: https://github.com/microsoft/qlib/blob/d08146c30fcc3eef6bc0adca6d646c4a2cb75a09/qlib/workflow/record_temp.py#L329
