### ISSUE TITLE
Can I use other markets instead  of CN and US

### ISSUE THREAD

**Issue by fsaop** [microsoft/qlib#387]
I try to use anather markets such as "set50" or "crypto" market, but the error return the instrument not exist for marke. So what should I do?

**Comment by you-n-g** [comment]
@fsaop
To support data from different market, you should implement [data collector ](https://github.com/microsoft/qlib/blob/main/scripts/data_collector/yahoo/collector.py)for them and [convert them to qlib format](https://qlib.readthedocs.io/en/latest/component/data.html#data-preparation)
Your PR is highly welcome!

Thanks.

**Comment by fsaop** [comment]
Thank for you response. But I already scrapping my own dataset from yahoo finance as a dataframe csv format and converted into qlib.After that, I use LSTM .yaml files for get my own prediction score. Here is my setting.
![1617462891879](https://user-images.githubusercontent.com/81777293/113482713-1b76b080-94ca-11eb-95ce-53b3071e38a0.jpg)
Unfortunately, the program response the error like this.
![1617462954316](https://user-images.githubusercontent.com/81777293/113482734-2c272680-94ca-11eb-9dea-2f9922f39154.jpg)
I run both in my machine and Google Colab and it appear same error.What should I do with error: instruments not exists for market

**Comment by fsaop** [comment]
![Uploading 1617463088147.png…]()
![Uploading 1617463080830.png…]()

**Comment by you-n-g** [comment]
@fsaop
It looks like that you didn't provide the right instruments universe symbol.
You can use `D.instruments('all')` to load all the [instruments](https://github.com/microsoft/qlib/blob/main/scripts/dump_bin.py#L30) or create your instruments universe.
