### ISSUE TITLE
Support for Inidian market

### ISSUE THREAD

**Issue by jaydotkay** [microsoft/qlib#388]
Hi Team, Currently QLib supports only two regions datasets. Any tentative dates when India region shall be supported and If I have to define India region on my own how to customize the data collector any high level pointers shall be helpful
thanks

**Comment by you-n-g** [comment]
Hi 
@jaydotkay  
Qlib doesn't limit the region of the datasets.
You can send PR to create a data collector to crawl data from india market.

To support data from different market, you should implement [data collector ](https://github.com/microsoft/qlib/blob/main/scripts/data_collector/yahoo/collector.py)for them and [convert them to qlib format](https://qlib.readthedocs.io/en/latest/component/data.html#data-preparation)
Your PR is highly welcome!

Thanks
