### ISSUE TITLE
Use dump update to add features

### ISSUE THREAD

**Issue by JessieJie1998** [microsoft/qlib#389]
## ❓ Questions and Help

I want to separate the basic data (e.g.close, open, ...) and the new factors data (e.g. fundamental factors). Can I dump_all basic data first and add other new factors by  dump update?

**Comment by zhupr** [comment]
Yes

**Comment by JessieJie1998** [comment]
I have two csv datasets. One contains the basic data  (e.g.close, open, ...). The other contains new factors (e.g.roe, ...). The. two dataset have the same time period and instruments. When I dump update the new factor csv data after I successfully dump all basic data. It raise value error:

'SH600000': 'concurrent.futures.process._RemoteTraceback: \n"""\nTraceback (most recent call last):\n  File "/opt/anaconda3/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker\n    r = call_item.fn(*call_item.args, **call_item.kwargs)\n  File "/qlib/scripts/dump_bin.py", line 261, in _dump_bin\n    self._data_to_bin(df, calendar_list, features_dir)\n  File "/qlib/scripts/dump_bin.py", line 230, in _data_to_bin\n    date_index = self.get_datetime_index(_df, calendar_list)\n  File "/qlib/scripts/dump_bin.py", line 219, in get_datetime_index\n    return calendar_list.index(df.index.min())\nValueError: NaT is not in list\n"""\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/qlib/scripts/dump_bin.py", line 479, in _dump_features\n    _future.result()\n  File "/opt/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 425, in result\n    return self.__get_result()\n  File "/opt/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result\n    raise self._exception\nValueError: NaT is not in list\n',

As is shown in the link below, when the stock in the previous instrument list, it seems that you only consider the update in the time but ignore the difference or update in the include-fields? I am not sure wether I understand this code correctly.
[https://github.com/microsoft/qlib/blob/70c84cbc77e52bea67e4528d6f79e2e462a4ffa6/scripts/dump_bin.py#L456](url)

**Comment by zhupr** [comment]
- `dump_update` is to update the new fields to ***qlib/features*** and ***qlib/instruments/all.txt*** based on the existing ***qlib/calendars/day.txt****(from dump_all)
 - the `datetime field` of the *new factor csv* must be in ***qlib/calendar/ day.txt***
 - *`NaT is not in list`* because the *datetime field* of *new factor csv* may contain `null`
