### ISSUE TITLE
Support for Financial Report period data.

### ISSUE THREAD

**Issue by Yolanflower** [microsoft/qlib#390]
## ❓ Questions and Help

Dear developers, 

I want to define some Alpha using data from financial report period data. Does qlib support this type of frequency? Or how can I dump in my own report period data into qlib_data.

**Comment by zhupr** [comment]
- corresponding "financial report period data" to the trading day (if data exists for non-trading days).
- use `dump_bin.py dump_fix --csv_path <financial data csv dir> --qlib_dir <qlib data dir> --include_fields <your dump fields> `

**Comment by you-n-g** [comment]
@Yolanflower 
Besides method proposed by @zhupr ,  you can keep an eye on https://github.com/microsoft/qlib/pull/343
Thanks for your attention
