### ISSUE TITLE
Hello, where can I set the number of trading stocks as a multiple of 100?

### ISSUE THREAD

**Issue by liu100286** [microsoft/qlib#395]
## ❓ Questions and Help
Hello, where can I set the number of trading stocks as a multiple of 100?

**Comment by you-n-g** [comment]
Hi,   you can implement such features  in strategy. 
The existing strategy has considered such feature and here is [an example](https://github.com/microsoft/qlib/blob/main/qlib/contrib/strategy/strategy.py#L403).

Thanks :)

**Comment by liu100286** [comment]
thanks
