### ISSUE TITLE
abnormal yield when backtesting with vwap

### ISSUE THREAD

**Issue by ke-fan** [microsoft/qlib#396]
## ❓ Questions and Help

I used wind's market data, (open close low high vwap) are adjusted in a post-weighted way, factor = adjusted_price / original_price, when I am using the close price for backtesting, everything looks normal,  daily return are less than 10%, but when I am using vwap for backtesting, the results will become strange, some daily returns are greater than 10%

![backtesting_with_vwap](https://user-images.githubusercontent.com/60644499/115528371-901c5e00-a2c4-11eb-973e-0312ba0b1fa3.png)

I checked the backtest detail: positions = recorder.load_object("portfolio_analysis/positions_normal.pkl")
`{Timestamp('2020-07-02 00:00:00'): {'cash': 100000000,  
  'today_account_value': 100000000},  
 Timestamp('2020-07-03 00:00:00'): {'cash': 96198100.0,  
  'today_account_value': 144327301.40487388,  
  'SZ000661': {'count': 1,  
   'amount': 4684.182645143626,  
   'price': 3047.1298828125,  
   'weight': 0.09889544649995681},  
  'SH600340': {'count': 1,  
   'amount': 76828.21035849101,  
   'price': 440.6700134277344,  
   'weight': 0.23457716011283875}},  
......`

And found some abnormal data:
It seems like the today_account_value is calculate by close * amount: 
96198100.0 + 4684.182645143626*3047.1298828125 + 76828.21035849101*440.6700134277344 - 144327301.40487388
 
And buy stock with vwap/factor:
96198100.0 + 4684.182645143626*3014.948486/7.432931 + 76828.21035849101*439.967285/17.790472 - 100000000

market data of ['SZ000661', 'SH600340']:
![market_data](https://user-images.githubusercontent.com/60644499/115530263-3026b700-a2c6-11eb-8e72-2e825d1a01db.png)

I want to know what I used wrong...
Thanks for your reply~

**Comment by you-n-g** [comment]
@ke-fan You can set a break point here https://github.com/microsoft/qlib/blob/main/qlib/contrib/backtest/report.py#L60
Check what happened on the date when the account a huge return.
