### ISSUE TITLE
How to convert data from other sources that can be used by qlib?

### ISSUE THREAD

**Issue by HansCui** [microsoft/qlib#402]
## ❓ Questions and Help

Hello there,

We are trying to get the latest stock data from Yahoo Finance, but the problem is the data coming out from there is in a different format that Qlib can accept. So we are wondering if we can access the logic to convert our own data into a form, which Qlib or the DataHandler module can handle? 

Thanks for any help in advance!

**Comment by you-n-g** [comment]
@HansCui 
Could this tutorial solve your problem?
https://qlib.readthedocs.io/en/latest/component/data.html#qlib-format-dataset
