### ISSUE TITLE
help

### ISSUE THREAD

**Issue by liu100286** [microsoft/qlib#403]
你好，我没有找到不训练，直接加载模型进行回测的示例。你能告诉我在哪里能找到么？谢谢。

**Comment by you-n-g** [comment]
@liu100286 
Did this tutorial solve your problem?
https://qlib.readthedocs.io/en/latest/component/backtest.html#example

**Comment by liu100286** [comment]
> @ liu100286
> 本教程是否解决了您的问题？
> [https://qlib.readthedocs.io/zh-CN/latest/component/backtest.html#example](https://qlib.readthedocs.io/en/latest/component/backtest.html#example)

No. I've looked at it carefully

I still don't know how to import the training completed model

**Comment by you-n-g** [comment]
@liu100286 

If your trained model are manged by Qlib. 
You can use  [recorder](https://qlib.readthedocs.io/en/latest/component/recorder.html#qlib-recorder) to load the model prediction as  `pred_score` in [this page ](https://qlib.readthedocs.io/en/latest/component/backtest.html#example) to backtest without retraining model.

Thanks

**Comment by liu100286** [comment]
thanks!!!
