### ISSUE TITLE
How to convert stock original data to 1min data?

### ISSUE THREAD

**Issue by zhwei79** [microsoft/qlib#410]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

**Comment by zhwei79** [comment]
The 'close.bin'  differ from original data,  how to convert?

![微信图片_20210507173220](https://user-images.githubusercontent.com/83813521/117430369-a67c1800-af5a-11eb-938a-77c74db0c33d.png)

**Comment by you-n-g** [comment]
Hi, @zhwei79 
Sorry, I'm a little confused about the question. What do you mean by `orginal data`,  `1min data` ?

**Comment by zhwei79** [comment]
Original data(stock SH600016) such as :
![微信图片_20210507181915](https://user-images.githubusercontent.com/83813521/117435844-e219e080-af60-11eb-8fcd-db8a7a1497a7.png)

**Comment by zhwei79** [comment]
We download data/1min data (cn_data_1min\features\sh600016\close.bin) such as :
![微信图片_20210507182335_close](https://user-images.githubusercontent.com/83813521/117436246-5e142880-af61-11eb-92f8-92182bd779a1.png)

**Comment by you-n-g** [comment]
The price data in qlib is adjusted.
 
If you want to convert your original data to Qlib data. You can follow [this tutorial ](https://qlib.readthedocs.io/en/latest/component/data.html#converting-csv-format-into-qlib-format)

**Comment by zhwei79** [comment]
Not convert file format, but  how to normalize or standandize the column 'close' ?

**Comment by zhwei79** [comment]
And how to convert stock original price to the column "close"

**Comment by you-n-g** [comment]
@zhwei79  
The tutorial includes both format converting and  stock price adjustment( i.e. `standandize` in your previous comments)
You must specify the `factor` column when converting data.

**Comment by you-n-g** [comment]
The factor column should come from the users' data source 
You can check the reference below
- https://baike.baidu.com/item/%E5%A4%8D%E6%9D%83%E5%9B%A0%E5%AD%90/7564322?fr=aladdin
- https://support.stockcharts.com/doku.php?id=policies:adjusted_data#:~:text=Historical%20prices%20are%20adjusted%20by,subsequently%20multiplied%20by%20this%20factor.

**Comment by you-n-g** [comment]
@zhwei79   Because adjusted price could potentially produce look-ahead bias.
To prevent changing the historical price.  Qlib normalized the price on the first date to 1.

**Comment by zhwei79** [comment]
@you-n-g Thanks a lot
