### ISSUE TITLE
優化模型

### ISSUE THREAD

**Issue by ChengYen-Tang** [microsoft/qlib#414]
請問能否建議如何優化模型
我使用 LGBModel + Alpha360
交易頻率:1hr
市場:
BTCUSDT-FUTURESUSDT
BTCUSDT-SPOT
ETHBTC-SPOT
ETHUSDT-FUTURESUSDT
ETHUSDT-SPOT
XRPBTC-SPOT
XRPETH-SPOT
XRPUSDT-FUTURESUSDT
XRPUSDT-SPOT
LTCBTC-SPOT
LTCETH-SPOT
LTCUSDT-FUTURESUSDT
LTCUSDT-SPOT
BNBBTC-SPOT
BNBETH-SPOT
BNBUSDT-FUTURESUSDT
BNBUSDT-SPOT
ADABTC-SPOT
ADAETH-SPOT
ADAUSDT-FUTURESUSDT
ADAUSDT-SPOT

![image](https://user-images.githubusercontent.com/32535494/117692688-dabc3680-b1ef-11eb-95fb-30219a5e654d.png)
![image](https://user-images.githubusercontent.com/32535494/117692805-f58eab00-b1ef-11eb-84eb-59a8291f90dc.png)
![image](https://user-images.githubusercontent.com/32535494/117692883-093a1180-b1f0-11eb-8dc8-b6736e90a736.png)
![image](https://user-images.githubusercontent.com/32535494/117692933-16ef9700-b1f0-11eb-9797-43c37980f177.png)
![image](https://user-images.githubusercontent.com/32535494/117692983-2373ef80-b1f0-11eb-902b-52c5b1b8c826.png)
![image](https://user-images.githubusercontent.com/32535494/117693070-35ee2900-b1f0-11eb-8ab9-1fe14991bd4b.png)
![image](https://user-images.githubusercontent.com/32535494/117693141-48686280-b1f0-11eb-8fe1-8762bff3def7.png)

**Comment by you-n-g** [comment]
@ChengYen-Tang   Model Optimization is quite an open problem.
You can find a huge amount of papers about fintech in google scholar
Good luck :D 

Thanks

**Comment by ChengYen-Tang** [comment]
我想請問一個問題，從這些圖表我不確定模型是否有價值
Score IC  +-波動很大，如果我的理解沒錯，負的IC應該代表Score與幣價走勢呈現反方向

**Comment by you-n-g** [comment]
It is a very common case to get a fluctuating IC over time. 
Normally,  researchers try to improve the average value of IC for a long time instead of every single day.
