### ISSUE TITLE
miss  numpy package

### ISSUE THREAD

**Issue by zhang787jun** [microsoft/qlib#417]
## 🐛 Bug Description

qlib/qlib/contrib/backtest/position.py /
```python
161        cash = pd.Series(dtype=np.float)
```
NameError: name 'np' is not defined

## To Reproduce

1. import numpy  at head 
```python
import numpy as np 
```

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version:
 - Python version:
 - OS (`Windows`, `Linux`, `MacOS`):
 - Commit number (optional, please provide it if you are using the dev version):

**Comment by you-n-g** [comment]
Hi, @zhang787jun  
Thanks so much for submitting this issue.
Would you mind sending a PR to fix this issue and become [one of the contributors of Qlib](https://github.com/microsoft/qlib/graphs/contributors)!
