### ISSUE TITLE
can't download high freq data

### ISSUE THREAD

**Issue by ZFgan** [microsoft/qlib#420]
## ❓ Questions and Help

I can not download hf data.

Traceback (most recent call last):
  File "scripts/get_data.py", line 9, in <module>
    fire.Fire(GetData)
  File "D:\Anaconda3_2002\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\Anaconda3_2002\lib\site-packages\fire\core.py", line 468, in _Fire
    target=component.__name__)
  File "D:\Anaconda3_2002\lib\site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "D:\Anaconda3_2002\lib\site-packages\qlib\tests\data.py", line 81, in qlib_data
    self._download_data(file_name.lower(), target_dir)
  File "D:\Anaconda3_2002\lib\site-packages\qlib\tests\data.py", line 32, in _download_data
    raise requests.exceptions.HTTPError()

**Comment by zhupr** [comment]
Use the following command:
`python scripts/get_data.py qlib_data --target_dir ~/.qlib/qlib_data/cn_data_1min --region cn --interval 1min`

**Comment by ZFgan** [comment]
i use this command，the problem is same

**Comment by ZFgan** [comment]
i use this command，the problem is same

**Comment by zhupr** [comment]
Can you open this URL: http://fintech.msra.cn
If it doesn't open, try changing networks

**Comment by ZFgan** [comment]
yes,can open

**Comment by ZFgan** [comment]
yes,can open,Microsoft AI for Finance Group

**Comment by ZFgan** [comment]
i can download daily data,but can not download hf data

**Comment by zhupr** [comment]
1d data： `191MB`
1min data: `537 MB`

Is the download interrupted due to bad internet connection?

You try downloading it manually: http://fintech.msra.cn/stock_data/downloads/v1/qlib_data_cn_1min_latest.zip
Then unzip the file

**Comment by ZFgan** [comment]
thanks

**Comment by ZFgan** [comment]
thanks

**Comment by Smalltarget108** [comment]
> 1d data： `191MB` 1min data: `537 MB`
> 
> Is the download interrupted due to bad internet connection?
> 
> You try downloading it manually: http://fintech.msra.cn/stock_data/downloads/v1/qlib_data_cn_1min_latest.zip Then unzip the file

Hello， thank you for the solution.
I can reach the site. however, it shows that my download speed is really slower than 20k/s, sometimes even 0b/s
Is there any other choice for downloading?
Many thanks.
