### ISSUE TITLE
How to solve the problem of stock suspension and unable to trade

### ISSUE THREAD

**Issue by ZFgan** [microsoft/qlib#424]
## ❓ Questions and Help
How to solve the problem of stock suspension and unable to trade?

I think it is important

**Comment by you-n-g** [comment]
Hi,  @ZFgan,
What do you mean by `problem`? 
Are you asking how strategies handle this situation or how the backtest workflow simulates it?

**Comment by ZFgan** [comment]
I would like to inquire about how to deal with the suspension of stock trading during the backtest.

**Comment by you-n-g** [comment]
@ZFgan
Currently, Qlib uses this function to handle suspension of stock trading during backtest
https://github.com/microsoft/qlib/blob/19eda8f4f0d0e4931efcc9566256edc2076a5a25/qlib/contrib/backtest/exchange.py#L166
