### ISSUE TITLE
some question about Alpha158

### ISSUE THREAD

**Issue by ZFgan** [microsoft/qlib#425]
## ❓ Questions and Help

I have some questions about Apha158,Can you explain these two sets of parameters?thanks

infer_processors : list
            - list of <description info> of processors to generate data for inference
learn_processors : list
            similar to infer_processors, but for generating data for learning models

_DEFAULT_LEARN_PROCESSORS = [
    {"class": "DropnaLabel"},
    {"class": "CSZScoreNorm", "kwargs": {"fields_group": "label"}},
]
_DEFAULT_INFER_PROCESSORS = [
    {"class": "ProcessInf", "kwargs": {}},
    {"class": "ZScoreNorm", "kwargs": {}},
    {"class": "Fillna", "kwargs": {}},
]

LEARN_PROCESSORS uses CSZScoreNorm. 
INFER_PROCESSORS uses ZScoreNorm
Why?

**Comment by you-n-g** [comment]
Hi, please read the documents about the learn_processor and infer_processor.
The label is only visible during training. 
So some processors are only required for training data.

Thanks

**Comment by ZFgan** [comment]
i read the document，infer_processor is using for data？learn_processors  is using for model？

**Comment by you-n-g** [comment]
When `process_type` is  `"independent"`
- `infer_processor` is for processing testing data
- `learn_processor` is for processing training data

When `process_type` is  `"append"`
- `infer_processor + learn_processor` is for processing testing data
- `infer_processor ` is for processing training data
