### ISSUE TITLE
how to close expression cache

### ISSUE THREAD

**Issue by ZFgan** [microsoft/qlib#426]
sometimes,i don't need expression cache

**Comment by zhupr** [comment]
```
import qlib
qlib.init(xxx, expression_cache=None)
# or 
qlib.init(xxx, redis_port=-1)
```

**Comment by ZFgan** [comment]
thans

**Comment by ZFgan** [comment]
when i load data and close expression_cachedata reading speed is slower than hdf5.

**Comment by you-n-g** [comment]
@ZFgan 
Without data cache, Qlib accelerates data retrieving by reusing duplicated computation and multi-processing.
However, your query leaves no chance to leverage the optimizations.

But your feedbacks are very valuable.  These two queries should take a similar amount of time.
We'll investigate this problem later (It would still be very helpful if you could share your profiling results).

Thanks for your feedbacks.
