### ISSUE TITLE
add free data source

### ISSUE THREAD

**Issue by ZFgan** [microsoft/qlib#427]
i think qlib can add  free data scoure jqdatasdk(https://www.joinquant.com/help/api/help#name:JQData),
a million pieces of free data a day

**Comment by you-n-g** [comment]
The data requires users to register accounts to log in.   We don't have the right or license to maintain such data on our servers.
But I think it is OK to add some scripts like [them](https://github.com/microsoft/qlib/tree/main/scripts/data_collector) to help users to download the data by themselves.

Would you mind sending a PR to add this feature and become [one of the contributors of Qlib](https://github.com/microsoft/qlib/graphs/contributors)!
:D

**Comment by ZFgan** [comment]
ok

**Comment by jingmouren** [comment]
自己准备CSV为数据源时，停牌日的数据应该怎么处理？略过还是用啥值填充？

**Comment by zhupr** [comment]
If trading is suspended on each `trading day (T)`, the volume and price data (open, close, high, low, volume, factor, etc.) for that day `(T)` are set to `np.nan`

> Each data source has the same trading `calendar` (excluding non-trading days), for example CN stock (http://www.szse.cn/aboutus/calendar/index.html);
Each stock will be aligned to this `calendar`, with suspended stocks populated with `np.nan`
