### ISSUE TITLE
Placing trade for the same day

### ISSUE THREAD

**Issue by shashank-yadav** [microsoft/qlib#428]
## ❓ Questions and Help
Hi, the example given in the repo tries to predict P<sub>t+2</sub>/P<sub>t+1</sub> - 1, since the executor places the trade for the next day. Is there a way to place the trade on the closing price of the same day (So for that P<sub>t+1</sub>/P<sub>t</sub> - 1 will be the target)? In other words, is it possible to make `pred_date` and `trade_date` same in the execution strategy?

**Comment by ZFgan** [comment]
In most cases, it is impossible because the transaction rate is not high and the capital capacity is limited.you can also use  Pt+1/Pt - 1  to predict,and and trade with the help of algorithm transaction in the next day.

**Comment by shashank-yadav** [comment]
My apologies for not being clear. Consider this example: suppose my strategy is to make predictions for P<sub>t+1</sub>/P<sub>t</sub> - 1 near the end of trading day and enter the positions with the highest predicted values before the day ends. I know how to train a model to make these predictions. But is there a way to backtest such a strategy? Currently, I can only place the trade for the next day.

**Comment by ZFgan** [comment]
if you use day frequency data to backtest,this requirement cannot be met by backtesting.if you use high frequency data,you can define yourself transaction rules.

**Comment by shashank-yadav** [comment]
Cool, I'll implement something myself for this part then. Thanks for the prompt reply!
