### ISSUE TITLE
About Label0

### ISSUE THREAD

**Issue by carry-xz** [microsoft/qlib#429]
## ❓ Questions and Help
hi, nice work!
I want to use the feature and label to train my model, and found LABEL0 = Ref($close, -2)/Ref($close, -1) - 1, why it's not  Ref($close, -1)/Ref($close, 0) - 1?  why use today's feature to predict yesterday's gain?

**Comment by ZFgan** [comment]
in qlib document，they explain it

**Comment by you-n-g** [comment]
@carry-xz 
Please refer to the documents
https://qlib.readthedocs.io/en/latest/component/data.html#example
