### ISSUE TITLE
WeChat or QQ group

### ISSUE THREAD

**Issue by pan-cai** [microsoft/qlib#43]
## ❓ Questions and Help

Do you have a WeChat or QQ group ?

**Comment by you-n-g** [comment]
No. We don't have one now.
If you want to discuss with us, you can use gitter.

**Comment by pan-cai** [comment]
Get, thank you!

**Comment by ChengYen-Tang** [comment]
@pan-cai @monkeycc,
Maybe we can set up a discussion group, I have WeChat but no QQ.
