### ISSUE TITLE
How to start debugging of the code step by step

### ISSUE THREAD

**Issue by Joshuajxy** [microsoft/qlib#430]
## ❓ Questions and Help

Hi,

I'm trying to run debugging with visual studio code to run the code step by step, I started with "workflow_by_code.py", I can process the code step by step in debugging mode, but when I tried to step in some functions like 
    model = init_instance_by_config(task["model"])
    dataset = init_instance_by_config(task["dataset"])

It did not go to the function init_instance_by_config itself, just step over. How can I run debugging mode into those APIs?

**Comment by you-n-g** [comment]
@Joshuajxy 
I don't have a similar problem when debugging...

I know a solution that will certainly work.
You can use PDB.   
Please insert `__import__('ipdb').set_trace()` into the place you want to set break point.

**Comment by zhupr** [comment]
@Joshuajxy 
Click on the `Step Into (F11)` button

**Comment by Joshuajxy** [comment]
When I try to start the debug session with "**workflow_by_code.py**", it looks it called the function like **init_instance_by_config** from the installed package but not the python source file, I tried to add some logs in the function, but it did not print out.
Can you give me some help on this?

Sorry for this naive question.

**Comment by zhupr** [comment]
You can refer to the following operations:
```
# 1. clone code
git clone https://github.com/microsoft/qlib.git

2. Installing qlib using the develop
pip install numpy cython && cd qlib && python setup.py develop

3. Open the qlib directory using vscode

```
Reference:
![debug](https://user-images.githubusercontent.com/18660661/119136001-b246fe80-ba71-11eb-8c6e-1b1700d9d7b1.gif)

**Comment by Joshuajxy** [comment]
Thanks for your detailed guide @zhupr.

The suggestion can  solve the problem on my side, but it need to be on top of a clean environment. 

I'll close this question.
