### ISSUE TITLE
Enter a position on open price and exit on close price

### ISSUE THREAD

**Issue by shashank-yadav** [microsoft/qlib#432]
Is it possible to to enter a position on the open price of t+1 and exit on the close price of the same day in the backtesting engine. There is an argument called ‘deal_price’ but that is used nowhere

**Comment by you-n-g** [comment]
Hi,  @shashank-yadav 
It will a little awkward to implement your feature in the current system.  

Please pay attention to https://github.com/microsoft/qlib/pull/408 for refracting the trading framework.  
You can implement your feature much easier in this new framework 

If you want this feature in the current system. You can implement your own executor https://github.com/microsoft/qlib/blob/main/qlib/contrib/online/executor.py .

**Comment by arisliang** [comment]
Curious on this feature as well. The PR mentioned is replaced by #438.
