### ISSUE TITLE
Can not cal alpha158

### ISSUE THREAD

**Issue by ZFgan** [microsoft/qlib#437]
## ❓ Questions and Help
I need help,like follow codes:

from qlib.contrib.data.handler import Alpha158
from qlib.data.filter import NameDFilter,ExpressionDFilter

nameDFilter = NameDFilter(name_rule_re='SH000300')  
instruments = D.instruments(market='csi300',filter_pipe = [nameDFilter])
instruments
data_handler_config = {
    'start_tme':'2020-01-01',
    'end_time':'2020-08-30',
    'fit_start_time':'2020-01-01',
    'fit_end_time':'2020-06-30',
    'instruments':instruments
}
h = Alpha158(**data_handler_config)

**error:**
ValueError: Number of processes must be at least 1

**Comment by you-n-g** [comment]
@ZFgan  Could you give more details about the error (e.g. full exception backtrace)? 
Thanks

**Comment by ZFgan** [comment]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-94-137375074c77> in <module>
     12     'instruments':instruments
     13 }
---> 14 h = Alpha158(**data_handler_config)

D:\Anaconda3_2002\lib\site-packages\qlib\contrib\data\handler.py in __init__(self, instruments, start_time, end_time, infer_processors, learn_processors, fit_start_time, fit_end_time, process_type, **kwargs)
    154             infer_processors=infer_processors,
    155             learn_processors=learn_processors,
--> 156             process_type=process_type,
    157         )
    158 

D:\Anaconda3_2002\lib\site-packages\qlib\data\dataset\handler.py in __init__(self, instruments, start_time, end_time, data_loader, infer_processors, learn_processors, process_type, **kwargs)
    320 
    321         self.process_type = process_type
--> 322         super().__init__(instruments, start_time, end_time, data_loader, **kwargs)
    323 
    324     def get_all_processors(self):

D:\Anaconda3_2002\lib\site-packages\qlib\data\dataset\handler.py in __init__(self, instruments, start_time, end_time, data_loader, init_data, fetch_orig)
     96         if init_data:
     97             with TimeInspector.logt("Init data"):
---> 98                 self.init()
     99         super().__init__()
    100 

D:\Anaconda3_2002\lib\site-packages\qlib\data\dataset\handler.py in init(self, init_type, enable_cache)
    401         """
    402         # init raw data
--> 403         super().init(enable_cache=enable_cache)
    404 
    405         with TimeInspector.logt("fit & process data"):

D:\Anaconda3_2002\lib\site-packages\qlib\data\dataset\handler.py in init(self, enable_cache)
    120         # _data may be with multiple column index level. The outer level indicates the feature set name
    121         with TimeInspector.logt("Loading data"):
--> 122             self._data = self.data_loader.load(self.instruments, self.start_time, self.end_time)
    123         # TODO: cache
    124 

D:\Anaconda3_2002\lib\site-packages\qlib\data\dataset\loader.py in load(self, instruments, start_time, end_time)
    120                 {
    121                     grp: self.load_group_df(instruments, exprs, names, start_time, end_time)
--> 122                     for grp, (exprs, names) in self.fields.items()
    123                 },
    124                 axis=1,

D:\Anaconda3_2002\lib\site-packages\qlib\data\dataset\loader.py in <dictcomp>(.0)
    120                 {
    121                     grp: self.load_group_df(instruments, exprs, names, start_time, end_time)
--> 122                     for grp, (exprs, names) in self.fields.items()
    123                 },
    124                 axis=1,

D:\Anaconda3_2002\lib\site-packages\qlib\data\dataset\loader.py in load_group_df(self, instruments, exprs, names, start_time, end_time)
    154             warnings.warn("`filter_pipe` is not None, but it will not be used with `instruments` as list")
    155 
--> 156         df = D.features(instruments, exprs, start_time, end_time)
    157         df.columns = names
    158         df = df.swaplevel().sort_index()  # NOTE: always return <datetime, instrument>

D:\Anaconda3_2002\lib\site-packages\qlib\data\data.py in features(self, instruments, fields, start_time, end_time, freq, disk_cache)
    973             disk_cache = False
    974         try:
--> 975             return DatasetD.dataset(instruments, fields, start_time, end_time, freq, disk_cache)
    976         except TypeError:
    977             return DatasetD.dataset(instruments, fields, start_time, end_time, freq)

D:\Anaconda3_2002\lib\site-packages\qlib\data\cache.py in dataset(self, instruments, fields, start_time, end_time, freq, disk_cache)
    311             # use and replace cache
    312             try:
--> 313                 return self._dataset(instruments, fields, start_time, end_time, freq, disk_cache)
    314             except NotImplementedError:
    315                 return self.provider.dataset(instruments, fields, start_time, end_time, freq)

D:\Anaconda3_2002\lib\site-packages\qlib\data\cache.py in _dataset(self, instruments, fields, start_time, end_time, freq, disk_cache)
    639             with CacheUtils.writer_lock(self.r, "dataset-%s" % _cache_uri):
    640                 features = self.gen_dataset_cache(
--> 641                     cache_path=cache_path, instruments=instruments, fields=fields, freq=freq
    642                 )
    643             if not features.empty:

D:\Anaconda3_2002\lib\site-packages\qlib\data\cache.py in gen_dataset_cache(self, cache_path, instruments, fields, freq)
    789         self.clear_cache(cache_path)
    790 
--> 791         features = self.provider.dataset(instruments, fields, _calendar[0], _calendar[-1], freq)
    792 
    793         if features.empty:

D:\Anaconda3_2002\lib\site-packages\qlib\data\data.py in dataset(self, instruments, fields, start_time, end_time, freq)
    706         end_time = cal[-1]
    707 
--> 708         data = self.dataset_processor(instruments_d, column_names, start_time, end_time, freq)
    709 
    710         return data

D:\Anaconda3_2002\lib\site-packages\qlib\data\data.py in dataset_processor(instruments_d, column_names, start_time, end_time, freq)
    423         workers = min(C.kernels, len(instruments_d))
    424         if C.maxtasksperchild is None:
--> 425             p = Pool(processes=workers)
    426         else:
    427             p = Pool(processes=workers, maxtasksperchild=C.maxtasksperchild)

D:\Anaconda3_2002\lib\multiprocessing\context.py in Pool(self, processes, initializer, initargs, maxtasksperchild)
    117         from .pool import Pool
    118         return Pool(processes, initializer, initargs, maxtasksperchild,
--> 119                     context=self.get_context())
    120 
    121     def RawValue(self, typecode_or_type, *args):

D:\Anaconda3_2002\lib\multiprocessing\pool.py in __init__(self, processes, initializer, initargs, maxtasksperchild, context)
    167             processes = os.cpu_count() or 1
    168         if processes < 1:
--> 169             raise ValueError("Number of processes must be at least 1")
    170 
    171         if initializer is not None and not callable(initializer):

ValueError: Number of processes must be at least 1

**Comment by ZFgan** [comment]
It might be a little messy.

**Comment by you-n-g** [comment]
@ZFgan  
Hi, I think you find a bug.

Would you mind sending a PR to fix this issue and become [one of the contributors of Qlib](https://github.com/microsoft/qlib/graphs/contributors)!

https://github.com/microsoft/qlib/blob/main/qlib/data/data.py#L718

I think you can fix it replace the above code with `workers = max(min(C.kernels, len(instruments_d)), 1)`


Thanks :)

**Comment by you-n-g** [comment]
Due to the filter, it is expected to get an empty DataFrame instead of raising an error.

**Comment by ZFgan** [comment]
Thank you very much.

**Comment by you-n-g** [comment]
You are welcome 
Looking forward to your PR  😄

**Comment by ZFgan** [comment]
I have another question.the configuration file seems to be invalid,when i set start_time = '2020-01-01',the result start_time is '2005-01-01'

**code**
instruments = D.instruments(market='csi300')
data_handler_config = {
    "start_tme":"2020-01-01",
    'end_time':'2020-08-30',
    'fit_start_time':'2020-01-01',
    'fit_end_time':'2020-06-30',
    'instruments':instruments
}

h1 = Alpha158(**data_handler_config)
h1.fetch(col_set = 'label‘）

**result**
		LABEL0
datetime	instrument	
2005-01-04	SH600000	-0.013294
SH600004	0.002301
SH600006	-0.012819
...	...	...
2020-08-28	SZ300413	0.032499
SZ300433	0.050911
SZ300498	-0.006483

**Comment by bxdd** [comment]
Hi, I am sorry for my late reply, do you have any questions at the moment?
