### ISSUE TITLE
How to import our own csi300.txt?

### ISSUE THREAD

**Issue by arisliang** [microsoft/qlib#445]
## ❓ Questions and Help
If download the demo 1d data using provided script, it would import a csi300.txt in instruments folder.

>python scripts/get_data.py qlib_data --target_dir ~/.qlib/qlib_data/cn_data --region cn

When importing our own data say in csv format, how do we import this csi300.txt file as well? This file is not in usual csv format, so cannot be provided through CSV import I assume.

**Comment by zhupr** [comment]
Import csi100 or csi300, reference: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/cn_index/README.md
```
python collector.py --index_name CSI300 --qlib_dir <user qlib data dir> --method parse_instruments
```

**Comment by arisliang** [comment]
Thanks, this works. What is the difference between `parse_instruments` and `save_new_companies`?

**Comment by zhupr** [comment]
`parse_instruments`： generate component stock changes with `"index"` history
`save_new_companies`: download only the `"index"` list of latest included stocks

**Comment by arisliang** [comment]
Thanks for the explanation!

**Comment by you-n-g** [comment]
@arisliang  
Would you mind sending a PR to improve the docs about this Question?
Other users who have similar confusion will be grateful to you :)
Thanks
