### ISSUE TITLE
Error when running LightGBM_Alpha158 model with minimal custom data

### ISSUE THREAD

**Issue by arisliang** [microsoft/qlib#446]
## 🐛 Bug Description

I try to import my own mini csv data (2 symbol and sh000300 index), and run the same model as demo:
>qrun benchmarks/LightGBM/workflow_config_lightgbm_Alpha158.yaml

However it gives this error:
>TypeError: Can only swap levels on a hierarchical axis.

## To Reproduce

1. import 3 data series into own data folder `cn_1d` through csv import.
>000615	2008-01-02	2021-04-30
603919	2016-03-10	2021-04-30
SH000300	2008-01-02	2021-04-30

2. Copy csi300.txt to own data folder subfolder `cn_1d\instruments`
3. Update workflow_config_lightgbm_Alpha158.yaml to point to own data folder `cn_1d`
4. run benchmark:
>qrun benchmarks/LightGBM/workflow_config_lightgbm_Alpha158.yaml

## Expected Behavior

Similar analysis result as running on demo cn 1d data, with reduced data set.

## Screenshot

![image](https://user-images.githubusercontent.com/1115503/119781258-64147e00-befd-11eb-9b20-295975a942b4.png)

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

Windows
AMD64
Windows-10-10.0.19041-SP0
10.0.19041

Python version: 3.8.8 (default, Feb 24 2021, 15:54:32) [MSC v.1928 64 bit (AMD64)]

Qlib version: 0.6.3.99
numpy==1.20.3
pandas==1.2.4
scipy==1.6.0
requests==2.25.1
sacred==0.8.2
python-socketio==3.1.2
redis==3.5.3
python-redis-lock==3.7.0
schedule==1.0.0
cvxpy==1.0.21
hyperopt==0.1.1
fire==0.4.0
statsmodels==0.12.1
xlrd==2.0.1
plotly==4.12.0
matplotlib==3.1.3
tables==3.6.1
pyyaml==5.4.1
mlflow==1.14.0
tqdm==4.61.0
loguru==0.5.3
lightgbm==3.1.1
tornado==6.1
joblib==1.0.1
fire==0.4.0
ruamel.yaml==0.16.12

 - Commit number (optional, please provide it if you are using the dev version): cbbf6cd82260e533662a7433ba72cf3391347619

**Comment by you-n-g** [comment]
@arisliang 
You can try to debug this line  https://github.com/microsoft/qlib/blob/main/qlib/data/dataset/loader.py#L177
and check the content of the variable `df`.

**Comment by arisliang** [comment]
`df` is empty. `markets` is 'csi300'. What does this mean? We need to include all stocks for csi300?

**Comment by you-n-g** [comment]
Please check the content in your ` ~/.qlib/qlib_data/cn_data/instruments/csi300.txt` file.
It indicates the stock pool of your data.
I think your customized data is not included in this stock pool.

You can either create your own stock pool or use the stock id list as the stock pool directly.

Thanks.

**Comment by arisliang** [comment]
Thanks, after change market to `all`, it runs through.
Although it encounter two issues in the analysis part later on.
1. score IC
![image](https://user-images.githubusercontent.com/1115503/120065420-c60ee800-c0a3-11eb-8c86-9350f09a5747.png)

2. model performance graph
![image](https://user-images.githubusercontent.com/1115503/120065432-d6bf5e00-c0a3-11eb-9fdf-e8580483ad80.png)

**Comment by you-n-g** [comment]
@arisliang  Could you give us  more info about label_df and pred_df?

**Comment by arisliang** [comment]
for `label_df` and `pred_df`:

![image](https://user-images.githubusercontent.com/1115503/120100475-87e0f980-c173-11eb-98b3-272bf92153ca.png)

**Comment by you-n-g** [comment]
@arisliang  Are your scores all zero?

**Comment by zhupr** [comment]
@arisliang 
You can check that part of the `qlib data` is consistent with the `original data`
```
import qlib
from qlib.data import D
qlib.init(provider_uri=<user qlib data dir>)
df = D.features(D.instruments("all"), ["$close", "$high", "$low", "$volume", "$open"])
print(df.tail())
```

**Comment by arisliang** [comment]
@zhupr result after running your script:
![image](https://user-images.githubusercontent.com/1115503/120235215-21033380-c28c-11eb-8ec5-a3c5836d9c96.png)

**Comment by zhupr** [comment]
@arisliang 
Does the `instrument` data match your own raw data?

**Comment by arisliang** [comment]
![image](https://user-images.githubusercontent.com/1115503/120348438-c3c0be00-c32f-11eb-8c90-d834473e40b6.png)

@zhupr yes, it does seem to match with the original data

**Comment by you-n-g** [comment]
@arisliang I think you can check why your model output all zeros for prediction.

**Comment by arisliang** [comment]
The zero value comes from `model.predict(dataset)`:
![image](https://user-images.githubusercontent.com/1115503/120917283-fb898600-c6e0-11eb-86eb-7875d7984dff.png)

Basically I took the default workflow notebook, and feed it with minimal csv data (000615,SH_000300, 2008-01-01 to 2020-08-01) and dump into qlib format. The LGBModel doesn't seem to improve with fit over 50 rounds, and predict all zeros, therefore no trades happen.

The benchmark report seems to be ok.
![image](https://user-images.githubusercontent.com/1115503/120917399-ab5ef380-c6e1-11eb-9c1f-ac901154e22e.png)

Not sure how the LGBModel works, could it be that it requires more symbols (>1) to train and predict?

**Comment by arisliang** [comment]
After running @zhupr's script again, the result is:

![image](https://user-images.githubusercontent.com/1115503/120917687-283e9d00-c6e3-11eb-8dd6-5e621d26a6ae.png)

**Comment by you-n-g** [comment]
@arisliang  
It seems there are some problems with your model
The best validation score is achieved in the first round.  So the model with initial parameters is used.
Please check the building process of your dataset and the parameters of your model.

**Comment by arisliang** [comment]
The building process of the dataset is just 1 symbol of daily data (000615), and 1 daily benchmark (SH003000). The model is default LGBModel. Does this model have some implicit requirement on data? There's no mentioning of it that I could find, so I assume it should work with 1 symbol, which might make sense, if user just want to include 1 stock in the pool.

**Comment by you-n-g** [comment]
It seems the distribution of validation data may be totally different from training data in your case. 
If you want to force your model to learn something, you can disable the early stopping feature of LightGBM.
But this is not a good idea.   I think you can spend more time on your models and data.

**Comment by arisliang** [comment]
I tried to copy one of the demo data `sz300800.csv`, and run the workflow code on it.

It gives the same error as #278

**Comment by you-n-g** [comment]
@arisliang
I think it is not a problem for the specific data.
The failure of the model may be caused by the problem setting.
I think it is not an easy thing to capture the pattern of one specific stock.

**Comment by arisliang** [comment]
Ok, I'll close this issue, since one specific stock may not be a good test. #278 is with full set of demo data though.
