### ISSUE TITLE
How to convert qlib format to csv?

### ISSUE THREAD

**Issue by arisliang** [microsoft/qlib#449]
We can use `dump_bin.py` to convert CSV to qlib format, like:
>python scripts/dump_bin.py dump_all --csv_path  ~/.qlib/csv_data/my_data --qlib_dir ~/.qlib/qlib_data/my_data --include_fields open,close,high,low,volume,factor

Conversely, can we convert qlib format back to CSV format?

**Comment by you-n-g** [comment]
@arisliang  
You can use `D.features` to load the data in qlib.  And use  `pandas.to_csv` to dump the data.

**Comment by arisliang** [comment]
That sounds great, thanks!
