### ISSUE TITLE
How to create a simple strategy in qlib?

### ISSUE THREAD

**Issue by arisliang** [microsoft/qlib#451]
## ❓ Questions and Help

By simple strategy, I mean comparing to the implemented ML models that needs train and forecast workflows. A simple conceived strategy with a simple if-else condition, say:
- if close > open, buy in the next day; and sell after holding for 3 days.

How do we achieve this kind of simple strategy in qlib framework?

**Comment by ZFgan** [comment]
Simple strategy can be built in qlib.
In strategy class,it has a function **generate_order_list**(self, **score_series**, current, trade_exchange, pred_date, trade_date),we can use ml to get score_series,we can also define  signal = close>open,just save the signal format like ml score_series

**Comment by arisliang** [comment]
Thanks, how can we skip the model train/forecast workflow in this case? For simple strategy at least.

**Comment by arisliang** [comment]
>where's the signal generated?
As stepped through, looks like it's from [`model.predict`](https://github.com/microsoft/qlib/blob/50be7a9171dd67b236a23cdf0d25ae17856050c2/qlib/contrib/workflow/record_temp.py#L34).

Still not sure how to skip the model train/forecast step, for the simple strategy.

**Comment by ZFgan** [comment]
In the qlib,the parts are decoupled(data/model/backtest/workflow),theres are many ways to do this.for example, you can use  backtest function instead of workflow,or you can define model,model.predict = close>open

**Comment by arisliang** [comment]
Find the [backtest example](https://github.com/microsoft/qlib/blob/v0.5.1/examples/train_backtest_analyze.ipynb) in the older version gives clearer view of the steps involved. It also illustrates backtest function usage better than the current workflow example.

Guess we should put it back in the current version? It'll make it easier to find. It seems these two styles of usage are both valid options, and have their strengths.

Thanks for the suggestion, I'll try the backtest function instead.

**Comment by you-n-g** [comment]
@arisliang  The usage of the old version backtest is included here https://qlib.readthedocs.io/en/latest/component/strategy.html#usage-example

You are welcome to improve the docs on this page.

**Comment by arisliang** [comment]
I see, missed that example from doc.

The doc refers to an non-existing notebook though:

>examples/train_backtest_analyze.ipynb

**Comment by you-n-g** [comment]
@arisliang   It is fixed now :)

**Comment by arisliang** [comment]
Is it removed? 😂

**Comment by you-n-g** [comment]
@arisliang Yes. The link is removed now. 
Because the docs contain similar code and the notebook does not exist in the main branch any longer.

Do you have any better suggestions about it😂 ?  Your PR is welcome.

**Comment by aca787** [comment]
I see this is a closed issue, but is there any working example for a simple strategy as mentioned here?

> Simple strategy can be built in qlib. In strategy class,it has a function **generate_order_list**(self, **score_series**, current, trade_exchange, pred_date, trade_date),we can use ml to get score_series,we can also define signal = close>open,just save the signal format like ml score_series
