### ISSUE TITLE
What is the difference between pytorch_lstm and pytorch_lstm_ts in qlib.contrib.model

### ISSUE THREAD

**Issue by cheng-zi-ya** [microsoft/qlib#453]
## ❓ Questions and Help

I tried to run all the baseline models, but I find it is cofusing for me to understand the difference between lstm and lstm_ts. Actually, I found that lstm_ts is been used in Alpha158 and lstm is been used in Alpha 360. Therefore, I would like to ask why this difference exists. Also, why some other models, like LR and LGB, don't need to do that.

**Comment by you-n-g** [comment]
`*_ts` are some models that leverage the  [TSDatasetH](https://github.com/microsoft/qlib/blob/main/examples/benchmarks/LSTM/workflow_config_lstm_Alpha158.yaml#L68) to easily create time-series samples.

LR and LGB don't support modeling time-series directly.  So they don't have the `*_ts` version.
