### ISSUE TITLE
Regarding datetime management for minute level data

### ISSUE THREAD

**Issue by shashank-yadav** [microsoft/qlib#454]
## ❓ Questions and Help
Hi, I was trying to implement my own backtesting function to handle minute-level data. Can you tell me what this part does in `qlib.contrib.backtest.__init__.py`:     
`
dates = np.append(dates, get_date_range(dates[-1], left_shift=1, right_shift=shift))  
`
As in why we need to do this? AFAIU this will just add the last date to the list of dates again. Can you help me in converting this to minute level? Thanks.

**Comment by you-n-g** [comment]
The earliest time to use the prediction at timestamp `T` for trading is  `T + 1`.
So one more trading date is appended to evaluate the signal produced at `T`.
We are developing a new framework that could better support minute-level data.
Please pay attention to [this PR](https://github.com/microsoft/qlib/pull/438)

Thanks .

**Comment by shashank-yadav** [comment]
Thanks for the prompt reply. Is there a timeline as to when this is supposed to get merged? Thanks!

**Comment by you-n-g** [comment]
I think it will be merged in 1~2 months

**Comment by shashank-yadav** [comment]
Thanks for the info!
