### ISSUE TITLE
How to connect this to real market

### ISSUE THREAD

**Issue by deathwing573** [microsoft/qlib#455]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

**Comment by ZFgan** [comment]
You can use record to get specific trading stocks for each time, and then use your own trading system to complete the transaction.

**Comment by you-n-g** [comment]
@deathwing573 
https://qlib.readthedocs.io/en/latest/component/online.html
You can use the new feature of Qlib to serve your model for online trading.
