### ISSUE TITLE
can I get lagged value of a financial var

### ISSUE THREAD

**Issue by specialuse** [microsoft/qlib#458]
for example i have column "roe" in my dataset, how can i get lag(roe)? i mean not yesterday's roe but the last quarter's roe 
thanks

**Comment by ZFgan** [comment]
It's a little difficult. You have to define the delay function yourself.

**Comment by specialuse** [comment]
Thanks   
But the basic data is {X i,t.a}，without “report_period” it is difficult to define such kind of functions

**Comment by ZFgan** [comment]
It can be processed in two steps, reading all the data first, and then cutting it yourself, although the processing speed will be slower. It will be troublesome if you use pit data, but if it is factor data, only one additional csv file is needed to store the financial report points in time, such as 0331, 0630, 0931, 1231 or 0501, 0901, 1101.

**Comment by you-n-g** [comment]
@specialuse 
#343 is designed for exactly your requriements.
Please pay attention to it.

**Comment by specialuse** [comment]
expecting
thanks
