### ISSUE TITLE
What is exp_info.json?

### ISSUE THREAD

**Issue by pan-cai** [microsoft/qlib#46]
examples/estimator/analyze_from_estimator

```
with CUR_DIR.joinpath(estimator_name, 'exp_info.json').open() as fp:
    latest_id = json.load(fp)['id']
```

Thanks

**Comment by bxdd** [comment]
Hi, your feedback is very welcome. Please refer to the `Estimator` documentation(https://qlib.readthedocs.io/en/latest/component/estimator.html#experiment-section) to know more about `exp_info.json`, the content in `exp_info_path` will help you a lot.

**Comment by pan-cai** [comment]
Thanks.

**Comment by you-n-g** [comment]
@pan-cai  We will design a more user-friendly interface to training model soon.
Please stay tuned for our next release :)
