### ISSUE TITLE
Walk Forward Optimisation

### ISSUE THREAD

**Issue by aLeX1443** [microsoft/qlib#469]
## 🌟 Feature Description

It would be great to implement walk forward optimisation the way it is described [here](https://algotrading101.com/learn/walk-forward-optimization/) and [here](https://en.wikipedia.org/wiki/Walk_forward_optimization).

Qlib already supports specifying the train, validation and test periods, so it seems trivial to implement:

- Create a loop where the train, validation and test dates are shifted forward by i.e., 1 month at a time
- Train the model on the train set and backtest on the test set
- Make sure to use the same `Account` to keep track of the overall portfolio performance

The issue I see is that in this loop we would need to re-create the data set object, e.g., `TSDatasetH` when we change the start and end times for the train, validation and test periods. This can be quite slow if we are using the whole of the daily US data from Yahoo since the year 2000 (~80GB of RAM is filled up by this data set).

Is there a way to update the start and end times of each split, or do we need to re-create the `TSDatasetH` object each time?

## Motivation

Implementing walk forward would give a better representation of how a model would perform in the real world, since we assume a user will want to re-train their model somewhat frequently to learn on new data.

## Additional Notes

I'm very happy to implement this feature, but it would be great to have some guidance on the best way to go about it :)

**Comment by you-n-g** [comment]
Hi, @aLeX1443 
The  Walk Forward Optimisation feature has been recently implemented (but with a different name called "Rolling")

Please refer to the [docs](https://qlib.readthedocs.io/en/latest/component/online.html#qlib.workflow.online.strategy.RollingStrategy) and the [examples](https://github.com/microsoft/qlib/blob/main/examples/model_rolling/task_manager_rolling.py)
