### ISSUE TITLE
Can build qlib in ubuntu docker, failed to build cvxpy ecos scs fastcache

### ISSUE THREAD

**Issue by yukonstars** [microsoft/qlib#486]
## ❓ Questions and Help

Could you give me a help to build qlib in docker?

My build failed due to 
#11 135.4 Failed to build cvxpy ecos scs fastcache
#11 135.4 ERROR: Could not build wheels for scs which use PEP 517 and cannot be installed directly

My Dockerfile is as following:

FROM ubuntu:latest
WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV LIBRARY_PATH=/lib:/usr/lib
ENV PATH /usr/src/app/bin:$PATH
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
            software-properties-common \
            python3-dev \
            netcat \
            graphviz \
            curl && \
    rm -rf /var/lib/apt/lists/*

RUN curl -fSsL -O https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    rm get-pip.py

RUN pip install --upgrade pip setuptools wheel
COPY requirements.txt ./requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

COPY . /usr/src/app/

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]

**Comment by zhupr** [comment]
@yukonstars Hi,
- Add `apt install g++` to `Run` 

You can use this image [minicoda](https://registry.hub.docker.com/r/continuumio/miniconda3): `FROM continuumio/miniconda3`
```
FROM continuumio/miniconda3

WORKDIR /usr/src/app

......

RUN apt-get update\
    && apt-get install -y g++\
    && apt-get clean\
    && rm -rf /var/lib/apt/lists/*\
    && pip install numpy cython\
    ......

```
