### ISSUE TITLE
Dose qrun support long_short_backtest, if so , how do I  set up the yaml file?

### ISSUE THREAD

**Issue by wuzhe1234** [microsoft/qlib#492]
I've tryed this, but it doesn't work.

port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy.strategy
        kwargs:
            topk: 10
            n_drop: 3
    long_short_backtest:
        verbose: False
        limit_threshold: 100
        account: 100000000
        deal_price: close
        open_cost: 0.0005
        close_cost: 0.0005
        min_cost: 0.0
        trade_unit: 1

**Comment by you-n-g** [comment]
@wuzhe1234 
Hi,  We have a long-short backtest function https://github.com/microsoft/qlib/blob/main/qlib/contrib/evaluate.py#L131
It is not integrated into a yaml-based workflow.

We'll try to improve it later.

Thanks.

**Comment by wuzhe1234** [comment]
> @wuzhe1234
> Hi, We have a long-short backtest function https://github.com/microsoft/qlib/blob/main/qlib/contrib/evaluate.py#L131
> It is not integrated into a yaml-based workflow.
> 
> We'll try to improve it later.
> 
> Thanks.

Thanks for your reply! Looking forward to it.
