### ISSUE TITLE
Need to release a new package to fix qlib-server issue.

### ISSUE THREAD

**Issue by chaosddp** [microsoft/qlib#499]
## 🐛 Bug Description

In commit e15ea06122bd570706ac8b6d3ab6b96b5ee64edb, we have fix the bug that incorrect python-socketio will cause qlib-server fail to start, but we have not release a new package, so we still cannot use current qlib-server source to start.

## To Reproduce

1.
1.
1.

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version:
 - Python version:
 - OS (`Windows`, `Linux`, `MacOS`):
 - Commit number (optional, please provide it if you are using the dev version):

**Comment by you-n-g** [comment]
Hi, @chaosddp

The latest qlib has been released now :) 

https://github.com/microsoft/qlib/releases/tag/v0.7.0

https://pypi.org/project/pyqlib/
