### ISSUE TITLE
How to run "estimator -c configuration.yaml" on Ubuntu ?

### ISSUE THREAD

**Issue by pan-cai** [microsoft/qlib#50]
It works om WinOS.
But I do not know where is estimator, and how to run "estimator -c configuration.yaml" on Ubuntu.

Thanks

On Jupyter,

```
! cd ./examples
! estimator -c estimator/estimator_config.yaml
```
---
`/bin/sh: 1: estimator: not found`

**Comment by bxdd** [comment]
Hi, it works on Ubuntu too. Please make sure that you have installed `Qlib` successfully.

**Comment by pan-cai** [comment]
Got it, thank you
