### ISSUE TITLE
TCTS model 

### ISSUE THREAD

**Issue by douhongkun** [microsoft/qlib#503]
## ❓ Questions and Help

In TCTS model, the outer level is optimized by Reinforcement algorithm. In this paper, the task needs to be sampled according to the probability distribution. However, why qlib directly uses argmax in the implementation of this model is lack of important exploration in reinforcement learning. Can you answer why it is different from the description in this paper and whether it will affect the results.Thanks.
![image](https://user-images.githubusercontent.com/77845036/125065995-15095d80-e0e5-11eb-97ed-4f919a318241.png)

**Comment by lwwang1995** [comment]
The implementation here is indeed slightly different from the algorithm in the paper. Among the two tasks involved in the paper, in the machine translation task, the task needs to be sampled according to the probability distribution, while in the stock return prediction task, we directly uses argmax to select the task. Our point of view is that these two methods are essentially the same. They both use the reinforcement learning model to find the best task. The difference is that the former is a soft approach, while the latter is a hard approach. 
In the future, we will also apply sampling task from the probability distribution to the task of stock return prediction.

**Comment by douhongkun** [comment]
> 这里的实现确实与论文中的算法略有不同。论文涉及的两个任务中，在机器翻译任务中，需要根据概率分布对任务进行采样，而在股票收益预测任务中，我们直接使用argmax来选择任务。我们的观点是，这两种方法本质上是一样的。他们都使用强化学习模型来寻找最佳任务。区别在于前者是软方法，而后者是硬方法。
> 未来，我们还将把概率分布的抽样任务应用到股票收益预测的任务中。

I see. Thank you
