### ISSUE TITLE
Why are we trading on the next day's `close` instead of the current day?

### ISSUE THREAD

**Issue by aLeX1443** [microsoft/qlib#506]
I've noticed that Qlib frequently references the [deal_price](https://github.com/microsoft/qlib/blob/b504cc6ac8d6f111591a25e8a838e24c1713dd3b/examples/benchmarks/LightGBM/workflow_config_lightgbm_Alpha158.yaml#L24) (i.e., what price we will use to execute trades, either `open` or `close`).

During backtesting, if we set this to `open` we have the following example scenario:
- We perform inference with our model using data up until Friday (i.e., we generate our prediction on Friday)
- We trade on Monday's `open` price

Ok, that scenario makes sense in the real world. We are trading on the next day's open using the most up to date data we have. However, consider the scenario where the `deal_price` is set to `close`:
- We perform inference with our model using data up until Friday (i.e., we generate our prediction on Friday)
- We trade on Monday's `close` price at the end of the day

Please correct me if I'm wrong, but this seems we are getting the next day's close price [here](https://github.com/microsoft/qlib/blob/b504cc6ac8d6f111591a25e8a838e24c1713dd3b/qlib/contrib/backtest/exchange.py#L202) since we are using `shift=1` [here](https://github.com/microsoft/qlib/blob/b504cc6ac8d6f111591a25e8a838e24c1713dd3b/qlib/contrib/backtest/__init__.py#L108) .

Does it make sense to set `shift=0` if we want to create our trade on the same day we predicted on? Let's say we want to collect current prices 10 mins before the market closes, treat that as our close price, perform inference on that day and trade on the same day.

Also, If we are using labels such as `"Ref($close, -2) / Ref($close, -1) - 1"` to train the model, does it make sense we should be using `"Ref($open, -2) / Ref($open, -1) - 1"` as the training label if we are setting `deal_price = "open"`?

Thanks in advance!

**Comment by you-n-g** [comment]
The setting of the label is explained in [this section](https://qlib.readthedocs.io/en/latest/component/data.html#example)

I think your cases are reasonable (trading before market closing or at the opening of the next trading day).
It is not forced to align the label setting to the trading setting (but in most cases, it will look more reasonable to align them)

**Comment by aLeX1443** [comment]
Thanks! Had a look through the document, that's answered my question.

**Comment by you-n-g** [comment]
@aLeX1443 
Do you have any suggestions about how to improve the docs?  (e.g. what prevent you find the answer directly)
If the answer is Yes,
would you mind sending a PR to improve the docs about this Question?
Other users who have similar confusion will be grateful to you :)
Thanks

**Comment by ZhangTP1996** [comment]
> @aLeX1443
> Do you have any suggestions about how to improve the docs? (e.g. what prevent you find the answer directly)
> If the answer is Yes,
> would you mind sending a PR to improve the docs about this Question?
> Other users who have similar confusion will be grateful to you :)
> Thanks

The PR has been sent.
