### ISSUE TITLE
about using my own instrument data

### ISSUE THREAD

**Issue by zymmatt** [microsoft/qlib#515]
I have some instrument trade data and want to put it in qlib workflow for backtesting. The data has instrument_id, open, close,high,low,datetime ,frequency and volume.  But it lacks some attributes which were shown in documents. They are factor,vwap and change. Does it matter if I do backtest without those attributes? Or can I try to calculate them?

**Comment by zhupr** [comment]
*factor*: `factor = adjusted_price / original_price`, adjusted price reference: [split adjusted](https://www.investopedia.com/terms/s/splitadjusted.asp), if *open/close/high/low/volume* is the `adjusted` data,`factor` can be ignored or `factor=1`
*vwap*: `vwap = amount / volume`，if `vwap` is not available, you can use `close` instead
*change*: `df["change"] = df["close"].pct_change(fill_method="ffill")`
```

**Comment by zymmatt** [comment]
> _factor_: `factor = adjusted_price / original_price`, adjusted price reference: [split adjusted](https://www.investopedia.com/terms/s/splitadjusted.asp), if _open/close/high/low/volume_ is the `adjusted` data,`factor` can be ignored or `factor=1`
> _vwap_: `vwap = amount / volume`，if `vwap` is not available, you can use `close` instead
> _change_: `df["change"] = df["close"].pct_change(fill_method="ffill")`

Thanks for your advice !

**Comment by you-n-g** [comment]
@zymmatt 
Would you mind sending a PR to improve the docs about this Question?
Other users who have similar confusion will be grateful to you :)
Thanks
