### ISSUE TITLE
可以导入本地的因子吗？

### ISSUE THREAD

**Issue by panshuaiyin** [microsoft/qlib#518]
## ❓ Questions and Help

本地有一个现成的因子库，请问有没有能把这个因子库中的因子（csv文件）直接导入的接口呢？

**Comment by you-n-g** [comment]
Sure.
https://qlib.readthedocs.io/en/latest/component/data.html#converting-csv-format-into-qlib-format

**Comment by panshuaiyin** [comment]
谢谢，这个我已经看过了，想问一下可不可以在计算alpha因子的步骤时，不通过qlib.contrib.data.handler里的alpha158和alpha360计算，也不通过修改get_feature_config方法得到的自定义特征计算方法来计算，而是在本地有一组alpha因子的csv文件，每个文件columns和index名称分别是股票代码和日期，值是某个alpha因子，直接将这一组alpha因子导入到dataset中（dataset指的是示例代码“dataset = init_instance_by_config(task["dataset"])”中的等号左边的变量），然后用于后续的训练，请问有没有这样的接口呢？期待您的回复。

**Comment by you-n-g** [comment]
Yes.
The alpha-factor you described has the same format as OHCLV. So you can import them into Qlib with OHCLV together.
And then,  you can create your own dataset based on the factors you need just like [this](https://github.com/microsoft/qlib/blob/main/examples/benchmarks/LightGBM/workflow_config_lightgbm_configurable_dataset.yaml)

**Comment by panshuaiyin** [comment]
明白了，感谢

**Comment by you-n-g** [comment]
@panshuaiyin 
Would you mind sending a PR to improve the docs about this Question?
Other users who have similar confusion will be grateful to you :)
Thanks

**Comment by panshuaiyin** [comment]
可以啊，请问怎么修改docs呢？修改docs的哪个部分呢？我还有点不太会用git

**Comment by you-n-g** [comment]
Please click the `pen` and create a pull request :)

Thanks in advance.
![image](https://user-images.githubusercontent.com/465606/126055587-e981e5a0-dd27-402f-99fd-8db196b7cd6e.png)

**Comment by panshuaiyin** [comment]
已经提交了

**Comment by you-n-g** [comment]
@panshuaiyin 
Sorry, I didn't find your PR(pull request)
https://github.com/microsoft/qlib/pulls?q=is%3Apr+is%3Aopen+

**Comment by panshuaiyin** [comment]
刚刚又提交了，您再看看有没有

**Comment by you-n-g** [comment]
@panshuaiyin  It is merged now. Thanks!

**Comment by GarfieldWhy** [comment]
> 谢谢，这个我已经看过了，想问一下可不可以在计算alpha因子的步骤时，不通过qlib.contrib.data.handler里的alpha158和alpha360计算，也不通过修改get_feature_config方法得到的自定义特征计算方法来计算，而是在本地有一组alpha因子的csv文件，每个文件columns和index名称分别是股票代码和日期，值是某个alpha因子，直接将这一组alpha因子导入到dataset中（dataset指的是示例代码“dataset = init_instance_by_config(task["dataset"])”中的等号左边的变量），然后用于后续的训练，请问有没有这样的接口呢？期待您的回复。

**Comment by GarfieldWhy** [comment]
> 明白了，感谢

您好！我还是没看明白需要怎么导入本地因子呀，他给的链接里依然是通过datahandlerlp算的因子呀~谢谢！

**Comment by you-n-g** [comment]
可以把本地因子当成基础数据 （就像ohlcv) 导入 就行
