### ISSUE TITLE
 sub-weight in DoubleEnsemble model

### ISSUE THREAD

**Issue by douhongkun** [microsoft/qlib#519]
## ❓ Questions and Help

Hi！In the DoubleEnsemble model, why is the weight of the sub-model not normalized in predict? Although it has no effect on the ranking, will it produce deviation to the predicted true value？Thanks.
![image](https://user-images.githubusercontent.com/77845036/125924398-f94c7bed-263f-43b4-b7d7-0b113eaab7bd.png)

**Comment by you-n-g** [comment]
https://github.com/microsoft/qlib/blob/main/qlib/contrib/model/double_ensemble.py#L47

The weights are fixed values.
What do you mean by normalizing the weight

**Comment by douhongkun** [comment]
> https://github.com/microsoft/qlib/blob/main/qlib/contrib/model/double_ensemble.py#L47
> 
> The weights are fixed values.
> What do you mean by normalizing the weight

The sum of subweight is 2, but all the base models are trained according to label, so does the final prediction result tend to be twice the real value？

**Comment by you-n-g** [comment]
@douhongkun  
In the example of DoubleEnsemble, the strategy only cares about the rank of the prediction.
So the range of the prediction does not affect the portfolio in this example.

**Comment by douhongkun** [comment]
> @douhongkun
> In the example of DoubleEnsemble, the strategy only cares about the rank of the prediction.
> So the range of the prediction does not affect the portfolio in this example.

I see，thank you.
