### ISSUE TITLE
如何使用低频数据

### ISSUE THREAD

**Issue by panshuaiyin** [microsoft/qlib#526]
## ❓ Questions and Help

我将日频数据只取偶数交易日的值，去掉奇数交易日的数据，然后dump_all成qlib类型的数据，然后导入到实例程序workflow_by_code.ipynb里进行训练，在train model过程中出现报错。但我看您之前回答某个问题中说“Qlib didn't hard code the data frequency.”，请问一下如果数据不是日频的，应该如何使用（包括导入，训练，回测）？谢谢

**Comment by you-n-g** [comment]
@panshuaiyin  
Can you give more details about your error?

**Comment by panshuaiyin** [comment]
原始数据是日频，使用qlib.init初始化时正常，文件夹下包含month.txt，month.txt内是每月最后一个交易日，使用D.calendar(start_time='2000-01-01',end_time='2021-07-20',freq='month')也能正常获取month.txt内的日期，但执行下面这段
语句时报错，
from qlib.contrib.data.handler import Alpha158
data_handle_config = {
    'start_time':'2000-01-01',
    'end_time':'2020-11-30',
    'fit_start_time':'2000-01-01',
    'fit_end_time':'2017-06-30',
    'instruments':instruments,
    'freq':'month',
}
h = Alpha158(**data_handle_config)
报错信息为：TypeError: Can only swap levels on a hierarchical axis.
![image](https://user-images.githubusercontent.com/56989678/126953581-9f93ad83-e510-4a79-99cf-b451132e7202.png)
![image](https://user-images.githubusercontent.com/56989678/126953648-bacb49cf-1dc0-484d-96e9-483713496a70.png)
![image](https://user-images.githubusercontent.com/56989678/126953685-f2c58386-6a94-4437-b3c3-05ebada45727.png)

**Comment by panshuaiyin** [comment]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-29-da705daf16c1> in <module>
      8     'freq':'month'
      9 }
---> 10 h = Alpha158(**data_handle_config)
     11 print(h.get_cols())

d:\miniconda3\envs\pytorch\lib\site-packages\pyqlib-0.7.0.99-py3.7-win-amd64.egg\qlib\contrib\data\handler.py in __init__(self, instruments, start_time, end_time, freq, infer_processors, learn_processors, fit_start_time, fit_end_time, process_type, filter_pipe, **kwargs)
    168             infer_processors=infer_processors,
    169             learn_processors=learn_processors,
--> 170             process_type=process_type,
    171         )
    172 

d:\miniconda3\envs\pytorch\lib\site-packages\pyqlib-0.7.0.99-py3.7-win-amd64.egg\qlib\data\dataset\handler.py in __init__(self, instruments, start_time, end_time, data_loader, infer_processors, learn_processors, process_type, drop_raw, **kwargs)
    371         self.process_type = process_type
    372         self.drop_raw = drop_raw
--> 373         super().__init__(instruments, start_time, end_time, data_loader, **kwargs)
    374 
    375     def get_all_processors(self):

d:\miniconda3\envs\pytorch\lib\site-packages\pyqlib-0.7.0.99-py3.7-win-amd64.egg\qlib\data\dataset\handler.py in __init__(self, instruments, start_time, end_time, data_loader, init_data, fetch_orig)
    104         if init_data:
    105             with TimeInspector.logt("Init data"):
--> 106                 self.setup_data()
    107         super().__init__()
    108 

d:\miniconda3\envs\pytorch\lib\site-packages\pyqlib-0.7.0.99-py3.7-win-amd64.egg\qlib\data\dataset\handler.py in setup_data(self, init_type, **kwargs)
    469         """
    470         # init raw data
--> 471         super().setup_data(**kwargs)
    472 
    473         with TimeInspector.logt("fit & process data"):

d:\miniconda3\envs\pytorch\lib\site-packages\pyqlib-0.7.0.99-py3.7-win-amd64.egg\qlib\data\dataset\handler.py in setup_data(self, enable_cache)
    147         # _data may be with multiple column index level. The outer level indicates the feature set name
    148         with TimeInspector.logt("Loading data"):
--> 149             self._data = self.data_loader.load(self.instruments, self.start_time, self.end_time)
    150         # TODO: cache
    151 

d:\miniconda3\envs\pytorch\lib\site-packages\pyqlib-0.7.0.99-py3.7-win-amd64.egg\qlib\data\dataset\loader.py in load(self, instruments, start_time, end_time)
    130                 {
    131                     grp: self.load_group_df(instruments, exprs, names, start_time, end_time)
--> 132                     for grp, (exprs, names) in self.fields.items()
    133                 },
    134                 axis=1,

d:\miniconda3\envs\pytorch\lib\site-packages\pyqlib-0.7.0.99-py3.7-win-amd64.egg\qlib\data\dataset\loader.py in <dictcomp>(.0)
    130                 {
    131                     grp: self.load_group_df(instruments, exprs, names, start_time, end_time)
--> 132                     for grp, (exprs, names) in self.fields.items()
    133                 },
    134                 axis=1,

d:\miniconda3\envs\pytorch\lib\site-packages\pyqlib-0.7.0.99-py3.7-win-amd64.egg\qlib\data\dataset\loader.py in load_group_df(self, instruments, exprs, names, start_time, end_time)
    178         df.columns = names
    179         if self.swap_level:
--> 180             df = df.swaplevel().sort_index()  # NOTE: if swaplevel, return <datetime, instrument>
    181         return df
    182 

d:\miniconda3\envs\pytorch\lib\site-packages\pandas\core\frame.py in swaplevel(self, i, j, axis)
   6798 
   6799         if not isinstance(result._get_axis(axis), MultiIndex):  # pragma: no cover
-> 6800             raise TypeError("Can only swap levels on a hierarchical axis.")
   6801 
   6802         if axis == 0:

TypeError: Can only swap levels on a hierarchical axis.

**Comment by zhupr** [comment]
@panshuaiyin Hi,
Add `print` here: https://github.com/microsoft/qlib/blob/main/qlib/data/dataset/loader.py#L179
```python
if self.swap_level:
    print(df.head())
    print(df.index)
    df = df.swaplevel().sort_index()  # NOTE: if swaplevel, return <datetime, instrument>
```
then post the print results.

What is your version of `pandas`

**Comment by panshuaiyin** [comment]
print的输出如下：
Empty DataFrame
Columns: [KMID, KLEN, KMID2, KUP, KUP2, KLOW, KLOW2, KSFT, KSFT2, OPEN0, HIGH0, LOW0, VWAP0, ROC5, ROC10, ROC20, ROC30, ROC60, MA5, MA10, MA20, MA30, MA60, STD5, STD10, STD20, STD30, STD60, BETA5, BETA10, BETA20, BETA30, BETA60, RSQR5, RSQR10, RSQR20, RSQR30, RSQR60, RESI5, RESI10, RESI20, RESI30, RESI60, MAX5, MAX10, MAX20, MAX30, MAX60, MIN5, MIN10, MIN20, MIN30, MIN60, QTLU5, QTLU10, QTLU20, QTLU30, QTLU60, QTLD5, QTLD10, QTLD20, QTLD30, QTLD60, RANK5, RANK10, RANK20, RANK30, RANK60, RSV5, RSV10, RSV20, RSV30, RSV60, IMAX5, IMAX10, IMAX20, IMAX30, IMAX60, IMIN5, IMIN10, IMIN20, IMIN30, IMIN60, IMXD5, IMXD10, IMXD20, IMXD30, IMXD60, CORR5, CORR10, CORR20, CORR30, CORR60, CORD5, CORD10, CORD20, CORD30, CORD60, CNTP5, CNTP10, ...]
Index: []

[0 rows x 158 columns]
Index([], dtype='object')

pandas的版本为1.0.3

**Comment by zhupr** [comment]
@panshuaiyin 
It doesn't look like it's getting the data, so try it:
```python
import qlib
from qlib.data import D
qlib.init(provider_uri=<qlib data dir>, expression_cache=None, dataset_cache=None)
if __name__ == "__main__":
    df = D.features(D.instruments(instruments), ["$close", "$open", "$high", "$low", "$volume", "$change"], freq="month")
    print(df.head())
```

**Comment by panshuaiyin** [comment]
输出结果如下：
Empty DataFrame
Columns: [$close, $open, $high, $low, $volume, $change]
Index: []

**Comment by zhupr** [comment]
Is there no `month` data?
What kind of raw data do you have and how do you `dump` the data

**Comment by panshuaiyin** [comment]
qlib数据的文件结构如下，不知道对解决问题有没有帮助：
calendars
--day.txt
--mon.txt
features
--hk0001
----change.day.bin
----close.day.bin
----factor.day.bin
----high.day.bin
----low.day.bin
----money.day.bin
----open.day.bin
----volume.day.bin
----vwap.day.bin
--hk0002
--hk0003
--……
--hkhsi
instruments
--all.txt

**Comment by zhupr** [comment]
Looking at the structure of the file, you have the "day" data, which is used according to the "month" data.
To use the "month" data you should do this:
- capture the "month" data or convert the "day" csv data to "month" csv data (`month_csv_data`)
- use `"dump_bin.py --csv_path month_csv_data --qlib_dir month_qlib_data <other parameters>"` to dump a new month data
- use the new data: `month_qlib_data`

**Comment by panshuaiyin** [comment]
我这么做过，把日频csv数据文件取每月第一个交易日转换为月频csv数据文件，然后使用dump_bin.py，后面的参数除了数据所在位置的路径以外，其他参数都一样，但是转换为qlib类型的数据后，文件名仍然是xxx.day.bin，并且上述问题依然会出现

**Comment by panshuaiyin** [comment]
我的网连github不太稳定，上传不了图片，而且经常断开，能加一下您微信或qq或其他通讯工具吗？

**Comment by panshuaiyin** [comment]
想直接传截图

**Comment by you-n-g** [comment]
Is gitter OK to you?
@zhupr  Could chat you on gitter ?
https://gitter.im/Microsoft/qlib?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by you-n-g** [comment]
@panshuaiyin 
We encourage public discussion instead of private discussion.
Because we hope the answered questions could benefit others.

**Comment by panshuaiyin** [comment]
刚刚试了一下gitter，可以传截图，在gitter里的对话是从
“Is there no month data?
What kind of raw data do you have and how do you dump the data”
这里继续的

**Comment by you-n-g** [comment]
Paste the chat link here https://gitter.im/Microsoft/qlib?at=610a2a2c4bfde341d94057eb
in case of other users are looking for solution of this issue
