### ISSUE TITLE
confusions about dump_bin.py

### ISSUE THREAD

**Issue by zymmatt** [microsoft/qlib#535]
In  https://github.com/microsoft/qlib/blob/main/scripts/dump_bin.py#L352   and
https://github.com/microsoft/qlib/blob/main/scripts/dump_bin.py#L315
There are two classes that I don't know how to use, class DumpDataFix(DumpDataAll), and  class DumpDataUpdate(DumpDataBase), can anyone explain it for me? I am looking for some  ways to update dump data, but did not succeed till now.

**Comment by wangze586** [comment]
![image](https://user-images.githubusercontent.com/55927141/127482060-373575f6-0a0b-4538-87e3-4ebed600a6aa.png)
me too when i update , it always wrong

**Comment by zhupr** [comment]
The dump has three classes:
- `DumpDataAll`: dump all data
  - Dump all data from `csv_pat`h into `qlib_dir`, which will **`overwrite all`** data (calendars/instruments/features)
- `DumpDataFix`: adding a *`new field`*, *`symbol`*, *`rewriting of an existing field`*
  - Dumping data from `csv_path` into `qlib_dir` will **`overwrite existing`** features data; if ***new fields*** are added, they will be added according to `qlib_dir/calendars/<freq>.txt` and the `qlib_dir/instruments/all. txt` file, **without modifying existing data**
 - `DumpDataUpdate`: append new data to existing data
    - **append** the data from `csv_path` to the existing data
  - For example:
    - Data already available
    ```
    # Data already available:
        qlib_dir/
            calendars/
                day.txt: [2021-06-01, 2021-06-02]
            instruments/
                all.txt: 
                    SH600000    2021-06-01  2021-06-02
            features/
                SH600000/
                    close.day.bin: [1, 2]
    ```
    -  csv_path
    ```                 
    # csv_path:
        SH600000.txt
            datetime    symbol  close open
            2021-06-01 SH600000  1.1   1
            2021-06-02 SH600000  1.2   1.1
            2021-06-03 SH600000  1.3   1.2
        SH600001.txt
            datetime    symbol  close open
            2021-06-01 SH600001  2.1   2
            2021-06-02 SH600001  2.2   2.1
            2021-06-03 SH600001  2.3   2.2
    ```
    - After DumpDataFix
    ```
    # After DumpDataFix:
      qlib_dir/
          calendars/
              day.txt: [2021-06-01, 2021-06-02]
          instruments/
              all.txt: 
                  SH600000    2021-06-01  2021-06-02
                  SH600001    2021-06-01  2021-06-02
          features/
              SH600000/
                  close.day.bin: [1.1, 1.2]
                  open.day.bin: [1, 1.1]
              SH600001/
                  close.day.bin: [2.1, 2.2]
                  open.day.bin: [2, 2.1]
    ```
    - After DumpDataUpdate
    ```
    # After DumpDataUpdate:
        qlib_dir/
            calendars/
                day.txt: [2021-06-01, 2021-06-02, 2021-06-03]
            instruments/
                all.txt: 
                    SH600000    2021-06-01  2021-06-03
                    SH600001    2021-06-01  2021-06-03
            features/
                SH600000/
                    close.day.bin: [1, 2, 1.3]
                    open.day.bin: [1.2] # Incomplete data, should be processed again using DumpFix
                SH600001/
                    close.day.bin: [2.3] # Incomplete data, should be processed again using DumpFix
                    open.day.bin: [2.2] # Incomplete data, should be processed again using DumpFix
    ```

**Comment by zhupr** [comment]
@wangze586 Hi, 
Only `numeric fields` (int/float) can be dumped, if they are `non-numeric` (e.g. symbol), you can use `--exlcude_fields` to specify the fields that do not need to be dumped, for example: 
```
# SH600000.csv
      date       symbol  close open     name
      2021-06-01 SH600000  1.1   1       test
      2021-06-02 SH600000  1.2   1.1      test
      2021-06-03 SH600000  1.3   1.2      test
```
`python dump_bin.py dump_all --csv_path xxx --qlib_dir xxx  --exlcude_fields datetime,symbol,name`
or
`python dump_bin.py dump_all --csv_path xxx --qlib_dir xxx  --include_fields close,open`

**Comment by wangze586** [comment]
here is mydata

#SZ000001.csv
date | open | high | low | close | pre_close | change | pct_chg | vol | amount
2021/7/24 | 17.5 | 18.55 | 17.2 | 18.29 | 17.45 | 0.84 | 4.81 | 82161 | 147325.4
2021/7/25 | 18.35 | 18.85 | 18 | 18.06 | 18.29 | -0.23 | -1.26 | 93993 | 173475.2
2021/7/26 | 18.02 | 19.05 | 17.75 | 18.78 | 18.06 | 0.72 | 3.99 | 120222 | 221192.5

I delete non-numeric data , but it still can't be updated
![image](https://user-images.githubusercontent.com/55927141/127611030-fbb05b06-b2e9-41b3-8693-f5846927ec76.png)

**Comment by zhupr** [comment]
@wangze586 
Add parameters `--exclude date`: 
```bash
python dump_bin.py dump_update --csv_path C:/User/wangz/Desktop/run/data --qlib_dir C:/User/wangz/Desktop/run/output/1day --exclude date
```

**Comment by wangze586** [comment]
..........same problem
![image](https://user-images.githubusercontent.com/55927141/127614199-c87dabc4-db70-4c5c-9588-912527591e4c.png)

**Comment by zhupr** [comment]
@wangze586  Sorry, the parameter name is wrong ......
```
python dump_bin.py dump_update --csv_path C:/User/wangz/Desktop/run/data --qlib_dir C:/User/wangz/Desktop/run/output/1day --exclude_fields date

```

**Comment by wangze586** [comment]
--exclude_fields date  I know it's wrong and i also change to correct one , problem still remain the same

**Comment by zhupr** [comment]
@wangze586 
After this line https://github.com/microsoft/qlib/blob/main/scripts/dump_bin.py#L218 add : 
```python
print(_df.dtypes)
print(self.get_dump_fields(_df.columns))
print(self._exclude_fields, self._include_fields)
```
Output the result of these three lines, and see the result

**Comment by wangze586** [comment]
![image](https://user-images.githubusercontent.com/55927141/127617895-d57b3cb1-a094-48de-942f-e6444743c8d7.png)

**Comment by zhupr** [comment]
```
python dump_bin.py dump_update --csv_path C:/User/wangz/Desktop/run/data --qlib_dir C:/User/wangz/Desktop/run/output/1day --exclude_fields date,symbol

```

**Comment by wangze586** [comment]
thank you !!! it works
![image](https://user-images.githubusercontent.com/55927141/127619388-f4513c37-9be9-41c9-a9af-f4203087fc46.png)

**Comment by you-n-g** [comment]
@wangze586 
Would you mind sending a PR to improve the docs(or docstrings) about this Question?
Other users who have similar confusion will be grateful to you :)
Thanks

**Comment by wangze586** [comment]
@you-n-g  
problem seems can be easily solved. just add  "--exclude_fields date,symbol"  , when use "dump_update"

**Comment by aiot-tech** [comment]
well done!
