### ISSUE TITLE
Is there any tools provided to trun the qlib data format to csv format?

### ISSUE THREAD

**Issue by cheng-zi-ya** [microsoft/qlib#54]
## ❓ Questions and Help

Your work helps me a lot. I would like to ask whether these has tools to turn the qlib data format to csv. Since I find it is a good format to use, but sometimes, I may need to trun it to csv to show it to my coworkers who may never use qlib before. I find Converting CSV Format into Qlib Format in your documentation but don't find the opposite.

**Comment by zhupr** [comment]
@cheng-zi-ya 
You can use the following code:

```python
import qlib
from qlib.data import D

qlib.init()
fields = ["$open", "$close", "$high", "$low", "$volume", "$factor", "$change"]
df = D.features(D.instruments("all"), fields)
df.to_csv()

```

**Comment by cheng-zi-ya** [comment]
Got it, thanks!

**Comment by qtbgo** [comment]
Good. If I don't know fields' names in the data, can we get all  fields' names in the data? If so, how?

**Comment by you-n-g** [comment]
Hi,  @qtbgo  Do you mean by getting the `fields` name of  data source in `qlib` ?

**Comment by qtbgo** [comment]
yes

**Comment by you-n-g** [comment]
@qtbgo 
Currently, only `open, close, high, low, volume, money and factor`  is supported in current released public data.

I opened a new issue #141  and we will provide more user friendly interface in the future.

Thanks.
