### ISSUE TITLE
Wrong documentation to "only_tradable"

### ISSUE THREAD

**Issue by ZhangTP1996** [microsoft/qlib#543]
## 📖 Documentation

The documentation to "only_tradable" is wrong in "TopkDropoutStrategy".

![image](https://user-images.githubusercontent.com/28586046/128142925-4faabb9e-f6b0-414b-b178-ed80ba568d33.png)

However, in the code it says:
![image](https://user-images.githubusercontent.com/28586046/128143000-a845360d-cb0b-4e18-b7cf-52b37f1b4525.png)
![image](https://user-images.githubusercontent.com/28586046/128143018-1300b821-6ea0-4f3c-b819-ca70c45a4099.png)

What is more weird, when I set "only_tradable=False", the number of trades and the turnover rate significantly drops, seeming to be contrary to what is written in the code... What happens?

**Comment by you-n-g** [comment]
When "only_tradable=True", the strategy will peek at the information in the short future to avoid untradable stocks.

When "only_tradable=False", the strategy will generate orders without peeking any information in the future, 
so the order generated by the strategies may fail.   Which results in a drop of the number of trades and the turnover rate. 

Thanks

**Comment by ZhangTP1996** [comment]
> When "only_tradable=True", the strategy will peek at the information in the short future to avoid untradable stocks.
> 
> When "only_tradable=False", the strategy will generate orders without peeking any information in the future,
> so the order generated by the strategies may fail. Which results in a drop of the number of trades and the turnover rate.
> 
> Thanks

Thanks for your rapid response! Yet I have another question. What does it mean that the strategies may fail? Does it mean I buy the stocks and then fail to sell it due to suspension? Is there any other reason that may cause the strategies to fail?

**Comment by you-n-g** [comment]
@ZhangTP1996 
Yes.  You are right.
Besides the suspension,  hitting the limit up(down) may cause failure.

**Comment by you-n-g** [comment]
@ZhangTP1996  

If your question is answered, would you mind sending a PR to improve the docs(or docstrings) about this Question?
Other users who have similar confusion will be grateful to you :)
Thanks

**Comment by ZhangTP1996** [comment]
> @ZhangTP1996
> Yes. You are right.
> Besides the suspension, hitting the limit up(down) may cause failure.

I find out that when I set "only_tradable=False", the strategy still generate orders that contain stocks that will hit the limit up which causes strategy failure. However, in real trading, when we execute orders, we are aware which stock hits the limit up (this does not require any future information at the time we buy stocks) and we will continue to buy other stocks (for example, if we are to buy top 10 stocks according to predictions, however the top 10 stocks all hit the limit up, we will try to buy top 11-20 stocks instead of failing the strategy completely). It seems that no matter how I set "only_tradable",  the trading scheme does not align with what we do in real trading.

**Comment by you-n-g** [comment]
@ZhangTP1996 
Will `only_tradable == True` align to what you want to do in real trading? 

The scenario you described contains intraday trading and interday trading.
The `only_tradable == False` is trying to align to the interday trading (the orders can be regarded as produced after close on the day before you executed the order)

**Comment by ZhangTP1996** [comment]
> @ZhangTP1996
> Will `only_tradable == True` align to what you want to do in real trading?
> 
> The scenario you described contains intraday trading and interday trading.
> The `only_tradable == False` is trying to align to the interday trading (the orders can be regarded as produced after close on the day before you executed the order)

I'm not sure how much future information it uses when I set `only_tradable==True`. If the "future information" it uses is what I can know when I execute the orders, then `only_tradable==True` aligns to what I want to do in real trading.
