### ISSUE TITLE
Is it possible to disable multi-process to make debugging easier?

### ISSUE THREAD

**Issue by fuchen** [microsoft/qlib#544]
When customize my own dataset, I need to print some debug values. But due to the multi-process execution, I cannot see these debug values. How can I disable multi-process execution?

**Comment by Anduinnnnnn** [comment]
Please try to modify line 92 in qlib/config.py to qlib.init(kernels=1), which means that the number of processes is set to one. If this does not solve your problem, please refer to https://github.com/microsoft/qlib/issues/477

**Comment by Anduinnnnnn** [comment]
Please try to modify line 92 in qlib/config.py to qlib.init(kernels=1), which means that the number of processes is set to one. If this does not solve your problem, please refer to https://github.com/microsoft/qlib/issues/477
