### ISSUE TITLE
How to avoid to process the features every time run the program?

### ISSUE THREAD

**Issue by Joshuajxy** [microsoft/qlib#548]
Hi,

Every time when I try to run the for a test, prepare dataset will cost a long time, but it does not seem to be necessary
    # model initialization
    model = init_instance_by_config(CSI300_GBDT_TASK["model"])
    dataset = init_instance_by_config(CSI300_GBDT_TASK["dataset"])

I tried to use the following function to dump data to a file, but don't know how to load it,
 dataset.to_pickle(path="dataset.pkl", dump_all=True)

Can you give me some help with how to load a preprocessed dataset from a file?

Thanks
Joshua

**Comment by you-n-g** [comment]
This question is similar to https://github.com/microsoft/qlib/issues/517#event-5125741153
We have already provided related features.

 @zhupr Please help Joshuajxy to answer this question

**Comment by you-n-g** [comment]
https://github.com/microsoft/qlib/blob/main/qlib/utils/__init__.py#L244

You can set the file path directly in the config to load the processed data directly without duplicated pre-processing.

**Comment by panshuaiyin** [comment]
I use the function 'dataset.to_pickle(path="dataset.pkl", dump_all=True)', but it gives me a file which is only 47KB. So it doesn't save the processed data to the 'dataset.pkl'. And I use the function 'dataset = init_instance_by_config("file:///dataset.pkl")'. It returns me the object which can't use the function 'dataset.prepare()'.(will get errors "'Alpha158' object has no attribute '_infer'")

So how could I save and load the processed data?

**Comment by you-n-g** [comment]
@panshuaiyin    
Please try this

```Python
dataset.config(dump_all=True, recursive=True)
dataset.to_pickle(path="dataset.pkl")
```
https://github.com/microsoft/qlib/blob/main/qlib/utils/serial.py#L50

**Comment by panshuaiyin** [comment]
It works. Thanks, you-n-g.
Could you explain the how the parameter 'recursive' influences the instance 'self'? I read the code but don't understand it. If you don't have the time, just ignore me.

**Comment by you-n-g** [comment]
@panshuaiyin 
The related code is here.
https://github.com/microsoft/qlib/blob/main/qlib/utils/serial.py#L71

Because there are nested Serializable objects (`Dataset` and `DataHandler`), `recursive` must be set to influence the behavior fo `DataHandler`

It is a little complicated...

Would you mind sending a PR to improve the docs(or docstrings) about this Question?
Other users who have similar confusion will be grateful to you :)
Thanks

**Comment by panshuaiyin** [comment]
Thanks, I have sent a PR.

**Comment by Joshuajxy** [comment]
Thanks, it works on my side also, adding the code I used here.

    # model initialization
    model = init_instance_by_config(CSI300_GBDT_TASK["model"])
    #dataset = init_instance_by_config(CSI300_GBDT_TASK["dataset"])

    ##=============dump dataset=============

    #dataset.config(dump_all=True, recursive=True)
    #dataset.to_pickle(path="dataset.pkl", dump_all=True)

    ##=============reload dataset=============
    with open("dataset.pkl", "rb") as file_dataset:
        dataset = pickle.load(file_dataset)
