### ISSUE TITLE
How to use the trade date as a feature?

### ISSUE THREAD

**Issue by wuzhe1234** [microsoft/qlib#551]
Is there a specific field expression for "date" or I need to add a column "date" to the provider uri?

**Comment by you-n-g** [comment]
@wuzhe1234 
You can refer to this example.
It is not design for your requirement but I think it will be a good example for you.
Welcome to send PR to implement expression operator   :) 

Thanks

**Comment by wuzhe1234** [comment]
Thanks, I'll look at it!

**Comment by you-n-g** [comment]
@wuzhe1234 
Sorry.  I forgot to paste the link.. 
https://github.com/microsoft/qlib/blob/main/examples/highfreq/highfreq_ops.py#L92
