### ISSUE TITLE
画分层图时出现报错

### ISSUE THREAD

**Issue by panshuaiyin** [microsoft/qlib#563]
## ❓ Questions and Help

在使用qlib.contrib.report.analysis_model.analysis_model_performance._group_return(pred_label)绘制分层图时出现如下报错：

IndexError                                Traceback (most recent call last)
<ipython-input-53-9371a12a3bbc> in <module>
----> 1 fun_res = analysis_model.analysis_model_performance._group_return(pred_label)
      2 fun_res

d:\miniconda3\envs\pytorch\lib\site-packages\pyqlib-0.7.0.99-py3.7-win-amd64.egg\qlib\contrib\report\analysis_model\analysis_model_performance.py in _group_return(pred_label, reverse, N, **kwargs)
     66             cols=2,
     67             print_grid=False,
---> 68             subplot_titles=["long-short", "long-average"],
     69         ),
     70     ).figure

d:\miniconda3\envs\pytorch\lib\site-packages\pyqlib-0.7.0.99-py3.7-win-amd64.egg\qlib\contrib\report\graph.py in __init__(self, df, kind_map, layout, sub_graph_layout, sub_graph_data, subplots_kwargs, **kwargs)
    294             self._init_sub_graph_data()
    295 
--> 296         self._init_figure()
    297 
    298     def _init_sub_graph_data(self):

d:\miniconda3\envs\pytorch\lib\site-packages\pyqlib-0.7.0.99-py3.7-win-amd64.egg\qlib\contrib\report\graph.py in _init_figure(self)
    358                         df=self._df.loc[:, [column_name]],
    359                         name_dict={column_name: temp_name},
--> 360                         graph_kwargs=_graph_kwargs,
    361                     )
    362                 )

d:\miniconda3\envs\pytorch\lib\site-packages\pyqlib-0.7.0.99-py3.7-win-amd64.egg\qlib\contrib\report\graph.py in get_instance_with_graph_parameters(graph_type, **kwargs)
     86             _graph_module = importlib.import_module("qlib.contrib.report.graph")
     87             _graph_class = getattr(_graph_module, graph_type)
---> 88         return _graph_class(**kwargs)
     89 
     90     @staticmethod

d:\miniconda3\envs\pytorch\lib\site-packages\pyqlib-0.7.0.99-py3.7-win-amd64.egg\qlib\contrib\report\graph.py in __init__(self, df, layout, graph_kwargs, name_dict, **kwargs)
     47 
     48         self._init_parameters(**kwargs)
---> 49         self._init_data()
     50 
     51     def _init_data(self):

d:\miniconda3\envs\pytorch\lib\site-packages\pyqlib-0.7.0.99-py3.7-win-amd64.egg\qlib\contrib\report\graph.py in _init_data(self)
     57             raise ValueError("df is empty.")
     58 
---> 59         self.data = self._get_data()
     60 
     61     def _init_parameters(self, **kwargs):

d:\miniconda3\envs\pytorch\lib\site-packages\pyqlib-0.7.0.99-py3.7-win-amd64.egg\qlib\contrib\report\graph.py in _get_data(self)
    163         _data_list = [_t_df[_col] for _col in self._name_dict]
    164         _label_list = list(self._name_dict.values())
--> 165         _fig = create_distplot(_data_list, _label_list, show_rug=False, **self._graph_kwargs)
    166 
    167         return _fig["data"]

d:\miniconda3\envs\pytorch\lib\site-packages\plotly-4.12.0-py3.7.egg\plotly\figure_factory\_distplot.py in create_distplot(hist_data, group_labels, bin_size, curve_type, colors, rug_text, histnorm, show_hist, show_curve, show_rug)
    196             rug_text,
    197             show_hist,
--> 198             show_curve,
    199         ).make_hist()
    200 

d:\miniconda3\envs\pytorch\lib\site-packages\plotly-4.12.0-py3.7.egg\plotly\figure_factory\_distplot.py in make_hist(self)
    341                     start=self.start[index],
    342                     end=self.end[index],
--> 343                     size=self.bin_size[index],
    344                 ),
    345                 opacity=0.7,

IndexError: invalid index to scalar variable.

请问一下应该怎么改呢？

**Comment by panshuaiyin** [comment]
而且还遇到一个迷之情况，就是换了一个模型重新跑，执行qlib.contrib.report.analysis_model.analysis_model_performance._group_return(pred_label)可以画出分层图；
执行qlib.contrib.report.analysis_model.analysis_model_performance._group_return(pred_label.loc['2018'])（取2018年的数据）可以画出分层图；
但是执行qlib.contrib.report.analysis_model.analysis_model_performance._group_return(pred_label.loc['2017'])（取2017年的数据）无法画出分层图，会报错，报错内容和之前一样；
想问一下这是咋回事啊？

**Comment by panshuaiyin** [comment]
[pred_label.csv](https://github.com/microsoft/qlib/files/7004247/pred_label.csv)

**Comment by panshuaiyin** [comment]
这个是迷之情况下的数据，其中第一列和第二列是DataFrame的index

**Comment by zhupr** [comment]
@panshuaiyin 
What are your `pandas` and `numpy` versions, you can run: `python scripts/collect_info.py all`
![image](https://user-images.githubusercontent.com/18660661/129833089-10e6a83b-0c8f-4d25-859f-39d76a7607fb.png)
![image](https://user-images.githubusercontent.com/18660661/129833308-ec1195e3-055b-4ce6-9863-5f26b140eab6.png)

**Comment by panshuaiyin** [comment]
numpy是1.21.2
pandas是1.3.2

**Comment by zhupr** [comment]
@panshuaiyin 
I can't reproduce your mistakes.
You can try the following method: 
  - reinstall `plotly`: `pip install plotly -U`

Identify the cause of the error:
  - If you run it in a `notebook`, run `%debug` in a new cell after the error, then output the relevant variables: `self.bin_size` and `index`
  - Run in another IDE (Pycharm, VSCode), add a breakpoint here(https://github.com/microsoft/qlib/blob/main/qlib/contrib/report/analysis_model/analysis_model_performance.py#L60) and debug

**Comment by panshuaiyin** [comment]
更新plotly版本后能画出分层图了，谢谢zhupr

**Comment by panshuaiyin** [comment]
更新plotly版本后能画出分层图了，谢谢zhupr

**Comment by panshuaiyin** [comment]
因为我当时在装qlib时，给我提醒要装plotly=4.12.0，所以就没装最新的，这里的提醒可能需要更新一下了@zhupr
![image](https://user-images.githubusercontent.com/56989678/129847043-fd25592c-c672-4018-8526-7ccc8e4f2f7e.png)

**Comment by panshuaiyin** [comment]
@zhupr
您好，又出现新的迷惑的问题了，刚刚说能画出分层图似乎不是因为更新了plotly，我直接执行qlib.contrib.report.analysis_model.analysis_model_performance._group_return(pred_label.loc['2017'])还是画不了，但把pred_label导出到本地，再重新导入，再执行qlib.contrib.report.analysis_model.analysis_model_performance._group_return(pred_label.loc['2017'])就可以画了，请问这个能解决吗？

**Comment by zhupr** [comment]
- After an error: run `%debug` in a new cell after the error, then output the relevant variables: `self.bin_size` and `index`
- Compare `pre_label.loc["2017"]` with `pred_label.loc["2017"]` after re-import

**Comment by panshuaiyin** [comment]
@zhupr 
- self.bin_size=0.001116345，index=0

- 我比较了pre_label.loc["2017"]和重新导入后的pred_label.loc["2017"]，两者nan的地方完全相同，不是nan的地方的数值大小相差不到10**-9

**Comment by zhupr** [comment]
@panshuaiyin 
I look at the source code of `plotly`, `self.bin_size` should be `list: [0.001116345]`, maybe` plotly` is not compatible with `np.float32`.
You try changing this line in the code( https://github.com/microsoft/qlib/blob/main/qlib/contrib/report/analysis_model/analysis_model_performance.py#L60) to: 
`_bin_size = float(((t_df.max() - t_df.min()) / 20).min())`

**Comment by panshuaiyin** [comment]
改了后就没有报错了，谢谢zhupr
