### ISSUE TITLE
How to use the gpu version of LightGBM

### ISSUE THREAD

**Issue by wuzhe1234** [microsoft/qlib#564]
I'm using the Double Esemble model of the example which is based on LightGBM, and it will take a lot of time to get the result.

If I install the GPU version of LightGBM following the instruction of the lightgbm website, and will it be automatically be used? Do I need to change some code of the qlib.contrib.model.gbdt.py?

**Comment by you-n-g** [comment]
Qlib doesn't manage the hardware.
It just literally runs the code in the model file.
https://github.com/microsoft/qlib/blob/main/qlib/contrib/model/gbdt.py

**Comment by wuzhe1234** [comment]
> Qlib doesn't manage the hardware.
> It just literally runs the code in the model file.
> https://github.com/microsoft/qlib/blob/main/qlib/contrib/model/gbdt.py

Thank you, I'll read the lightgbm docs to figure out.

**Comment by you-n-g** [comment]
Would you mind sending a PR to improve the docs(or docstrings) about this Question?
(e.g.  give more docs on [this page](https://qlib.readthedocs.io/en/latest/component/model.html))
Other users who have similar confusion will be grateful to you :)
Thanks
