### ISSUE TITLE
想把qrun加入到path中，但没找到qrun在哪

### ISSUE THREAD

**Issue by panshuaiyin** [microsoft/qlib#567]
请问一下qrun在哪个目录下呢

**Comment by Gwill** [comment]
你用 pip 安装以后就会自动在 path 里创建 qrun

**Comment by panshuaiyin** [comment]
但是我不是用pip安装的，我当时是下载下来后用python setup.py install安装的

**Comment by you-n-g** [comment]
@panshuaiyin  一般会在你conda环境目录的 bin 子目录下。  在linux下你可以直接通过 `which qrun` 查看

**Comment by panshuaiyin** [comment]
看到了，谢谢you-n-g
