### ISSUE TITLE
about rolling_oneline_management

### ISSUE THREAD

**Issue by yieldbook** [microsoft/qlib#568]
## ❓ Questions and Help
I used OnlineManager.get_signal() to get the signal for next trade date, but what I really want is the buy/sell list of stocks. Is there any way to generate the list? Or I have to do that by myself?

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

**Comment by you-n-g** [comment]
@yieldbook   this requires an online portfolio management module.

We have a portfolio management module, but it is not online.

The trading module is under refactoring which considers online portfolio management.
It is under development  https://github.com/microsoft/qlib/pull/438 
Please stay tuned.

Thanks
