### ISSUE TITLE
在PortAnaRecord().generate()函数上卡死

### ISSUE THREAD

**Issue by panshuaiyin** [microsoft/qlib#570]
在vscode的终端里运行到
`with R.start(experiment_name="backtest_analysis"):
    recorder = R.get_recorder(recorder_id='71ea843624ce4eb5b597b26edc47d8b2', experiment_name="train_model")
    model = recorder.load_object("trained_model")

    # prediction
    recorder = R.get_recorder()
    ba_rid = recorder.id
    R.log_params(experiment_name='backtest_analysis',recorder_id=ba_rid)
    sr = SignalRecord(model, dataset, recorder)
    sr.generate()

    # backtest & analysis
    sar = SigAnaRecord(recorder, ana_long_short=True, ann_scaler=252, label_col=0)
    sar.generate()
    par = PortAnaRecord(recorder, port_analysis_config)
    par.generate()`
电脑会卡死，在任务管理器里或者调试模式下都能观察到出现很多python进程，占用大量内存和cpu，最终导致不得不结束程序，无法观察到报错。
但把代码复制到jupyter notebook里运行就什么事都没有，顺利运行。
通过注释代码反复运行可以锁定问题出在par.generate（）这行，但无法继续确定具体问题出在哪了，请问一下这是怎么回事呢？

**Comment by you-n-g** [comment]
@panshuaiyin  
1. 你的系统环境是什么？https://github.com/microsoft/qlib/blob/main/scripts/collect_info.py
2. 你卡死的时候跑的完整脚本能发送一下吗？

**Comment by panshuaiyin** [comment]
系统环境如下：
Windows
AMD64
Windows-10-10.0.19041-SP0
10.0.19041

Python version: 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]

Qlib version: 0.7.0.99
numpy==1.21.2
pandas==1.3.2
scipy==1.7.1
requests==2.26.0
sacred==0.8.2
python-socketio==5.4.0
redis==3.5.3
python-redis-lock==3.7.0
schedule==1.1.0
cvxpy==1.0.21
hyperopt==0.1.1
fire==0.4.0
statsmodels==0.12.2
xlrd==2.0.1
plotly==5.2.1
matplotlib==3.1.3
tables==3.6.1
pyyaml==5.4.1
mlflow==1.19.0
tqdm==4.62.1
loguru==0.5.3
lightgbm==3.2.1
tornado==6.1
joblib==1.0.1
fire==0.4.0
ruamel.yaml==0.17.10

**Comment by you-n-g** [comment]
你可以看看是不是和这个问题相关
https://qlib.readthedocs.io/en/latest/FAQ/FAQ.html#runtimeerror-an-attempt-has-been-made-to-start-a-new-process-before-the-current-process-has-finished-its-bootstrapping-phase

**Comment by panshuaiyin** [comment]
确实相关，我加上if __name__ == ‘__main__’后就没问题了，而且通过调试定位程序卡死时运行的最后一条语句是data.py里DatasetProvider.dataset_processor（）函数里的
if C.maxtasksperchild is None:
    p = Pool(processes=workers)
else:
    p = Pool(processes=workers, maxtasksperchild=C.maxtasksperchild)
也确实和多线程相关，感觉这个问题和解决方式都有点迷惑，
总之谢谢您了，you-n-g

**Comment by panshuaiyin** [comment]
确实相关，我加上if name == ‘main’后就没问题了，而且通过调试定位程序卡死时运行的最后一条语句是data.py里的https://github.com/microsoft/qlib/blob/6608a40965cb824269fea637c8a6be177994b523/qlib/data/data.py#L446-L449
```
        if C.maxtasksperchild is None:
            p = Pool(processes=workers)
        else:
            p = Pool(processes=workers, maxtasksperchild=C.maxtasksperchild)
```
也确实和多线程相关，感觉这个问题和解决方式都有点迷惑，
总之谢谢您了，you-n-g

**Comment by panshuaiyin** [comment]
确实相关，我加上if name == ‘main’后就没问题了，而且通过调试定位程序卡死时运行的最后一条语句是data.py里的
https://github.com/microsoft/qlib/blob/6608a40965cb824269fea637c8a6be177994b523/qlib/data/data.py#L446-L449
也确实和多线程相关，感觉这个问题和解决方式都有点迷惑，
总之谢谢您了，you-n-g
