### ISSUE TITLE
Wrapper class and alias

### ISSUE THREAD

**Issue by Mete-ora** [microsoft/qlib#573]
## ❓ Questions and Help
![1629701542(1)](https://user-images.githubusercontent.com/57750681/130405607-bc667931-268c-40a9-96ab-38b87aaa5af2.png)
![1629701587(1)](https://user-images.githubusercontent.com/57750681/130405624-74a50799-32d9-4649-8375-2de30f177e2e.png)
How to explain the structure  D: BaseProviderWrapper = Wrapper()

**Comment by you-n-g** [comment]
`Wrapper()` is a wrapper for the inner object. 
With it, users could replace the inner object without modifying the variable references to D.
