### ISSUE TITLE
did you open source for all code?

### ISSUE THREAD

**Issue by nickhuangxinyu** [microsoft/qlib#58]
i found estimator is just a binary executable file, does this open sourced?

**Comment by you-n-g** [comment]
All the code are released as opensource.
estimator  is automatically generated by python `https://github.com/microsoft/qlib/blob/main/setup.py#L100`
The source code is [here](https://github.com/microsoft/qlib/blob/main/qlib/contrib/estimator/launcher.py)

**Comment by nickhuangxinyu** [comment]
thanks.

This is a masterpiece!!!
