### ISSUE TITLE
[SH6000000 ] the source stock data looks different  from Yahoo Finance.

### ISSUE THREAD

**Issue by KaiZheng2020** [microsoft/qlib#590]
Qlib:

![image](https://user-images.githubusercontent.com/54108006/132711091-ddf18470-361e-495c-8b28-0e77acfc3b12.png)

Yahoo Finance: 
https://finance.yahoo.com/quote/600000.SS/history?period1=1546300800&period2=1548979200&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true

![image](https://user-images.githubusercontent.com/54108006/132710748-6a6b7da2-7c28-4b9a-abfd-128e0e701966.png)

**Comment by zhupr** [comment]
@KaiZheng2020 Hi,
qlib_data(`from get_data.py`) has been `adjusted` for Yahoo Finance, two steps of adjusted:
1. use `ajdclose`: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/yahoo/collector.py#L396
```python
factor = ajdclose / close
open = open * factor
...
volume = volume / factor
```
2. adjusted according to the `first close` of each symbol: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/yahoo/collector.py#L432
```python
first_close = get_first_close(df) # https://github.com/microsoft/qlib/blob/main/scripts/data_collector/yahoo/collector.py#L421

close = close / first_close
open = open / first_close
...
volume = volume * first_close
```

You can "`normalize`" the data as follows: https://github.com/microsoft/qlib/tree/main/scripts/data_collector/yahoo#collector-yahoofinance-data-to-qlib
`python scripts/data_collector/yahoo/collector.py normalize_data --source_dir <data dir> --normalize_dir <save dir> --max_workers 16`

**Comment by KaiZheng2020** [comment]
I use this script: GetData().qlib_data(target_dir=provoder_uri, region=REG_CN) to download the data, and find that it is different.

**Comment by zhupr** [comment]
"`GetData().qlib_data(target_dir=provoder_uri, region=REG_CN)`" is normalized: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/yahoo/collector.py#L380

**Comment by KaiZheng2020** [comment]
OK, thanks!

**Comment by TompaBay** [comment]
> ```python
> pen / fir
> ```

Hi, may I ask will the second adjustment, i.e. divide over first close, affect the calculation of the factor? Or the factor is always adjprice/price? I check the data and feel like it doesn't corresponds to the calculation. Thx!

**Comment by you-n-g** [comment]
> the second adjustment, i.e. divide over first close, affect the calculation of the factor?
Yes, it will affect the factor.

 >  Or the factor is always adjprice/price?
Yes.

**Comment by luxiaolei** [comment]
> [@KaiZheng2020](https://github.com/KaiZheng2020) Hi, qlib_data(`from get_data.py`) has been `adjusted` for Yahoo Finance, two steps of adjusted:
> 
> 1. use `ajdclose`: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/yahoo/collector.py#L396
> 
> factor = ajdclose / close
> open = open * factor
> ...
> volume = volume / factor
>  2. adjusted according to the `first close` of each symbol: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/yahoo/collector.py#L432
> 
> first_close = get_first_close(df) # https://github.com/microsoft/qlib/blob/main/scripts/data_collector/yahoo/collector.py#L421
> 
> close = close / first_close
> open = open / first_close
> ...
> volume = volume * first_close
> You can "`normalize`" the data as follows: https://github.com/microsoft/qlib/tree/main/scripts/data_collector/yahoo#collector-yahoofinance-data-to-qlib `python scripts/data_collector/yahoo/collector.py normalize_data --source_dir <data dir> --normalize_dir <save dir> --max_workers 16`

layout the equation, we got: 

`qlibclose = ajdclose / firstclose` 

the `close` is cancelled out. 

Which makes the statement in document that:

    Users can leverage $factor to get the original trading price (e.g. $close / $factor to get the original close price).

is wrong.
