### ISSUE TITLE
 Fix bugs  Add new feature  Update documentation

### ISSUE THREAD

**Issue by Sumantsahu9888** [microsoft/qlib#593]
## To Reproduce

1.
1.
1.

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version:
 - Python version:
 - OS (`Windows`, `Linux`, `MacOS`):
 - Commit number (optional, please provide it if you are using the dev version):

**Comment by you-n-g** [comment]
@Sumantsahu9888  Sorry I can't understand this issue.
Could you give more details about this issue?

**Comment by Sumantsahu9888** [comment]
Use label

**Comment by Sumantsahu9888** [comment]
And nested tag use

**Comment by Sumantsahu9888** [comment]
I think you can understand
