### ISSUE TITLE
How to add market data?

### ISSUE THREAD

**Issue by jmrichardson** [microsoft/qlib#601]
Hi, I am using this command to convert CSV data:

`python scripts/dump_bin.py dump_all --csv_path data/daily/csv --qlib_dir data/daily --date_field_name date`

It updates the all.txt in instruments folder but doesn't create/update the market files (ie sp500.txt).  How are the market files generated?  Is it possible to use folder name for csv data to "imply" appropriate market or some other method?

**Comment by jmrichardson** [comment]
Hi, I found it:

`python scripts/data_collector/us_index/collector.py --index_name SP500 --qlib_dir data/daily --method parse_instruments`

Great lib!

**Comment by you-n-g** [comment]
@jmrichardson 
Would you mind sending a PR to improve the docs(or docstrings) about this Question?
Other users who have similar confusion will be grateful to you :)
Thanks

**Comment by jmrichardson** [comment]
I will help with documentation.  I want to learn the lib first so that I have a better understanding of how things work.

**Comment by you-n-g** [comment]
@jmrichardson

Thanks so much!
