### ISSUE TITLE
Enable caching without Redis?

### ISSUE THREAD

**Issue by jmrichardson** [microsoft/qlib#603]
Hi, I am running windows 10 and not able to run Redis.  Currently, all of the processors need to execute and fields need to be generated when loading Alpha158 each time.  I am assuming that caching will prevent this and store the calculated data on disk.  Is there a way/example of doing this?  I have searched the documentation and examples and can't find a way to enable without redis.  Thank you.

**Comment by zhupr** [comment]
@jmrichardson
Fix `SimpleDatasetCache`: https://github.com/microsoft/qlib/pull/604.

 `SimpleDatasetCache` can be used: `qlib.init(<other parameters>, dataset_cache="SimpleDatasetCache")`
