### ISSUE TITLE
Recommended way to add custom indicators?

### ISSUE THREAD

**Issue by jmrichardson** [microsoft/qlib#607]
Hi, 

I would like to add technical analysis features to the data for which are not already included.  Looking at the documentation, there is a ElemOperator single feature expressions and I believe the PairOperator for 2.  However, is there a recommended way to add an indicator that has OHLCV (up to 5 features)?  Or should a custom processor be used?  Or should this just be done outside of qlib?  Thanks for the advice.

**Comment by jmrichardson** [comment]
I went the custom processor route

**Comment by you-n-g** [comment]
@jmrichardson 
Qlib is very flexible. There are a lot of ways to implement such a feature.

Here is an example configuration that exposes a place to write his own indicator based on the basic OHLCV data and the expression Engine of Qlib.
https://github.com/microsoft/qlib/blob/main/examples/benchmarks/LightGBM/workflow_config_lightgbm_configurable_dataset.yaml#L15

**Comment by jmrichardson** [comment]
Hi @you-n-g ,  yes Qlib is very nice and flexible especially with the the expression engine.  Thanks for sharing the link.  I am currently using talib for some of the indicators I don't know how to write mathematically (using expressions).  Thank you for this great library and feedback!

**Comment by Wangwuyi123** [comment]
@jmrichardson
Qlib has explicit doc for how to write mathematically .
https://qlib.readthedocs.io/en/latest/advanced/alpha.html#introduction

Please tell me why you didn't see it,It allows us to improve.

Thanks
