### ISSUE TITLE
'TSDataSampler' object has no attribute 'data'

### ISSUE THREAD

**Issue by jingmouren** [microsoft/qlib#614]
What's the matter with the following problem?
pytorch_gats_ts.py", line 257, in fit
    sampler_train = DailyBatchSampler(dl_train)
  File "python3.7/site-packages/qlib/contrib/model/pytorch_gats_ts.py", line 32, in __init__
    self.data = self.data_source.data.loc[self.data_source.get_index()]
AttributeError: 'TSDataSampler' object has no attribute 'data'

**Comment by you-n-g** [comment]
Please update your qlib to the latest version.
It is different from your current version now. 
https://github.com/microsoft/qlib/blob/main/qlib/contrib/model/pytorch_gats_ts.py#L33
