### ISSUE TITLE
backtest too slow

### ISSUE THREAD

**Issue by yieldbook** [microsoft/qlib#617]
## ❓ Questions and Help
It takes about an hour to finish the backtest of the CSI500 universe. Is there any possibility to speed up the backtest process? 
Thank you!

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

**Comment by you-n-g** [comment]
@yieldbook 
We are developing a new version of backtesting. https://github.com/microsoft/qlib/pull/438
It will be much faster than the old one.
Please stay tuned for its release.
It will be before October

Thanks

**Comment by yieldbook** [comment]
Great! Looking forward to that!
