### ISSUE TITLE
TypeError: qlib_data() got an unexpected keyword argument 'exists_skip'

### ISSUE THREAD

**Issue by niurencheng** [microsoft/qlib#621]
(Rl) D:\pythonProject\qlib>python examples/run_all_model.py --models=lightgbm
Traceback (most recent call last):
File "examples/run_all_model.py", line 39, in
GetData().qlib_data(target_dir=provider_uri, region=REG_CN, exists_skip=True)
TypeError: qlib_data() got an unexpected keyword argument 'exists_skip'

thanks,

**Comment by zhupr** [comment]
@niurencheng Hi,
Are you using the latest `qlib` code：https://github.com/microsoft/qlib/blob/main/qlib/tests/data.py#L116
> cd tests
> is the link in line `116` of `data.py` the same as above

It is recommended to update to the latest code
