### ISSUE TITLE
How can I use multiple rule expressions to filter the instruments?

### ISSUE THREAD

**Issue by WizardandCat** [microsoft/qlib#637]
## ❓ How can I use multiple rule expressions to filter the instruments?

For example, if I want to keep stocks that satisfy three conditions at the same time:
1. 1 < $close < 100
2. ($high + $low) / $open < 1.05
3. 10000 < $volume < 100000

What should I write in the "rule_expression"?

`expressionDFilter = ExpressionDFilter(rule_expression=???)`

Thank you!

**Comment by you-n-g** [comment]
@WizardandCat 
Would you mind sending a PR to improve the docs(or docstrings) about this Question?
Other users who have similar confusion will be grateful to you :)
Thanks

**Comment by WizardandCat** [comment]
> @WizardandCat
> Would you mind sending a PR to improve the docs(or docstrings) about this Question?
> Other users who have similar confusion will be grateful to you :)
> Thanks

I'm glad to do so! Please give me some time as I'm a beginner of Github and haven't sent a PR before and I'm occupied with schools' finals this week. I will learn how to send a PR later :)
