### ISSUE TITLE
anaconda(3.8) + qlib，UnicodeEncodeError: 'ascii' codec can't encode characters in position 18-20: ordinal not in range(128)

### ISSUE THREAD

**Issue by ailabx** [microsoft/qlib#648]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 18-20: ordinal not in range(128)

I have successfully installed pyqlib， and run workflow.py on pycharm.
It doweloaded data.

then raises exception:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 18-20: ordinal not in range(128)

![image](https://user-images.githubusercontent.com/26896592/137436179-2d1e71f5-9b8e-4337-bb35-86b52223dea1.png)

**Comment by Wangwuyi123** [comment]
@ailabx UnicodeEncodeError: 'ascii' codec can't encode characters in position 18-20: ordinal not in range(128)
This error is Python3 does not use UTF8 correctly
you can use `PYTHONIOENCODING=utf-8 python workflow.py`

**Comment by Liumh-01** [comment]
请问解决了吗 我也遇到相同问题
