### ISSUE TITLE
Why the results of new backtest and old backtest are so different?

### ISSUE THREAD

**Issue by yieldbook** [microsoft/qlib#652]
I set the thresh to 0 in old backtest and keep other parameters the same as those in the new backtest, but the results are so different from each other that I can't believe they are generated from the same pred_score.  Any reasons for that? Which one is correct?

**Comment by you-n-g** [comment]
@yieldbook we are creating docs for the new version of backtesting.
Please check out [the commit](https://github.com/microsoft/qlib/commit/22ff8fdc4467ed743e11532ebf0dc95786ffd067) for future details.
Thanks
