### ISSUE TITLE
meaning of "score" in the example

### ISSUE THREAD

**Issue by kurucan** [microsoft/qlib#662]
What is the meaning of score? 

is it expected stock returns ?

**Comment by you-n-g** [comment]
I added some descriptions about the score just now.
Please check it out to see if it answers your question?

https://github.com/microsoft/qlib/blob/main/examples/benchmarks/README.md#benchmarks-performance

**Comment by kurucan** [comment]
many thanks, we are creating one single model for the whole market, right?

**Comment by you-n-g** [comment]
Yes.
