### ISSUE TITLE
kfold cross validation

### ISSUE THREAD

**Issue by kurucan** [microsoft/qlib#665]
is it possible to do k-fold cross validation?

**Comment by you-n-g** [comment]
[ Cross-validation on a rolling basis ](https://medium.com/@soumyachess1496/cross-validation-in-time-series-566ae4981ce4) is a more common practice in time-series data

Here is [an example](https://github.com/microsoft/qlib/blob/main/examples/model_rolling/task_manager_rolling.py) you can base on. Perhaps you need some future modification.
