### ISSUE TITLE
Append data to existing dataset without go through dump csv

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#667]
Suppose I have set up a `data_handler_config` and have a `dataset` by `init_instance_by_config`. Now I would like to append the data for next day onto this `dataset`, without go through the dump_update csv and rebuild the whole `dataset`. How can I do this? Thanks for the help.

**Comment by zhupr** [comment]
@2young-2simple-sometimes-naive Hi, try using `cache`:
- add parameters to `qlib.init`: `qlib.init(dataset_cache="DiskDatasetCache", expression_cache="DiskExpressionCache", redis_host=<host>, redis_port=<redis port>, xxx)`
- append the `new data` to `qlib_dir`: https://github.com/microsoft/qlib/blob/main/scripts/dump_bin.py
- update cache: https://github.com/microsoft/qlib-server/blob/main/scripts/update_cache.py

**Comment by 2young-2simple-sometimes-naive** [comment]
> * dataset_cache="DiskDatasetCache", expression_cache="DiskExpressionCache",

How to use cache on provider_uri, without redis?

**Comment by you-n-g** [comment]
Hi, 
Currently, the two types of cache implement read and  write lock based on Redis
https://github.com/microsoft/qlib/blob/main/qlib/data/cache.py#L650

You can remove the lock (and Redis can also be removed) if you are sure there is no risk of concurrent writing.
