### ISSUE TITLE
请问qlib的回测功能能否像优矿、聚宽、米筐那些量化平台的回测引擎一样呢？

### ISSUE THREAD

**Issue by wbzhang233** [microsoft/qlib#671]
## ❓ Questions and Help
尊敬的作者：
    您好！我看作者是国人，所以就用国语向您提问了。我很好奇qlib提供的回测功能是不是像优矿、聚宽那些平台一样，会产生交易指令，然后下单，最后输出更多、更详实的回测结果报告。
    我认为似乎不行。很期待能得到您的回复。

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

**Comment by you-n-g** [comment]
Qlib的回测侧重点会不一样；
Qlib 在设计和开发时会优先考虑支持AI算法的集成和迭代， 所以现在版本更关注这部分功能。 
与实际交易的对接现在还没有集成到Qlib中。

**Comment by TompaBay** [comment]
您好，不知道是否可以透露，具体在回测中在选择交易量和价格是如何选择的呢，例如数据是以天为单位的话，qlib在回测时如何选择股价和交易量呢？谢谢！
