### ISSUE TITLE
some need 

### ISSUE THREAD

**Issue by hufeide** [microsoft/qlib#672]
我用这个项目的时候，发现一些基础的功能没有例子，例如使用权重回测、对单个品种使用交叉信号回测，在生成自己指标数据的时候，例子也很少，整个回测框架都已经做好了，这些简单的功能，能不能以更多的例子给出，并且网上可参考的文章太少了，对于框架不熟悉的读者说，可能不需要非常复杂的人工智能算法，而是需要可参考的基础的实例，你们能给出一些最基础的功能例子吗？例如我提到的，资产优化方面生成权重后并回测的整个过程，单指数择时的回测过程。

**Comment by you-n-g** [comment]
多谢关注 ， 我们会尽量补充现在还缺的例子， 也欢迎大家一起来补充。
