### ISSUE TITLE
Question over installing from source

### ISSUE THREAD

**Issue by TompaBay** [microsoft/qlib#675]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

As I saw from some issues before, when I install from source so I can adjust models from local qlib folder, it doesn't allow me to import qlib packages with the following information:
Do not import qlib package in the repository directory in case of importing qlib from . without compiling

Then what should I do if I want to adjust the model? Thanks!

**Comment by zhupr** [comment]
@TompaBay Hi，
You can refer to this solution：https://qlib.readthedocs.io/en/latest/FAQ/FAQ.html#modulenotfounderror-no-module-named-qlib-data-libs-rolling
> If the error occurs when importing `qlib` package with command `python` ,  users need to change the running directory to ensure that the script does not run in the project directory.

**Comment by TompaBay** [comment]
I think there is bug due to the difference between install from source and pip. When I installed from pip, everything is fine.  But when I installed from source, for same configuration file, I'll get bug from ops.py saying two np arrays for np.divide have different dimension. I wonder if I wanted to change the given models, is there any method that I can change it even though I installed from pip? Thanks!

**Comment by zhupr** [comment]
> I think there is bug due to the difference between install from source and pip. When I installed from pip, everything is fine. But when I installed from source, for same configuration file, I'll get bug from ops.py saying two np arrays for np.divide have different dimension. I wonder if I wanted to change the given models, is there any method that I can change it even though I installed from pip? Thanks!

Hi, already fixed in this PR:https://github.com/microsoft/qlib/pull/685
Thank you for your feedback!
