### ISSUE TITLE
how to run python file 

### ISSUE THREAD

**Issue by hufeide** [microsoft/qlib#680]
how to run python file "qlib/tests/backtest/test_file_strategy.py"?
i get:
usage: pydevconsole.py [-h] [-v] [-q] [--locals] [-f] [-c] [-b]
                       [-k TESTNAMEPATTERNS]
                       [tests [tests ...]]

**Comment by zhupr** [comment]
@hufeide Hi，
`python` or `pytest`: 
- `python qlib/tests/backtest/test_file_strategy.py` 
- `pytest qlib/tests/backtest/test_file_strategy.py`
