### ISSUE TITLE
Dataloading broke with recent commits

### ISSUE THREAD

**Issue by AtlantixJJ** [microsoft/qlib#681]
## 🐛 Bug Description

No matter running which model, I get the following error:

```
......
[25866:MainThread](2021-11-11 17:44:49,303) WARNING - qlib.ops - [ops.py:329]
- Loading SH601155: Div($vwap,$close); np.divide(series_left, series_right), T
he length of series_left and series_right is different: (0, 1135), series_left is $vwap, series_right is $close. Please check the data
[25881:MainThread](2021-11-11 17:44:49,365) WARNING - qlib.ops - [ops.py:329]
- Loading SH601162: Div($vwap,$close); np.divide(series_left, series_right), T
he length of series_left and series_right is different: (0, 426), series_left is $vwap, series_right is $close. Please check the data
[25868:MainThread](2021-11-11 17:44:49,381) WARNING - qlib.ops - [ops.py:329]
- Loading SH601166: Div($vwap,$close); np.divide(series_left, series_right), T
he length of series_left and series_right is different: (0, 3061), series_left is $vwap, series_right is $close. Please check the data
......
```

I install from the source the latest version of qlib. I used commit id 01bdf6c1b11cb3bbeb6deef1de4d7c4a88fea1d6, but this problem actually started to exist after a certain update after commit 2461575d30e334ce1b380f90cafa325e752228dc in Sep. 9, because this version of qlib worked well.

## To Reproduce

1. git clone the latest version of qlib and run `python setup.py build_ext --inplace`.
2. run `ipython scripts/get_data.py -- qlib_data --target_dir <some dir> --region cn`
3. run `ipython qlib/workflow/cli.py -- examples/benchmarks/Linear/workflow_config_linear_Alpha158.yaml`.

## Expected Behavior

These steps should have worked out.

## Environment

 - Qlib version: commit 01bdf6c1b11cb3bbeb6deef1de4d7c4a88fea1d6
 - Python version: 3.8
 - OS (`Windows`, `Linux`, `MacOS`): Linux
 - Commit number (optional, please provide it if you are using the dev version):

## Additional Notes

Thank you and look forward to your reply.

**Comment by TompaBay** [comment]
Same issue here, work when installed from pip but got this issue when installed from source.

**Comment by zhupr** [comment]
Hi, already fixed in this PR:#685

**Comment by kurucan** [comment]
same issue here

**Comment by zhupr** [comment]
> 

Does the same problem occur when using the latest `qlib` code?
