### ISSUE TITLE
Why label is calculated on the day after tomorrow?

### ISSUE THREAD

**Issue by AtlantixJJ** [microsoft/qlib#682]
## ❓ Questions and Help

In most of your config files, the label is set to be `label: ["Ref($close, -2) / Ref($close, -1) - 1"]`. As I understand, this means the ratio of increase of the day after tomorrow over tomorrow.

My question is: why don't you use the ratio of increase of tomorrow directly? In other words, set `label: ["Ref($close, -1) / $close - 1"]`?

My guess is that the current prediction algorithms are assumed to be offline, which means the algorithm will run after today's information is fully collected, and decide what to buy or sell tomorrow. And the order executor assumes that the order is going to be executed using the close price of tomorrow, therefore, predicting the increase of the day after tomorrow is a direct prediction of profit.

Is my understanding correct? Thank you.

**Comment by you-n-g** [comment]
Yes. You are absolutely right.

https://qlib.readthedocs.io/en/latest/component/data.html#example
![image](https://user-images.githubusercontent.com/465606/141610725-9d53984e-f2f0-4b9b-9b5b-2e14294ea872.png)
