### ISSUE TITLE
Is US v2 data available?

### ISSUE THREAD

**Issue by ChenglongChen** [microsoft/qlib#687]
I try to use the following command to download the v2 data for US, but the end date of this data is still 2020-11-10, is the v2 data of US provided? I test with CN market, it works correctly with end data as 2021-06-11.

command for downloading US v2 data:
python scripts/get_data.py qlib_data --target_dir ~/.qlib/qlib_data/qlib_us_1d --region us --interval 1d --version v2

**Comment by Wangwuyi123** [comment]
@ChenglongChen 
You can refer to it `https://github.com/microsoft/qlib/tree/main/scripts/data_collector/yahoo`to get the US data

**Comment by Wangwuyi123** [comment]
@ChenglongChen 
You can refer to it https://github.com/microsoft/qlib/tree/main/scripts/data_collector/yahooto get the US data

**Comment by Wangwuyi123** [comment]
You can refer to it `https://github.com/microsoft/qlib/tree/main/scripts/data_collector/yahoo` to get the US data

**Comment by ChenglongChen** [comment]
> You can refer to it `https://github.com/microsoft/qlib/tree/main/scripts/data_collector/yahoo` to get the US data

Hi, I actually refer to the above link and the scripts for downloading the V2 version data for US, however, the date still ends at  2020-11-10.

**Comment by you-n-g** [comment]
@ChenglongChen 
The ready-made data (usually downloaded with `python scripts/get_data.py qlib_data --target_dir ~/.qlib/qlib_data/qlib_us_1d --region us --interval 1d`) is not updated very frequently.

You can follow the steps below to crawl the latest data. 
https://github.com/microsoft/qlib/tree/main/scripts/data_collector/yahoo#collector-yahoofinance-data-to-qlib

**Comment by zhupr** [comment]
> > You can refer to it `https://github.com/microsoft/qlib/tree/main/scripts/data_collector/yahoo` to get the US data
> 
> Hi, I actually refer to the above link and the scripts for downloading the V2 version data for US, however, the date still ends at 2020-11-10.

Use this command to incrementally update: `python scripts/data_collector/yahoo/collector.py update_data_to_bin --qlib_data_1d_dir <user data dir> --trading_date <start date> --end_date <end date>`
https://github.com/microsoft/qlib/tree/main/scripts/data_collector/yahoo#automatic-update-of-daily-frequency-datafrom-yahoo-finance

**Comment by ChenglongChen** [comment]
Thanks for pointing that out! I will try to crawl and prepare the data using the mentioned scripts.

**Comment by orchardc** [comment]
I have the same issue when downloading the v2 data using 
`python scripts/data_collector/yahoo/collector.py update_data_to_bin --qlib_data_1d_dir ~/.qlib/qlib_data/us_data --region us --interval 1d --version v2 --trading_date 2008-01-01 --end_date 2021-05-31`

By the way, if v2 end date is 2021-06, how can we get the data till 2021-12-31 ?

![image](https://user-images.githubusercontent.com/16193516/147893786-255bb0c3-cb4d-4f10-89e3-8590a094260c.png)

**Comment by orchardc** [comment]
Hi @ChenglongChen , do you have an update on this?

**Comment by Wangwuyi123** [comment]
@orchardc 
We have reproduced your error and are repairing it, please stay tuned.

**Comment by orchardc** [comment]
Ok great, thanks!
