### ISSUE TITLE
rolling_process_data example still use too much RAM

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#690]
Does the rolling_process_data example suppose to solve the problem of training data too large to be loaded into RAM? It fails at `self._dump_pre_handler("pre_handler.pkl")` because of the following error:

`MemoryError: Unable to allocate 67.5 GiB for an array with shape (360, 50321774) and data type float32`

**Comment by you-n-g** [comment]
@2young-2simple-sometimes-naive 
Currently,  it will load the data into memory directly.  The easiest way to load the data is by expanding swap or RAM.
Thanks.
