### ISSUE TITLE
error in qlib/examples/workflow_by_code.ipyb  "module_path": "qlib.contrib.strategy.model_strategy", should be "module_path": "qlib.contrib.strategy.signal_strategy"

### ISSUE THREAD

**Issue by wan9c9** [microsoft/qlib#691]
## 🐛 Bug Description
In qlib/examples/workflow_by_code.ipyb,
  "module_path": "qlib.contrib.strategy.model_strategy", should be "module_path": "qlib.contrib.strategy.signal_strategy",

**Comment by you-n-g** [comment]
Thanks for issuing this bug!
Would you like to send a PR to fix this issue?
[Contributing](https://github.com/microsoft/qlib#contributing) is quite easy on Github.

**Comment by Qiwen-Yu** [comment]
@you-n-g I am new to this project, can I take this one, thank you!

**Comment by you-n-g** [comment]
@Qiwen-Yu 
This issue has been resolved https://github.com/microsoft/qlib/pull/697
There are a lot of things to be done in Qlib. 
You are highly welcome to contribute to Qlib!
