### ISSUE TITLE
Is there a handler to define custom label for the dataset?

### ISSUE THREAD

**Issue by foolcage** [microsoft/qlib#692]
Not just the simple performance.
Maybe relative performance, volatility, drawdown on different time range.

**Comment by you-n-g** [comment]
Here is an example to customize the label https://github.com/microsoft/qlib/blob/main/examples/benchmarks/GRU/workflow_config_gru_Alpha158.yaml#L29

It is a relative performance because it is normalized cross-sectionally with Rank

**Comment by foolcage** [comment]
> Here is an example to customize the label https://github.com/microsoft/qlib/blob/main/examples/benchmarks/GRU/workflow_config_gru_Alpha158.yaml#L29
> 
> It is a relative performance because it is normalized cross-sectionally with Rank

Thanks.
