### ISSUE TITLE
About pit

### ISSUE THREAD

**Issue by yieldbook** [microsoft/qlib#696]
I tried the pit branch. It's very slow to fetch the period data and the following error happens randomly. 
error: unpack requires a buffer of 20 bytes.

In terms of 'randomly', I mean it's not related to a specific stock or field. Any stock and field can have such a problem. 

Any suggestion? Thanks in advance.

**Comment by you-n-g** [comment]
Sorry, It is under development and not stable
We don't much bandwidth recently to finish it. 
We'll try to discuss with you when we continue the development of PIT later.
Thanks.
