### ISSUE TITLE
backtest results: which stocks are in the portfolio per time?

### ISSUE THREAD

**Issue by kurucan** [microsoft/qlib#698]
I see the report_normal_df provides summarized bactest results. Is it possible to export detailed backtest results as df such as which stocks are being held in the portfolio as per time under TopkDropoutStrategy?

**Comment by you-n-g** [comment]
The positions are saved in `positions_normal_day.pkl` 
Here is the related code.
`https://github.com/microsoft/qlib/blob/main/qlib/workflow/record_temp.py#L420`

**Comment by kurucan** [comment]
thanks but I see a qlib object, how can I read this file as a dataframe ? 



![positions](https://user-images.githubusercontent.com/7413036/142510619-78c8fc9f-1cab-44d8-bf6e-4001b963e0aa.png)

**Comment by you-n-g** [comment]
Please look at this class 
https://github.com/microsoft/qlib/blob/main/qlib/backtest/position.py#L227

**Comment by kurucan** [comment]
Thanks, is this recorded on experiment?

**Comment by you-n-g** [comment]
Yes.  It can be loaded by pickle (in your picture, it looks like that you have already loaded it). You can use it like normal Python objects.
