### ISSUE TITLE
highfreq test dataset range?

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#701]
I have tried to run the highfreq workflow using the given example qlib_data downloaded (yahoo_cn_1min). The `MARKET = "all"` gives an IC of around 0.008, which is far from the reported 0.3 in the example. In fact I don't believe IC~0.3 could be achieved with ~4000 symbols. Is the example actually using csi300 market?

**Comment by zhupr** [comment]
@2young-2simple-sometimes-naive Hi,
The example of highfreq is csi300 market, which has been fixed for the results: https://github.com/microsoft/qlib/pull/702
Need to re-download data: `python scripts/get_data.py qlib_data --target_dir <1min dir> --interval 1min`

**Comment by 2young-2simple-sometimes-naive** [comment]
> @2young-2simple-sometimes-naive Hi, The example of highfreq is csi300 market, which has been fixed for the results: #702 Need to re-download data: `python scripts/get_data.py qlib_data --target_dir <1min dir> --interval 1min`

Yep. IC~0.03 is more like it.
