### ISSUE TITLE
About the feature format

### ISSUE THREAD

**Issue by foolcage** [microsoft/qlib#705]
Market data is ts data, it seems current model is:

(ti, fi, fi, fi, ...) -> (li)
i is [1,N], t is timestamp, f is feature, l is label
ti maybe contain past window, e.g ma30. 
li maybe contain future window,e.g performance in next 10 days.

My question is:
Should we add ti as feaure too if the feature has contained some past time window information.
This would effect the data of the model:

(ti, fi(current data), fi, fi, ...) -> (li)
(ti, fi(current data), fi, fi, ...) -> (li)
====== more samles

(ti, fi(window data), fi, fi, ...) -> (li)
======less samples, we has computed the data from past windows.

Which format is better?
Is there some custom hanlder to define it ?

**Comment by you-n-g** [comment]
> Should we add ti as feaure too if the feature has contained some past time window information.
It depends on what information you want to expose to your model.

Besides, creating features with a past time window of information will not necessarily make the samples less.
e.g.   the window for the feature may be 10, but the steps to create features can be 1 (adjacent samples may have some information overlap)

A lot of features in Qlib's datasets contains some past time window information.  (e.g. https://github.com/microsoft/qlib/blob/103f8579c10f18219b729cd27837b3d119f9762c/qlib/contrib/data/handler.py#L103)

**Comment by foolcage** [comment]
@you-n-g Thanks for your reply.
Yes, It depends the model design. 
So the model may be built on many non independent features.
Anyway it's market domain knowledge.
I'm thinking about whether we could add some mechanism to handle this.
Your information is very helpful.Thanks again!
