### ISSUE TITLE
Add new dataset: crypto dataset from CoinGecko

### ISSUE THREAD

**Issue by b4thesunrise** [microsoft/qlib#716]
## 🌟 Feature Description
Add new data set of cryptocurrencies

## Motivation

1. Application scenario: support cryptocurrencies investment strategy research. Free api can be found at https://www.coingecko.com/en/api/documentation
2. Related works (Papers, Github repos etc.):
3. Any other relevant and important information:

**Comment by b4thesunrise** [comment]
is the same format as qlib/scripts/data_collector/fund/ is enough to add a dataset? not sure how to update the cache to the data server

**Comment by zhupr** [comment]
> is the same format as qlib/scripts/data_collector/fund/ is enough to add a dataset? not sure how to update the cache to the data server

`qlib/scripts/data_collector/fund/` is the sample code to get the fund data from the network and save it locally as a `csv`, the conversion of the `csv` to data available in `qlib` requires via `scripts/dump_bin.py`: https://qlib.readthedocs.io/en/latest/component/data.html#converting-csv-format-into-qlib-format. 

If `qlib.init` uses `expression_cache="DiskExpressionCache" and dataset_cache="DiskDatasetCache"`, you can update the cache with this script https://github.com/microsoft/qlib-server/blob/main/scripts/update_cache.py

**Comment by b4thesunrise** [comment]
got it, thanks so much!

**Comment by b4thesunrise** [comment]
> > is the same format as qlib/scripts/data_collector/fund/ is enough to add a dataset? not sure how to update the cache to the data server
> 
> `qlib/scripts/data_collector/fund/` is the sample code to get the fund data from the network and save it locally as a `csv`, the conversion of the `csv` to data available in `qlib` requires via `scripts/dump_bin.py`: https://qlib.readthedocs.io/en/latest/component/data.html#converting-csv-format-into-qlib-format.
> 
> If `qlib.init` uses `expression_cache="DiskExpressionCache" and dataset_cache="DiskDatasetCache"`, you can update the cache with this script https://github.com/microsoft/qlib-server/blob/main/scripts/update_cache.py

got it, thanks so much!
