### ISSUE TITLE
deal_amount nan

### ISSUE THREAD

**Issue by takacsg84** [microsoft/qlib#717]
git/qlib/backtest/exchange.py:739: RuntimeWarning: divide by zero encountered in double_scalars
  adj_cost_ratio = self.impact_cost * (trade_val / total_trade_val) ** 2

This happens when we are trying to close an order on a date when volume == 0. This messes up the whole backtest pipeline, and further orders will have deal_amount nan

**Comment by you-n-g** [comment]
Thanks so much for reporting the bug.
We'll try to fix it soon

**Comment by zhupr** [comment]
@takacsg84 Hi,
This issue has been resolved https://github.com/microsoft/qlib/pull/719
