### ISSUE TITLE
qlib.contrib.strategy.model_strategy - bug keeps happening

### ISSUE THREAD

**Issue by ander-son-almeida** [microsoft/qlib#724]
Hi guys,

I've been following the discussion about the "qlib.contrib.strategy.model_strategy" bug here: https://github.com/microsoft/qlib/issues/714

However, even updating the code, I still have the same module loading failure problem.

I ran the tests in workflow_by_code.py and workflow_by_code.ipynb.

Tks!

**Comment by zhupr** [comment]
@Queituron Hi,
Do you run `workflow_by_code.py` with the same `strategy` as the latest : https://github.com/microsoft/qlib/blob/main/examples/workflow_by_code.py#L34

**clone or pull the latest code locally**
