### ISSUE TITLE
怎样单独使用test.csv或者pred_score来回测 

### ISSUE THREAD

**Issue by zzz6060092** [microsoft/qlib#726]
![image](https://user-images.githubusercontent.com/52370630/144580982-334d1afb-9896-4c9a-a940-c59397337ba3.png)
我现在能够打印出test.csv，但如何通过这个csv文件来进行top-k回测？
api说明里的接口似乎已经作废了。
![image](https://user-images.githubusercontent.com/52370630/144581230-c1c00bc6-900d-49a2-9c6a-0f0c39fd08cb.png)

**Comment by zhupr** [comment]
@zzz6060092 Hi,
这个文档很快就会更新，在这个PR：https://github.com/microsoft/qlib/pull/719
也可以先按照下面的样例写：
```python
from pprint import pprint

import qlib
import pandas as pd
from qlib.utils.time import Freq
from qlib.utils import flatten_dict
from qlib.backtest import backtest, executor
from qlib.contrib.evaluate import risk_analysis
from qlib.contrib.strategy import TopkDropoutStrategy


if __name__ == "__main__":

    qlib.init(provider_uri=r"G:\stock_data\.qlib\qlib_data\2021-07-15")
    pred_score = pd.read_csv("test.csv")["score"]
    CSI300_BENCH = "SH000300"
    FREQ = "day"
    STRATEGY_CONFIG = {
        "topk": 50,
        "n_drop": 5,
        "signal": pred_score,
    }

    EXECUTOR_CONFIG = {
        "time_per_step": "day",
        "generate_portfolio_metrics": True,
        "verbose": True,
    }

    backtest_config = {
        "start_time": "2017-01-01",
        "end_time": "2020-08-01",
        "account": 100000000,
        "benchmark": CSI300_BENCH,
        "exchange_kwargs": {
            "freq": FREQ,
            "limit_threshold": 0.095,
            "deal_price": "close",
            "open_cost": 0.0005,
            "close_cost": 0.0015,
            "min_cost": 5,
        },
    }

    strategy_obj = TopkDropoutStrategy(**STRATEGY_CONFIG)
    executor_obj = executor.SimulatorExecutor(**EXECUTOR_CONFIG)

    portfolio_metric_dict, indicator_dict = backtest(executor=executor_obj, strategy=strategy_obj, **backtest_config)
    analysis_freq = "{0}{1}".format(*Freq.parse(FREQ))

    report_normal, positions_normal = portfolio_metric_dict.get(analysis_freq)
    analysis = dict()
    analysis["excess_return_without_cost"] = risk_analysis(
        report_normal["return"] - report_normal["bench"], freq=analysis_freq
    )
    analysis["excess_return_with_cost"] = risk_analysis(
        report_normal["return"] - report_normal["bench"] - report_normal["cost"], freq=analysis_freq
    )

    analysis_df = pd.concat(analysis)  # type: pd.DataFrame
    # log metrics
    analysis_dict = flatten_dict(analysis_df["risk"].unstack().T.to_dict())
    # print out results
    pprint(f"The following are analysis results of benchmark return({analysis_freq}).")
    pprint(risk_analysis(report_normal["bench"], freq=analysis_freq))
    pprint(f"The following are analysis results of the excess return without cost({analysis_freq}).")
    pprint(analysis["excess_return_without_cost"])
    pprint(f"The following are analysis results of the excess return with cost({analysis_freq}).")
    pprint(analysis["excess_return_with_cost"])
```

**Comment by zzz6060092** [comment]
感谢回答，但似乎有一点bug。
仅仅改动了箭头处
![image](https://user-images.githubusercontent.com/52370630/144601660-8ac4be07-ecf0-4f1e-bdad-de335533e837.png)
会出现下面的报错。
![image](https://user-images.githubusercontent.com/52370630/144601730-d4eaca2d-b2a5-4fcc-9458-635d4e62a45d.png)
![image](https://user-images.githubusercontent.com/52370630/144601757-c38fc21f-d09a-429e-a74a-ead113443922.png)

**Comment by zhupr** [comment]
> 感谢回答，但似乎有一点bug。 仅仅改动了箭头处 ![image](https://user-images.githubusercontent.com/52370630/144601660-8ac4be07-ecf0-4f1e-bdad-de335533e837.png) 会出现下面的报错。 ![image](https://user-images.githubusercontent.com/52370630/144601730-d4eaca2d-b2a5-4fcc-9458-635d4e62a45d.png) ![image](https://user-images.githubusercontent.com/52370630/144601757-c38fc21f-d09a-429e-a74a-ead113443922.png)

score的index的类型需要是pd.Timestamp： `score.index = pd.to_datetime(score.index)`

**Comment by zzz6060092** [comment]
> > 感谢回答，但似乎有一点bug。 仅仅改动了箭头处 ![image](https://user-images.githubusercontent.com/52370630/144601660-8ac4be07-ecf0-4f1e-bdad-de335533e837.png) 会出现下面的报错。 ![image](https://user-images.githubusercontent.com/52370630/144601730-d4eaca2d-b2a5-4fcc-9458-635d4e62a45d.png) ![image](https://user-images.githubusercontent.com/52370630/144601757-c38fc21f-d09a-429e-a74a-ead113443922.png)
> 
> score的index的类型需要是pd.Timestamp： `score.index = pd.to_datetime(score.index)`

但这样的话index就没有instrument了？我的pred_score的index是MultiIndex。
![image](https://user-images.githubusercontent.com/52370630/144698290-fd47a3fc-86c5-4b25-ae8e-305fda346451.png)

或者您的源代码里的 pred_score = pd.read_csv("test.csv")["score"] 是什么样子呢？能否给个示例。

**Comment by zhupr** [comment]
> 



> 

不好意思，那个pd.to_dateitme是不对的; 
你可以把详细的错误信息发出来我看下在qlib的哪一行代码出错误吗

**Comment by zhupr** [comment]
> > > 感谢回答，但似乎有一点bug。 仅仅改动了箭头处 ![image](https://user-images.githubusercontent.com/52370630/144601660-8ac4be07-ecf0-4f1e-bdad-de335533e837.png) 会出现下面的报错。 ![image](https://user-images.githubusercontent.com/52370630/144601730-d4eaca2d-b2a5-4fcc-9458-635d4e62a45d.png) ![image](https://user-images.githubusercontent.com/52370630/144601757-c38fc21f-d09a-429e-a74a-ead113443922.png)
> > 
> > 
> > score的index的类型需要是pd.Timestamp： `score.index = pd.to_datetime(score.index)`
> 
> 但这样的话index就没有instrument了？我的pred_score的index是MultiIndex。 ![image](https://user-images.githubusercontent.com/52370630/144698290-fd47a3fc-86c5-4b25-ae8e-305fda346451.png)
> 
> 或者您的源代码里的 pred_score = pd.read_csv("test.csv")["score"] 是什么样子呢？能否给个示例。

不好意思，那个pd.to_dateitme是不对的;
你可以把详细的错误信息发出来我看下在qlib的哪一行代码出错误吗

**Comment by zzz6060092** [comment]
这是我读入的pred_score.csv文件。
![image](https://user-images.githubusercontent.com/52370630/144703224-d674dc02-234b-4d71-8eae-58620c675233.png)

按照您的代码运行后，只读入了该文件的‘score’一列，所以index就是0.1.2....报错如下
KeyError                                  Traceback (most recent call last)
D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_slice_bound(self, label, side, kind)
   5389         try:
-> 5390             slc = self.get_loc(label)
   5391         except KeyError as err:

D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\range.py in get_loc(self, key, method, tolerance)
    353                     raise KeyError(key) from err
--> 354             raise KeyError(key)
    355         return super().get_loc(key, method=method, tolerance=tolerance)

KeyError: Timestamp('2020-08-31 00:00:00')

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-11-459e9d13e7a1> in <module>
     46     executor_obj = executor.SimulatorExecutor(**EXECUTOR_CONFIG)
     47 
---> 48     portfolio_metric_dict, indicator_dict = backtest(executor=executor_obj, strategy=strategy_obj, **backtest_config)
     49     analysis_freq = "{0}{1}".format(*Freq.parse(FREQ))
     50 

D:\ProgramData\Anaconda3\lib\site-packages\pyqlib-0.7.2.99-py3.8-win-amd64.egg\qlib\backtest\__init__.py in backtest(start_time, end_time, strategy, executor, benchmark, account, exchange_kwargs, pos_type)
    250         pos_type=pos_type,
    251     )
--> 252     portfolio_metrics, indicator = backtest_loop(start_time, end_time, trade_strategy, trade_executor)
    253     return portfolio_metrics, indicator
    254 

D:\ProgramData\Anaconda3\lib\site-packages\pyqlib-0.7.2.99-py3.8-win-amd64.egg\qlib\backtest\backtest.py in backtest_loop(start_time, end_time, trade_strategy, trade_executor)
     26     """
     27     return_value = {}
---> 28     for _decision in collect_data_loop(start_time, end_time, trade_strategy, trade_executor, return_value):
     29         pass
     30     return return_value.get("portfolio_metrics"), return_value.get("indicator")

D:\ProgramData\Anaconda3\lib\site-packages\pyqlib-0.7.2.99-py3.8-win-amd64.egg\qlib\backtest\backtest.py in collect_data_loop(start_time, end_time, trade_strategy, trade_executor, return_value)
     63         _execute_result = None
     64         while not trade_executor.finished():
---> 65             _trade_decision: BaseTradeDecision = trade_strategy.generate_trade_decision(_execute_result)
     66             _execute_result = yield from trade_executor.collect_data(_trade_decision, level=0)
     67             bar.update(1)

D:\ProgramData\Anaconda3\lib\site-packages\pyqlib-0.7.2.99-py3.8-win-amd64.egg\qlib\contrib\strategy\signal_strategy.py in generate_trade_decision(self, execute_result)
    106         trade_start_time, trade_end_time = self.trade_calendar.get_step_time(trade_step)
    107         pred_start_time, pred_end_time = self.trade_calendar.get_step_time(trade_step, shift=1)
--> 108         pred_score = self.signal.get_signal(start_time=pred_start_time, end_time=pred_end_time)
    109         if pred_score is None:
    110             return TradeDecisionWO([], self)

D:\ProgramData\Anaconda3\lib\site-packages\pyqlib-0.7.2.99-py3.8-win-amd64.egg\qlib\backtest\signal.py in get_signal(self, start_time, end_time)
     59         # so resampling from the data is necessary
     60         # the latest signal leverage more recent data and therefore is used in trading.
---> 61         signal = resam_ts_data(self.signal_cache, start_time=start_time, end_time=end_time, method="last")
     62         return signal
     63 

D:\ProgramData\Anaconda3\lib\site-packages\pyqlib-0.7.2.99-py3.8-win-amd64.egg\qlib\utils\resam.py in resam_ts_data(ts_feature, start_time, end_time, method, method_kwargs)
    179     datetime_level = get_level_index(feature, level="datetime") == 0
    180     if datetime_level:
--> 181         feature = feature.loc[selector_datetime]
    182     else:
    183         feature = feature.loc(axis=0)[(slice(None), selector_datetime)]

D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py in __getitem__(self, key)
    893 
    894             maybe_callable = com.apply_if_callable(key, self.obj)
--> 895             return self._getitem_axis(maybe_callable, axis=axis)
    896 
    897     def _is_scalar_access(self, key: Tuple):

D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py in _getitem_axis(self, key, axis)
   1100         if isinstance(key, slice):
   1101             self._validate_key(key, axis)
-> 1102             return self._get_slice_axis(key, axis=axis)
   1103         elif com.is_bool_indexer(key):
   1104             return self._getbool_axis(key, axis=axis)

D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py in _get_slice_axis(self, slice_obj, axis)
   1134 
   1135         labels = obj._get_axis(axis)
-> 1136         indexer = labels.slice_indexer(
   1137             slice_obj.start, slice_obj.stop, slice_obj.step, kind="loc"
   1138         )

D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in slice_indexer(self, start, end, step, kind)
   5275         slice(1, 3, None)
   5276         """
-> 5277         start_slice, end_slice = self.slice_locs(start, end, step=step, kind=kind)
   5278 
   5279         # return a slice

D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in slice_locs(self, start, end, step, kind)
   5474         start_slice = None
   5475         if start is not None:
-> 5476             start_slice = self.get_slice_bound(start, "left", kind)
   5477         if start_slice is None:
   5478             start_slice = 0

D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_slice_bound(self, label, side, kind)
   5391         except KeyError as err:
   5392             try:
-> 5393                 return self._searchsorted_monotonic(label, side)
   5394             except ValueError:
   5395                 # raise the original KeyError

D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in _searchsorted_monotonic(self, label, side)
   5342     def _searchsorted_monotonic(self, label, side="left"):
   5343         if self.is_monotonic_increasing:
-> 5344             return self.searchsorted(label, side=side)
   5345         elif self.is_monotonic_decreasing:
   5346             # np.searchsorted expects ascending sort order, have to reverse

D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\base.py in searchsorted(self, value, side, sorter)
   1290     @doc(_shared_docs["searchsorted"], klass="Index")
   1291     def searchsorted(self, value, side="left", sorter=None) -> np.ndarray:
-> 1292         return algorithms.searchsorted(self._values, value, side=side, sorter=sorter)
   1293 
   1294     def drop_duplicates(self, keep="first"):

D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\algorithms.py in searchsorted(arr, value, side, sorter)
   1906             value = value.to_datetime64()
   1907 
-> 1908     result = arr.searchsorted(value, side=side, sorter=sorter)
   1909     return result
   1910 

TypeError: '<' not supported between instances of 'int' and 'Timestamp'


但我认为是不是应该把整个csv文件都读入进去，即直接load"pred.pkl"
![image](https://user-images.githubusercontent.com/52370630/144703438-9dab32f2-5f20-4cfb-950b-74ba1013f427.png)
这样的话pred_score的index就是我上面发的MultiIndex，但仍然会报下面的错误。
![image](https://user-images.githubusercontent.com/52370630/144703476-c5a6129e-3359-49dd-be6a-b22f9b5b383c.png)

**Comment by zhupr** [comment]
> 这是我读入的pred_score.csv文件。 ![image](https://user-images.githubusercontent.com/52370630/144703224-d674dc02-234b-4d71-8eae-58620c675233.png)
> 
> 按照您的代码运行后，只读入了该文件的‘score’一列，所以index就是0.1.2....报错如下 KeyError Traceback (most recent call last) D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_slice_bound(self, label, side, kind) 5389 try: -> 5390 slc = self.get_loc(label) 5391 except KeyError as err:
> 
> D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\range.py in get_loc(self, key, method, tolerance) 353 raise KeyError(key) from err --> 354 raise KeyError(key) 355 return super().get_loc(key, method=method, tolerance=tolerance)
> 
> KeyError: Timestamp('2020-08-31 00:00:00')
> 
> During handling of the above exception, another exception occurred:
> 
> TypeError Traceback (most recent call last) in 46 executor_obj = executor.SimulatorExecutor(**EXECUTOR_CONFIG) 47 ---> 48 portfolio_metric_dict, indicator_dict = backtest(executor=executor_obj, strategy=strategy_obj, **backtest_config) 49 analysis_freq = "{0}{1}".format(*Freq.parse(FREQ)) 50
> 
> D:\ProgramData\Anaconda3\lib\site-packages\pyqlib-0.7.2.99-py3.8-win-amd64.egg\qlib\backtest__init__.py in backtest(start_time, end_time, strategy, executor, benchmark, account, exchange_kwargs, pos_type) 250 pos_type=pos_type, 251 ) --> 252 portfolio_metrics, indicator = backtest_loop(start_time, end_time, trade_strategy, trade_executor) 253 return portfolio_metrics, indicator 254
> 
> D:\ProgramData\Anaconda3\lib\site-packages\pyqlib-0.7.2.99-py3.8-win-amd64.egg\qlib\backtest\backtest.py in backtest_loop(start_time, end_time, trade_strategy, trade_executor) 26 """ 27 return_value = {} ---> 28 for _decision in collect_data_loop(start_time, end_time, trade_strategy, trade_executor, return_value): 29 pass 30 return return_value.get("portfolio_metrics"), return_value.get("indicator")
> 
> D:\ProgramData\Anaconda3\lib\site-packages\pyqlib-0.7.2.99-py3.8-win-amd64.egg\qlib\backtest\backtest.py in collect_data_loop(start_time, end_time, trade_strategy, trade_executor, return_value) 63 _execute_result = None 64 while not trade_executor.finished(): ---> 65 _trade_decision: BaseTradeDecision = trade_strategy.generate_trade_decision(_execute_result) 66 _execute_result = yield from trade_executor.collect_data(_trade_decision, level=0) 67 bar.update(1)
> 
> D:\ProgramData\Anaconda3\lib\site-packages\pyqlib-0.7.2.99-py3.8-win-amd64.egg\qlib\contrib\strategy\signal_strategy.py in generate_trade_decision(self, execute_result) 106 trade_start_time, trade_end_time = self.trade_calendar.get_step_time(trade_step) 107 pred_start_time, pred_end_time = self.trade_calendar.get_step_time(trade_step, shift=1) --> 108 pred_score = self.signal.get_signal(start_time=pred_start_time, end_time=pred_end_time) 109 if pred_score is None: 110 return TradeDecisionWO([], self)
> 
> D:\ProgramData\Anaconda3\lib\site-packages\pyqlib-0.7.2.99-py3.8-win-amd64.egg\qlib\backtest\signal.py in get_signal(self, start_time, end_time) 59 # so resampling from the data is necessary 60 # the latest signal leverage more recent data and therefore is used in trading. ---> 61 signal = resam_ts_data(self.signal_cache, start_time=start_time, end_time=end_time, method="last") 62 return signal 63
> 
> D:\ProgramData\Anaconda3\lib\site-packages\pyqlib-0.7.2.99-py3.8-win-amd64.egg\qlib\utils\resam.py in resam_ts_data(ts_feature, start_time, end_time, method, method_kwargs) 179 datetime_level = get_level_index(feature, level="datetime") == 0 180 if datetime_level: --> 181 feature = feature.loc[selector_datetime] 182 else: 183 feature = feature.loc(axis=0)[(slice(None), selector_datetime)]
> 
> D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py in **getitem**(self, key) 893 894 maybe_callable = com.apply_if_callable(key, self.obj) --> 895 return self._getitem_axis(maybe_callable, axis=axis) 896 897 def _is_scalar_access(self, key: Tuple):
> 
> D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py in _getitem_axis(self, key, axis) 1100 if isinstance(key, slice): 1101 self._validate_key(key, axis) -> 1102 return self._get_slice_axis(key, axis=axis) 1103 elif com.is_bool_indexer(key): 1104 return self._getbool_axis(key, axis=axis)
> 
> D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py in _get_slice_axis(self, slice_obj, axis) 1134 1135 labels = obj._get_axis(axis) -> 1136 indexer = labels.slice_indexer( 1137 slice_obj.start, slice_obj.stop, slice_obj.step, kind="loc" 1138 )
> 
> D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in slice_indexer(self, start, end, step, kind) 5275 slice(1, 3, None) 5276 """ -> 5277 start_slice, end_slice = self.slice_locs(start, end, step=step, kind=kind) 5278 5279 # return a slice
> 
> D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in slice_locs(self, start, end, step, kind) 5474 start_slice = None 5475 if start is not None: -> 5476 start_slice = self.get_slice_bound(start, "left", kind) 5477 if start_slice is None: 5478 start_slice = 0
> 
> D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_slice_bound(self, label, side, kind) 5391 except KeyError as err: 5392 try: -> 5393 return self._searchsorted_monotonic(label, side) 5394 except ValueError: 5395 # raise the original KeyError
> 
> D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in _searchsorted_monotonic(self, label, side) 5342 def _searchsorted_monotonic(self, label, side="left"): 5343 if self.is_monotonic_increasing: -> 5344 return self.searchsorted(label, side=side) 5345 elif self.is_monotonic_decreasing: 5346 # np.searchsorted expects ascending sort order, have to reverse
> 
> D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\base.py in searchsorted(self, value, side, sorter) 1290 @doc(_shared_docs["searchsorted"], klass="Index") 1291 def searchsorted(self, value, side="left", sorter=None) -> np.ndarray: -> 1292 return algorithms.searchsorted(self._values, value, side=side, sorter=sorter) 1293 1294 def drop_duplicates(self, keep="first"):
> 
> D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\algorithms.py in searchsorted(arr, value, side, sorter) 1906 value = value.to_datetime64() 1907 -> 1908 result = arr.searchsorted(value, side=side, sorter=sorter) 1909 return result 1910
> 
> TypeError: '<' not supported between instances of 'int' and 'Timestamp'
> 
> 但我认为是不是应该把整个csv文件都读入进去，即直接load"pred.pkl" ![image](https://user-images.githubusercontent.com/52370630/144703438-9dab32f2-5f20-4cfb-950b-74ba1013f427.png) 这样的话pred_score的index就是我上面发的MultiIndex，但仍然会报下面的错误。 ![image](https://user-images.githubusercontent.com/52370630/144703476-c5a6129e-3359-49dd-be6a-b22f9b5b383c.png)

- 按照你的csv格式, 需要这样读取：
```python
score_df = pd.read_csv("test.csv")
score_df["datetime"] = pd.to_datetime(score_df["datetime"])
score = score_df.set_index(["datetime", "instrument"])["score"]
```
- 目前的main分支单独使用score还有点问题，暂时先使用这个PR的代码或者等合并后在使用main分支的代码, 这个PR最近两天就会merge:https://github.com/microsoft/qlib/pull/719

**Comment by zzz6060092** [comment]
> 

好的，感谢解答。

**Comment by zzz6060092** [comment]
@zhupr 好的，感谢您的解答。

**Comment by zzz6060092** [comment]
@zhupr 不好意思，我看不懂您的pr。按照您给的读取方式和示例代码，还是会报错。
![image](https://user-images.githubusercontent.com/52370630/144810170-b5a4d273-25fb-4ec0-a70b-ffb869ed49b3.png)
![image](https://user-images.githubusercontent.com/52370630/144810198-fe3574b4-3009-4e83-b909-bb0040966c93.png)
pred_score打印出来如下
![image](https://user-images.githubusercontent.com/52370630/144810305-b44a17ee-3eb9-4326-a4c1-f6bef04efd18.png)

**Comment by zhupr** [comment]
> @zhupr 不好意思，我看不懂您的pr。按照您给的读取方式和示例代码，还是会报错。 ![image](https://user-images.githubusercontent.com/52370630/144810170-b5a4d273-25fb-4ec0-a70b-ffb869ed49b3.png) ![image](https://user-images.githubusercontent.com/52370630/144810198-fe3574b4-3009-4e83-b909-bb0040966c93.png) pred_score打印出来如下 ![image](https://user-images.githubusercontent.com/52370630/144810305-b44a17ee-3eb9-4326-a4c1-f6bef04efd18.png)

使用的是这个分支的代码吗：https://github.com/zhupr/qlib/tree/fix_backtest：
  -  `git clone -b fix_backtest https://github.com/zhupr/qlib`
  - cd qlib
  - python setup.py install

**Comment by zzz6060092** [comment]
> > @zhupr 不好意思，我看不懂您的pr。按照您给的读取方式和示例代码，还是会报错。 ![image](https://user-images.githubusercontent.com/52370630/144810170-b5a4d273-25fb-4ec0-a70b-ffb869ed49b3.png) ![image](https://user-images.githubusercontent.com/52370630/144810198-fe3574b4-3009-4e83-b909-bb0040966c93.png) pred_score打印出来如下 ![image](https://user-images.githubusercontent.com/52370630/144810305-b44a17ee-3eb9-4326-a4c1-f6bef04efd18.png)
> 
> 使用的是这个分支的代码吗：[https://github.com/zhupr/qlib/tree/fix_backtest：](https://github.com/zhupr/qlib/tree/fix_backtest%EF%BC%9A)
> 
> * `git clone -b fix_backtest https://github.com/zhupr/qlib`
> * cd qlib
> * python setup.py install

可以了，十分感谢！！！！
