### ISSUE TITLE
problem with datetime_groupby_apply()

### ISSUE THREAD

**Issue by yieldbook** [microsoft/qlib#727]
I called ProcessInf and encountered an error: _pickle.PicklingError: Could not pickle the task to send it to the workers.
It seems to be a problem of joblib and my joblib version is 1.1.0

https://github.com/microsoft/qlib/blob/84103c7d43eaa0ff74118a4d05884f659f0548eb/qlib/data/dataset/processor.py#L175

Any suggestion? Thanks!

**Comment by zhupr** [comment]
Which script is being run? 
What is the python environment: `python scripts/collect_info.py all`

**Comment by yieldbook** [comment]
> Which script is being run? What is the python environment: `python scripts/collect_info.py all`

I wasn't running a script.  In the dataset initialization step, I use a processor named ProcessInf  to clean the inf in the dataset and the error happened. 

Below please find the python environment:

Windows
AMD64
Windows-10-10.0.19041-SP0
10.0.19041

Python version: 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]

Qlib version: 0.7.0.99
numpy==1.19.4
pandas==1.3.1
scipy==1.7.1
requests==2.25.1
sacred==0.8.2
python-socketio==3.1.2
redis==3.5.3
python-redis-lock==3.7.0
schedule==0.6.0
cvxpy==1.0.21
hyperopt==0.1.1
fire==0.3.1
statsmodels==0.12.1
xlrd==2.0.1
plotly==4.12.0
matplotlib==3.1.3
tables==3.6.1
pyyaml==5.3.1
mlflow==1.20.2
tqdm==4.56.0
loguru==0.5.3
lightgbm==3.1.1
tornado==5.1.1
joblib==1.1.0
fire==0.3.1
ruamel.yaml==0.16.12

**Comment by zhupr** [comment]
> 



> > Which script is being run? What is the python environment: `python scripts/collect_info.py all`
> 
> I wasn't running a script. In the dataset initialization step, I use a processor named ProcessInf to clean the inf in the dataset and the error happened.
> 
> Below please find the python environment:
> 
> Windows AMD64 Windows-10-10.0.19041-SP0 10.0.19041
> 
> Python version: 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]
> 
> Qlib version: 0.7.0.99 numpy==1.19.4 pandas==1.3.1 scipy==1.7.1 requests==2.25.1 sacred==0.8.2 python-socketio==3.1.2 redis==3.5.3 python-redis-lock==3.7.0 schedule==0.6.0 cvxpy==1.0.21 hyperopt==0.1.1 fire==0.3.1 statsmodels==0.12.1 xlrd==2.0.1 plotly==4.12.0 matplotlib==3.1.3 tables==3.6.1 pyyaml==5.3.1 mlflow==1.20.2 tqdm==4.56.0 loguru==0.5.3 lightgbm==3.1.1 tornado==5.1.1 joblib==1.1.0 fire==0.3.1 ruamel.yaml==0.16.12

How did you implement it and how should you reproduce this error?
