### ISSUE TITLE
在win系统上安装不上，提示缺少Microsoft Visual C++ 14.0。该软件一定要装吗

### ISSUE THREAD

**Issue by aiot-tech** [microsoft/qlib#729]
`error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
`

**Comment by zhupr** [comment]
> 



> `error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/ `

是的，有些库是必须依赖Visual C++的

**Comment by aiot-tech** [comment]
谢谢回复！本地的机器存储太少了，有其他的替代方案吗？比如装一个比较小的C++编译器？

**Comment by zhupr** [comment]
> 



> 谢谢回复！本地的机器存储太少了，有其他的替代方案吗？比如装一个比较小的C++编译器？或者qlib有相应的whl文件吗

之前Visual C++官方提供的就很小，后来不知道怎么变大了，你试试这个：https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjcldyEuNH0AhWFA94KHYzwAE8QFnoECAUQAQ&url=https%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D691126&usg=AOvVaw0geDw_h-TSCfzTMvYE2ZOw

**Comment by aiot-tech** [comment]
感谢感谢
