### ISSUE TITLE
install from source with pip install . will cause import error: FileNotFoundError: [Errno 2] No such file or directory: '~/qlib/qlib/VERSION.txt'

### ISSUE THREAD

**Issue by b4thesunrise** [microsoft/qlib#731]
## To Reproduce

1.install the latest master branch with pip install .
2.python, import qlib
3. FileNotFoundError: [Errno 2] No such file or directory: '~/qlib/qlib/VERSION.txt'

## Screenshot

![image](https://user-images.githubusercontent.com/43727375/145143163-15b00bd2-18d9-4946-adb5-77dd074ce182.png)

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version:0.8.0.99
 - Python version:3.7
 - OS (`Windows`, `Linux`, `MacOS`):Macos
 - Commit number (optional, please provide it if you are using the dev version):

**Comment by Wangwuyi123** [comment]
@b4thesunrise 
According to your environment, I did not reproduce the same bug, please test it in your environment again, if the same bug reproduces, please be sure to inform.

**Comment by you-n-g** [comment]
@b4thesunrise 
Thanks so much  for your contribution.

The  VERSION.txt will be automatically created when you run `python setup.py install` or `python setup.py develop` 
https://github.com/microsoft/qlib/blob/main/setup.py#L19

Did you encounter any problems when creating it?

**Comment by b4thesunrise** [comment]
> @b4thesunrise Thanks so much for your contribution.
> 
> The VERSION.txt will be automatically created when you run `python setup.py install` or `python setup.py develop` https://github.com/microsoft/qlib/blob/main/setup.py#L19
> 
> Did you encounter any problems when creating it?

> @b4thesunrise According to your environment, I did not reproduce the same bug, please test it in your environment again, if the same bug reproduces, please be sure to inform.

I haven't encounter problem when creating the version.txt file by `python setup.py install`, the reason why I encounter the problem is I first use `python setup.py install` to  install qlib at first, after that, I tried to update the version by git clone, cd qlib, and `python install .`, and encounter the FileNotFoundError. I think that's because I understand the documentation wrongly, thanks for your help!

**Comment by you-n-g** [comment]
@b4thesunrise 
I tried `pip install .` later and encountered the same error. 
It is indeed a bug that should be fixed.
Thanks for your reporting

Looking forward to your update on [this pr](https://github.com/microsoft/qlib/pull/732)
