### ISSUE TITLE
数据到6.11号预测可以到6.11，为何交易明细只能到6.10

### ISSUE THREAD

**Issue by benduofen007** [microsoft/qlib#735]
你好作者，有一点比较困惑的是，根据观察，CN的交易数据是到2021年6月11号的，预测的结果也是到6.11号，但是交易明细和持仓信息没有到6.11，到6.10就结束了。
按照真实的使用场景，假设今天是6.11，6.11下午交易结束了，交易结束后获得了最新的6.11股票数据，这时需要知道明天怎么买入卖出，6.12的交易操作怎么获得呢？
非常感谢可以抽出一点时间答疑

**Comment by 1eunght** [comment]
Similar problem. After we dumped the newest data from Jqdata into .bin files and tried to test, the prediction only ends on "2021-06-11". The transaction details are also weird.
Noticing that the v2 Yahoo CN data also updates to 2021-06, I wonder is it possible that the [dump_bin.py](https://github.com/microsoft/qlib/blob/main/scripts/dump_bin.py) is set to use the date of Yahoo CN v2? Therefore, the prediction aborts because of the truncated data or process? If that is the case, how to modify the scripts to make predictions?
Thanks a lot!!

同问，使用jqdata的最新数据并dump为bin文件后，预测的结果同样只到2021-06-11，查看交易明细结果都是异常的。
留意到Yahoo的CN数据同样是更新到2021年6月，有没有可能是[dump_bin.py](https://github.com/microsoft/qlib/blob/main/scripts/dump_bin.py)有设置使用Yahoo的数据日期，因此在dump过程中数据截断了？如果是的话，应该如何设置呢？
感谢作者的解答！！

### Screenshot
![image](https://user-images.githubusercontent.com/63780886/145340643-5d6ccf04-1cfc-4bd6-827a-032d954ec7fb.png)
![image](https://user-images.githubusercontent.com/63780886/145340729-7b76abe6-66d6-4e2b-89c1-04670d18083e.png)

**Comment by zhupr** [comment]
> 你好作者，有一点比较困惑的是，根据观察，CN的交易数据是到2021年6月11号的，预测的结果也是到6.11号，但是交易明细和持仓信息没有到6.11，到6.10就结束了。 按照真实的使用场景，假设今天是6.11，6.11下午交易结束了，交易结束后获得了最新的6.11股票数据，这时需要知道明天怎么买入卖出，6.12的交易操作怎么获得呢？ 非常感谢可以抽出一点时间答疑

@benduofen007 Hi，
持仓信息到6.10的问题已经在这里修复了(https://github.com/microsoft/qlib/pull/719/commits/236ab6ec0aa7e6089795ef2eacb1f5b077d3c9e7#diff-0bfa3d82b4c66a0a5c04a89164a40cbd981b4ced02151a75af6286f48f4c1367L73), 把代码更新到最新重试下看看是否正常：
- `git clone https://github.com/microsoft/qlib.git `
- `cd qlib && python setup.py install`

对于下个交易日怎么操作，可以参考这个：https://github.com/microsoft/qlib/issues/722#issuecomment-984690526

**Comment by zhupr** [comment]
> Similar problem. After we dumped the newest data from Jqdata into .bin files and tried to test, the prediction only ends on "2021-06-11". The transaction details are also weird. Noticing that the v2 Yahoo CN data also updates to 2021-06, I wonder is it possible that the [dump_bin.py](https://github.com/microsoft/qlib/blob/main/scripts/dump_bin.py) is set to use the date of Yahoo CN v2? Therefore, the prediction aborts because of the truncated data or process? If that is the case, how to modify the scripts to make predictions? Thanks a lot!!
> 
> 同问，使用jqdata的最新数据并dump为bin文件后，预测的结果同样只到2021-06-11，查看交易明细结果都是异常的。 留意到Yahoo的CN数据同样是更新到2021年6月，有没有可能是[dump_bin.py](https://github.com/microsoft/qlib/blob/main/scripts/dump_bin.py)有设置使用Yahoo的数据日期，因此在dump过程中数据截断了？如果是的话，应该如何设置呢？ 感谢作者的解答！！
> 
> ### Screenshot
> ![image](https://user-images.githubusercontent.com/63780886/145340643-5d6ccf04-1cfc-4bd6-827a-032d954ec7fb.png) ![image](https://user-images.githubusercontent.com/63780886/145340729-7b76abe6-66d6-4e2b-89c1-04670d18083e.png)

@1eunght Hi，
jqdata的数据不能直接更新到Yahoo CN数据上；因为Yahoo数据做了一些操作(除以第一天的close)，可以使用这个脚本把jqdata的数据append到Yahoo CN数据上: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/yahoo/collector.py
- `python collector.py normalize_data_1d_extend --old_qlib_dir <yahoo cn qlib data> --source_dir <jqdata csv> --normalize_dir <jqdata normalize csv> --region CN --interval 1d`
- `python scripts/dump_bin.py dump_update --csv_path <jqdata normalize csv> --qlib_dir <yahoo cn qlib data> --freq day --date_field_name <date> --symbol_field_name <symbol> --exclude_fields <symbol,date>`
具体参考: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/yahoo/collector.py#L954

**不建议把两个不同数据源的数据合并到一起，因为复权算法可能不同；建议使用同一个数据源的数据**

**Comment by 1eunght** [comment]
@zhupr  
我没有用Yahoo的数据，只用了jqdata。问题与楼主的相同，并已经通过更新代码解决了。非常感谢！

**Comment by benduofen007** [comment]
更新代码后https://github.com/microsoft/qlib/blob/125922b77aec41f493c54822caf1af11548751b6/qlib/backtest/utils.py#L117 
self._calendar[calendar_index], epsilon_change(self._calendar[calendar_index + 1])回测报错IndexError: index 3995 is out of bounds for axis 0 with size 3995 ，end_index 可能大于了len(self._calendar)，是否可以修改类似下面的逻辑：
 end_index = calendar_index + 1
 if end_index >= len(self._calendar):
      end_index = len(self._calendar) - 1
return self._calendar[calendar_index], epsilon_change(self._calendar[end_index])

**Comment by zhupr** [comment]
> 更新代码后
> 
> https://github.com/microsoft/qlib/blob/125922b77aec41f493c54822caf1af11548751b6/qlib/backtest/utils.py#L117
> 
> 
> self._calendar[calendar_index], epsilon_change(self._calendar[calendar_index + 1])回测报错IndexError: index 3995 is out of bounds for axis 0 with size 3995 ，end_index 可能大于了len(self._calendar)，是否可以修改类似下面的逻辑：
> end_index = calendar_index + 1
> if end_index >= len(self._calendar):
> end_index = len(self._calendar) - 1
> return self._calendar[calendar_index], epsilon_change(self._calendar[end_index])

qlib数据中有个day_future.txt，表示未来一年的交易日；可以利用这个文件来解决这个错误，在获取calendar的时候指定future=True： `D.calendar(future=True)`, 这个bug在这里修复了：https://github.com/microsoft/qlib/pull/751
