### ISSUE TITLE
Change to MLP Model "mat1 and mat2 shapes cannot be multiplied"

### ISSUE THREAD

**Issue by hhr8** [microsoft/qlib#736]
## 🐛 Bug Description

I follow the [benchmark"workflow_config_mlp"](https://github.com/microsoft/qlib/blob/main/examples/benchmarks/MLP/workflow_config_mlp_Alpha158.yaml) to change the model config from default LGBMModel to MLP, but was unable to run the workflow.
 

## Expected Behavior

use MLP model to run the demo work_flow_by_code.py

## Screenshot

![image](https://user-images.githubusercontent.com/95335092/145330167-a3c53e83-56f3-41e8-a263-0fb7b40f10cd.png)

## Environment

 - Qlib version: 0.7.2.99
 - Python version: 3.8
 - OS (`Windows`, `Linux`, `MacOS`): `Windows`
 - Commit number (optional, please provide it if you are using the dev version):

**Comment by Wangwuyi123** [comment]
@hhr8 
可以具体说说你将config修改成什么，或者发一下修改后的脚本，我来测试一下

**Comment by Wangwuyi123** [comment]
@hhr8 
Tell me specifically what you changed the config to, or send a modified script and I'll test it.
