### ISSUE TITLE
为什么example 中model rolling 在更新 config的时候，仅更新了segment 而没有更新handler中的fit_start_time 和end_time

### ISSUE THREAD

**Issue by louis-xuy** [microsoft/qlib#737]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

**Comment by louis-xuy** [comment]
执行 ：  python .\examples\model_rolling\task_manager_rolling.py main

出现结果
 {'dataset': {'class': 'DatasetH',
              'kwargs': {'handler': {'class': 'Alpha158',
                                     'kwargs': {'end_time': '2021-12-31',
                                                'fit_end_time': '2015-12-31',
                                                'fit_start_time': '2013-01-01',
                                                'instruments': 'csi300',
                                                'start_time': '2014-01-01'},
                                     'module_path': 'qlib.contrib.data.handler'},
                         'segments': {'test': (Timestamp('2017-12-05 00:00:00'),
                                               Timestamp('2018-11-07 00:00:00')),
                                      'train': (Timestamp('2013-12-13 00:00:00'),
                                                Timestamp('2016-12-05 00:00:00')),
                                      'valid': (Timestamp('2016-12-06 00:00:00'),
                                                Timestamp('2017-12-04 00:00:00'))}},
              'module_path': 'qlib.data.dataset'},

**Comment by you-n-g** [comment]
@louis-xuy  Thanks for your reporting
We'll try to solve this problem.

A quick solution I come up with is to enhance the feature of placeholder.  Make it possible to automatically fill the time from the segments to `fit_start_time` and `fit_end_time`
https://github.com/microsoft/qlib/blob/7cb1f7cee01c7de6fcc65e75e413406499b0604d/qlib/model/trainer.py#L53

**Comment by you-n-g** [comment]
If you are interested in this feature, you can also try to send a PR to fix this issue and become [one of the contributors of Qlib](https://github.com/microsoft/qlib/graphs/contributors)!

**Comment by you-n-g** [comment]
@louis-xuy 
This feature has been implemented here
https://github.com/microsoft/qlib/pull/773

Please try if it meets your requirements.

**Comment by quant2008** [comment]
滚动案例中似乎仍然没有改变fit时间。我看了如下修订似乎改正了。但是搜索qlib目录，没发现哪里调用了如下函数，这是不是说明滚动按理并没有调用如下函数来确定fit时间？

def get_data_handler_config(
    start_time="2008-01-01",
    end_time="2020-08-01",
    fit_start_time="<dataset.kwargs.segments.train.0>",
    fit_end_time="<dataset.kwargs.segments.train.1>",
    instruments=CSI300_MARKET,
):
