### ISSUE TITLE
met a bug when running the example:cannot import name 'backtest' from 'qlib.contrib.evaluate'

### ISSUE THREAD

**Issue by aiot-tech** [microsoft/qlib#738]
## To Reproduce

1.jupyter 运行 workflow_by_code.ipynb以下代码时
---------------------------------------------------------------------------
```python
import qlib
import pandas as pd
from qlib.config import REG_CN
from qlib.contrib.model.gbdt import LGBModel
from qlib.contrib.data.handler import Alpha158
from qlib.contrib.evaluate import (
    backtest as normal_backtest,
    risk_analysis,
)
from qlib.utils import exists_qlib_data, init_instance_by_config
from qlib.workflow import R
from qlib.workflow.record_temp import SignalRecord, PortAnaRecord
from qlib.utils import flatten_dict
```
出现Error:
---------------------------------------------------------------------------
```Please install necessary libs for CatBoostModel.
ImportError                               Traceback (most recent call last)
<ipython-input-3-c5163a916697> in <module>
      4 from qlib.contrib.model.gbdt import LGBModel
      5 from qlib.contrib.data.handler import Alpha158
----> 6 from qlib.contrib.evaluate import (
      7     backtest as normal_backtest,
      8     risk_analysis,

ImportError: cannot import name 'backtest' from 'qlib.contrib.evaluate'
```

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version:'0.8.0.99
 - Python version:3.8.5 
 - OS (`Windows`, `Linux`, `MacOS`):Windows
 - Commit number (optional, please provide it if you are using the dev version):main-branch e50ad4309e997c3ef9d4cf9467dac3a81b8ca7b9

**Comment by zhupr** [comment]
@aiot-tech Hi,
Delete  the following code(fixed: https://github.com/microsoft/qlib/pull/740):
```python
from qlib.contrib.model.gbdt import LGBModel
from qlib.contrib.data.handler import Alpha158
from qlib.contrib.evaluate import (
    backtest as normal_backtest,
    risk_analysis,
)
```

**Comment by aiot-tech** [comment]
Thanks a lot!

**Comment by zhupr** [comment]
@aiot-tech Hi,
Which script is being run?
What environment is it: `python scripts\collect_info.py all`

**Comment by aiot-tech** [comment]
hi@zhupr，the environment is :
```
Windows
AMD64
Windows-10-10.0.19041-SP0
10.0.19041

Python version: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]

Qlib version: 0.8.0.99
numpy==1.21.4
pandas==1.3.4
scipy==1.7.3
requests==2.26.0
sacred==0.8.2
python-socketio==5.5.0
redis==4.0.2
python-redis-lock==3.7.0
schedule==1.1.0
cvxpy==1.1.17
hyperopt==0.1.1
fire==0.4.0
statsmodels==0.13.1
xlrd==2.0.1
plotly==5.4.0
matplotlib==3.5.0
tables==3.6.1
pyyaml==6.0
mlflow==1.22.0
tqdm==4.62.3
loguru==0.5.3
lightgbm==3.3.1
tornado==6.1
joblib==1.1.0
fire==0.4.0
ruamel.yaml==0.17.17
```

**Comment by zhupr** [comment]
> hi@zhupr，the environment is :
> 
> ```
> Windows
> AMD64
> Windows-10-10.0.19041-SP0
> 10.0.19041
> 
> Python version: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
> 
> Qlib version: 0.8.0.99
> numpy==1.21.4
> pandas==1.3.4
> scipy==1.7.3
> requests==2.26.0
> sacred==0.8.2
> python-socketio==5.5.0
> redis==4.0.2
> python-redis-lock==3.7.0
> schedule==1.1.0
> cvxpy==1.1.17
> hyperopt==0.1.1
> fire==0.4.0
> statsmodels==0.13.1
> xlrd==2.0.1
> plotly==5.4.0
> matplotlib==3.5.0
> tables==3.6.1
> pyyaml==6.0
> mlflow==1.22.0
> tqdm==4.62.3
> loguru==0.5.3
> lightgbm==3.3.1
> tornado==6.1
> joblib==1.1.0
> fire==0.4.0
> ruamel.yaml==0.17.17
> ```

@aiot-tech 
I can't reproduce this error here, can you provide more information or a script to reproduce this error?

**Comment by aiot-tech** [comment]
ok! I will try it again.Thanks a lot~
