### ISSUE TITLE
Video tutorial suggestion

### ISSUE THREAD

**Issue by Queituron** [microsoft/qlib#745]
Hi all, 

I have a small suggestion: the creation of a video tutorial on the execution of the qlib workflow, mainly for USA stocks. Despite the documentation and some tips found here on github, I still have difficulties running and understanding how the program works, precisely because I am a beginner in quantitative AI-oriented. A video tutorial would help us (beginners) get started in the area.

Thanks!

**Comment by you-n-g** [comment]
QLib is under active development currently.
It is a good idea to create a video tutorial after it becomes stable.

Thanks for your attention and suggestion :)
