### ISSUE TITLE
Typo in DataHandlerLP section

### ISSUE THREAD

**Issue by ChiahungTai** [microsoft/qlib#746]
## 📖 Documentation

See https://qlib.readthedocs.io/en/latest/component/data.html#datahandlerlp:

In order to achieve so, Qlib provides a base class qlib.data.dataset.DataHandlerLP. The core idea of this class is that: we will have some leanable Processors which can learn the parameters of data processing(e.g., parameters for zscore normalization). 
                   ^^^^^^ learnable

**Comment by zhupr** [comment]
@ChiahungTai   Thanks for your reporting
If you are interested in this feature, you can also try to send a PR to fix this issue and become [one of the contributors of Qlib!](https://github.com/microsoft/qlib/graphs/contributors)

**Comment by ChiahungTai** [comment]
NP! Will do.

**Comment by ChiahungTai** [comment]
Merged.
