### ISSUE TITLE
The format of description of process_data is weird.

### ISSUE THREAD

**Issue by ChiahungTai** [microsoft/qlib#747]
## 📖 Documentation

See https://qlib.readthedocs.io/en/latest/component/data.html#qlib.data.dataset.handler.DataHandlerLP.process_data

The format below looks weird to me.
<img width="771" alt="Screen Shot 2021-12-16 at 6 41 47 AM" src="https://user-images.githubusercontent.com/2509830/146276162-83e76791-6bad-4379-b41c-679b30eb514c.png">

**Comment by zhupr** [comment]
@ChiahungTai Thanks for your reporting
We'll try to solve this problem.
If you are interested in this feature, you can also try to send a PR to fix this issue and become [one of the contributors of Qlib!](https://github.com/microsoft/qlib/graphs/contributors)

**Comment by ChiahungTai** [comment]
NP! Will do.
