### ISSUE TITLE
is it possible to update with a subset of all stocks in a market?

### ISSUE THREAD

**Issue by wan9c9** [microsoft/qlib#748]
Hi,

Is it possible to update only a subset of all stocks, for example, only sp500 components, by the collector?

Thanks!

**Comment by zhupr** [comment]
@wan9c9 Hi,
Need to change the code of the collector: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/yahoo/collector.py#L254
```python
    def get_instrument_list(self):
        logger.info("get US stock symbols......")
        import qlib
        from qlib.data import D

        qlib.init(provider_uri="~/.qlib/qlib_data/us_data")
        symbols = D.list_instruments(D.instruments("SP500"), as_list=True) + [
            "^GSPC",
            "^NDX",
            "^DJI",
        ]
        logger.info(f"get {len(symbols)} symbols.")
        return symbols
```

and then execute : `python collector.py download_data --source_dir ~/.qlib/stock_data/source/us_1d --start 2020-01-01 --end 2020-12-31 --delay 1 --interval 1d --region US` 
reference: https://github.com/microsoft/qlib/tree/main/scripts/data_collector/yahoo#collector-yahoofinance-data-to-qlib

**Comment by wan9c9** [comment]
Thanks a lot! It would be great if there could be an option so that one can specify a symbol set at the command line, rather than modifying the code directly. 

Will this be a reasonable feature request?

Thanks!

Chao

**Comment by zhupr** [comment]
> Thanks a lot! It would be great if there could be an option so that one can specify a symbol set at the command line, rather than modifying the code directly.
> 
> Will this be a reasonable feature request?
> 
> Thanks!
> 
> Chao

This is a reasonable requirement and can be added to [`utils.py`](https://github.com/microsoft/qlib/blob/main/scripts/data_collector/utils.py#L220):`def get_sp500_stock_symbol`
If you are interested in this feature, you can also try to send a PR to fix this issue and become [one of the contributors of Qlib!](https://github.com/microsoft/qlib/graphs/contributors)
