### ISSUE TITLE
framework.svg is not showing.

### ISSUE THREAD

**Issue by ChiahungTai** [microsoft/qlib#749]
## 📖 Documentation

In https://qlib.readthedocs.io/en/latest/component/highfreq.html, the framework.svg is not available.

See below diagram.
<img width="791" alt="Screen Shot 2021-12-16 at 2 19 38 PM" src="https://user-images.githubusercontent.com/2509830/146318874-da8d75a3-f380-483a-94e9-a4f5de9c610e.png">

**Comment by zhupr** [comment]
@ChiahungTai Hi,
I can access here is normal, is the network reason, you can try to refresh more times
![image](https://user-images.githubusercontent.com/18660661/146399106-8d878f4b-e6ce-495b-b567-90157e978497.png)

**Comment by ChiahungTai** [comment]
Yes, it is netwrok reason. Close this issue.

**Comment by Junzhilan123** [comment]
我也是正常打开的
