### ISSUE TITLE
Use custom operator

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#752]
Suppose I have implemented a custom operator `FooOperator(ElemOperator)`, and want to use it on labels:` 'label': ["FooOperator(Ref($close, -2) / Ref($close, -1) - 1)"]`. How can I import the operator from an outside file (not in the qlib git) to be recognized by the workflow?

**Comment by zhupr** [comment]
@2young-2simple-sometimes-naive Hi,
```Python
qlib.init(custom_ops=[FooOperator])
```
Reference: https://github.com/microsoft/qlib/blob/main/tests/test_register_ops.py#L51
