### ISSUE TITLE
bug in update script?

### ISSUE THREAD

**Issue by takacsg84** [microsoft/qlib#758]
https://github.com/microsoft/qlib/blob/3480fd932fe38b04b4ebc7cf06ce423c9650b56a/scripts/dump_bin.py#L462

Shouldn't this be 

`                        _df[_df[self.date_field_name] > self._update_instruments[_code][self.INSTRUMENTS_END_FIELD]][`

instead?

**Comment by Wangwuyi123** [comment]
I don't think it's a bug, but can talk about how you realized it was a bug

**Comment by you-n-g** [comment]
@takacsg84 
Sorry for the uninformative response,  we'll look into the code and response later.

**Comment by takacsg84** [comment]
In response to @Wangwuyi123  : i thought that the point of that method is to add new information that is not already there, that's why i thought that we should care about data that is after the end date and the start date.

**Comment by zhupr** [comment]
@takacsg84 Thank you for your feedback
Fixed: https://github.com/microsoft/qlib/pull/783
