### ISSUE TITLE
qlib/scripts/data_collector/cn_index/collector.py seems not able to request the web page

### ISSUE THREAD

**Issue by wan9c9** [microsoft/qlib#759]
The cn_index/collector.py seems not able to request the web page, the  res variable returned was an empty list.
  File "/home/chao/workspace/investWorkspace/src/qlib/scripts/data_collector/cn_index/collector.py", line 140, in get_changes
    return pd.concat(res, sort=False)
  File "/home/chao/.conda/envs/qlib/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 285, in concat
    op = _Concatenator(
  File "/home/chao/.conda/envs/qlib/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 342, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

Can anyone please confirm if it's a issue from the the website or from my own computer?

Thanks!

**Comment by Wangwuyi123** [comment]
It seems that this is not everyone’s mistake. Please test it again in your environment. If the same problem still exists, send out your specific environment and code.

**Comment by wan9c9** [comment]
Thanks to @Wangwuyi123's comments. I just downloaded the latest collector.py code, and tried it again, but I saw the same problem. Please see below for the errors and my conda env. Thanks!

(qlib) chao@msi:~/workspace/investWorkspace/src/qlib/scripts/data_collector/cn_index$ python collector.py --index_name CSI300 --qlib_dir ~/.qlib/qlib_data/cn_data --method parse_instruments
2021-12-22 09:58:38.837 | INFO     | data_collector.index:parse_instruments:211 - start parse csi300 companies.....
2021-12-22 09:58:38.837 | INFO     | data_collector.cn_index.collector:get_changes:134 - get companies changes......
2021-12-22 09:58:42.482 | INFO     | data_collector.cn_index.collector:get_changes:139 - get companies changes finish
Traceback (most recent call last):
  File "collector.py", line 349, in <module>
    fire.Fire(get_instruments)
  File "/home/chao/.conda/envs/qlib/lib/python3.8/site-packages/fire-0.4.0-py3.8.egg/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/chao/.conda/envs/qlib/lib/python3.8/site-packages/fire-0.4.0-py3.8.egg/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/chao/.conda/envs/qlib/lib/python3.8/site-packages/fire-0.4.0-py3.8.egg/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "collector.py", line 345, in get_instruments
    getattr(obj, method)()
  File "/home/chao/workspace/investWorkspace/src/qlib/scripts/data_collector/index.py", line 213, in parse_instruments
    changers_df = self.get_changes()
  File "/home/chao/workspace/investWorkspace/src/qlib/scripts/data_collector/cn_index/collector.py", line 140, in get_changes
    return pd.concat(res, sort=False)
  File "/home/chao/.conda/envs/qlib/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 285, in concat
    op = _Concatenator(
  File "/home/chao/.conda/envs/qlib/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 342, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
(qlib) chao@msi:~/workspace/investWorkspace/src/qlib/scripts/data_collector/cn_index$ cond env list

Command 'cond' not found, did you mean:

  command 'cons' from deb cons (2.3.0.1+2.2.0-2)

Try: sudo apt install <deb name>

(qlib) chao@msi:~/workspace/investWorkspace/src/qlib/scripts/data_collector/cn_index$ conda list
# packages in environment at /home/chao/.conda/envs/qlib:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
aiohttp                   3.8.1                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
alembic                   1.4.1                    pypi_0    pypi
alpha-vantage             2.3.1                    pypi_0    pypi
altair                    4.1.0                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
async-timeout             4.0.1                    pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
backports-zoneinfo        0.2.1                    pypi_0    pypi
base58                    2.1.1                    pypi_0    pypi
bidict                    0.21.4                   pypi_0    pypi
bleach                    4.1.0                    pypi_0    pypi
blinker                   1.4                      pypi_0    pypi
ca-certificates           2021.10.26           h06a4308_2  
cachetools                4.2.4                    pypi_0    pypi
catboost                  1.0.3                    pypi_0    pypi
certifi                   2021.10.8        py38h06a4308_0  
cffi                      1.15.0                   pypi_0    pypi
chardet                   4.0.0                    pypi_0    pypi
charset-normalizer        2.0.9                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
cloudpickle               2.0.0                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
cssselect                 1.1.0                    pypi_0    pypi
cssutils                  2.3.0                    pypi_0    pypi
cvxpy                     1.1.17                   pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.25                  pypi_0    pypi
databricks-cli            0.16.2                   pypi_0    pypi
debugpy                   1.5.1                    pypi_0    pypi
decorator                 5.1.0                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
deprecated                1.2.13                   pypi_0    pypi
dill                      0.3.4                    pypi_0    pypi
docker                    5.0.3                    pypi_0    pypi
ecos                      2.0.8                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
filelock                  3.4.0                    pypi_0    pypi
fire                      0.4.0                    pypi_0    pypi
flask                     2.0.2                    pypi_0    pypi
fonttools                 4.28.3                   pypi_0    pypi
frozenlist                1.2.0                    pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gitdb                     4.0.9                    pypi_0    pypi
gitpython                 3.1.24                   pypi_0    pypi
greenlet                  1.1.2                    pypi_0    pypi
gunicorn                  20.1.0                   pypi_0    pypi
hyperopt                  0.1.1                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
importlib-metadata        4.8.2                    pypi_0    pypi
importlib-resources       5.4.0                    pypi_0    pypi
ipykernel                 6.6.0                    pypi_0    pypi
ipython                   7.30.1                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.6.5                    pypi_0    pypi
itsdangerous              2.0.1                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.0.3                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jsonpickle                1.5.2                    pypi_0    pypi
jsonschema                4.3.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            7.1.0                    pypi_0    pypi
jupyter-console           6.4.0                    pypi_0    pypi
jupyter-core              4.9.1                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-widgets        1.0.2                    pypi_0    pypi
kiwisolver                1.3.2                    pypi_0    pypi
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgomp                   9.3.0               h5101ec6_17  
libstdcxx-ng              9.3.0               hd4cf53a_17  
lightgbm                  3.3.1                    pypi_0    pypi
loguru                    0.5.3                    pypi_0    pypi
lxml                      4.7.1                    pypi_0    pypi
mako                      1.1.6                    pypi_0    pypi
markupsafe                2.0.1                    pypi_0    pypi
matplotlib                3.3.3                    pypi_0    pypi
matplotlib-inline         0.1.3                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mlflow                    1.22.0                   pypi_0    pypi
multidict                 5.2.0                    pypi_0    pypi
munch                     2.5.1.dev12              pypi_0    pypi
nbclient                  0.5.9                    pypi_0    pypi
nbconvert                 6.3.0                    pypi_0    pypi
nbformat                  5.1.3                    pypi_0    pypi
ncurses                   6.3                  h7f8727e_2  
nest-asyncio              1.5.4                    pypi_0    pypi
networkx                  2.6.3                    pypi_0    pypi
notebook                  6.4.6                    pypi_0    pypi
numexpr                   2.8.1                    pypi_0    pypi
numpy                     1.21.4                   pypi_0    pypi
openssl                   1.1.1l               h7f8727e_0  
osqp                      0.6.2.post0              pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pandas                    1.2.2                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
patsy                     0.5.2                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.4.0                    pypi_0    pypi
pip                       21.2.4           py38h06a4308_0  
plotly                    5.4.0                    pypi_0    pypi
premailer                 3.10.0                   pypi_0    pypi
prometheus-client         0.12.0                   pypi_0    pypi
prometheus-flask-exporter 0.18.6                   pypi_0    pypi
prompt-toolkit            3.0.24                   pypi_0    pypi
protobuf                  4.0.0rc2                 pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
py-cpuinfo                8.0.0                    pypi_0    pypi
pyarrow                   6.0.1                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pydeck                    0.7.1                    pypi_0    pypi
pygments                  2.10.0                   pypi_0    pypi
pymongo                   3.7.2                    pypi_0    pypi
pympler                   1.0                      pypi_0    pypi
pyparsing                 3.0.6                    pypi_0    pypi
pyqlib                    0.7.2.99                 pypi_0    pypi
pyrsistent                0.18.0                   pypi_0    pypi
python                    3.8.12               h12debd9_0  
python-dateutil           2.8.2                    pypi_0    pypi
python-editor             1.0.4                    pypi_0    pypi
python-engineio           4.3.0                    pypi_0    pypi
python-graphviz           0.19.1                   pypi_0    pypi
python-redis-lock         3.7.0                    pypi_0    pypi
python-socketio           5.5.0                    pypi_0    pypi
pytz                      2021.3                   pypi_0    pypi
pytz-deprecation-shim     0.1.0.post0              pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     22.3.0                   pypi_0    pypi
qdldl                     0.1.5.post0              pypi_0    pypi
qtconsole                 5.2.2                    pypi_0    pypi
qtpy                      1.11.3                   pypi_0    pypi
querystring-parser        1.2.4                    pypi_0    pypi
readline                  8.1                  h27cfd23_0  
redis                     4.1.0rc2                 pypi_0    pypi
requests                  2.25.1                   pypi_0    pypi
requests-futures          1.0.0                    pypi_0    pypi
ruamel-yaml               0.17.17                  pypi_0    pypi
ruamel-yaml-clib          0.2.6                    pypi_0    pypi
sacred                    0.8.2                    pypi_0    pypi
schedule                  1.1.0                    pypi_0    pypi
scikit-learn              1.0.1                    pypi_0    pypi
scipy                     1.8.0rc1                 pypi_0    pypi
scs                       2.1.4                    pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
setuptools                58.0.4           py38h06a4308_0  
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.0                    pypi_0    pypi
sqlalchemy                1.4.28                   pypi_0    pypi
sqlite                    3.36.0               hc218d9a_0  
sqlparse                  0.4.2                    pypi_0    pypi
statsmodels               0.13.1                   pypi_0    pypi
streamlit                 1.3.0                    pypi_0    pypi
tables                    3.6.1                    pypi_0    pypi
tabulate                  0.8.9                    pypi_0    pypi
tenacity                  8.0.1                    pypi_0    pypi
terminado                 0.12.1                   pypi_0    pypi
testpath                  0.5.0                    pypi_0    pypi
threadpoolctl             3.0.0                    pypi_0    pypi
tk                        8.6.11               h1ccaba5_0  
toml                      0.10.2                   pypi_0    pypi
toolz                     0.11.2                   pypi_0    pypi
torch                     1.10.1                   pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
tqdm                      4.62.3                   pypi_0    pypi
traitlets                 5.1.1                    pypi_0    pypi
typing-extensions         4.0.1                    pypi_0    pypi
tzdata                    2021.5                   pypi_0    pypi
tzlocal                   4.1                      pypi_0    pypi
urllib3                   1.26.7                   pypi_0    pypi
validators                0.18.2                   pypi_0    pypi
watchdog                  2.1.6                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.2.3                    pypi_0    pypi
werkzeug                  2.0.2                    pypi_0    pypi
wheel                     0.37.0                   pypi_0    pypi
widgetsnbextension        3.5.2                    pypi_0    pypi
wrapt                     1.13.3                   pypi_0    pypi
xgboost                   1.5.1                    pypi_0    pypi
xlrd                      2.0.1                    pypi_0    pypi
xz                        5.2.5                h7b6447c_0  
yagmail                   0.14.260                 pypi_0    pypi
yahooquery                2.2.15                   pypi_0    pypi
yarl                      1.7.2                    pypi_0    pypi
zipp                      3.6.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3

**Comment by zhupr** [comment]
@wan9c9 Thank you for your feedback.
This is due to a change in the data or web structure of the CSI website, we will fix this exception as soon as possible.

**Comment by wan9c9** [comment]
Thanks. I tried to fix it myself, but didn’t know how to parse the new web
content.

**Comment by zhupr** [comment]
@wan9c9 Hi,
Fixed: https://github.com/microsoft/qlib/pull/780
