### ISSUE TITLE
why class Alpha360's fields CLOSE0 and VOLUME0 is zero

### ISSUE THREAD

**Issue by l1351868270** [microsoft/qlib#762]
## ❓ Questions and Help

I debug follow the doc:
```
Begin debug:  
    python -m pdb qlib/workflow/cli.py examples/benchmarks/Transformer/workflow_config_transformer_Alpha360.yaml
Debug commands:
    b qlib/contrib/model/pytorch_transformer.py:178
    c
    p df_train["feature"]["CLOSE0"]
    p df_train["feature"]["VOLUME0"]
Results:

datetime    instrument
2008-01-02  SH600000      0.0
            SH600004      0.0
            SH600006      0.0
            SH600007      0.0
            SH600008      0.0
                         ...
2014-12-31  SZ300070      0.0
            SZ300124      0.0
            SZ300133      0.0
            SZ300146      0.0
            SZ300251      0.0

```
The results is zero, but the code is:
```       
qlib/contrib/data/handler.py:100
    fields += ["$close/$close"]
    names += ["CLOSE0"]
qlib/contrib/data/handler.py:125
    fields += ["$volume/$volume"]
    names += ["VOLUME0"]
```
I have a confusion. I think the results will be one, but it is zero.

**Comment by Wangwuyi123** [comment]
https://qlib.readthedocs.io/en/latest/hidden/tuner.html?highlight=Alpha360

Here is our explanatory documentation on aplha360, which you can refer to

**Comment by you-n-g** [comment]
https://github.com/microsoft/qlib/pull/777/files

@l1351868270  I added some docs for Alpha360.
Can your question be answered?

Thanks.

**Comment by l1351868270** [comment]
@you-n-g Thanks. These days, i read the source code carefully. Now, I know the question why.  As the docs that you give, because of the process_type is PTYPE_A, so the learn_processors will also use the RobustZScoreNorm in the infer_processors . RobustZScoreNorm will lead the column zeros. 

ps:
I test the five type of norms:
MinMaxNorm and ZScoreNorm is one;
RobustZScoreNorm and CSZScoreNorm is zero;
CSRankNorm is not zero or one.
If further normalization are executed. What value of them depend on the formula of the normalization type.
