### ISSUE TITLE
Method to convert prediction score to label numbers (numbers before normalization)

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#767]
## 🌟 Feature Description
Suppose the pred algorithm gives the following table:

```
stock  score
A      0.14
B      0.00
C     -0.12
...
```
The scores represent the normalized labels, not the actual change in price. It is better to have a method to convert the scores back to labels before normalization, so it can be interpreted.

**Comment by you-n-g** [comment]
I added some [docs here](https://github.com/microsoft/qlib/commit/41a5778684b88700e89f7ba5f4a672f5f73d4365)
Is your question answered?

**Comment by 2young-2simple-sometimes-naive** [comment]
> I added some [docs here](https://github.com/microsoft/qlib/commit/41a5778684b88700e89f7ba5f4a672f5f73d4365) Is your question answered?

So suppose I get a series of scores 
```
stock  score
A      0.14
B      0.00
C     -0.12
```
and I want to submit an order, either long A or short C. If I compare absolute value of A and absolute value of C, abs(A.score) > abs(C.score), does this imply A has higher return in the prediction? Or the absolute value of scores does not mean anything?

**Comment by you-n-g** [comment]
The values of model prediction don't have a fixed mean.
It depends on the data and training process of the model.
