### ISSUE TITLE
bug!!! in dataset processor

### ISSUE THREAD

**Issue by xulangping** [microsoft/qlib#770]
the code use NORM processor before split train test data, which will lead to data leakage, the right correct way is fitting on the train data and then transform the test data, can you please fix the bug!!!

**Comment by you-n-g** [comment]
Hi,  @xulangping 
Thanks for your reporting. Could you please paste the link to the code of the bug?

**Comment by xulangping** [comment]
https://github.com/microsoft/qlib/blob/main/qlib/data/dataset/processor.py
in this code, i think all processor need an other transform method. 
https://github.com/microsoft/qlib/blob/main/qlib/contrib/data/handler.py
 you process data in handle before spliting the data,I think you should move the processor step to model, after spliting the data

**Comment by xulangping** [comment]
by the way, this maybe a big bug, all your yaml process the data first, then split the data, but the NORM processor will lead to data leakage, which lead to false effect preferences！！ @you-n-g

**Comment by you-n-g** [comment]
@xulangping 
I add some docs here for an explanation.
https://github.com/microsoft/qlib/pull/771/files

Does it solve your concerns?

**Comment by xulangping** [comment]
thanks
