### ISSUE TITLE
UnicodeDecodeError when install from source.

### ISSUE THREAD

**Issue by ChiahungTai** [microsoft/qlib#772]
## 🐛 Bug Description
Run python setup.py install in source code repo might cause unicode decode error in some Windows language(ex. Big5)
Error message.
UnicodeDecodeError: 'cp950' codec can't decode byte 0xe9 in position 3935: illegal multibyte sequence

## To Reproduce

1. Install from source in a Big5 Windows OS.

## Expected Behavior

No error message
## Screenshot
![image](https://user-images.githubusercontent.com/2509830/147355087-5f8ef63a-296b-41ff-b665-94881ba26688.png)

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version: 0.8.0.99
 - Python version: 3.8
 - OS (`Windows`, `Linux`, `MacOS`): Windows
 - Commit number (optional, please provide it if you are using the dev version):
ef161715f7aeb33d46fd724c8c2cd0700e55637b

**Comment by you-n-g** [comment]
Thank you  for solving this problem here https://github.com/microsoft/qlib/pull/773
