### ISSUE TITLE
Scroll backtest

### ISSUE THREAD

**Issue by codezealot** [microsoft/qlib#776]
## 🌟 Feature Description

Is there a plan to support rolling backtesting？

**Comment by you-n-g** [comment]
Yes.
It is supported in this PR
https://github.com/microsoft/qlib/pull/743/files#diff-ee20362bbe69672d6a8f1b2eff5e65e049cb2a41704a9f8ab5e0a0ea4ab50dabR89

The backtest results will be stored in mlflow.

Please try it  :)
