### ISSUE TITLE
get_recorder use self defined directory

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#786]
Suppose I am moving mlrun to another directory, how do I define R.get_recorder so it loads under another directory?

**Comment by you-n-g** [comment]
https://github.com/microsoft/qlib/blob/main/qlib/workflow/__init__.py#L337
Please use this method to set the `uri` to your _another directory_ , then  `R.get_recorder`  will run with the changed `uri` instead of the current directory.
