### ISSUE TITLE
When useing online mode ,  run D.calendar throws 'NoneType' object is not subscriptable error

### ISSUE THREAD

**Issue by hotwind2015** [microsoft/qlib#787]
## 🐛 Bug Description

it can init from yaml file , but run other error

## To Reproduce

import qlib
from qlib.data import D

qlib.init_from_yaml_conf("qlib_clinet_config.yaml")

D.calendar(start_time='2010-01-01', end_time='2021-12-30', freq='day')

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version: 0.8.0
 - Python version: 3.8.5
 - OS (`Windows`, `Linux`, `MacOS`): Windows
 - Commit number (optional, please provide it if you are using the dev version):

## Additional Notes

qlib-server is build according by https://qlib-server.readthedocs.io/en/latest/

**Comment by you-n-g** [comment]
This bug may be fixed in this PR.
Please try it to test if it works.
Thanks
