### ISSUE TITLE
How to use processor?

### ISSUE THREAD

**Issue by bbbzhai** [microsoft/qlib#789]
Hi,
I'm wondering how to use processor and what's the difference between processor and operator?
I've been reading about processor and confused on how to use it. 
For instance, `qlib.data.dataset.processor.MinMaxNorm`. 
I tried and it cannot be used like `MinMaxNorm($close)`.
So what are the use case of processor?

More specifically, I wanted to use cross sectional ranking `CSRankNorm($close)`. But I cannot achieve that. Is there anyway I can convert a processor to operator?

Thanks

**Comment by bbbzhai** [comment]
I'm happy to write some operator which can operate row-wise, if that's not currently supported. 
Wanted to run by your guys first before I start, cause I suspect it's already supported but I overlooked.

**Comment by you-n-g** [comment]
I add some docs about data processing.
https://github.com/microsoft/qlib/pull/797

Is your question answered?

**Comment by bbbzhai** [comment]
> I add some docs about data processing. #797
> 
> Stock-wise operators (I understand your `row-wise` as `stock-wise`) are not supported now.
> 
> Is your question answered?

Thanks for your comments. I was looking for stock-wise operators. Since it's not currently supported, I will try something else.
Thanks!

**Comment by bbbzhai** [comment]
btw, what's the difference between infer_processor and learn_processor?

> Is this processor usable for inference Some processors are not usable for inference.

I see this statement from the docs. Could you provide an example to clarify the difference? Thanks.

**Comment by bbbzhai** [comment]
I wrote a processor to test for myself. I added a new column to the dataframe.
I also try to use `DropCol` processor
However, when I try to print it with `dataset.prepare("train")`, I couldn't see the column I added and the columns I dropped are still there.
Can anybody help?

**Comment by bbbzhai** [comment]
I can see in checkpoint https://github.com/microsoft/qlib/blob/a67f67db6e175791e1e0f4e3bb818da394c8e522/qlib/data/dataset/handler.py#L414
that the df returned was dropped column and my new columns added. 
But when I check with `dataset.prepare("train")`, it's not there anymore.

**Comment by bbbzhai** [comment]
I realized the data that get train are the ones that after processed, but in `dataset.prepare("train")` it shows the original dataframe. Is this a bug?
I still don't understand `learn_processor` and `infer_processor`.

**Comment by you-n-g** [comment]
@bbbzhai
Sorry for the late response
You understand it correctly
I added some docs just now. 

Can https://github.com/microsoft/qlib/pull/879/files answer your question?
