### ISSUE TITLE
How to define a list of shares (20 us shares for example) for predicting? Rather than the entire nasdaq100 or sp500?

### ISSUE THREAD

**Issue by orchardc** [microsoft/qlib#794]
How to define a list of shares (20 us shares for example) for predicting? Rather than the entire nasdaq100 or sp500?

Is there a sample?

Many thanks!

**Comment by you-n-g** [comment]
There are two approaches I come up with now.
1. You can follow the example here  ~/.qlib/qlib_data/cn_data/instruments to define your own universe. And create a dataset based on this universe.
2. If you want to train the model on a larger universe and test data on a smaller universe, you can filter your data when model inference. You can define some processors which only apply to inference data https://github.com/microsoft/qlib/blob/main/qlib/data/dataset/handler.py#L442

**Comment by orchardc** [comment]
Thank you-n-g, for your #1 suggestion.

For quick testing:
I create a file called: **nasdaq2.txt**  that includes 2 records copied from the sample file, then put in the **instruments**  folder.
![image](https://user-images.githubusercontent.com/16193516/147986740-b477f14b-be12-4dd6-81a1-ac6ebb44bf52.png)

Then change the `market = "NASDAQ2"` in the .ipynb file.
![image](https://user-images.githubusercontent.com/16193516/147986801-e3610026-ccf7-4f58-806c-5b9f47b572c3.png)

Is that everything or do I need to change something else? The purpose is only to use these 2 stocks for training and testing.

In the prediction result, I got:
![image](https://user-images.githubusercontent.com/16193516/147986945-0d3b849e-3b68-49b3-87ee-8467470cbf23.png)
![image](https://user-images.githubusercontent.com/16193516/147986982-925adae2-767e-474e-8e1c-93dd4ab168ba.png)

**Comment by orchardc** [comment]
Any idea? @you-n-g

**Comment by you-n-g** [comment]
@orchardc 
It looks like your model learned nothing (the initial model gets the lowest loss and predicts the same value for all samples).

**Comment by you-n-g** [comment]
I think more data will be helpful

**Comment by orchardc** [comment]
Thanks @you-n-g , I think you are right! With more stocks, I start seeing some data...although I'd like the model to only use selective stocks for training/testing.

**Comment by orchardc** [comment]
The NASDAQ prediction result isn't good, but I guess the sample workflow was designed for CSI300, not for the US market.

![image](https://user-images.githubusercontent.com/16193516/148306597-8d28d5ab-3787-4612-8537-f28bd2d9ab02.png)
