### ISSUE TITLE
 No module named 'qlib.tests'

### ISSUE THREAD

**Issue by aGiant** [microsoft/qlib#80]
## ❓ Questions and Help

!git clone https://github.com/microsoft/qlib
!python ./qlib/scripts/get_data.py qlib_data_cn --target_dir ./qlib/qlib_data/cn_data

-> Traceback (most recent call last):
  File "./qlib/scripts/get_data.py", line 4, in <module>
    from qlib.tests.data import GetData
ModuleNotFoundError: No module named 'qlib.tests'

**Comment by you-n-g** [comment]
Please  install qlib first by `python setup.py install`

**Comment by you-n-g** [comment]
@aGiant 
Your command is form the old version.
Please use the latest command in the index README.md
`python scripts/get_data.py qlib_data --target_dir ~/.qlib/qlib_data/cn_data --region cn`

**Comment by aGiant** [comment]
> setup.py install

Error in Colab:

!python qlib/setup.py install

--> 
/usr/local/lib/python3.6/dist-packages/setuptools/dist.py:452: UserWarning: Normalizing '0.6.0.dev' to '0.6.0.dev0'
  warnings.warn(tmpl.format(**locals()))
running install
running bdist_egg
running egg_info
creating pyqlib.egg-info
writing pyqlib.egg-info/PKG-INFO
writing dependency_links to pyqlib.egg-info/dependency_links.txt
writing entry points to pyqlib.egg-info/entry_points.txt
writing requirements to pyqlib.egg-info/requires.txt
writing top-level names to pyqlib.egg-info/top_level.txt
writing manifest file 'pyqlib.egg-info/SOURCES.txt'
reading manifest file 'pyqlib.egg-info/SOURCES.txt'
writing manifest file 'pyqlib.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
cythoning qlib/data/_libs/rolling.pyx to qlib/data/_libs/rolling.cpp
creating qlib/data
creating qlib/data/_libs
error: /content/qlib/data/_libs/rolling.pyx

**Comment by you-n-g** [comment]
@aGiant 
Please install Cython. 
Thanks
![image](https://user-images.githubusercontent.com/465606/101637067-3464dd00-3a67-11eb-8b1b-a8aa46342d5e.png)

**Comment by aGiant** [comment]
> @aGiant
> Please install Cython.
> Thanks
> ![image](https://user-images.githubusercontent.com/465606/101637067-3464dd00-3a67-11eb-8b1b-a8aa46342d5e.png)

**Requirement already up-to-date: cython in /usr/local/lib/python3.6/dist-packages (0.29.21)**
/usr/local/lib/python3.6/dist-packages/setuptools/dist.py:452: UserWarning: Normalizing '0.6.0.dev' to '0.6.0.dev0'
  warnings.warn(tmpl.format(**locals()))
running install
running bdist_egg
running egg_info
writing pyqlib.egg-info/PKG-INFO
writing dependency_links to pyqlib.egg-info/dependency_links.txt
writing entry points to pyqlib.egg-info/entry_points.txt
writing requirements to pyqlib.egg-info/requires.txt
writing top-level names to pyqlib.egg-info/top_level.txt
reading manifest file 'pyqlib.egg-info/SOURCES.txt'
writing manifest file 'pyqlib.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
cythoning qlib/data/_libs/rolling.pyx to qlib/data/_libs/rolling.cpp
error: /content/qlib/data/_libs/rolling.pyx

**Comment by you-n-g** [comment]
There some issue with Cython on Python 3.6, Please try python 3.7 or 3.8. 
Thanks

**Comment by aGiant** [comment]
installed using python 3.7 but got errors by running examples/workflow_by_code.ipynb.

Have you guys tested the "examples/workflow_by_code.ipynb" notebook?

None same results for "Cumulative Return of groups" as posted on GitHub page and analysis_model.model_performance_graph(pred_label) returns "Spine object has no attribute 'is_frame_like'"...

**Comment by zhupr** [comment]
@aGiant
Please update matplotlab and plotly:
```bash
python -m pip install -U matplotlib==3.1.3 plotly==4.12.0
```
Thanks

**Comment by aGiant** [comment]
> @aGiant
> Please update matplotlab and plotly:
> 
> ```shell
> python -m pip install -U matplotlib==3.1.3 plotly==4.12.0
> ```
> 
> Thanks

This worked, many thanks 👍
