### ISSUE TITLE
Outliers in prediction score

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [microsoft/qlib#800]
What does the outliers in prediction score mean. For example:
```
       datetime instrument     score
1944 2021-12-31       TADS  3.052688
242  2021-12-31       CBSE  0.212113
255  2021-12-31        CHB  0.209660
545  2021-12-31       EWCO  0.207444
1884 2021-12-31       SPQQ  0.193577
...         ...        ...       ...
63   2021-12-31       ARKG -0.665926
1695 2021-12-31       RIGZ -0.673914
64   2021-12-31       ARKK -0.675445
1342 2021-12-31       MJXL -0.705074
1970 2021-12-31       THCX -0.834564
```
The TADS is apparently an outlier. Should it be considered as unreliable for TADS?

**Comment by you-n-g** [comment]
As far as I know, I don't find a general solution to explain these predictions with extreme values.

It depends on your data and model.
Maybe there are similar examples in your training data and your model overfits these examples.
