### ISSUE TITLE
Data Retrieval for a list of stock.

### ISSUE THREAD

**Issue by bbbzhai** [microsoft/qlib#804]
qlib's data retrieval is very useful. I use it as a database.
Is there anyway that I can query one stock or provide a list?

I see from https://qlib.readthedocs.io/en/latest/start/getdata.html that I can query based on namefilter.

What if I want to query say APPL, FB? 
Is there any way that I can do: 
```>> from qlib.data import D
>> from qlib.data.filter import NameDFilter
>> nameDFilter = NameDFilter(name_list=['AAPL', 'FB'])
>> instruments = D.instruments(market='sp500', filter_pipe=[nameDFilter])
```

**Comment by wan9c9** [comment]
From the same html in your link, there is an example:

>> from qlib.data import D
>> instruments = ['SH600000']
>> fields = ['$close', '$volume', 'Ref($close, 1)', 'Mean($close, 3)', '$high-$low']
>> D.features(instruments, fields, start_time='2010-01-01', end_time='2017-12-31', freq='day').head()

                           $close     $volume  Ref($close, 1)  Mean($close, 3)  $high-$low
   instrument  datetime
   SH600000    2010-01-04  86.778313  16162960.0       88.825928        88.061483    2.907631
               2010-01-05  87.433578  28117442.0       86.778313        87.679273    3.235252
               2010-01-06  85.713585  23632884.0       87.433578        86.641825    1.720009
               2010-01-07  83.788803  20813402.0       85.713585        85.645322    3.030487
               2010-01-08  84.730675  16044853.0       83.788803        84.744354    2.047623


So I think you can set 
>> instruments = ['AAPL', 'FB']

then query similarly as the example above.

**Comment by bbbzhai** [comment]
Can't believe I miss that example! 
Thanks!
