### ISSUE TITLE
Converting data to qlib format

### ISSUE THREAD

**Issue by bbbzhai** [microsoft/qlib#810]
What's the recommended way of converting qlib data?

I have a new set of data coming in csv everyday.
The data will be consist of two part:
1. new data of unadjusted stocks
2. new data of adjusted stocks as well as their adjusted historical data.

I see qlib have three dump feature: `dump_all`, `dump_update`, `dump_fix`. Their respective function is explained in #535 

> The dump has three classes:
> - `DumpDataAll`: dump all data
>   - Dump all data from `csv_pat`h into `qlib_dir`, which will **`overwrite all`** data (calendars/instruments/features)
> - `DumpDataFix`: adding a *`new field`*, *`symbol`*, *`rewriting of an existing field`*
>   - Dumping data from `csv_path` into `qlib_dir` will **`overwrite existing`** features data; if ***new fields*** are added, they will be added according to `qlib_dir/calendars/<freq>.txt` and the `qlib_dir/instruments/all. txt` file, **without modifying existing data**
>  - `DumpDataUpdate`: append new data to existing data
>     - **append** the data from `csv_path` to the existing data

Currently, the dump feature part of dump_update takes roughly the same time as `dump_all`, sometimes more. Note I don't have new features, all the features are **_the same_** as my initial dump_all

And if I understand correctly, I have to do a separate dump_fix to fix the old data if they split or dividend that day. 

So all I did now is:
1. separate data in two folder: only_append_folder, fix_historical_and_append_folder.
2. `dump_update only_append_folder`
3. `dump_fix fix_historical_and_append_folder `

Is this the correct procedure?

Maybe an enhancement on dump_update?

**Comment by Wangwuyi123** [comment]
@bbbzhai 
hi,Here is the document about CSV conversion to Qlib format
https://qlib.readthedocs.io/en/latest/component/data.html#converting-csv-format-into-qlib-format

**Comment by Wangwuyi123** [comment]
If you don't have new features, you can skip `dump_fix fix_historical_and_append_folder`

split&dividend does not affect dump_bin.

**Comment by bbbzhai** [comment]
> If you don't have new features, you can skip `dump_fix fix_historical_and_append_folder`
> 
> split&dividend does not affect dump_bin.

cool! This is what I hope it should achieve. Thanks!
