### ISSUE TITLE
not to create env everytime 

### ISSUE THREAD

**Issue by jeffzhengye** [microsoft/qlib#814]
everytime, I run the experiments, qlib creates a new env in the /tmp fold.
Is there a way that I can fix the env? It takes too much doing this and it's unnecessary for experiments.

**Comment by Wangwuyi123** [comment]
Can you specifically talk about your experiments

**Comment by jeffzhengye** [comment]
Isn't that for all the experiments? 
It doesn't matther what experiments you do. qlib just has to create a new env and install all the python lib in requirements. 
It's very time cosuming. Just don't understand why we need that?

I just did: python run_all_model.py run --models=add --qlib_uri=/mnt/d/code/quant/qlib

**Comment by Wangwuyi123** [comment]
@jeffzhengye 
Each workflow has a different env, so multiple environments will be created when run_all_models is used, and the corresponding env will be deleted by default after the model execution ends. The specific deletion is as follows`https://github.com/microsoft/qlib/blob/main/examples/run_all_model.py#L358`

**Comment by jeffzhengye** [comment]
The point is creating a new env is very very time comsuming. 
Why we need to create a new one even when we just repete the same experiment or just due to reboot? 
I know exactly how the code runs.

**Comment by Wangwuyi123** [comment]
We understand what you want us to do
I think we can add whether env is deleted by default to the run argument
But we have no time to add this feature right now, would you be interested in becoming a Qlib contributor

**Comment by you-n-g** [comment]
I think adding two parameters to  `run_all_models.py` will support this feature
1. specify which environment to run the experiment to avoid recreating a new environment.
2. Whether to delete the environment after experiment
