### ISSUE TITLE
How can I get the constituents stocks list of csi300 in the dataset?

### ISSUE THREAD

**Issue by Waterkin** [microsoft/qlib#817]
## ❓ Questions and Help

I want to know what the constituent stocks of csi300 is during the whole training and testing period? 
How can I get the list of the training stocks?
If I do 
`inst = D.list_instruments(D.instruments(market='csi300'),start_time='2008-01-01', end_time='2020-08-01', freq="day", as_list=True)`
it returns a list of 690 stocks(not 300), which is extremely strange.

**Comment by Waterkin** [comment]
Find it in ~/.qlib/qlib_data/cn_data/instruments

**Comment by Wangwuyi123** [comment]
@Waterkin 
You can refer to issure `https://github.com/microsoft/qlib/issues/823#issuecomment-1008593482`
