### ISSUE TITLE
Workflow questions

### ISSUE THREAD

**Issue by Queituron** [microsoft/qlib#820]
First of all, thanks to you developers and Qlib contributors. This platform is contributing to my learning of the Quant world and especially Python programming, topics that I'm still a beginner.

I'm from Brazil and running Qlib strategies for brazilian stocks. Luckily I managed to convert my dataset originally from CSV to qlib format and it seems to be working. 

That's why I have some doubts about the workflow, which if solved, will help me to flow in the work here.

1. In “market” do I define a benchmark for my country? In Brazil we use the IBOVESPA benchmark, but as I have not yet selected the stocks that make up the index, I left this option as “all”. Whereas the “market” option is where I define the benchmark. What is the “benchmark” option in the workflow? lol is confusing to me. Was it my portfolio?

![image](https://user-images.githubusercontent.com/70342250/148586529-4829942d-2924-4663-97a8-4aa4b848db26.png)

2. I am using LGBModel for testing. I see that in the prediction results the “sr.generate()” generates a score of the actions. What would this result be? Are the stocks that improve performed in the backtest?

![image](https://user-images.githubusercontent.com/70342250/148586562-2cba93f3-531b-4169-8883-5b702e8b9ebd.png)

3. If I understand the “market” and “benchmark” functions in workflow I should understand these results below. But I would like to know if I can change the frequency to “week” instead of “day”? Would I have to change my dataset?

One suggestion: write some comments in the workflow_by_code.ipynb file I think it will help beginners like me.

**Comment by Wangwuyi123** [comment]
the `market `： Is your stock pool refers to what kind of stock you are making predictions in.

the`benchmark`： Your last strategy is to compare with `benchmark`，and  `benchmark `is an index.

**Comment by Queituron** [comment]
Thanks for helping Wangwuyi123!

In question 2, I wanted to understand the meaning of the score and its relationship with classified stocks.

In question 3, I refer to the frequency of transactions.

**Comment by you-n-g** [comment]
@Queituron  
Is your questions answered in https://github.com/microsoft/qlib/pull/853

**Comment by Queituron** [comment]
@you-n-g thank you so much!

**Comment by igor17400** [comment]
@Queituron, I’m trying to implement QLib framework using Brazil's stock market as well!

I have faced a problem similar to yours. I have successfully made the conversion from B3 stocks from CSV format into qlib format. 

However, in order to train and backtest a model such as LGBModel for example, If understood the process correctly, I have to provide a “market” and a “benchmark”. 

The training part executed successfully, however in the backtest part I have received the following error as an output:

`ValueError: The benchmark ['IBOV'] does not exist. Please provide the right benchmark`

I believe my doubts are similar to yours

>  Whereas the “market” option is where I define the benchmark. What is the “benchmark” option in the workflow? 

Did you figure it out how to add Brazil’s stock market bechmark (Ibovespa - IBOV) to QLIB?

**Comment by igor17400** [comment]
@Queituron 
I believe I’ve understood part of the process.

We need to create a .txt file with all the stocks listed in the benchmark, in our case, for Ibovespa benchmark we should create a ibovespa.txt file. Such as this one,

[ibovespa.txt](https://github.com/microsoft/qlib/files/7916099/ibovespa.txt)

Afterwards, we need to download a .csv file containing the benchmark’s history value and convert it into qlib format. In that case, that file name would be BVSP.csv. As the one attached below.

[BVSP.csv](https://github.com/microsoft/qlib/files/7916103/BVSP.csv)

Subsequently, run the script to convert it to qlib.  And then `bvsp` folder with qlib data will be added to features folder in `~/.qlib`

Finally, market and benchmark variables should be 

`market=“ibovespa”`


and 

`benchmark = "bvsp”`

---------------

The training part run successfully. However,  I've received an error in backtest part and the scores were really bad.

Error:

`IndexError: index 3112 is out of bounds for axis 0 with size 3112`

Scores:

<img width="555" alt="Screen Shot 2022-01-21 at 16 22 15" src="https://user-images.githubusercontent.com/42355184/150587693-c31a1fe1-a142-40a7-89df-096c51037bce.png">

**Comment by you-n-g** [comment]
@igor17400  
I added some docs here https://github.com/microsoft/qlib/pull/885/files . I hope it will be helpful

Can you reproduce this bug in Qlib's data?

**Comment by igor17400** [comment]
@you-n-g thanks for the document! 

I have done exactly what you wrote in the document. I have a `ibovespa.txt` file which is  "**A SET** of stocks like csi300" and `BVSP.csv` which is **ONE normal instrument**. 

As it can be seen in the image below, I have the BVSP instrument as a "normal instrument".

![Screen Shot 2022-01-24 at 17 52 59](https://user-images.githubusercontent.com/42355184/150862922-f4ea19d6-ec32-4cb1-9fdd-810995769b54.png)

And for it is the `ibovespa.txt`, I have attached the file if you want to take a look or the print screen of it

[ibovespa.txt](https://github.com/microsoft/qlib/files/7928777/ibovespa.txt)

![Screen Shot 2022-01-24 at 17 51 47](https://user-images.githubusercontent.com/42355184/150862741-1c722554-223c-4b21-a017-e6c96686ac09.png)

Sorry, but what do you mean when you say "Can you reproduce this bug in Qlib's data?"?

**Comment by you-n-g** [comment]
It seems that it is out the boundary of the calendar. 
Maybe you can create a calendar_future.txt  like  Qlib's data.

**Comment by igor17400** [comment]
The data I've acquired was between `2008-01-02` and `2020-07-31`. For my backtest configuration I was defining `end_time` variable as `2020-07-31`, maybe that's why it was retrieving `index out of bounds` error. 

I've changed this variable to `2020-07-30`, one day before the last day of `calendar.txt` and it worked! 

The backtest configuration was then defined as,
```
"backtest": {
        "start_time": "2017-01-02",
        "end_time": "2020-07-30",
        "account": 100000000,
        "benchmark": benchmark,
        "exchange_kwargs": {
            "freq": "day",
            "limit_threshold": 0.095,
            "deal_price": "close",
            "open_cost": 0.0005,
            "close_cost": 0.0015,
            "min_cost": 5,
        },
    },
```

Thanks for your support, @you-n-g!!

I just have one last doubt, what is the purpose of `calendar_future.txt`? 
Because when downloading US's Qlib data is doesn't come with this file, only the CN's data.

**Comment by you-n-g** [comment]
The `calendar.txt` for storing the dates for existing historical dates.
But sometimes, the historical DateTime is not enough.  So the calendar in the future is stored in `calendar_future.txt`
