### ISSUE TITLE
How does qlib train when instruments are not component stocks of csi300 at certain time?

### ISSUE THREAD

**Issue by Waterkin** [microsoft/qlib#821]
## ❓ Questions and Help

![image](https://user-images.githubusercontent.com/41324537/148631262-ff2754a6-8d50-4c3f-9801-c0be4471b899.png)
The first stock, SZ688088 (in csi300) became a component stock since 2020, does qlib only train with its data after 2020?
Or will qlib train with all the component stocks(about 680 from 2008 - 2020) sequences from start time to end time?

**Comment by Wangwuyi123** [comment]
@Waterkin 
In the current Qlib version, 300 stocks per day are used to train model.
SZ688088 is not in the training data of csi300.
