### ISSUE TITLE
How can we get Qlib csi300 dataset to csv?

### ISSUE THREAD

**Issue by Waterkin** [microsoft/qlib#822]

**Comment by Wangwuyi123** [comment]
@Waterkin 
I believe you already know how to convert CSV format to Qlib format, you just need to push back.

**Comment by you-n-g** [comment]
@Waterkin  Maybe you can try to Pandas' `to_csv` method if after you query the data from qlib by `D.instruments`

**Comment by Waterkin** [comment]
> @Waterkin
> I believe you already know how to convert CSV format to Qlib format, you just need to push back.

okay, thx, I'll try it.

**Comment by Waterkin** [comment]
> @Waterkin I believe you already know how to convert CSV format to Qlib format, you just need to push back.

thx, but how to push it back?

**Comment by Waterkin** [comment]
> @Waterkin Maybe you can try to Pandas' `to_csv` method after you query the data from qlib by `D.features`

This could work.
