### ISSUE TITLE
Why is csi300.txt contains 872 instruments?

### ISSUE THREAD

**Issue by Waterkin** [microsoft/qlib#823]
## ❓ Questions and Help

It should be 300 stocks?

**Comment by zzz6060092** [comment]
Because the cSI300 stock will be adjusted every six months

**Comment by Wangwuyi123** [comment]
@Waterkin 
As said above, the stock pool of csi300 is dynamic.

**Comment by wan9c9** [comment]
@Waterkin
FYI, there is also a file csi300_only_new.txt, which consists of latest csi300 components and close to 300.

**Comment by Waterkin** [comment]
> 

thx but where is the file csi300_only_new.txt? I don't see it in the repo.

**Comment by you-n-g** [comment]
Qlib didn't provide a file named  ` csi300_only_new.txt`.
