### ISSUE TITLE
The Alpha158 could not match the actual data

### ISSUE THREAD

**Issue by tengerye** [microsoft/qlib#825]
I ran the [example code](https://github.com/microsoft/qlib/blob/main/examples/workflow_by_code.ipynb) and displayed the data.
![image](https://user-images.githubusercontent.com/15181821/148674500-10ce5158-87d9-45c2-ba89-438b95008463.png)

I carefully check the price. The close prices of SH600008 on 2015-01-05, 2015-01-06, 2015-01-07 are 4.75, 5.21, and 5.00 respectively. According to the [explanation](https://qlib.readthedocs.io/en/latest/component/data.html#example) and this [answer](https://github.com/microsoft/qlib/issues/682), the label is expected to be -0.04.

**Comment by Wangwuyi123** [comment]
@tengerye 
The stats you noticed were via Prosess.So it's different from the theory

**Comment by tengerye** [comment]
@Wangwuyi123 I have also checked the data from your document. It does not make any sense.
![image](https://user-images.githubusercontent.com/15181821/149622211-d195cdf6-e8f1-4e32-b806-48fc96fb71a2.png)

**Comment by you-n-g** [comment]
@tengerye 
Can the [docs  here](https://qlib.readthedocs.io/en/latest/component/data.html#qlib-format-dataset) answer your question?
> The price volume data look different from the actual dealling price because of they are adjusted (adjusted price). And then you may find that the adjusted price may be different from different data sources. This is because different data sources may vary in the way of adjusting prices. Qlib normalize the price on first trading day of each stock to 1 when adjusting them.

**Comment by tengerye** [comment]
@you-n-g Thank you for your kind reply. So the data depends on the stocks I prepare for training. May I ask is it possible to check the raw actual price data please?

**Comment by you-n-g** [comment]
@tengerye
Can this answer your questions?
https://github.com/microsoft/qlib/pull/878

**Comment by tengerye** [comment]
@you-n-g Sorry for the late reply. Is the following operation correct?
![image](https://user-images.githubusercontent.com/15181821/150687685-deae93d2-6181-43ea-bbc3-d9f156bf5e7f.png)
As you can see, the price could not match.

**Comment by igor17400** [comment]
@tengerye Shouldn't the calculatioin be `'$adjclose * $factor'`? 

![Screen Shot 2022-01-24 at 21 38 48](https://user-images.githubusercontent.com/42355184/150888810-04ce0810-7843-46b7-bbc4-425a1060a3cb.png)

**Comment by you-n-g** [comment]
@tengerye 

Our data is from Yahoo! finance.
It looks the same as [it returns](https://finance.yahoo.com/chart/600000.SS#eyJpbnRlcnZhbCI6ImRheSIsInBlcmlvZGljaXR5IjoxLCJ0aW1lVW5pdCI6bnVsbCwiY2FuZGxlV2lkdGgiOjUuNzA0MjI1MzUyMTEyNjc2LCJmbGlwcGVkIjpmYWxzZSwidm9sdW1lVW5kZXJsYXkiOnRydWUsImFkaiI6dHJ1ZSwiY3Jvc3NoYWlyIjp0cnVlLCJjaGFydFR5cGUiOiJsaW5lIiwiZXh0ZW5kZWQiOmZhbHNlLCJtYXJrZXRTZXNzaW9ucyI6e30sImFnZ3JlZ2F0aW9uVHlwZSI6Im9obGMiLCJjaGFydFNjYWxlIjoibGluZWFyIiwic3R1ZGllcyI6eyLigIx2b2wgdW5kcuKAjCI6eyJ0eXBlIjoidm9sIHVuZHIiLCJpbnB1dHMiOnsiaWQiOiLigIx2b2wgdW5kcuKAjCIsImRpc3BsYXkiOiLigIx2b2wgdW5kcuKAjCJ9LCJvdXRwdXRzIjp7IlVwIFZvbHVtZSI6IiMwMGIwNjEiLCJEb3duIFZvbHVtZSI6IiNmZjMzM2EifSwicGFuZWwiOiJjaGFydCIsInBhcmFtZXRlcnMiOnsid2lkdGhGYWN0b3IiOjAuNDUsImNoYXJ0TmFtZSI6ImNoYXJ0In19fSwicGFuZWxzIjp7ImNoYXJ0Ijp7InBlcmNlbnQiOjEsImRpc3BsYXkiOiI2MDAwMDAuU1MiLCJjaGFydE5hbWUiOiJjaGFydCIsImluZGV4IjowLCJ5QXhpcyI6eyJuYW1lIjoiY2hhcnQiLCJwb3NpdGlvbiI6bnVsbH0sInlheGlzTEhTIjpbXSwieWF4aXNSSFMiOlsiY2hhcnQiLCLigIx2b2wgdW5kcuKAjCJdfX0sInNldFNwYW4iOm51bGwsImxpbmVXaWR0aCI6Miwic3RyaXBlZEJhY2tncm91bmQiOnRydWUsImV2ZW50cyI6dHJ1ZSwiY29sb3IiOiIjMDA4MWYyIiwic3RyaXBlZEJhY2tncm91ZCI6dHJ1ZSwiZXZlbnRNYXAiOnsiY29ycG9yYXRlIjp7ImRpdnMiOnRydWUsInNwbGl0cyI6dHJ1ZX0sInNpZ0RldiI6e319LCJyYW5nZSI6bnVsbCwic3ltYm9scyI6W3sic3ltYm9sIjoiNjAwMDAwLlNTIiwic3ltYm9sT2JqZWN0Ijp7InN5bWJvbCI6IjYwMDAwMC5TUyIsInF1b3RlVHlwZSI6IkVRVUlUWSIsImV4Y2hhbmdlVGltZVpvbmUiOiJBc2lhL1NoYW5naGFpIn0sInBlcmlvZGljaXR5IjoxLCJpbnRlcnZhbCI6ImRheSIsInRpbWVVbml0IjpudWxsLCJzZXRTcGFuIjpudWxsfV19)
![image](https://user-images.githubusercontent.com/465606/151159830-12f0ac56-e76c-41ff-8012-87c1c1452607.png)

**Comment by igor17400** [comment]
@tengerye Did you figure out why LABEL0 has a different value than the one you calculated?
Because, even if you normalize the results I've not managed to understand how the value of LABEL0 is obtained.
Similar issue in #1024 but with different data format (Alpha360)
