### ISSUE TITLE
How to get tomorrow's trading order

### ISSUE THREAD

**Issue by zzz6060092** [microsoft/qlib#826]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.
I read the Online Serving in https://qlib.readthedocs.io/en/latest/component/online.html ，but I can‘t understand how to get tomorrow's trading order，just like the backtest.

**Comment by Wangwuyi123** [comment]
@zzz6060092 
Ask if you want sell_ORDER_list & buy_order_list
https://github.com/microsoft/qlib/issues/215
