### ISSUE TITLE
Can you provide more details about TopkDropoutStrategy?

### ISSUE THREAD

**Issue by zzz6060092** [microsoft/qlib#828]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

I read the documentation from https://qlib.readthedocs.io/en/latest/component/strategy.html#introduction，and set topk=50,n_drop = 5.
When performing the backtest, the strategy bought the 50 stocks with the highest scores on the first day, but sold 2 stocks and bought 4 stocks on the second day. This does not match the strategy described in the document. Can you provide more details about the strategy?
The first day is 2019/01/03
![image](https://user-images.githubusercontent.com/52370630/148731689-46992d49-a2b3-40ad-a02b-a7daef11a29b.png)

**Comment by Wangwuyi123** [comment]
@zzz6060092 
When encountering the stock in strategy encounters limit up & limit dow, can bring about cannot buy that stock

**Comment by zzz6060092** [comment]
> @zzz6060092 When encountering the stock in strategy encounters limit up & limit dow, can bring about cannot buy that stock

Thanks.

**Comment by igor17400** [comment]
@zzz6060092 how did you manage to obtain the information for each stock bought and sold each day (Terminal picture in the question you made) ?
