### ISSUE TITLE
qlib dataset is not up-to-date

### ISSUE THREAD

**Issue by AugustMeng** [microsoft/qlib#839]
I run the get_data file and try to update data to the latest. However, the data can only be updated to 2021-5-30. I assume the problem might be yahoo-finance is not supoorted in China mainland. Is there any approach to update the data? Or I have to manually do that.

**Comment by Wangwuyi123** [comment]
@AugustMeng 
The data we provided on the server was only updated to 2021-5-30, but we provided a way to obtain the latest data.
Please refer to the following documentation
https://qlib.readthedocs.io/en/latest/component/data.html#converting-csv-format-into-qlib-format

**Comment by you-n-g** [comment]
I think @Wangwuyi123  want provide this link https://qlib.readthedocs.io/en/latest/component/data.html#automatic-update-of-daily-frequency-data

**Comment by AugustMeng** [comment]
> I think @Wangwuyi123 want provide this link https://qlib.readthedocs.io/en/latest/component/data.html#automatic-update-of-daily-frequency-data

Thanks for your reply but this link isn't working properly. Connection issue.

**Comment by you-n-g** [comment]
Maybe it is GFWed... 
<img width="791" alt="image" src="https://user-images.githubusercontent.com/465606/149663586-f820b44e-8169-4950-84ec-d13ac376b911.png">

**Comment by AugustMeng** [comment]
> Maybe it is GFWed... <img alt="image" width="791" src="https://user-images.githubusercontent.com/465606/149663586-f820b44e-8169-4950-84ec-d13ac376b911.png">

Sorry, I didn't mean the link you posted cannot be opend. I can open the link but when I run the script it shows:
![捕获](https://user-images.githubusercontent.com/6684683/149664193-4c6691e3-3acb-4530-a7e7-bdb0e2226466.PNG)
I think this is due to the reason Wangwuyi posted.
