### ISSUE TITLE
backtest frequency

### ISSUE THREAD

**Issue by AugustMeng** [microsoft/qlib#847]
## ❓ Questions and Help
I want to backtest on a monthly basis, but when I change the freq to 'month', I get a exeption:
instrument: {'__DEFAULT_FREQ': '/root/.qlib/qlib_data/cn_data'} does not contain data for month

I cheked the cn_data folder and it does not contain monthly data. So is there a way that I can backtest monthly? How can I do that.

**Comment by SITONGRUC** [comment]
Maybe you could change the data source and try to use cn_fund_data
