### ISSUE TITLE
Could you provide the dataset used to benchmark various storage solutions in the paper?

### ISSUE THREAD

**Issue by qiuwei** [microsoft/qlib#85]
## ❓ Questions and Help

Could you provide the dataset used to benchmark various storage solutions in the paper?
We would like to further benchmark other potential solutions such as partitioned parquet, tiledb, duckdb, dolphindb etc.

**Comment by you-n-g** [comment]
We've tested it on CSI800 in China stock market.
The dataset is not public and the testing code is not well arrange.
We'll make clean and release the test code it in the future on other public data.
