### ISSUE TITLE
ModuleNotFoundError: No module named 'qlib.constant

### ISSUE THREAD

**Issue by igor17400** [microsoft/qlib#856]
## 🐛 Bug Description

When running `python scripts/data_collector/yahoo/collector.py download_data --source_dir ~/.qlib/stock_data/source/cn_1min --region CN --start 2021-05-20 --end 2021-05-23 --delay 0.1 --interval 1min --limit_nums 10` it returns the following bug

```
ModuleNotFoundError: No module named 'qlib.constant'
```

## To Reproduce

1. Download qlib repo
2. Run the command `python scripts/data_collector/yahoo/collector.py download_data --source_dir ~/.qlib/stock_data/source/cn_1min --region CN --start 2021-05-20 --end 2021-05-23 --delay 0.1 --interval 1min --limit_nums 10`

## Expected Behavior

It should return the following bug `ModuleNotFoundError: No module named 'qlib.constant'`

## Screenshot
![Screen Shot 2022-01-17 at 19 55 54](https://user-images.githubusercontent.com/42355184/149845436-09ddbd00-8aa1-4b17-aba3-d950332c320e.png)

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

Darwin
x86_64
macOS-10.16-x86_64-i386-64bit
Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101

Python version: 3.8.12 (default, Oct 12 2021, 06:23:56)  [Clang 10.0.0 ]

Qlib version: 0.8.0
numpy==1.22.0
pandas==1.3.5
scipy==1.7.3
requests==2.27.1
sacred==0.8.2
python-socketio==5.5.1
redis==4.1.0
python-redis-lock==3.7.0
schedule==1.1.0
cvxpy==1.1.18
hyperopt==0.1.1
fire==0.4.0
statsmodels==0.13.1
xlrd==2.0.1
plotly==5.5.0
matplotlib==3.5.1
tables==3.7.0
pyyaml==6.0
mlflow==1.22.0
tqdm==4.62.3
loguru==0.5.3
lightgbm==3.3.2
tornado==6.1
joblib==1.1.0
fire==0.4.0
ruamel.yaml==0.17.20

## Additional Notes

I have solved this problem by importing `from qlib.config import REG_CN as REGION_CN` instead of `from qlib.constant import REG_CN as REGION_CN`

**Comment by zhupr** [comment]
@igor17400 Hi,
Try using the latest code: `git pull`

**Comment by igor17400** [comment]
@zhupr Hi!
I have executed `git pull` and it returned `Already up to date.`. 

However, the problem when running `python scripts/data_collector/yahoo/collector.py download_data --source_dir ~/.qlib/stock_data/source/cn_1min --region CN --start 2021-05-20 --end 2021-05-23 --delay 0.1 --interval 1min --limit_nums 10` continues returning `ModuleNotFoundError: No module named 'qlib.constant'`

**Comment by you-n-g** [comment]
@igor17400 
It's here https://github.com/microsoft/qlib/blob/main/qlib/constant.py 
Please make sure you have removed the previous version and installed the latest one.
You can try to re-install it in a clean environment.

**Comment by igor17400** [comment]
Silly mistake here, sorry ;-;

For all those that may encounter the same problem. If you are running your code inside Jupyter Notebook and you have made modifications in QLIB project I believe you need to follow those two steps in order to overcome this problem:

1) Run `pip .` inside qlib folder
2) Restart Jupyter  session

Thanks for the help @you-n-g!
