### ISSUE TITLE
API for appending data 

### ISSUE THREAD

**Issue by qiuwei** [microsoft/qlib#86]
## ❓ Questions and Help

According to the paper, appending data should be super easy using qlib data format.
Is there any documentation about how to use this feature?

BTW:
Is there any api to write dataframes into the data store directly? 
We would like to use the data store in a more interactive way, e.g., read some data from the data store, transform it, then write the result back to the data store using a different identifier.

Thanks in advance!

**Comment by you-n-g** [comment]
@qiuwei 
The data are stored as [bytes on the disk](https://github.com/microsoft/qlib/blob/main/qlib/utils/__init__.py#L42)
You can update the data by appending bytes directly.
We have an internal version scripts for updating data, but they are not readly enough for opensource.
