### ISSUE TITLE
benchmarks_dynamic recurrent error

### ISSUE THREAD

**Issue by louis-xuy** [microsoft/qlib#862]
## ❓ Questions and Help
i run the code of qlib/examples/benchmarks_dynamic/ by use 
`python3 examples/benchmarks_dynamic/baseline/rolling_benchmark.py run_all`

but result is 
'The following are analysis results of benchmark return(1day).'
                       risk
mean               0.000495
std                0.012300
annualized_return  0.117864
information_ratio  0.621155
max_drawdown      -0.370479
'The following are analysis results of the excess return without cost(1day).'
                       risk
mean              -0.000429
std                0.005920
annualized_return -0.101990
information_ratio -1.116691
max_drawdown      -0.398905
'The following are analysis results of the excess return with cost(1day).'
                       risk
mean              -0.000584
std                0.005919
annualized_return -0.138933
information_ratio -1.521589
max_drawdown      -0.529336
[31051:MainThread](2022-01-17 15:55:25,743) INFO - qlib.workflow - [record_temp.py:521] - Indicator analysis record 'indicator_analysis_1day.pkl' has been saved as the artifact of the Experiment 4
'The following are analysis results of indicators(1day).'
     value
ffr    1.0
pa     0.0
pos    0.0

i do not know why

**Comment by wendili-cs** [comment]
I tried on the newest Qlib version and get 

'The following are analysis results of the excess return without cost(1day).'
                       risk
mean               0.000498
std                0.004251
annualized_return  0.118473
information_ratio  1.806549
max_drawdown      -0.072263
'The following are analysis results of the excess return with cost(1day).'
                       risk
mean               0.000324
std                0.004254
annualized_return  0.077101
information_ratio  1.174928
max_drawdown      -0.086469

Can you update Qlib to the newest version and run it again in the new environment?
