### ISSUE TITLE
Label does not match calculation from sorce data

### ISSUE THREAD

**Issue by hensejiang** [microsoft/qlib#872]
## ❓ Questions and Help
Tried to understand how Qlib works and hit this issue: I calculated a label by Excel and compared it with the same label dumped from Qlib code, by same stock instrument in same year. They did NOT match, not evel close. I know even the 'source data' from Yahoo Finance was pre-processed by some notmalization but since my lebel involves only the close feature, it is supposed to remain unchanged through the process. See my screenshot below.

In the left marked in yello is the source data calculation in Excel, data was fetched by D.feature and stored in csv, dumped to .bin then finally feed into 'provider_uri'; in the right marked in blue is the dump from DatasetH.prepare() by Qlib code. Please see both labels have same calculating expression but totally different values.

![image](https://user-images.githubusercontent.com/43102199/150081567-4169e864-1e42-42e2-afda-5127b6a7bae4.png)

So why am I seeing this?

**Comment by hensejiang** [comment]
Append more proof.
I made a test which set the label directly to $close (label:'$close' in DatasetH config) , then I dump the test data generated by Alpha360, supposely the label in dataset should show same value as 'close' feature. The label in Qlib process is marked as yello, and source (after normalization) is in blue. See what I got:
![image](https://user-images.githubusercontent.com/43102199/150287830-db05c21a-126c-42f8-bff9-49fd229d687b.png)
Even if there was any process that I didn't see, the market moving trend should remain unchanged. But here I saw for day by day trending from Jan 2 to Jan 9:

> Qlib generated label value: down, down, down, down, down,
> Source data in same period: down, up, up, down, up

Did I do anything wrong, or what I missed?

**Comment by hensejiang** [comment]
Well, it's getting interesting. I set the label to this: 'label': ['$close / $close']. This is supposed to set the label to always be 1 for any model training. 

Now see the actual labels dumped from Qlib:
![image](https://user-images.githubusercontent.com/43102199/150310071-91489b1b-7c36-4054-a3a0-c93a5fdef1b0.png)
The label is not 1, and the value changes for each date! 
The program's gone really wild...

**Comment by hensejiang** [comment]
Well, it's getting interesting. I set the label to this: 'label': ['$close / $close']. This is supposed to set the label to always be 1 for any model training. 

Now see the actual labels dumped from Qlib:
![image](https://user-images.githubusercontent.com/43102199/150310071-91489b1b-7c36-4054-a3a0-c93a5fdef1b0.png)
The label is not 1, and the value changes for each date! 
The program's gone really wild...

**Comment by you-n-g** [comment]
@hensejiang 
The label in the dataset provided by Qlib was processed by  `CSZScoreNorm` https://github.com/microsoft/qlib/blob/main/qlib/contrib/data/handler.py#L40

It is normalized daily.

**Comment by hensejiang** [comment]
Thank you man.
Is there any function in Qlib to get the reverse-normalization value of the label prediction?
Need that value that indicates market trending by both direction and strength.

**Comment by you-n-g** [comment]
@hensejiang  Currently, there is no step to inverse the normalization from the label prediction.
 Stock prediction is very noisy, it is hard to get your expected meaningful values after reversing the normalization.
CSZscoreNorm is not the reverse of ZscoreNorm.

**Comment by hensejiang** [comment]
Got confused.
If QLIB normalize data everyday, and the normalization covers not only the source trading data but also the labels, that could make the label changes at time being with the execution. Then how can you keep the consistency by setting targets for the forecast models? Let’s say when Qlib runs at date T evening with latest updated data, it makes some prediction by the data normalized and fed into a model. Then one day later, the same model is executed again upon the same data targeting same label, how will Qlib handle it by a different normalization output?

Docs of Alpha158 says:
In the Alpha158, Qlib uses the label Ref($close, -2)/Ref($close, -1) - 1 that means the change from T+1 to T+2, rather than Ref($close, -1)/$close - 1, of which the reason is that when getting the T day close price of a china stock, the stock can be bought on T+1 day and sold on T+2 day.

If same label expression changes everyday due to ‘daily normalization’, what is the behavior that I should expect from a model at T+1 and T+2?

**Comment by you-n-g** [comment]
If your trading strategy expects to reverse the normalization of the score from the model,  you can implement the reversion in the trading strategy. 

For example, you can follow this strategy: 
 https://github.com/microsoft/qlib/blob/144e1e2459ca072052945a66628b5710774a21b3/qlib/contrib/strategy/optimizer/enhanced_indexing.py#L114

**Comment by hensejiang** [comment]
I found some indications from docs as below, which matches perfect with what you’ve told.

My question is about the ‘scale’ in the doc: how can I know what the scale-change is in each model? Is there any rule or algorithm that a model follows when it ‘learns with a different scale’? From the model output scores I couldn’t see any simple rules about the scale, sometimes it seems like linear but not always.

I am OK some engineering works to implement ‘the rescaling the prediction score’, please share more info about how. Really need a meaningful score other than just the order. Thank you.



Forecast Model module can make predictions, please refer to Forecast Model: Model Training & Prediction<https://qlib.readthedocs.io/en/latest/component/model.html>.

Normally, the prediction score is the output of the models. But some models are learned from a label with a different scale. So the scale of the prediction score may be different from your expectation(e.g. the return of instruments).

Qlib didn’t add a step to scale the prediction score to a unified scale. Because not every trading strategy cares about the scale(e.g. TopkDropoutStrategy only cares about the order). So the strategy is responsible for rescaling the prediction score(e.g. some portfolio-optimization-based strategies may require a meaningful scale).

**Comment by you-n-g** [comment]
The model has the flexibility to define the target, loss, and data processing. 
So I don't think there is a silver bullet to rescale it back directly barely based on the model's outputs. 

If you want to scale it back to some meaningful values(e.g. stock returns.), an intuitive solution is to create a regression model for the model's recent outputs and your recent target values.

**Comment by hensejiang** [comment]
I got the idea and thank you for the heads up you’ve given.

Another congression model will bring new deviations and lower down the overall accuracy of prediction, that could be tricky.
