### ISSUE TITLE
How to avoid INFO WARNING output in console?

### ISSUE THREAD

**Issue by Waterkin** [microsoft/qlib#874]
## ❓ Questions and Help
It is a little annoying. Thanks!
We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

**Comment by you-n-g** [comment]
Can [this PR](https://github.com/microsoft/qlib/pull/880) answer your question?
