### ISSUE TITLE
Did not get graph in jupyternotebook 

### ISSUE THREAD

**Issue by lipengyuan1994** [microsoft/qlib#88]
Hi, 

I ran the jupyter notebook in my local, but did not see any graphs, 
I downloaded US data using ` python scripts/get_data.py qlib_data --target_dir ../.qlib/qlib_data/us_data --region us
`

![Imgur](https://i.imgur.com/nt8YmaM.png)

and set:  

```
market = "sp500" 

benchmark = "_^ndx"
```

![Imgur](https://i.imgur.com/O7lk0Hi.png)

Can anyone give me some guidance how to get the graph show up in jupyternotebook?  
Any help/hint will be appreciated! Thanks.

**Comment by zhupr** [comment]
@lipengyuan1994 Hi，
What version of plotly is: `pip list|grep plotly`
Update plotly:` pip install -U plotly==4.12.0`

If the graph is not displayed, press `F12` in the browser to see if there are any errors

**Comment by lipengyuan1994** [comment]
> @lipengyuan1994 Hi，
> What version of plotly is: `pip list|grep plotly`
> Update plotly:` pip install -U plotly==4.12.0`
> 
> If the graph is not displayed, press `F12` in the browser to see if there are any errors



Thanks for reply !
the plotly  version in my env is `4.12.0`  
and sorry I am not familiar with the frontend code, I copied the screenshot below. 
![Imgur](https://i.imgur.com/xUkWtJ2.png)


![Imgur](https://i.imgur.com/SrnQuG5.png)



Thank you!

**Comment by zhupr** [comment]
@lipengyuan1994 Hi
There are 13 errors in the browser. I don't see the key information in the screenshot, sorry.

Currently qlib only supports the default renderer and *google colab*, you can try to choose the appropriate renderer

You can try the following code:
```python
# analysis_position.report_graph(report_normal_df)
ipykernel = str(type(get_ipython()))
print(ipykernel)

# get support renderers
import plotly.io as pio
print(pio.renderers)

# Select a matching renderer based on the content of ipykernel
renderer = <The renderer of the current notebook>

figs = analysis_position.report_graph(report_normal_df, show_notebook=False)
for _fig in figs:
    _fig.show(renderer=renderer)
```

If the code above is still not displayed, you can post the output or error screenshot here.

**Comment by lipengyuan1994** [comment]
@zhupr Hi,


I tried the code in colab,  there is no error, but just no plotting. 

![Imgur](https://i.imgur.com/58l6SCH.png)

**Comment by zhupr** [comment]
@lipengyuan1994 
In colab, the renderer is set to colab: `renderer = "colab"`, reference:  https://plotly.com/python/renderers/

**Comment by lipengyuan1994** [comment]
@zhupr Thanks,  


the default render was `plotly_mimetype+notebookf` I changed the render to 'colab' and got the plotting, 
![Imgur](https://i.imgur.com/WFrdOGO.png)

Thanks for help!
