### ISSUE TITLE
Delete feature in qlib

### ISSUE THREAD

**Issue by bbbzhai** [microsoft/qlib#894]
Is there anyway to delete a feature that we calculate wrong in qlib? No updating it, simply delete.

**Comment by you-n-g** [comment]
Do you mean the features in directories like `~/.qlib/qlib_data/cn_data`?

Maybe you can delete it like this

For example, if you want to delete the $close feature, 
you can  do it by  `cd ~/.qlib/qlib_data/cn_data ;  find . -name 'close.day.bin' -exec rm {} \; `

**Comment by bbbzhai** [comment]
Yes, I see. I can delete them this way.
Thanks for replying.
