### ISSUE TITLE
How to manually add qrun to PATH

### ISSUE THREAD

**Issue by xy666** [microsoft/qlib#90]
## ❓ Questions and Help

![image](https://user-images.githubusercontent.com/21954868/101736082-cf0ffb00-3afd-11eb-8efd-8760c35e63f6.png)

After installing Qlib, the **qrun** command is still not found. How can we manually add the qrun path to PATH? Thanks.

**Comment by you-n-g** [comment]
Typically,  you'll get output like `/home/<your username>/miniconda3/envs/<your env>/bin/qrun`  by running `which qrun` after you install qlib by `python setup.py install`

**Comment by xy666** [comment]
> Typically, you'll get output like `/home/<your username>/miniconda3/envs/<your env>/bin/qrun` by running `which qrun` after you install qlib by `python setup.py install`

I get **qrun not found** by running which qrun. I'm not managing my env by conda and installed qlib by python setup.py install --user.

**Comment by you-n-g** [comment]
Conda solves a lot of environment problems and is suggested for installing `qlib`.
