### ISSUE TITLE
和BigQuant的接口设计和代码命名都是一样的，这个不侵犯知识产权么？

### ISSUE THREAD

**Issue by bitoutou** [microsoft/qlib#91]
- 看了几个数据接口和变量命名，都是一样的
- BigQuant 16年就就发布了，这个应该是来自BigQuant的
- 微软是否有考虑知识产权问题。我们公司在商业中使用，是否会有连带知识产权问题？

![image](https://user-images.githubusercontent.com/39846742/101744216-de934200-3b05-11eb-8c2b-326d2883c82c.png)
![image](https://user-images.githubusercontent.com/39846742/101744453-ece15e00-3b05-11eb-9cc0-2167c9c4ccac.png)
![image](https://user-images.githubusercontent.com/39846742/101745040-0f737700-3b06-11eb-8dc3-db45faba8bdb.png)

**Comment by you-n-g** [comment]
All the code is written by ourselves and released under **MIT licence**.  You can use it for commercial purpose.

Similar variable and function names are very common in many projects (such as  `foo`, `bar`) . LOL

**Comment by bitoutou** [comment]
但这里面有几个专有的，各个量化平台都不同，有些BigQuant自己特有的，qlib好像是直接复制的，比如数据表达式、数据缓存等实现。你们是有BigQuant团队的人？

**Comment by you-n-g** [comment]
**We didn't copy any code.**   I even don't know where I can find the source code of BigQuant. 

Quering features, calculating expressions and caching data  are very common requirements in Quant.  We don't have much choices for the function and variable names.

We implemented them all by ourselves in the way which we think is optimal.

**Comment by bitoutou** [comment]
嗯，主要是看起来太像了，大家都叫AI量化平台（这个BigQuant应该是第一个这么自称的），用户一眼就能看出来。比如因子，一般量化里面叫factor，qlib和BigQuant用的是feature，太明显了。不知道这个是否会侵权，能否改一下

**Comment by you-n-g** [comment]
@bitoutou  Please spare your valuable time to read our code.
I think we are very lucky to have 66.7%  different variable names (_start_time, end_time, freq, disk_cache_).
It's really hard for programmers to name variables.   (ಥ﹏ಥ)

https://github.com/microsoft/qlib/blob/main/qlib/data/data.py#L952
![image](https://user-images.githubusercontent.com/465606/101750240-b73e7400-3b09-11eb-9628-996df2fbe624.png)

**Comment by you-n-g** [comment]
@bitoutou  Did I solve your problems?
Could I prepend "[已澄清]" to your title and close this issue?

**Comment by qingtiandalaoye** [comment]
我看论文都是中国人名字，可能开发也是国内组的小朋友，值得高兴。
新功能不急着开发，抓紧时间在手册上多写几个中国股票，期货的例子，容易上手使用的人才会多。

微软自有Azure，这套系统能够容易部署的话，国内靠卖服务器算力的“量化云”要崩塌了。所以，遇到，国人碰瓷了，不必担心。
不论是“先有瓷器后有中国”还是“先有中国后有瓷器”，总之，是不可分割的一部分嘛，碰一碰正常。

**Comment by lipengyuan1994** [comment]
> 嗯，主要是看起来太像了，大家都叫AI量化平台（这个BigQuant应该是第一个这么自称的），用户一眼就能看出来。比如因子，一般量化里面叫factor，qlib和BigQuant用的是feature，太明显了。不知道这个是否会侵权，要不要改一下

多虑了，variable 命名方式没有侵犯是指产权一说，就好像你的车方向盘叫方向盘，劳斯莱斯的方向盘也叫方向盘。 在模型里factor就是应该叫feature， ML 和DL的通用就是feature

**Comment by RustFlow** [comment]
- 支持开源精神，ubuntu也借鉴了很多Windows的架构和界面设计，微软也没有说侵权
- 但是微软这样的大企业去碰瓷创业公司有点low了，这是一个python库，取一个AI量化平台一样的名字不太合适

**Comment by you-n-g** [comment]
@RustFlow  Qlib is just released as a Python library.  Actually it is a quantitative investment platform.

The function name is really a coincidence. 
We have so many APIs(I visited [Bigquant‘s API](https://bigquant.com/docs/develop/modules/trade/usage.html) yesterday and learned a lot.). I failed to find the second API we are similar.
I think it is very likely to have one similar function name if both of us are implementing a quantitative investment platform.

![image](https://user-images.githubusercontent.com/465606/101852877-932a7380-3b99-11eb-8ceb-63948cd2f473.png)
![image](https://user-images.githubusercontent.com/465606/101852859-886fde80-3b99-11eb-9dd1-98f39052b95f.png)

**Comment by RustFlow** [comment]
开放量化平台被业内普遍看不起，觉得最多是个玩具。是一条艰苦的路，加油

**Comment by bxdd** [comment]
@RustFlow Hi, you might as well use ``Qlib`` first before concluding. "Open source quantitative platforms are just toys" may only exist before ``Qlib`` open source.

**Comment by RustFlow** [comment]
这个说法是看知乎上的评论和量化行业的朋友的反馈。我是程序员，我认为开放是更好的。

**Comment by davidxiaolux** [comment]
哈哈。。。。。。。。， 这知识产权太宽了吧，

**Comment by grammy-jiang** [comment]
> 这个说法是看知乎上的评论和量化行业的朋友的反馈。我是程序员，我认为开放是更好的。

The idea that open source is better is quite common in programmers/software developers and I also agree with it.

The reason most programmers think the open-source quantitative platform is more like a toy than a real tool is that most of the projects are not designed or programmed by the experienced architect or programmer. Even in this project, the settings are placed with the settings class in the same file:

* https://github.com/microsoft/qlib/blob/main/qlib/config.py

This project is still a good one, I like it.

**Comment by qiuwei** [comment]
As far as I know, bigquant's api is also very similar to quantopian's.

**Comment by the-oaks** [comment]
@you-n-g I think you can pretend this issue with "[pengci]" and close the issue ...

**Comment by bitoutou** [comment]
> As far as I know, bigquant's api is also very similar to quantopian's.

你说的joinquant吧，bigquant完全是另一套API体系啊，列式时序数据存储、表达式引擎、数据缓存等这些都是特有的，微软这个模仿不能更明显了。小公司也就罢了，微软也这么干就说不过去了

**Comment by atlasju** [comment]
就是变量命名有了类似，这就开始说抄袭了，你要么是bigquant的人，要么就是太闲着，吃饱撑着没事
