### ISSUE TITLE
Does qlib support custom database or other format instead of qlib format

### ISSUE THREAD

**Issue by mojerro** [microsoft/qlib#910]
I have some data from database and HDF5, and it successive have new data，I don't want to change it to qlib format every time

**Comment by you-n-g** [comment]
Qlib is designed in a decoupled way. You can implement according to adaptors.
But you may dive deep into Qlib's code.

Here is an example to read Arctic from Qlib.
https://github.com/microsoft/qlib/pull/744

**Comment by mojerro** [comment]
That's what I need, thx
It's a little bit hard for me to know the whole struct, and this example is really helpful.
