### ISSUE TITLE
Can not save model with R.save_objects

### ISSUE THREAD

**Issue by chn489** [microsoft/qlib#911]
When I try to save my tensorflow model using R.save_objects, I encountered an error like this:

AttributeError                            Traceback (most recent call last)
<ipython-input-3-7f8899872844> in <module>()
      2     R.log_params(**flatten_dict(task))
      3     model.fit(dataset)
----> 4     R.save_objects(trained_model=model)
      5     rid = R.get_recorder().id

E:\Anaconda3.5\lib\site-packages\qlib\workflow\__init__.py in save_objects(self, local_path, artifact_path, **kwargs)
    487                 "You can choose only one of `local_path`(save the files in a path) or `kwargs`(pass in the objects directly)"
    488             )
--> 489         self.get_exp().get_recorder().save_objects(local_path, artifact_path, **kwargs)
    490 
    491     def load_object(self, name: Text):

E:\Anaconda3.5\lib\site-packages\qlib\workflow\recorder.py in save_objects(self, local_path, artifact_path, **kwargs)
    323             for name, data in kwargs.items():
    324                 path = temp_dir / name
--> 325                 Serializable.general_dump(data, path)
    326                 self.client.log_artifact(self.id, temp_dir / name, artifact_path)
    327             shutil.rmtree(temp_dir)

E:\Anaconda3.5\lib\site-packages\qlib\utils\serial.py in general_dump(obj, path)
    141         path = Path(path)
    142         if isinstance(obj, Serializable):
--> 143             obj.to_pickle(path)
    144         else:
    145             with path.open("wb") as f:

E:\Anaconda3.5\lib\site-packages\qlib\utils\serial.py in to_pickle(self, path, dump_all, exclude)
     88         with Path(path).open("wb") as f:
     89             # pickle interface like backend; such as dill
---> 90             self.get_backend().dump(self, f, protocol=C.dump_protocol_version)
     91 
     92     @classmethod

AttributeError: Can't pickle local object 'Layer.add_loss.<locals>._tag_callable'

I would really appreciate it if someone could point out the reason for the error.

**Comment by you-n-g** [comment]
@chn489
Qlib uses the pickle to save the file in the underlying API.
Maybe you can try to dump your model with naive pickle API for debugging.

**Comment by chn489** [comment]
@[you-n-g](https://github.com/you-n-g)
I solved this problem using tensorflow.keras.models.save method, however, it raised another error:
 ValueError: Failed to find data adapter that can handle input: <class 'qlib.data.dataset.DatasetH'>, <class 'NoneType'>
when I was doing backtest using SignalRecord method.

**Comment by chn489** [comment]
> If you simply want to save model for further usage then why not follow the offical doc here [https://qlib.readthedocs.io/en/latest/advanced/serial.html](url) with the to_pickle() function. It works quite well.

Thank you for your suggestion. However, it doesn't work for me. That's weird.

**Comment by you-n-g** [comment]
Recently, I found some tricks that could make TensorFlow models picklable
You can check if it is helpful
```Python
from tensorflow.keras.models import load_model, save_model, Model
import tempfile
# Hotfix function
def make_keras_picklable():

    def __getstate__(self):
        model_str = ""
        with tempfile.NamedTemporaryFile(suffix='.hdf5', delete=True) as fd:
            save_model(self, fd.name, overwrite=True)
            model_str = fd.read()
        d = {'model_str': model_str}
        return d

    def __setstate__(self, state):
        with tempfile.NamedTemporaryFile(suffix='.hdf5', delete=True) as fd:
            fd.write(state['model_str'])
            fd.flush()
            model = load_model(fd.name)
        self.__dict__.update(model.__dict__)
    cls = Model
    cls.__getstate__ = __getstate__
    cls.__setstate__ = __setstate__
# Run the function
make_keras_picklable()
```

**Comment by you-n-g** [comment]
@chn489  Please read the docs here https://qlib.readthedocs.io/en/latest/component/recorder.html .
Qlib save the models based on MLflow  and this is the interface to load them
