### ISSUE TITLE
Does the Backtest exclude the stocks at limit up which cannot be bought? 回测模块是否排除了不能购买的涨停股票？

### ISSUE THREAD

**Issue by 1eunght** [microsoft/qlib#913]
I wonder if the Backtest module has excluded **the stocks at limit up or suspended** ? Because we cannot buy the stocks that reached the limit up or suspened, there might be bias in the backtest result if we don't exclude these stocks. How can I set the **Backtest Configuration** to eliminate the bias?

我想知道回测的时候是否已经排除了**涨停或者停牌股票**呢？因为现实中无法买入这些股票，如果不排除的话可能会使回测结果有偏误。我应该怎样设置**回测模块的参数**，以便避免回测时买入这些股票呢？

Refering to [workflow_by_code.ipynb](https://github.com/microsoft/qlib/blob/main/examples/workflow_by_code.ipynb), I noticed that there are several `kwargs` in `port_analysis_config["backtest"]`. Using the same model and dataset, no matter how I change the `"limit_threshold"`, I still only get exactly the same backtest results. I wonder what do these `kwargs` mean and how they work when backtesting? Can I use the `kwargs` to fix my problem above?

[workflow_by_code.ipynb](https://github.com/microsoft/qlib/blob/main/examples/workflow_by_code.ipynb)中的回测有如`"limit_threshold"`这样的参数，但是我并不清楚具体含义。当我使用相同的模型和数据进行回测，无论怎么修改`"limit_threshold"`都改变不了回测结果（改为0.0001）。所以我很好奇这些参数的含义，以及它们到底怎样影响回测结果？我能通过这些参数解决上述问题吗？

Thanks in advance! 谢谢！

**Comment by hensejiang** [comment]
Rather leave a note here for any updates or answers from the team.
From what I know limit_threshold is the pre_designed parameter for China market, where the regulation requires stop trading if the stock price went over the limit (+-10%). You should not modify it in your program.

Workflow_by_code in qlib focuses on building a workflow to simulate the process of stock trading, while within the framework I can imagine strategy is a much closer place to work for your question.

**Comment by you-n-g** [comment]
@1eunght 

If `limit_threshold` parameter doesn't work, you can try to place a breakpoint here to make sure it takes effect
https://github.com/microsoft/qlib/blob/main/qlib/backtest/exchange.py#L33

Hope to get feedback from you to know how to make the interface more user-friendly after you find the problem  :)

**Comment by 1eunght** [comment]
@you-n-g 

I don't believe that the parameter `limit_threshold` is disabled, because when I set it to be greater than 0.1, there is warning that `WARNING - qlib.online operator - [exchange.py:140] - limit_threshold may not be set to a reasonable value`. 

However, no matter how I set the parameter, I still get exactly the same backtest result, even if I set it to be `None`. I just wonder why it is the case? Slightly changing other parameters like `open_cost` or `close_cost` will generate different results.

![image](https://user-images.githubusercontent.com/63780886/154019294-00bedc9d-5dff-4261-bab9-335dbeccae9e.png)

![image](https://user-images.githubusercontent.com/63780886/154018972-615144a8-066c-4465-97d1-b20bf41a792e.png)

**Comment by you-n-g** [comment]
@1eunght 
You can try to set the limit_threshold to 0 (which indicate that any  change will hit the trading limitation)
Then you can debug [here](https://github.com/microsoft/qlib/blob/main/qlib/backtest/exchange.py#L310) to check why it does not limit the trading.

**Comment by tengerye** [comment]
@you-n-g parameter `limit_threshold` is not a proper way to solve this problem. 涨跌停是需要四舍五入的。并且科创板怎么办？前五日没有涨跌停怎么办？Maybe daily limit price is a better option?

**Comment by you-n-g** [comment]
@tengerye  
Yes.  You are right.
Currently, the limit_threshold is not controlled very accurately. 
Qlib leaves an API to enable users to control the trading limitation more accurately
https://github.com/microsoft/qlib/blob/main/qlib/backtest/exchange.py#L58

Users can write expressions to implement more detailed and accurate rules.
(e.g. maybe some rules can not simply be expressed by existing operators. Extra operators may need to be implemented)

**Comment by ShiZipengArthur** [comment]
我也遇到了一样的问题，发现回测结果positions中出现购买了一字板（主板）的情况，不知道您解决了没有。
