### ISSUE TITLE
How to convert dataframe to qlib format directluy

### ISSUE THREAD

**Issue by TraderWithPython** [microsoft/qlib#916]
## ❓ Questions and Help

I know that we can convert dataframe to csv and then to qlib format. But it is not friendly for online applications.
Is there any other method to do this?
Tks

**Comment by you-n-g** [comment]
Thanks for your advice. It is very helpful!

The [previous scripts](https://github.com/microsoft/qlib/blob/cfc3e886ed0956aeef2e4dd65bed8e976a96643b/scripts/dump_bin.py#L20) didn't decouple the data reading and processing feature. So it may take some time to refactor it to support converting data to Qlib format from `pd.DataFrame` directly.
We may try to fix it later.

If you are interested to join us to help refactor it, please feel free to contact us.

**Comment by TraderWithPython** [comment]
> 

Tks for your contribution and hope qlib will be better
