### ISSUE TITLE
ERROR - qlib.workflow - [utils.py:38] - An exception has been raised[ValueError: can't find a freq from [Freq(day)] that can resample to 1min!].

### ISSUE THREAD

**Issue by Waterkin** [microsoft/qlib#925]
## To Reproduce

df = D.features([code], ['$high', '$low', '$close', '$open','$volume','$money'],
                    start_time='%s 09:31:00'%str(start_time)[:10],
                    end_time='%s 15:00:00'%str(end_time)[:10],
                    freq='1min', disk_cache=0)

## Screenshot

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/41324537/155052775-e0cb1ca4-ba25-4b97-9e5a-dfba5ccc4da7.png">

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version:Newest
 - Python version:3.7.9
 - OS (`Windows`, `Linux`, `MacOS`):MacOS
 - Commit number (optional, please provide it if you are using the dev version):

**Comment by zhupr** [comment]
@Waterkin Hi, 
Is `provider_uri` a `1min` dataset ? 
Get sample `1min` data ref: `python scripts/get_data.py qlib_data --target_dir ~/.qlib/qlib_data/cn_data_1min --region cn -- interval 1min`

**Comment by Waterkin** [comment]
> 
Yep, I can set Qlib.init(provider_uri='1min_dataset'), and I have downloaded the 1min dataset by your command.
But I am trying to resample a 1min dataset by using D.features(... , freq='1min'), is there anything wrong,
or can I call the interface to select certain stock and certain time interval to resample a 1min dataset?

**Comment by zhupr** [comment]
The user can only resample from "high frequencies" to "low frequencies", e.g. from `1min` to `5min`, `1day`, `1week` etc.
To resample to `1min`, a higher frequency data set than `1min` is required.

**Comment by Waterkin** [comment]
> 

Thanks for your patience. I am wondering whether I can directly get 1min dataset by `D.features(... , freq='1min')`, or is there any way to do this rather than resampling?

**Comment by you-n-g** [comment]
Sorry, Qlib didn't support automatically resampling now.

**Comment by fenggeHu** [comment]
I think that the writer of readthedocs did'nt run the codes step by step.

**Comment by yuhorun** [comment]
https://qlib.readthedocs.io/en/latest/FAQ/FAQ.html#runtimeerror-an-attempt-has-been-made-to-start-a-new-process-before-the-current-process-has-finished-its-bootstrapping-phase
