### ISSUE TITLE
Values for market and benchmark other than  CSI300 and SH000300

### ISSUE THREAD

**Issue by johnnytorresm** [microsoft/qlib#929]
## ❓ Questions and Help
I would like to know which values are available right now for "market" and "benchmark" when using qrun. I am trying to test qlib for bitcoin price evolution and also for the French Stock Market. How can I create my own benchmarks?

Johnny

**Comment by zhupr** [comment]
@johnnytorresm Hi,
The `"market"` is a collection of symbols (a collection of stocks) and the `"benchmark"` is the benchmark data for this `"collection"`.

`"market"` is the name of the stock market index (*CAC40*) and `"benchmark"` is the code corresponding to the index (*FCHI*)

`"benchmark"` is used to calculate the excess return, so the `"benchmark"` can be chosen according to the specific market; for example, the average value of the `"market"` can be used as the `"benchmark"`

**Comment by johnnytorresm** [comment]
Dear Sir,

I appreciate your reply.

best regards,

 -------------------------------------------------------
Johnny Torres
***@***.******@***.***>
Mobile: +33 (0) 6 14 35 45 83
Skype : johnnytorresm
-------------------------------------------------------
CyberSysNet - True Business Intelligence
***@***.******@***.***>
-------------------------------------------------------
________________________________
