### ISSUE TITLE
python setup.py install failure

### ISSUE THREAD

**Issue by yuelng** [microsoft/qlib#93]
qlib/data/_libs/rolling.cpp:630:10: fatal error: 'ios' file not found
#include "ios"
         ^~~~~
1 warning and 1 error generated.
error: command 'gcc' failed with exit status 1
We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

**Comment by yuelng** [comment]
CFLAGS='-stdlib=libc++' pip install pyroaring 
this work ！！

**Comment by baoxiehao** [comment]
> CFLAGS='-stdlib=libc++' pip install pyroaring
> this work ！！

It doesn't work for me...

**Comment by you-n-g** [comment]
@baoxiehao   We have tested the installation process  in all kinds of systems & Python versions in CI
https://github.com/microsoft/qlib/blob/main/.github/workflows/test.yml

You can follow it. 
Looking forward to your  feedbacks about what's wrong in your case.

Thanks
