### ISSUE TITLE
Is the class name of HasingStockStorage a typo?

### ISSUE THREAD

**Issue by ChiahungTai** [microsoft/qlib#930]
## 🐛 Bug Description

Should HasingStockStorage be HashingStockStorage?
See https://github.com/microsoft/qlib/blob/ec8969a3ae24f0eddcc71309d6291246d760241e/qlib/data/dataset/storage.py#L62
Is it a typo? @you-n-g 

## To Reproduce

1.
1.
1.

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version:
 - Python version:
 - OS (`Windows`, `Linux`, `MacOS`):
 - Commit number (optional, please provide it if you are using the dev version):

**Comment by SunsetWolf** [comment]
This is indeed a typo, would you like to fix it?
