### ISSUE TITLE
您好，TRA模型的数据怎么下载呢？feature、label、ret三个文件，好像都是从qlib里面下载的，有官方提示吗？

### ISSUE THREAD

**Issue by junyaoChengoo** [microsoft/qlib#934]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.

**Comment by you-n-g** [comment]
Is this what you are looking for?

**Comment by you-n-g** [comment]
The data come from some private data source and the data processing code is not published.

But It is easy to reproduce similar data.

For example
```python
import pandas as pd
import baostock as bs

df = pd.read_pickle('feature.pkl')
target = df.loc[pd.Timestamp('2020-06-30'), 'PE_TTM']

res = {}
for code in target.index:
    res[code] = bs.query_history_k_data_plus(code[:2].lower()+'.'+code[2:], "peTTM", start_date='2020-06-30', end_date='2020-06-30').get_data().squeeze()
src = pd.Series(res).astype('float')

src = src.rank(pct=True)
src -= 0.5
src *= 3.46
print('corr:', src.corr(target, method='spearman'))
print('max diff:', (src - target).abs().nlargest(10))
```

In addition,   you can refer to the details of data description in the paper
<img width="520" alt="0750b48a7c20f5cefe218786b9f7aca" src="https://user-images.githubusercontent.com/465606/157806622-c135c99f-1f52-4d83-a44d-2e8ac30805b5.png">

P.S.
Thanks to all the above information come from @evanzd

**Comment by junyaoChengoo** [comment]
> The data come from some private data source and the data processing code is not published.
> 
> But It is easy to reproduce similar data.
> 
> For example
> 
> ```python
> import pandas as pd
> import baostock as bs
> 
> df = pd.read_pickle('feature.pkl')
> target = df.loc[pd.Timestamp('2020-06-30'), 'PE_TTM']
> 
> res = {}
> for code in target.index:
>     res[code] = bs.query_history_k_data_plus(code[:2].lower()+'.'+code[2:], "peTTM", start_date='2020-06-30', end_date='2020-06-30').get_data().squeeze()
> src = pd.Series(res).astype('float')
> 
> src = src.rank(pct=True)
> src -= 0.5
> src *= 3.46
> print('corr:', src.corr(target, method='spearman'))
> print('max diff:', (src - target).abs().nlargest(10))
> ```
> 
> In addition, you can refer to the details of data description in the paper <img alt="0750b48a7c20f5cefe218786b9f7aca" width="520" src="https://user-images.githubusercontent.com/465606/157806622-c135c99f-1f52-4d83-a44d-2e8ac30805b5.png">
> 
> P.S. Thanks to all the above information come from @evanzd

谢谢您的回复！十分有用！另外，我还有一个问题想请教：在复现TRA模型的过程，我发现原作者将TRA模型与Linear、LightGBM、MLP、SFM、ALSTM+TS、Transformer+TS进行比较，这些结果都写在qlib\examples\benchmarks\TRA\Reports.ipynb里面。我尝试运行这些模型的workflow，再运行Reports.ipynb，出现了报错。
请问，如何同时复现这些模型，并且与TRA模型一起进行回测呢？

**Comment by SunsetWolf** [comment]
> > The data come from some private data source and the data processing code is not published.
> > But It is easy to reproduce similar data.
> > For example
> > ```python
> > import pandas as pd
> > import baostock as bs
> > 
> > df = pd.read_pickle('feature.pkl')
> > target = df.loc[pd.Timestamp('2020-06-30'), 'PE_TTM']
> > 
> > res = {}
> > for code in target.index:
> >     res[code] = bs.query_history_k_data_plus(code[:2].lower()+'.'+code[2:], "peTTM", start_date='2020-06-30', end_date='2020-06-30').get_data().squeeze()
> > src = pd.Series(res).astype('float')
> > 
> > src = src.rank(pct=True)
> > src -= 0.5
> > src *= 3.46
> > print('corr:', src.corr(target, method='spearman'))
> > print('max diff:', (src - target).abs().nlargest(10))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In addition, you can refer to the details of data description in the paper <img alt="0750b48a7c20f5cefe218786b9f7aca" width="520" src="https://user-images.githubusercontent.com/465606/157806622-c135c99f-1f52-4d83-a44d-2e8ac30805b5.png">
> > P.S. Thanks to all the above information come from @evanzd
> 
> 谢谢您的回复！十分有用！另外，我还有一个问题想请教：在复现TRA模型的过程，我发现原作者将TRA模型与Linear、LightGBM、MLP、SFM、ALSTM+TS、Transformer+TS进行比较，这些结果都写在qlib\examples\benchmarks\TRA\Reports.ipynb里面。我尝试运行这些模型的workflow，再运行Reports.ipynb，出现了报错。 请问，如何同时复现这些模型，并且与TRA模型一起进行回测呢？

As you said: running the workflow for these models, and then running Report.ipynb, an error was reported.
I am now trying to reproduce this error in full, I hope you can help me with more information? Thanks!

**Comment by Super-ooho** [comment]
> > The data come from some private data source and the data processing code is not published.
> > But It is easy to reproduce similar data.
> > For example
> > ```python
> > import pandas as pd
> > import baostock as bs
> > 
> > df = pd.read_pickle('feature.pkl')
> > target = df.loc[pd.Timestamp('2020-06-30'), 'PE_TTM']
> > 
> > res = {}
> > for code in target.index:
> >     res[code] = bs.query_history_k_data_plus(code[:2].lower()+'.'+code[2:], "peTTM", start_date='2020-06-30', end_date='2020-06-30').get_data().squeeze()
> > src = pd.Series(res).astype('float')
> > 
> > src = src.rank(pct=True)
> > src -= 0.5
> > src *= 3.46
> > print('corr:', src.corr(target, method='spearman'))
> > print('max diff:', (src - target).abs().nlargest(10))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In addition, you can refer to the details of data description in the paper <img alt="0750b48a7c20f5cefe218786b9f7aca" width="520" src="https://user-images.githubusercontent.com/465606/157806622-c135c99f-1f52-4d83-a44d-2e8ac30805b5.png">
> > P.S. Thanks to all the above information come from @evanzd
> 
> 谢谢您的回复！十分有用！另外，我还有一个问题想请教：在复现TRA模型的过程，我发现原作者将TRA模型与Linear、LightGBM、MLP、SFM、ALSTM+TS、Transformer+TS进行比较，这些结果都写在qlib\examples\benchmarks\TRA\Reports.ipynb里面。我尝试运行这些模型的workflow，再运行Reports.ipynb，出现了报错。 请问，如何同时复现这些模型，并且与TRA模型一起进行回测呢？

你好，请问您的数据替换的问题解决了么？想问一下，label.pkl这个标签文件里的lebel是怎么得到的呢？我现在想要替换成自己的数据，但是不清楚label数据表示的是什么，怎么得到的。谢谢
