### ISSUE TITLE
How to get weekly and monthly data from daily K-line data

### ISSUE THREAD

**Issue by PalanQu** [microsoft/qlib#940]
## ❓ Questions and Help

 Many indicators like MACD, KDJ need weekly or monthly K-line data to analyse some pattern, is there and method to get these data from daily data?

**Comment by SunsetWolf** [comment]
@PalanQu 
Sorry! This feature is not available yet.

**Comment by you-n-g** [comment]
Thanks so much!
Looking forward to your contribution!
Please feel free to contact me if you need further discussion.
