### ISSUE TITLE
Bug in TCTS model

### ISSUE THREAD

**Issue by Tribleave** [microsoft/qlib#943]
https://github.com/microsoft/qlib/blob/4dc66932d571fe6008db403f5780317ff2a3d09f/qlib/contrib/model/pytorch_tcts.py#L146-L148

Why set `p.init_fore_model = False` in line 148, this field makes no sense and not used in other place. 

I think it is a typo and should be `p.requires_grad = False` as the `init_fore_model` is not updated when training `fore_model.` 

Since it is a typo but the result of TCTS should be unchanged because it only update the parameters in `fore_optimizer`.

**Comment by you-n-g** [comment]
Thanks! 
It is OK to just remove the two lines. 

Would you mind sending a PR to fix this issue and become [one of the contributors of Qlib](https://github.com/microsoft/qlib/graphs/contributors)
;)
