### ISSUE TITLE
how to get unscaled ohlc？

### ISSUE THREAD

**Issue by qtbgo** [microsoft/qlib#944]
The following commands seems get scaled ohlc prices. I wonder how to get unscaled ohlc.
fields = ["$open", "$close", "$high", "$low", "$volume", "$factor", "$change"]
df = D.features(D.instruments("csi300"), fields)
df.head()

**Comment by wan9c9** [comment]
See https://qlib.readthedocs.io/en/latest/component/data.html#data-preparation, in particular, the following
factor:The Restoration factor. Normally, factor = adjusted_price / original_price, adjusted price reference: [split adjusted](https://www.investopedia.com/terms/s/splitadjusted.asp)

So the original price can be obtained by price*factor, where price is the (adjusted) open/high/low/close price in Qlib.

**Comment by qtbgo** [comment]
Thanks. But "original price can be obtained by price/factor" is not correct, because Qlib normalize the price on first trading day of each stock to 1 when adjusting them.

**Comment by you-n-g** [comment]
@qtbgo  Yes, Qlib normalizes the price on the first trading day and generates $factor.
But It will not affect the original price obtained by price/factor.   The normalization will only affect the generated $factor
