### ISSUE TITLE
possible bug here in class Rolling when checking for self.N:  isinstance(self.N, int) and 0 < self.N < 1

### ISSUE THREAD

**Issue by wan9c9** [microsoft/qlib#945]
Hi,

I have a questions about a line of code 

 isinstance(self.N, int) and 0 < self.N < 1:

in the class below. It doesn't make sense to me that self.N can be an int, and still in (0,1), can you please clarify?

class Rolling(ExpressionOps):
    """Rolling Operator
    The meaning of rolling and expanding is the same in pandas.
    When the window is set to 0, the behaviour of the operator should follow `expanding`
    Otherwise, it follows `rolling`

    Parameters
    ----------
    feature : Expression
        feature instance
    N : int
        rolling window size
    func : str
        rolling method

    Returns
    ----------
    Expression
        rolling outputs
    """

    def __init__(self, feature, N, func):
        self.feature = feature
        self.N = N
        self.func = func

    def __str__(self):
        return "{}({},{})".format(type(self).__name__, self.feature, self.N)

    def _load_internal(self, instrument, start_index, end_index, freq):
        series = self.feature.load(instrument, start_index, end_index, freq)
        # NOTE: remove all null check,
        # now it's user's responsibility to decide whether use features in null days
        # isnull = series.isnull() # NOTE: isnull = NaN, inf is not null
        if isinstance(self.N, int) and self.N == 0:
            series = getattr(series.expanding(min_periods=1), self.func)()
        **elif isinstance(self.N, int) and 0 < self.N < 1:**
            series = series.ewm(alpha=self.N, min_periods=1).mean()
        else:
            series = getattr(series.rolling(self.N, min_periods=1), self.func)()
            # series.iloc[:self.N-1] = np.nan
        # series[isnull] = np.nan
        return series

**Comment by you-n-g** [comment]
Yes.  Thanks for reporting the BUG!
I think the right code should be  `elif isinstance(self.N, float) and 0 < self.N < 1:` 
Would you like to send a PR to fix this issue? Thanks!

**Comment by wan9c9** [comment]
Thanks for confirming that. I'll send an PR to fix it
