### ISSUE TITLE
`get_risk_degree` not in `BaseStrategy`

### ISSUE THREAD

**Issue by tengerye** [microsoft/qlib#948]
## 📖 Documentation

In [this part](https://qlib.readthedocs.io/en/latest/component/strategy.html#basestrategy) from the document, " All strategy classes need to inherit the base class and implement its interface. `get_risk_degree` and `generate_order_list`". However, in current version of [code](https://github.com/microsoft/qlib/blob/ea4fb33ff2cb95ff8577aa0ccdec98eb7f9d0b7c/qlib/strategy/base.py#L19). Class `BaseStrategy` does not have these two methods. [Class `SBBStrategyBase`](https://github.com/microsoft/qlib/blob/ea4fb33ff2cb95ff8577aa0ccdec98eb7f9d0b7c/qlib/contrib/strategy/rule_strategy.py#L125) does not have these two methods either.

**Comment by you-n-g** [comment]
Sorry, the doc is too old and for previous version

The latest version of the code is https://github.com/microsoft/qlib/blob/main/qlib/strategy/base.py#L117
The generate_trade_decision is the key interface.

**Comment by tengerye** [comment]
@you-n-g I see. In my humble opinion, it is the right time to refine the document.

**Comment by you-n-g** [comment]
@SunsetWolf  will help to fix this part of the docs.

**Comment by SunsetWolf** [comment]
This issue is fixed in [this PR](https://github.com/microsoft/qlib/pull/986).
