### ISSUE TITLE
Remove argument interval in BaseRun:download_data

### ISSUE THREAD

**Issue by ChiahungTai** [microsoft/qlib#949]
## 🐛 Bug Description

BaseRun:download_data use interval in argument. But the interval in self already save in the BaseRun:__init__.
We can simplified by use self.interval in BaseRun:download_data.

## To Reproduce

1.
1.
1.

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version:
 - Python version:
 - OS (`Windows`, `Linux`, `MacOS`):
 - Commit number (optional, please provide it if you are using the dev version):

**Comment by you-n-g** [comment]
Thanks for your advice.

To make it compatible with the previous version of the command. 
I think we can change [this parameter ](https://github.com/microsoft/qlib/blob/main/scripts/data_collector/base.py#L322) to `default_interval`. 

And then make this [parameter ](https://github.com/microsoft/qlib/blob/main/scripts/data_collector/base.py#L360) optional

What do you think about the idea?

**Comment by ChiahungTai** [comment]
> Thanks for your advice.
> 
> To make it compatible with the previous version of the command. I think we can change [this parameter ](https://github.com/microsoft/qlib/blob/main/scripts/data_collector/base.py#L322) to `default_interval`.
> 
> And then make this [parameter ](https://github.com/microsoft/qlib/blob/main/scripts/data_collector/base.py#L360) optional
> 
> What do you think about the idea?

This might cause the incositency between default_interval and interval.
Might cause some confuses.

But IIUC, remove the argument interval in download_data  might not affect the CLI command.
Becasue you use the fire.Fire(Run) not fire.Fire(download_data), the interval argument in command line will pass to BaseRun first and go to download_data.
Actually the code - [download_data](https://github.com/microsoft/qlib/blob/07f0d4f599cc707ccaea680f4893277d1f881356/scripts/data_collector/yahoo/collector.py#L863) in yahoo/collector.py already remove the interval. I found this issue because the pycharm highlight me the signature is different from the BaseRun::download_data.

**Comment by you-n-g** [comment]
@ChiahungTai 

Thanks!   
Sorry. I misunderstood the design of `fire`. 
I tried [an example](https://github.com/you-n-g/cheatsheets/blob/master/code_to_copy/backend/python_apps/fire_example.py#L11)  just now and find that you are absolutely right!
Would you like to contribute to simplify it?

**Comment by ChiahungTai** [comment]
No problem
