### ISSUE TITLE
is it possible to add inheritance graph or UML to Qlib docs? 

### ISSUE THREAD

**Issue by wan9c9** [microsoft/qlib#952]
## 📖 Documentation

Hi, for the API document, is it possible to add inheritance graph or UML to the docs? There will be very helpful if one wants to write additional Ops or other classes.

Thanks!

**Comment by SunsetWolf** [comment]
It's good to get your issue, I think you are having some problems with operating qlib, asking specific questions will help us help you better. 
It's like when you want to learn bubble sorting and someone gives you a copy of Introduction to Algorithms, which does help the problem but makes it more problematic. 
We would prefer that you ask a specific problem and we help you solve it.

**Comment by wan9c9** [comment]
Thank you for your comments. I was trying to write a RefData type which is similar to DiskExpressionCache, but has a name and can be loaded in the same way as original features. 

I was not able to generate inheritance graph through sphinx, but used Pylint to generate a a dot file. If anyone is interested, you can use xdot to view it here: https://github.com/wan9c9/qlib/blob/main/classes_QLIB.dot

**Comment by you-n-g** [comment]
If you want to  `  regularly and updated when new data is dumped to Qlib`, 
I think the method with minimal cost is reuse DiskExpressionCache and DiskDatasetCache.
The feature of data updating has already been implemented [here](https://github.com/microsoft/qlib-server/blob/main/scripts/update_cache.py#L17).
