### ISSUE TITLE
Add new dataset and index: ibovespa and B3 datasets from Brazil Stock Exchange

### ISSUE THREAD

**Issue by igor17400** [microsoft/qlib#956]
## 🌟 Feature Description

Brazil's stock exchange is one of the biggest in the world and therefore adding its dataset into qlib can help people do research via qlib infrastructure using different datasets.

## Motivation

1. Application scenario: support brazilian stocks exchange investment strategy research.
2. Related works (Papers, Github repos etc.): Not applicable
3. Any other relevant and important information: More details on Brazil's stock exchange can be found on [B3](https://www.b3.com.br/en_us/)

## Alternatives

No other alternative have been considered, since the data is required to proceed with an investment strategy research.

## Additional Notes

The ideia is to 
- add code into `data_collector` to get data about the largest index in Brazil's stocks exchange - ibovespa
- add code into `yahoo` folder in order to download stocks historic prices.

**Comment by SunsetWolf** [comment]
> ## 🌟 Feature Description
> Brazil's stock exchange is one of the biggest in the world and therefore adding its dataset into qlib can help people do research via qlib infrastructure using different datasets.
> 
> ## Motivation
> 1. Application scenario: support brazilian stocks exchange investment strategy research.
> 2. Related works (Papers, Github repos etc.): Not applicable
> 3. Any other relevant and important information: More details on Brazil's stock exchange can be found on [B3](https://www.b3.com.br/en_us/)
> 
> ## Alternatives
> No other alternative have been considered, since the data is required to proceed with an investment strategy research.
> 
> ## Additional Notes
> The ideia is to
> 
> * add code into `data_collector` to get data about the largest index in Brazil's stocks exchange - ibovespa
> * add code into `yahoo` folder in order to download stocks historic prices.

Hi, thank you for submitting PR, now, your PR didn't pass the CI test, I think to solve this problem, you can try to merge the main branch of qlib.
