### ISSUE TITLE
A scaled down approach to examples

### ISSUE THREAD

**Issue by aleeusgr** [microsoft/qlib#98]
## 🌟 Feature Description
Provide settings to test the functionality of the package quickly.
## Motivation
When I study a new package, the quality of its analysis is of little importance: the main goal is to research the pipeline, tools, find out valid inputs, decision points, etc. I.e. I don't need valid results, just any results: I will check the data on the next step as documentation suggests.  
Current requirement to run examples is 5G/16G, which I will need to substitute for another volume of data anyway.  I suggest you add option to get a limited-size dataset to test-run the package,  look up valid data format and decompose the pipeline into wrapper functions

**Comment by you-n-g** [comment]
@aleeusgr  We have [tests](https://github.com/microsoft/qlib/tree/main/tests) for CI  which use simplified dataset.
You can try try it.w

**Comment by aleeusgr** [comment]
thank you
