### ISSUE TITLE
Add pre-commit hooks

### ISSUE THREAD

**Issue by Chaoyingz** [microsoft/qlib#989]
## 🌟 Feature Description

Can a [pre-commit hook](https://pre-commit.com/) be added? In this way, when submitting code, you no longer need to manually execute commands like `black` and `pylint`.
## Motivation

1. Application scenario
2. Related works (Papers, Github repos etc.):
3. Any other relevant and important information:

**Comment by you-n-g** [comment]
Thanks for your advice
I added a PR to implement to automate black
@SunsetWolf  will continue to complete this PR

https://github.com/microsoft/qlib/pull/992

**Comment by SunsetWolf** [comment]
[PR 992](https://github.com/microsoft/qlib/pull/992) has been merged, and you can read the [developer documentation](https://github.com/microsoft/qlib/blob/main/docs/developer/code_standard.rst) to learn how to use pre-commit.
