### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by hitlixuan** [microsoft/qlib#993]
## ❓ Questions and Help

![image](https://user-images.githubusercontent.com/98740232/158992009-726e1dbb-2b32-47f4-b63e-59086a89afc3.png)
BrokenPipeError                           Traceback (most recent call last)
~\AppData\Local\Temp\2\ipykernel_12508\4052663599.py in <module>
     76 
     77     # 训练模型，得到训练好的模型model
---> 78     model.fit(dataset)
     79 
     80     # 保存训练好的模型对象到磁盘

C:\ProgramData\Anaconda3\envs\lxqlib\lib\site-packages\qlib\contrib\model\pytorch_lstm_ts.py in fit(self, dataset, evals_result, save_path, reweighter)
    254             self.logger.info("Epoch%d:", step)
    255             self.logger.info("training...")
--> 256             self.train_epoch(train_loader)
    257             self.logger.info("evaluating...")
    258             train_loss, train_score = self.test_epoch(train_loader)

C:\ProgramData\Anaconda3\envs\lxqlib\lib\site-packages\qlib\contrib\model\pytorch_lstm_ts.py in train_epoch(self, data_loader)
    165         self.LSTM_model.train()
    166 
--> 167         for (data, weight) in data_loader:
    168             feature = data[:, :, 0:-1].to(self.device)
    169             label = data[:, -1, -1].to(self.device)

C:\ProgramData\Anaconda3\envs\lxqlib\lib\site-packages\torch\utils\data\dataloader.py in __iter__(self)
    366             return self._iterator
    367         else:
--> 368             return self._get_iterator()
    369 
    370     @property

C:\ProgramData\Anaconda3\envs\lxqlib\lib\site-packages\torch\utils\data\dataloader.py in _get_iterator(self)
    312         else:
    313             self.check_worker_number_rationality()
--> 314             return _MultiProcessingDataLoaderIter(self)
    315 
    316     @property

C:\ProgramData\Anaconda3\envs\lxqlib\lib\site-packages\torch\utils\data\dataloader.py in __init__(self, loader)
    925             #     before it starts, and __del__ tries to join but will get:
    926             #     AssertionError: can only join a started process.
--> 927             w.start()
    928             self._index_queues.append(index_queue)
    929             self._workers.append(w)

C:\ProgramData\Anaconda3\envs\lxqlib\lib\multiprocessing\process.py in start(self)
    110                'daemonic processes are not allowed to have children'
    111         _cleanup()
--> 112         self._popen = self._Popen(self)
    113         self._sentinel = self._popen.sentinel
    114         # Avoid a refcycle if the target function holds an indirect

C:\ProgramData\Anaconda3\envs\lxqlib\lib\multiprocessing\context.py in _Popen(process_obj)
    221     @staticmethod
    222     def _Popen(process_obj):
--> 223         return _default_context.get_context().Process._Popen(process_obj)
    224 
    225 class DefaultContext(BaseContext):

C:\ProgramData\Anaconda3\envs\lxqlib\lib\multiprocessing\context.py in _Popen(process_obj)
    320         def _Popen(process_obj):
    321             from .popen_spawn_win32 import Popen
--> 322             return Popen(process_obj)
    323 
    324     class SpawnContext(BaseContext):

C:\ProgramData\Anaconda3\envs\lxqlib\lib\multiprocessing\popen_spawn_win32.py in __init__(self, process_obj)
     87             try:
     88                 reduction.dump(prep_data, to_child)
---> 89                 reduction.dump(process_obj, to_child)
     90             finally:
     91                 set_spawning_popen(None)

C:\ProgramData\Anaconda3\envs\lxqlib\lib\multiprocessing\reduction.py in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)
     61 
     62 #

**BrokenPipeError: [Errno 32] Broken pipe**

**Comment by zhupr** [comment]
It is possible that the memory on your computer is small, try running it again
