### ISSUE TITLE
an error in qlib/data/dataset/handler.py  at line 518

### ISSUE THREAD

**Issue by ning213** [microsoft/qlib#994]
if self.process_type == DataHandlerLP.PTYPE_I:
            _learn_df = _shared_df

**Comment by zhupr** [comment]
@ning213 Hi,
What are the specific errors?

**Comment by ning213** [comment]
# data processing flow of self.process_type == DataHandlerLP.PTYPE_I
        (self._data)-[shared_processors]-(_shared_df)-[learn_processors]-(_learn_df)
                                               \
                                                -[infer_processors]-(_infer_df)

157     if self.process_type == DataHandlerLP.PTYPE_I:
158        _learn_df = self._data

**Comment by you-n-g** [comment]
@ning213  
Thanks for your reporting this bug!
Will [this PR](https://github.com/microsoft/qlib/pull/1044) fix your issue?

**Comment by ning213** [comment]
@

> @ning213 Thanks for your reporting this bug! Will [this PR](https://github.com/microsoft/qlib/pull/1044) fix your issue?

yes, thanks
