### ISSUE TITLE
About nested decision execution

### ISSUE THREAD

**Issue by ChiahungTai** [microsoft/qlib#997]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://qlib.readthedocs.io/) of our library as well as the official [paper](https://arxiv.org/abs/2009.11189). After that, if you still feel puzzled, please describe the question clearly under this issue.
Hi, @you-n-g,
Can you help me for the questions?  

The [readme](https://github.com/microsoft/qlib/tree/main/examples/nested_decision_execution) is not consistent to the codes in below statement. 

**[](https://github.com/microsoft/qlib/tree/main/examples/nested_decision_execution#usage)This workflow provides an example that uses a DropoutTopkStrategy (a strategy based on the daily frequency Lightgbm model) in weekly frequency for portfolio generation and uses SBBStrategyEMA (a rule-based strategy that uses EMA for decision-making) to execute orders in daily frequency.**

From my understanding, the code(https://github.com/microsoft/qlib/blob/main/examples/nested_decision_execution/workflow.py) use  "time_per_step": "day" not weekly abd SBBStrategyEMA in 30 mins not daily. Also it use 5 mins for TWAPStrategy.
Should we update the readme to meet the latest change of codes?

The second question is do you have any weekly frequency example? I don't find any of this.

**Comment by you-n-g** [comment]
Sorry, the docs are outdated.
We don't have a weekly frequency example now.
The community will appreciate it if you would like to fix it :)
Thanks

**Comment by ChiahungTai** [comment]
I have check the blame. Looks like you guys use the weekly before. Do you have any particular reason to remove the weekly part? Is there any trap of using weekly?
Thanks.

**Comment by you-n-g** [comment]
We implement the intraday version instead of the weekly version to align to an internal example in our research work.
By design, the weekly version is supported by the framework (it indeed involves a lot of processing of the details, [for example](https://github.com/microsoft/qlib/blob/main/qlib/utils/resam.py#L52)).

**Comment by ChiahungTai** [comment]
Thanks for your reply. It is very useful.
